ALBA: albaDecl.h File Reference
albaDecl.h File Reference
#include "albaDefines.h"
#include <wx/bitmap.h>
#include "albaString.h"
#include <vector>
Classes
struct WidgetDataType
Functions
ALBA_EXPORT wxWindow * albaGetFrame ()
ALBA_EXPORT void albaSetFrame (wxWindow *frame)
ALBA_EXPORT void albaYield ()
ALBA_EXPORT void albaEnableYielding (bool enable=true)
ALBA_EXPORT wxString albaGetDirName (const char *initial, const char *title="Select Directory", wxWindow *parent=NULL)
ALBA_EXPORT wxString albaGetOpenFile (const char *initial, const char *wildcard, const char *title="Open File", wxWindow *parent=NULL)
ALBA_EXPORT void albaGetOpenMultiFiles (const char *path, const char *wildcard, std::vector< wxString > &files, const char *title="Open Files", wxWindow *parent=NULL)
ALBA_EXPORT wxString albaGetSaveFile (const char *initial, const char *wildcard, const char *title="Save File", wxWindow *parent=NULL, bool warnOverWrite=true)
ALBA_EXPORT void albaResetRandomColor ()
ALBA_EXPORT wxColour albaRandomColor ()
ALBA_EXPORT wxBitmap albaWhiteFade (wxBitmap bmp, double level=0.5)
ALBA_EXPORT wxBitmap albaBlueScale (wxBitmap bmp)
ALBA_EXPORT wxString albaGetApplicationDirectory ()
ALBA_EXPORT wxString albaGetAppDataDirectory ()
ALBA_EXPORT wxString albaGetDocumentsDirectory ()
ALBA_EXPORT wxString albaGetLastUserFolder ()
ALBA_EXPORT void albaSetAppDebugDir (wxString ddir)
ALBA_EXPORT wxString albaGetConfigDirectory ()
ALBA_EXPORT void albaSetLastUserFolder (albaString folder)
ALBA_EXPORT wxString albaIdString (int id)
ALBA_EXPORT float RoundValue (float f_in, int decimal_digits=2)
ALBA_EXPORT double RoundValue (double d_in, int decimal_digits=2)
ALBA_EXPORT void albaFormatDataSize (long long size, albaString &szOut)
ALBA_EXPORT int * GetALBAExpertMode ()
Variables
const int MAXWIDGET = 4096
const int MAXOP = 200
const int MAXVIEW = 200
const int MAXWIZARD = 50
enum ALBA_EXPORT WIDGET_DATA_TYPE_ID
NULL_DATA
INT_DATA
FLOAT_DATA
DOUBLE_DATA
STRING_DATA
enum ALBA_EXPORT DEVICE_BUTTONS
ALBA_ANY_BUTTON = -1
ALBA_LEFT_BUTTON = 0
ALBA_MIDDLE_BUTTON
enum ALBA_EXPORT DEVICE_MODIFIERS
ALBA_SHIFT_KEY = 0
ALBA_CTRL_KEY
MENU_START = 10000
MENU_FILE_START
MENU_FILE_NEW
MENU_FILE_OPEN
MENU_FILE_SAVE
MENU_FILE_SAVEAS
MENU_FILE_MERGE
MENU_FILE_PRINT
MENU_FILE_PRINT_PREVIEW
MENU_FILE_PRINT_SETUP
MENU_FILE_PRINT_PAGE_SETUP
MENU_FILE_QUIT
MENU_FILE_END
MENU_EDIT_START
MENU_EDIT_FIND_VME
MENU_OP
MENU_EDIT_END
MENU_VIEW_START
MENU_VIEW_LAYOUT
MENU_VIEW_LAYOUT_MSF
SASH_START
MENU_VIEW_TOOLBAR
MENU_VIEW_LOGBAR
MENU_VIEW_SIDEBAR
MENU_VIEW_TIMEBAR
MENU_VIEW_USER_FIRST
MENU_VIEW_USER_LAST = MENU_VIEW_USER_FIRST + 20
SASH_END
MENU_LAYOUT_START
LAYOUT_ONE
LAYOUT_TWO_VERT
LAYOUT_TWO_HORZ
LAYOUT_THREE_UP
LAYOUT_THREE_DOWN
LAYOUT_THREE_LEFT
LAYOUT_THREE_RIGHT
LAYOUT_FOUR
LAYOUT_LOAD
LAYOUT_SAVE
MENU_LAYOUT_END
MENU_VIEW_END
MENU_SETTINGS_START
MENU_OPTION_APPLICATION_SETTINGS
MENU_OPTION_DEVICE_SETTINGS
MENU_OPTION_LOCALE_SETTINGS
MENU_OPTION_MEASURE_UNIT_SETTINGS
PRINT_TREE
ID_APP_SETTINGS
ID_TIMEBAR_SETTINGS
ID_VIEW_SETTINGS
MENU_SETTINGS_END
MENU_HELP_START
ABOUT_APPLICATION
REGISTER_PRODUCT
GENERATE_LICENCE
HELP_HOME
MENU_HELP_END
GUI_HELP_START
GET_BUILD_HELP_GUI
OPEN_HELP_PAGE
GUI_HELP_END
EVT_START
UPDATE_UI
UPDATE_PROPERTY
BIND_TO_PROGRESSBAR
PROGRESSBAR_SHOW
PROGRESSBAR_HIDE
PROGRESSBAR_SET_VALUE
PROGRESSBAR_SET_TEXT
VME_ADDED
VME_REMOVING
VME_SELECT
VME_DCLICKED
VME_SELECTED
VME_TRANSFORM
VME_CHOOSE
VME_PICKED
VME_PICKING
VME_CHOOSE_MATERIAL
VME_CHOOSE_TRANSFER_FUNCTION
VME_CHOOSE_FEM_PROPERTY
VME_REF_SYS_CHOOSED
VME_FEM_DATA_CHOOSED
CREATE_STORAGE
VIEW_QUIT
VIEW_CREATE
VIEW_CREATED
VIEW_DELETE
VIEW_SELECT
VIEW_SELECTED
VIEW_CLICKED
VIEW_MAXIMIZE
VIEW_RESIZE
VIEW_SAVE_IMAGE
PER_PUSH
PER_POP
GET_CURRENT_PER
CAMERA_FRONT
CAMERA_BACK
CAMERA_LEFT
CAMERA_RIGHT
CAMERA_TOP
CAMERA_BOTTOM
CAMERA_PERSPECTIVE
CAMERA_RX_FRONT
CAMERA_RX_LEFT
CAMERA_RX_RIGHT
CAMERA_DRR_FRONT
CAMERA_DRR_LEFT
CAMERA_DRR_RIGHT
CAMERA_CT
CAMERA_OS_X
CAMERA_OS_Y
CAMERA_OS_Z
CAMERA_OS_P
CAMERA_PERSPECTIVE_FRONT
CAMERA_PERSPECTIVE_BACK
CAMERA_PERSPECTIVE_LEFT
CAMERA_PERSPECTIVE_RIGHT
CAMERA_PERSPECTIVE_TOP
CAMERA_PERSPECTIVE_BOTTOM
CAMERA_ARB
CAMERA_SYNCHRONOUS_UPDATE
CAMERA_UPDATE
CAMERA_RESET
CAMERA_FIT
CAMERA_FLYTO
CAMERA_PRE_RESET
CAMERA_POST_RESET
CAMERA_MOVED
CAMERA_RXFEM_XNEG
CAMERA_RXFEM_XPOS
CAMERA_RXFEM_YNEG
CAMERA_RXFEM_YPOS
CAMERA_RXFEM_ZNEG
CAMERA_RXFEM_ZPOS
CAMERA_BLEND
OP_ADD
OP_REMOVE
OP_ENABLE
OP_EXEC
OP_RUN
OP_RUN_OK
OP_RUN_CANCEL
OP_RUN_STARTING
OP_RUN_TERMINATED
OP_SHOW_GUI
OP_HIDE_GUI
OP_FORCE_STOP
ITEM_SELECTED
IMPORT_FILE
CLEAR_UNDO_STACK
LOG_ALL_EVENT
LOG_TO_FILE
MOUSE_DOWN
MOUSE_MOVE
MOUSE_UP
MOUSE_WHEEL
ID_TRANSFORM
SHOW_VIEW_CONTEXTUAL_MENU
SHOW_TREE_CONTEXTUAL_MENU
INTERACTOR_ADD
INTERACTOR_REMOVE
DEVICE_ADD
DEVICE_REMOVE
DEVICE_GET
TILE_WINDOW_CASCADE
TILE_WINDOW_HORIZONTALLY
TILE_WINDOW_VERTICALLY
EVT_USER_START
EVT_USER_END = EVT_USER_START + 1000
EVT_END
MENU_USER_START
MENU_USER_END = MENU_USER_START + 1000
MENU_END
OP_START
OP_UNDO
OP_REDO
OP_DELETE
OP_CUT
OP_COPY
OP_PASTE
OP_RENAME
OP_REPARENT
OP_ADD_GROUP
OP_SELECT
OP_TRANSFORM
OP_USER
OP_END = OP_START + MAXOP
VIEW_START
VIEW_END = VIEW_START + MAXVIEW
WIDGETS_START
ID_LAYOUT
ID_CLOSE_SASH
ID_LABEL_CLICK
ID_DISPLAY_LIST
ID_SETTINGS
ID_RANGE_MODIFIED
WIDGETS_END
PIC_START
TIME_SET
TIME_PLAY
TIME_STOP
TIME_PREV
TIME_NEXT
TIME_BEGIN
TIME_END
MOVIE_RECORD
PIC_END
PIC_USER_START = PIC_START + 500
PIC_USER_END = PIC_USER_START + 100
PARSE_STRING
APPSTAMP
MCH_START
MCH_UP
MCH_DOWN
MCH_INPUT
MCH_OUTPUT
MCH_NODE
MCH_ANY
MCH_VTK
MCH_END
NODE_START
NODE_DETACHED_FROM_TREE
NODE_ATTACHED_TO_TREE
NODE_DESTROYED
NODE_GET_STORAGE
NODE_GET_ROOT
VME_TIME_SET
VME_MATRIX_CHANGED
VME_MATRIX_PREUPDATE
VME_MATRIX_UPDATE
VME_ABSMATRIX_UPDATE
VME_OUTPUT_DATA_PREUPDATE
VME_OUTPUT_DATA_UPDATE
VME_OUTPUT_DATA_CHANGED
VME_GET_NEWITEM_ID
NODE_END
AVATAR_ADDED
AVATAR_REMOVED
MATRIX_UPDATED
MINID
MAXID = MINID + MAXWIDGET
ID_GUI_UPDATE
enum MED_MAIN_EVENT_ID {
ID_VME_BEHAVIOR_UPDATE = EVT_USER_START , MENU_FILE_SNAPSHOT , MENU_FILE_MANAGE_SNAPSHOT , ID_GET_FILENAME ,
WIZARD_RUN_STARTING , WIZARD_RUN_CONTINUE , WIZARD_RUN_TERMINATED , WIZARD_REQUIRED_VIEW ,
WIZARD_DELETE_VIEW , WIZARD_RUN_OP , WIZARD_UPDATE_WINDOW_TITLE , WIZARD_PAUSE ,
WIZARD_OP_DELETE , WIZARD_OP_NEW , WIZARD_SWITCH , WIZARD_RELOAD_MSF ,
WIZARD_INFORMATION_BOX_SHOW_SET , WIZARD_INFORMATION_BOX_SHOW_GET , WIZARD_START , WIZARD_END = WIZARD_START + MAXWIZARD ,
MED_EVT_USER_START
}
enum MED_MENU_EVENT_ID { MENU_WIZARD = MENU_USER_START , MED_MENU_USER_START }
enum ALBA_EXPORT MAIN_EVENT_ID
Enumeration Type Documentation
MED_MAIN_EVENT_ID
enum MED_MAIN_EVENT_ID
Most of the constants used in ALBA are declared here.
These constants must be non-overlapping. Constants are grouped by bracket xx_START, xx_END as needed by albaGUIFrame
Enumerator
ID_VME_BEHAVIOR_UPDATE
MENU_FILE_SNAPSHOT
MENU_FILE_MANAGE_SNAPSHOT
ID_GET_FILENAME
WIZARD_RUN_STARTING
WIZARD_RUN_CONTINUE
WIZARD_RUN_TERMINATED
WIZARD_REQUIRED_VIEW
WIZARD_DELETE_VIEW
WIZARD_RUN_OP
WIZARD_UPDATE_WINDOW_TITLE
WIZARD_PAUSE
WIZARD_OP_DELETE
WIZARD_OP_NEW
WIZARD_SWITCH
WIZARD_RELOAD_MSF
WIZARD_INFORMATION_BOX_SHOW_SET
WIZARD_INFORMATION_BOX_SHOW_GET
WIZARD_START
WIZARD_END
MED_EVT_USER_START
Definition at line 428 of file albaDecl.h.
MED_MENU_EVENT_ID
enum MED_MENU_EVENT_ID
Most of the constants used in ALBA are declared here.
These constants must be non-overlapping. Constants are grouped by bracket xx_START, xx_END as needed by albaGUIFrame
Enumerator
MENU_WIZARD
MED_MENU_USER_START
Definition at line 453 of file albaDecl.h.
Function Documentation
albaGetFrame()
ALBA_EXPORT wxWindow * albaGetFrame ()
return the application frame window.
to be used as parent of panels to be shown later.
Referenced by albaGUI::Remove().
albaSetFrame()
ALBA_EXPORT void albaSetFrame (wxWindow * frame)
global function to retrieve the vme base type.
to be used by albaGUIFrame and derived class only
albaYield()
ALBA_EXPORT void albaYield ()
process pending events.
be careful not to call it recursively
albaEnableYielding()
ALBA_EXPORT void albaEnableYielding (bool enable = true)
process pending events.
be careful not to call it recursively
albaGetDirName()
ALBA_EXPORT wxString albaGetDirName (const char * initial, const char * title = "Select Directory", wxWindow * parent = NULL)
show the Dir Selection Dialog Box
albaGetOpenFile()
ALBA_EXPORT wxString albaGetOpenFile (const char * initial, const char * wildcard, const char * title = "Open File", wxWindow * parent = NULL)
show the File Open Dialog Box
albaGetOpenMultiFiles()
ALBA_EXPORT void albaGetOpenMultiFiles (const char * path, const char * wildcard, std::vector< wxString > & files, const char * title = "Open Files", wxWindow * parent = NULL)
show the File Open Dialog Box for multiple file selection
albaGetSaveFile()
ALBA_EXPORT wxString albaGetSaveFile (const char * initial, const char * wildcard, const char * title = "Save File", wxWindow * parent = NULL, bool warnOverWrite = true)
show the File Save Dialog Box
albaResetRandomColor()
ALBA_EXPORT void albaResetRandomColor ()
Resets the Random Color Selection used for test repeatability.
albaRandomColor()
ALBA_EXPORT wxColour albaRandomColor ()
return a random wxColour from a palette of 16
albaWhiteFade()
ALBA_EXPORT wxBitmap albaWhiteFade (wxBitmap bmp, double level = 0.5)
Used to generate gray scale bitmap given a colored one.
albaBlueScale()
ALBA_EXPORT wxBitmap albaBlueScale (wxBitmap bmp)
Used to generate red scale bitmap to represent a VME with data not present.
albaGetApplicationDirectory()
ALBA_EXPORT wxString albaGetApplicationDirectory ()
return the application start-up directory
albaGetAppDataDirectory()
ALBA_EXPORT wxString albaGetAppDataDirectory ()
return the WorkingData directory
albaGetDocumentsDirectory()
ALBA_EXPORT wxString albaGetDocumentsDirectory ()
return the Documents directory
albaGetLastUserFolder()
ALBA_EXPORT wxString albaGetLastUserFolder ()
return the Last User directory
albaSetAppDebugDir()
ALBA_EXPORT void albaSetAppDebugDir (wxString ddir)
return the Last User directory
albaGetConfigDirectory()
ALBA_EXPORT wxString albaGetConfigDirectory ()
return the config directory
albaSetLastUserFolder()
ALBA_EXPORT void albaSetLastUserFolder (albaString folder)
Set the Last User directory.
albaIdString()
ALBA_EXPORT wxString albaIdString (int id)
translate an event-id into a readable string
RoundValue() [1/2]
ALBA_EXPORT float RoundValue (float f_in, int decimal_digits = 2)
RoundValue() [2/2]
ALBA_EXPORT double RoundValue (double d_in, int decimal_digits = 2)
albaFormatDataSize()
ALBA_EXPORT void albaFormatDataSize (long long size, albaString & szOut)
Formats the specified size to B, KB, MB or GB.
GetALBAExpertMode()
ALBA_EXPORT int * GetALBAExpertMode ()
Referenced by albaLogicWithManagers::ALBAExpertModeOff(), albaLogicWithManagers::ALBAExpertModeOn(), and albaLogicWithManagers::SetALBAExpertMode().
Variable Documentation
MAXWIDGET
const int MAXWIDGET = 4096
Definition at line 70 of file albaDecl.h.
MAXOP
const int MAXOP = 200
Definition at line 71 of file albaDecl.h.
MAXVIEW
const int MAXVIEW = 200
Definition at line 72 of file albaDecl.h.
MAXWIZARD
const int MAXWIZARD = 50
Definition at line 73 of file albaDecl.h.
WIDGET_DATA_TYPE_ID
enum ALBA_EXPORT WIDGET_DATA_TYPE_ID
Data Type enum that identify data stored in WidgetDataType struct.
Definition at line 78 of file albaDecl.h.
NULL_DATA
NULL_DATA
Definition at line 80 of file albaDecl.h.
INT_DATA
INT_DATA
Definition at line 81 of file albaDecl.h.
FLOAT_DATA
FLOAT_DATA
Definition at line 82 of file albaDecl.h.
DOUBLE_DATA
DOUBLE_DATA
Definition at line 83 of file albaDecl.h.
STRING_DATA
STRING_DATA
Definition at line 84 of file albaDecl.h.
DEVICE_BUTTONS
enum ALBA_EXPORT DEVICE_BUTTONS
conventional device button values
Definition at line 97 of file albaDecl.h.
ALBA_ANY_BUTTON
ALBA_ANY_BUTTON = -1
Definition at line 99 of file albaDecl.h.
ALBA_LEFT_BUTTON
ALBA_LEFT_BUTTON = 0
Definition at line 100 of file albaDecl.h.
ALBA_MIDDLE_BUTTON
ALBA_MIDDLE_BUTTON
Definition at line 101 of file albaDecl.h.
DEVICE_MODIFIERS
enum ALBA_EXPORT DEVICE_MODIFIERS
conventional key modifiers values
Definition at line 106 of file albaDecl.h.
ALBA_SHIFT_KEY
ALBA_SHIFT_KEY = 0
Definition at line 108 of file albaDecl.h.
ALBA_CTRL_KEY
ALBA_CTRL_KEY
Definition at line 109 of file albaDecl.h.
MENU_START
MENU_START = 10000
Definition at line 122 of file albaDecl.h.
MENU_FILE_START
MENU_FILE_START
Definition at line 123 of file albaDecl.h.
MENU_FILE_NEW
MENU_FILE_NEW
Definition at line 124 of file albaDecl.h.
MENU_FILE_OPEN
MENU_FILE_OPEN
Definition at line 125 of file albaDecl.h.
MENU_FILE_SAVE
MENU_FILE_SAVE
Definition at line 126 of file albaDecl.h.
MENU_FILE_SAVEAS
MENU_FILE_SAVEAS
Definition at line 127 of file albaDecl.h.
MENU_FILE_MERGE
MENU_FILE_MERGE
Definition at line 128 of file albaDecl.h.
MENU_FILE_PRINT
MENU_FILE_PRINT
Definition at line 129 of file albaDecl.h.
MENU_FILE_PRINT_PREVIEW
MENU_FILE_PRINT_PREVIEW
Definition at line 130 of file albaDecl.h.
MENU_FILE_PRINT_SETUP
MENU_FILE_PRINT_SETUP
Definition at line 131 of file albaDecl.h.
MENU_FILE_PRINT_PAGE_SETUP
MENU_FILE_PRINT_PAGE_SETUP
Definition at line 132 of file albaDecl.h.
MENU_FILE_QUIT
MENU_FILE_QUIT
Definition at line 133 of file albaDecl.h.
MENU_FILE_END
MENU_FILE_END
Definition at line 134 of file albaDecl.h.
MENU_EDIT_START
MENU_EDIT_START
Definition at line 135 of file albaDecl.h.
MENU_EDIT_FIND_VME
MENU_EDIT_FIND_VME
Definition at line 136 of file albaDecl.h.
MENU_OP
MENU_OP
Definition at line 137 of file albaDecl.h.
MENU_EDIT_END
MENU_EDIT_END
Definition at line 138 of file albaDecl.h.
MENU_VIEW_START
MENU_VIEW_START
Definition at line 139 of file albaDecl.h.
MENU_VIEW_LAYOUT
MENU_VIEW_LAYOUT
Definition at line 140 of file albaDecl.h.
MENU_VIEW_LAYOUT_MSF
MENU_VIEW_LAYOUT_MSF
Definition at line 141 of file albaDecl.h.
SASH_START
SASH_START
Definition at line 142 of file albaDecl.h.
MENU_VIEW_TOOLBAR
MENU_VIEW_TOOLBAR
Definition at line 143 of file albaDecl.h.
MENU_VIEW_LOGBAR
MENU_VIEW_LOGBAR
Definition at line 144 of file albaDecl.h.
MENU_VIEW_SIDEBAR
MENU_VIEW_SIDEBAR
Definition at line 145 of file albaDecl.h.
MENU_VIEW_TIMEBAR
MENU_VIEW_TIMEBAR
Definition at line 146 of file albaDecl.h.
MENU_VIEW_USER_FIRST
MENU_VIEW_USER_FIRST
Definition at line 147 of file albaDecl.h.
MENU_VIEW_USER_LAST
MENU_VIEW_USER_LAST = MENU_VIEW_USER_FIRST + 20
Definition at line 148 of file albaDecl.h.
SASH_END
SASH_END
Definition at line 149 of file albaDecl.h.
MENU_LAYOUT_START
MENU_LAYOUT_START
Definition at line 150 of file albaDecl.h.
LAYOUT_ONE
LAYOUT_ONE
Definition at line 151 of file albaDecl.h.
LAYOUT_TWO_VERT
LAYOUT_TWO_VERT
Definition at line 152 of file albaDecl.h.
LAYOUT_TWO_HORZ
LAYOUT_TWO_HORZ
Definition at line 153 of file albaDecl.h.
LAYOUT_THREE_UP
LAYOUT_THREE_UP
Definition at line 154 of file albaDecl.h.
LAYOUT_THREE_DOWN
LAYOUT_THREE_DOWN
Definition at line 155 of file albaDecl.h.
LAYOUT_THREE_LEFT
LAYOUT_THREE_LEFT
Definition at line 156 of file albaDecl.h.
LAYOUT_THREE_RIGHT
LAYOUT_THREE_RIGHT
Definition at line 157 of file albaDecl.h.
LAYOUT_FOUR
LAYOUT_FOUR
Definition at line 158 of file albaDecl.h.
LAYOUT_LOAD
LAYOUT_LOAD
Definition at line 159 of file albaDecl.h.
LAYOUT_SAVE
LAYOUT_SAVE
Definition at line 160 of file albaDecl.h.
MENU_LAYOUT_END
MENU_LAYOUT_END
Definition at line 161 of file albaDecl.h.
MENU_VIEW_END
MENU_VIEW_END
Definition at line 162 of file albaDecl.h.
MENU_SETTINGS_START
MENU_SETTINGS_START
Definition at line 163 of file albaDecl.h.
MENU_OPTION_APPLICATION_SETTINGS
MENU_OPTION_APPLICATION_SETTINGS
Definition at line 164 of file albaDecl.h.
MENU_OPTION_DEVICE_SETTINGS
MENU_OPTION_DEVICE_SETTINGS
Definition at line 165 of file albaDecl.h.
MENU_OPTION_LOCALE_SETTINGS
MENU_OPTION_LOCALE_SETTINGS
Definition at line 166 of file albaDecl.h.
MENU_OPTION_MEASURE_UNIT_SETTINGS
MENU_OPTION_MEASURE_UNIT_SETTINGS
Definition at line 167 of file albaDecl.h.
PRINT_TREE
PRINT_TREE
Definition at line 168 of file albaDecl.h.
ID_APP_SETTINGS
ID_APP_SETTINGS
Definition at line 169 of file albaDecl.h.
ID_TIMEBAR_SETTINGS
ID_TIMEBAR_SETTINGS
Definition at line 170 of file albaDecl.h.
ID_VIEW_SETTINGS
ID_VIEW_SETTINGS
Definition at line 171 of file albaDecl.h.
MENU_SETTINGS_END
MENU_SETTINGS_END
Definition at line 172 of file albaDecl.h.
MENU_HELP_START
MENU_HELP_START
Definition at line 173 of file albaDecl.h.
ABOUT_APPLICATION
ABOUT_APPLICATION
Definition at line 174 of file albaDecl.h.
REGISTER_PRODUCT
REGISTER_PRODUCT
Definition at line 175 of file albaDecl.h.
GENERATE_LICENCE
GENERATE_LICENCE
Definition at line 176 of file albaDecl.h.
HELP_HOME
HELP_HOME
Definition at line 177 of file albaDecl.h.
MENU_HELP_END
MENU_HELP_END
Definition at line 178 of file albaDecl.h.
GUI_HELP_START
GUI_HELP_START
Definition at line 179 of file albaDecl.h.
GET_BUILD_HELP_GUI
GET_BUILD_HELP_GUI
Definition at line 180 of file albaDecl.h.
OPEN_HELP_PAGE
OPEN_HELP_PAGE
Definition at line 181 of file albaDecl.h.
GUI_HELP_END
GUI_HELP_END
Definition at line 182 of file albaDecl.h.
EVT_START
EVT_START
Definition at line 184 of file albaDecl.h.
UPDATE_UI
UPDATE_UI
Definition at line 185 of file albaDecl.h.
UPDATE_PROPERTY
UPDATE_PROPERTY
Definition at line 186 of file albaDecl.h.
BIND_TO_PROGRESSBAR
BIND_TO_PROGRESSBAR
Definition at line 188 of file albaDecl.h.
PROGRESSBAR_SHOW
PROGRESSBAR_SHOW
Definition at line 190 of file albaDecl.h.
PROGRESSBAR_HIDE
PROGRESSBAR_HIDE
Definition at line 191 of file albaDecl.h.
PROGRESSBAR_SET_VALUE
PROGRESSBAR_SET_VALUE
Definition at line 192 of file albaDecl.h.
PROGRESSBAR_SET_TEXT
PROGRESSBAR_SET_TEXT
Definition at line 193 of file albaDecl.h.
VME_ADDED
VME_ADDED
Definition at line 195 of file albaDecl.h.
VME_REMOVING
VME_REMOVING
Definition at line 196 of file albaDecl.h.
VME_SELECT
VME_SELECT
Definition at line 197 of file albaDecl.h.
VME_DCLICKED
VME_DCLICKED
Definition at line 198 of file albaDecl.h.
VME_SELECTED
VME_SELECTED
Definition at line 199 of file albaDecl.h.
VME_TRANSFORM
VME_TRANSFORM
Definition at line 200 of file albaDecl.h.
VME_CHOOSE
VME_CHOOSE
Definition at line 201 of file albaDecl.h.
VME_PICKED
VME_PICKED
Definition at line 202 of file albaDecl.h.
VME_PICKING
VME_PICKING
Definition at line 203 of file albaDecl.h.
VME_CHOOSE_MATERIAL
VME_CHOOSE_MATERIAL
Definition at line 204 of file albaDecl.h.
VME_CHOOSE_TRANSFER_FUNCTION
VME_CHOOSE_TRANSFER_FUNCTION
Definition at line 205 of file albaDecl.h.
VME_CHOOSE_FEM_PROPERTY
VME_CHOOSE_FEM_PROPERTY
Definition at line 206 of file albaDecl.h.
VME_REF_SYS_CHOOSED
VME_REF_SYS_CHOOSED
Definition at line 207 of file albaDecl.h.
VME_FEM_DATA_CHOOSED
VME_FEM_DATA_CHOOSED
Definition at line 208 of file albaDecl.h.
CREATE_STORAGE
CREATE_STORAGE
Definition at line 209 of file albaDecl.h.
VIEW_QUIT
VIEW_QUIT
Definition at line 212 of file albaDecl.h.
VIEW_CREATE
VIEW_CREATE
Definition at line 213 of file albaDecl.h.
VIEW_CREATED
VIEW_CREATED
Definition at line 214 of file albaDecl.h.
VIEW_DELETE
VIEW_DELETE
Definition at line 215 of file albaDecl.h.
VIEW_SELECT
VIEW_SELECT
Definition at line 216 of file albaDecl.h.
VIEW_SELECTED
VIEW_SELECTED
Definition at line 217 of file albaDecl.h.
VIEW_CLICKED
VIEW_CLICKED
Definition at line 218 of file albaDecl.h.
VIEW_MAXIMIZE
VIEW_MAXIMIZE
Definition at line 219 of file albaDecl.h.
VIEW_RESIZE
VIEW_RESIZE
Definition at line 220 of file albaDecl.h.
VIEW_SAVE_IMAGE
VIEW_SAVE_IMAGE
Definition at line 221 of file albaDecl.h.
PER_PUSH
PER_PUSH
Definition at line 222 of file albaDecl.h.
PER_POP
PER_POP
Definition at line 223 of file albaDecl.h.
GET_CURRENT_PER
GET_CURRENT_PER
Definition at line 224 of file albaDecl.h.
CAMERA_FRONT
CAMERA_FRONT
Definition at line 226 of file albaDecl.h.
CAMERA_BACK
CAMERA_BACK
Definition at line 227 of file albaDecl.h.
CAMERA_LEFT
CAMERA_LEFT
Definition at line 228 of file albaDecl.h.
CAMERA_RIGHT
CAMERA_RIGHT
Definition at line 229 of file albaDecl.h.
CAMERA_TOP
CAMERA_TOP
Definition at line 230 of file albaDecl.h.
CAMERA_BOTTOM
CAMERA_BOTTOM
Definition at line 231 of file albaDecl.h.
CAMERA_PERSPECTIVE
CAMERA_PERSPECTIVE
Definition at line 232 of file albaDecl.h.
CAMERA_RX_FRONT
CAMERA_RX_FRONT
Definition at line 233 of file albaDecl.h.
CAMERA_RX_LEFT
CAMERA_RX_LEFT
Definition at line 234 of file albaDecl.h.
CAMERA_RX_RIGHT
CAMERA_RX_RIGHT
Definition at line 235 of file albaDecl.h.
CAMERA_DRR_FRONT
CAMERA_DRR_FRONT
Definition at line 236 of file albaDecl.h.
CAMERA_DRR_LEFT
CAMERA_DRR_LEFT
Definition at line 237 of file albaDecl.h.
CAMERA_DRR_RIGHT
CAMERA_DRR_RIGHT
Definition at line 238 of file albaDecl.h.
CAMERA_CT
CAMERA_CT
Definition at line 239 of file albaDecl.h.
CAMERA_OS_X
CAMERA_OS_X
Definition at line 240 of file albaDecl.h.
CAMERA_OS_Y
CAMERA_OS_Y
Definition at line 241 of file albaDecl.h.
CAMERA_OS_Z
CAMERA_OS_Z
Definition at line 242 of file albaDecl.h.
CAMERA_OS_P
CAMERA_OS_P
Definition at line 243 of file albaDecl.h.
CAMERA_PERSPECTIVE_FRONT
CAMERA_PERSPECTIVE_FRONT
Definition at line 244 of file albaDecl.h.
CAMERA_PERSPECTIVE_BACK
CAMERA_PERSPECTIVE_BACK
Definition at line 245 of file albaDecl.h.
CAMERA_PERSPECTIVE_LEFT
CAMERA_PERSPECTIVE_LEFT
Definition at line 246 of file albaDecl.h.
CAMERA_PERSPECTIVE_RIGHT
CAMERA_PERSPECTIVE_RIGHT
Definition at line 247 of file albaDecl.h.
CAMERA_PERSPECTIVE_TOP
CAMERA_PERSPECTIVE_TOP
Definition at line 248 of file albaDecl.h.
CAMERA_PERSPECTIVE_BOTTOM
CAMERA_PERSPECTIVE_BOTTOM
Definition at line 249 of file albaDecl.h.
CAMERA_ARB
CAMERA_ARB
Definition at line 250 of file albaDecl.h.
CAMERA_SYNCHRONOUS_UPDATE
CAMERA_SYNCHRONOUS_UPDATE
Definition at line 252 of file albaDecl.h.
CAMERA_UPDATE
CAMERA_UPDATE
Definition at line 253 of file albaDecl.h.
CAMERA_RESET
CAMERA_RESET
Definition at line 254 of file albaDecl.h.
CAMERA_FIT
CAMERA_FIT
Definition at line 255 of file albaDecl.h.
CAMERA_FLYTO
CAMERA_FLYTO
Definition at line 256 of file albaDecl.h.
CAMERA_PRE_RESET
CAMERA_PRE_RESET
Definition at line 257 of file albaDecl.h.
CAMERA_POST_RESET
CAMERA_POST_RESET
Definition at line 258 of file albaDecl.h.
CAMERA_MOVED
CAMERA_MOVED
Definition at line 259 of file albaDecl.h.
CAMERA_RXFEM_XNEG
CAMERA_RXFEM_XNEG
Definition at line 262 of file albaDecl.h.
CAMERA_RXFEM_XPOS
CAMERA_RXFEM_XPOS
Definition at line 263 of file albaDecl.h.
CAMERA_RXFEM_YNEG
CAMERA_RXFEM_YNEG
Definition at line 264 of file albaDecl.h.
CAMERA_RXFEM_YPOS
CAMERA_RXFEM_YPOS
Definition at line 265 of file albaDecl.h.
CAMERA_RXFEM_ZNEG
CAMERA_RXFEM_ZNEG
Definition at line 266 of file albaDecl.h.
CAMERA_RXFEM_ZPOS
CAMERA_RXFEM_ZPOS
Definition at line 267 of file albaDecl.h.
CAMERA_BLEND
CAMERA_BLEND
Definition at line 270 of file albaDecl.h.
OP_ADD
OP_ADD
Definition at line 272 of file albaDecl.h.
OP_REMOVE
OP_REMOVE
Definition at line 273 of file albaDecl.h.
OP_ENABLE
OP_ENABLE
Definition at line 274 of file albaDecl.h.
OP_EXEC
OP_EXEC
Definition at line 275 of file albaDecl.h.
OP_RUN
OP_RUN
Definition at line 276 of file albaDecl.h.
OP_RUN_OK
OP_RUN_OK
Definition at line 277 of file albaDecl.h.
OP_RUN_CANCEL
OP_RUN_CANCEL
Definition at line 278 of file albaDecl.h.
OP_RUN_STARTING
OP_RUN_STARTING
Definition at line 279 of file albaDecl.h.
OP_RUN_TERMINATED
OP_RUN_TERMINATED
Definition at line 280 of file albaDecl.h.
OP_SHOW_GUI
OP_SHOW_GUI
Definition at line 281 of file albaDecl.h.
OP_HIDE_GUI
OP_HIDE_GUI
Definition at line 282 of file albaDecl.h.
OP_FORCE_STOP
OP_FORCE_STOP
Definition at line 283 of file albaDecl.h.
ITEM_SELECTED
ITEM_SELECTED
Definition at line 285 of file albaDecl.h.
IMPORT_FILE
IMPORT_FILE
Definition at line 287 of file albaDecl.h.
CLEAR_UNDO_STACK
CLEAR_UNDO_STACK
Definition at line 289 of file albaDecl.h.
LOG_ALL_EVENT
LOG_ALL_EVENT
Definition at line 291 of file albaDecl.h.
LOG_TO_FILE
LOG_TO_FILE
Definition at line 292 of file albaDecl.h.
MOUSE_DOWN
MOUSE_DOWN
Definition at line 295 of file albaDecl.h.
MOUSE_MOVE
MOUSE_MOVE
Definition at line 296 of file albaDecl.h.
MOUSE_UP
MOUSE_UP
Definition at line 297 of file albaDecl.h.
MOUSE_WHEEL
MOUSE_WHEEL
Definition at line 298 of file albaDecl.h.
ID_TRANSFORM
ID_TRANSFORM
Definition at line 300 of file albaDecl.h.
SHOW_VIEW_CONTEXTUAL_MENU
SHOW_VIEW_CONTEXTUAL_MENU
Definition at line 301 of file albaDecl.h.
SHOW_TREE_CONTEXTUAL_MENU
SHOW_TREE_CONTEXTUAL_MENU
Definition at line 302 of file albaDecl.h.
INTERACTOR_ADD
INTERACTOR_ADD
Definition at line 305 of file albaDecl.h.
INTERACTOR_REMOVE
INTERACTOR_REMOVE
Definition at line 306 of file albaDecl.h.
DEVICE_ADD
DEVICE_ADD
Definition at line 308 of file albaDecl.h.
DEVICE_REMOVE
DEVICE_REMOVE
Definition at line 309 of file albaDecl.h.
DEVICE_GET
DEVICE_GET
Definition at line 310 of file albaDecl.h.
TILE_WINDOW_CASCADE
TILE_WINDOW_CASCADE
Definition at line 312 of file albaDecl.h.
TILE_WINDOW_HORIZONTALLY
TILE_WINDOW_HORIZONTALLY
Definition at line 313 of file albaDecl.h.
TILE_WINDOW_VERTICALLY
TILE_WINDOW_VERTICALLY
Definition at line 314 of file albaDecl.h.
EVT_USER_START
EVT_USER_START
Definition at line 316 of file albaDecl.h.
EVT_USER_END
EVT_USER_END = EVT_USER_START + 1000
Definition at line 317 of file albaDecl.h.
EVT_END
EVT_END
Definition at line 319 of file albaDecl.h.
MENU_USER_START
MENU_USER_START
Definition at line 321 of file albaDecl.h.
MENU_USER_END
MENU_USER_END = MENU_USER_START + 1000
Definition at line 322 of file albaDecl.h.
MENU_END
MENU_END
Definition at line 324 of file albaDecl.h.
OP_START
OP_START
Definition at line 328 of file albaDecl.h.
OP_UNDO
OP_UNDO
Definition at line 329 of file albaDecl.h.
OP_REDO
OP_REDO
Definition at line 330 of file albaDecl.h.
OP_DELETE
OP_DELETE
Definition at line 331 of file albaDecl.h.
OP_CUT
OP_CUT
Definition at line 332 of file albaDecl.h.
OP_COPY
OP_COPY
Definition at line 333 of file albaDecl.h.
OP_PASTE
OP_PASTE
Definition at line 334 of file albaDecl.h.
OP_RENAME
OP_RENAME
Definition at line 335 of file albaDecl.h.
OP_REPARENT
OP_REPARENT
Definition at line 336 of file albaDecl.h.
OP_ADD_GROUP
OP_ADD_GROUP
Definition at line 337 of file albaDecl.h.
OP_SELECT
OP_SELECT
Definition at line 338 of file albaDecl.h.
OP_TRANSFORM
OP_TRANSFORM
Definition at line 339 of file albaDecl.h.
OP_USER
OP_USER
Definition at line 340 of file albaDecl.h.
OP_END
OP_END = OP_START + MAXOP
Definition at line 341 of file albaDecl.h.
VIEW_START
VIEW_START
Definition at line 345 of file albaDecl.h.
VIEW_END
VIEW_END = VIEW_START + MAXVIEW
Definition at line 346 of file albaDecl.h.
WIDGETS_START
WIDGETS_START
Definition at line 350 of file albaDecl.h.
ID_LAYOUT
ID_LAYOUT
Definition at line 351 of file albaDecl.h.
ID_CLOSE_SASH
ID_CLOSE_SASH
Definition at line 352 of file albaDecl.h.
ID_LABEL_CLICK
ID_LABEL_CLICK
Definition at line 353 of file albaDecl.h.
ID_DISPLAY_LIST
ID_DISPLAY_LIST
Definition at line 354 of file albaDecl.h.
ID_SETTINGS
ID_SETTINGS
Definition at line 355 of file albaDecl.h.
ID_RANGE_MODIFIED
ID_RANGE_MODIFIED
Definition at line 356 of file albaDecl.h.
WIDGETS_END
WIDGETS_END
Definition at line 357 of file albaDecl.h.
PIC_START
PIC_START
Definition at line 360 of file albaDecl.h.
TIME_SET
TIME_SET
Definition at line 361 of file albaDecl.h.
TIME_PLAY
TIME_PLAY
Definition at line 362 of file albaDecl.h.
TIME_STOP
TIME_STOP
Definition at line 363 of file albaDecl.h.
TIME_PREV
TIME_PREV
Definition at line 364 of file albaDecl.h.
TIME_NEXT
TIME_NEXT
Definition at line 365 of file albaDecl.h.
TIME_BEGIN
TIME_BEGIN
Definition at line 366 of file albaDecl.h.
TIME_END
TIME_END
Definition at line 367 of file albaDecl.h.
MOVIE_RECORD
MOVIE_RECORD
Definition at line 368 of file albaDecl.h.
PIC_END
PIC_END
Definition at line 378 of file albaDecl.h.
PIC_USER_START
PIC_USER_START = PIC_START + 500
Definition at line 379 of file albaDecl.h.
PIC_USER_END
PIC_USER_END = PIC_USER_START + 100
Definition at line 380 of file albaDecl.h.
PARSE_STRING
PARSE_STRING
Definition at line 382 of file albaDecl.h.
APPSTAMP
APPSTAMP
Definition at line 383 of file albaDecl.h.
MCH_START
MCH_START
Definition at line 386 of file albaDecl.h.
MCH_UP
MCH_UP
channel used to send events up in the tree
Definition at line 387 of file albaDecl.h.
MCH_DOWN
MCH_DOWN
channel used to send events down in the tree
Definition at line 388 of file albaDecl.h.
MCH_INPUT
MCH_INPUT
channel used for events coming from an input device
Definition at line 389 of file albaDecl.h.
MCH_OUTPUT
MCH_OUTPUT
channel used for events sent to an output device
Definition at line 390 of file albaDecl.h.
MCH_NODE
MCH_NODE
channel used by nodes for sending events to observers
Definition at line 391 of file albaDecl.h.
MCH_ANY
MCH_ANY
Id used by albaAgent to identify any channel connected to it.
Definition at line 392 of file albaDecl.h.
MCH_VTK
MCH_VTK
channel used to as a bridge from VTK objects
Definition at line 393 of file albaDecl.h.
MCH_END
MCH_END
Definition at line 394 of file albaDecl.h.
NODE_START
NODE_START
Definition at line 397 of file albaDecl.h.
NODE_DETACHED_FROM_TREE
NODE_DETACHED_FROM_TREE
issued when the node is detachment from the tree
Definition at line 398 of file albaDecl.h.
NODE_ATTACHED_TO_TREE
NODE_ATTACHED_TO_TREE
issued when the node is attached to the tree
Definition at line 399 of file albaDecl.h.
NODE_DESTROYED
NODE_DESTROYED
issued when the node is destroyed
Definition at line 400 of file albaDecl.h.
NODE_GET_STORAGE
NODE_GET_STORAGE
issued by tree elements to retrieve the storage (served by albaVMERoot)
Definition at line 401 of file albaDecl.h.
NODE_GET_ROOT
NODE_GET_ROOT
issued by subnode components to extract ROOT node
Definition at line 402 of file albaDecl.h.
VME_TIME_SET
VME_TIME_SET
used either to set or to advise of time changes
Definition at line 403 of file albaDecl.h.
VME_MATRIX_CHANGED
VME_MATRIX_CHANGED
issued when the matrix in the output has changed (e.g. when matrix pipe is changed at runtime)
Definition at line 404 of file albaDecl.h.
VME_MATRIX_PREUPDATE
VME_MATRIX_PREUPDATE
issued by albaMatrixPipe before updating the matrix
Definition at line 405 of file albaDecl.h.
VME_MATRIX_UPDATE
VME_MATRIX_UPDATE
issued when pose matrix is updated
Definition at line 406 of file albaDecl.h.
VME_ABSMATRIX_UPDATE
VME_ABSMATRIX_UPDATE
issued when absolute pose matrix is updated
Definition at line 407 of file albaDecl.h.
VME_OUTPUT_DATA_PREUPDATE
VME_OUTPUT_DATA_PREUPDATE
issued by albaDataPipe before the output data is actually updated
Definition at line 408 of file albaDecl.h.
VME_OUTPUT_DATA_UPDATE
VME_OUTPUT_DATA_UPDATE
issued when the output data is updated
Definition at line 409 of file albaDecl.h.
VME_OUTPUT_DATA_CHANGED
VME_OUTPUT_DATA_CHANGED
issued when the output data object has changed (i.e. object pointer changed)
Definition at line 410 of file albaDecl.h.
VME_GET_NEWITEM_ID
VME_GET_NEWITEM_ID
issued by VMEItems or DataVector to retrieve a new item-ID (served by albaVMERoot)
Definition at line 411 of file albaDecl.h.
NODE_END
NODE_END
Definition at line 412 of file albaDecl.h.
AVATAR_ADDED
AVATAR_ADDED
used to advise the InteractionManager an avatar has been added (issued by mmdTracker's)
Definition at line 414 of file albaDecl.h.
AVATAR_REMOVED
AVATAR_REMOVED
used to advise the InteractionManager an avatar has been removed (issued by mmdTracker's)
Definition at line 415 of file albaDecl.h.
MATRIX_UPDATED
MATRIX_UPDATED
issue by a matrix pipe to advise consumers of output matrix updating
Definition at line 417 of file albaDecl.h.
MINID
MINID
Definition at line 420 of file albaDecl.h.
Referenced by albaGUI::GetModuleId().
MAXID
MAXID = MINID + MAXWIDGET
Definition at line 421 of file albaDecl.h.
ID_GUI_UPDATE
ID_GUI_UPDATE
Definition at line 423 of file albaDecl.h.