ALBA 2: itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh > Class Template Reference
itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh > Class Template Reference
#include <vtkALBADeformableSimplexMeshFilter.h>
Public Types
typedef vtkALBADeformableSimplexMeshFilter Self
typedef DeformableSimplexMesh3DFilter< TInputMesh, TOutputMesh > Superclass
typedef SmartPointer< Self > Pointer
typedef SmartPointer< const Self > ConstPointer
typedef TInputMesh InputMeshType
typedef TOutputMesh OutputMeshType
typedef Superclass::PointType PointType
typedef Superclass::GradientIndexType GradientIndexType
typedef Superclass::GradientIndexValueType GradientIndexValueType
typedef Superclass::GradientType GradientType
typedef Superclass::GradientImageType GradientImageType
typedef InputMeshType::Pointer InputMeshPointer
typedef OutputMeshType::Pointer OutputMeshPointer
typedef InputMeshType::PixelType PixelType
typedef Image< PixelType, 3 > GradientIntensityImageType
typedef GradientIntensityImageType::Pointer GradientIntensityImagePointer
typedef Image< float, 3 > OriginalImageType
typedef OriginalImageType::IndexType OriginalImageIndexType
typedef OriginalImageIndexType::IndexValueType ImageIndexValueType
typedef OriginalImageType::ConstPointer OriginalImagePointer
typedef vtkALBAStentModelSource::Strut Strut
typedef std::vector< Strut >::const_iterator StrutIterator
typedef itk::Vector< double, 3 > VectorType
Public Member Functions
itkNewMacro (Self)
itkTypeMacro (vtkALBADeformableSimplexMeshFilter, DeformableSimplexMesh3DFilter)
void SetStrutLength (double len)
double GetStrutLength () const
void SetLinkLength (double len)
double GetLinkLength () const
void SetCurrentStepNum (double n)
int GetCurrentStepNum () const
void SetEpsilon (double len)
double GetEpsilon () const
void SetStrutLinkIter (StrutIterator StrutStart, StrutIterator StrutEnd, StrutIterator LinkStart, StrutIterator LinkEnd)
void SetStrutLinkFromCellArray (vtkCellArray *strut, vtkCellArray *link)
void SetVesselPointsKDTreeFromPolyData (vtkPolyData *surface)
int IsPointInsideVessel1 (const double *stentPoint, double *surfacePoint) const
int IsPointInsideVessel2 (const double *stentPoint, double *surfacePoint) const
int IsPointInsideVessel2 (const double *stentPoint, int surfacePtId) const
double computeDirectionFromPoint2Face (double *stentPoint, vtkIdType p1, vtkIdType p2, vtkIdType p3)
void SetCenterLocationIdx (std::vector< int >::const_iterator centerLocationIndex)
void SetCenterLocationIdxRef (std::vector< int > const &ve)
void SetTestValue (int value)
void vectorSubtract (double *endPoint, double *startPoint, double *result)
const CatheterCalculator * GetCatheterCalculator () const
CatheterCalculator * GetCatheterCalculator ()
const DeformationHistory * GetDeformationHistory () const
DeformationHistory * GetDeformationHistory ()
void SetMinDistanceToVessel (double dist)
Protected Member Functions
vtkALBADeformableSimplexMeshFilter ()
~vtkALBADeformableSimplexMeshFilter ()
vtkALBADeformableSimplexMeshFilter (const Self &)
void operator= (const Self &)
virtual void ComputeDisplacement ()
virtual void ComputeExternalForce (SimplexMeshGeometry *data)
Protected Attributes
double m_StrutLength
double m_LinkLength
Detailed Description
template<class TInputMesh, class TOutputMesh>
class itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >
Definition at line 49 of file vtkALBADeformableSimplexMeshFilter.h.
Member Typedef Documentation
Self
template<class TInputMesh , class TOutputMesh > typedef vtkALBADeformableSimplexMeshFilter itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::Self
Standard "Self" typedefs.
Definition at line 54 of file vtkALBADeformableSimplexMeshFilter.h.
Superclass
template<class TInputMesh , class TOutputMesh > typedef DeformableSimplexMesh3DFilter< TInputMesh, TOutputMesh > itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::Superclass
Standard "Superclass" typedef.
Definition at line 57 of file vtkALBADeformableSimplexMeshFilter.h.
Pointer
template<class TInputMesh , class TOutputMesh > typedef SmartPointer< Self > itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::Pointer
Smart pointer typedef support.
Definition at line 60 of file vtkALBADeformableSimplexMeshFilter.h.
ConstPointer
template<class TInputMesh , class TOutputMesh > typedef SmartPointer< const Self > itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::ConstPointer
Definition at line 61 of file vtkALBADeformableSimplexMeshFilter.h.
InputMeshType
template<class TInputMesh , class TOutputMesh > typedef TInputMesh itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::InputMeshType
Some typedefs.
Definition at line 70 of file vtkALBADeformableSimplexMeshFilter.h.
OutputMeshType
template<class TInputMesh , class TOutputMesh > typedef TOutputMesh itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::OutputMeshType
Definition at line 71 of file vtkALBADeformableSimplexMeshFilter.h.
PointType
template<class TInputMesh , class TOutputMesh > typedef Superclass::PointType itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::PointType
Definition at line 73 of file vtkALBADeformableSimplexMeshFilter.h.
GradientIndexType
template<class TInputMesh , class TOutputMesh > typedef Superclass::GradientIndexType itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::GradientIndexType
Definition at line 74 of file vtkALBADeformableSimplexMeshFilter.h.
GradientIndexValueType
template<class TInputMesh , class TOutputMesh > typedef Superclass::GradientIndexValueType itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::GradientIndexValueType
Definition at line 75 of file vtkALBADeformableSimplexMeshFilter.h.
GradientType
template<class TInputMesh , class TOutputMesh > typedef Superclass::GradientType itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::GradientType
Definition at line 76 of file vtkALBADeformableSimplexMeshFilter.h.
GradientImageType
template<class TInputMesh , class TOutputMesh > typedef Superclass::GradientImageType itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::GradientImageType
Definition at line 77 of file vtkALBADeformableSimplexMeshFilter.h.
InputMeshPointer
template<class TInputMesh , class TOutputMesh > typedef InputMeshType::Pointer itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::InputMeshPointer
Mesh pointer definition.
Definition at line 80 of file vtkALBADeformableSimplexMeshFilter.h.
OutputMeshPointer
template<class TInputMesh , class TOutputMesh > typedef OutputMeshType::Pointer itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::OutputMeshPointer
Definition at line 81 of file vtkALBADeformableSimplexMeshFilter.h.
PixelType
template<class TInputMesh , class TOutputMesh > typedef InputMeshType::PixelType itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::PixelType
Definition at line 83 of file vtkALBADeformableSimplexMeshFilter.h.
GradientIntensityImageType
template<class TInputMesh , class TOutputMesh > typedef Image< PixelType, 3 > itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::GradientIntensityImageType
Definition at line 85 of file vtkALBADeformableSimplexMeshFilter.h.
GradientIntensityImagePointer
template<class TInputMesh , class TOutputMesh > typedef GradientIntensityImageType::Pointer itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::GradientIntensityImagePointer
Definition at line 86 of file vtkALBADeformableSimplexMeshFilter.h.
OriginalImageType
template<class TInputMesh , class TOutputMesh > typedef Image< float, 3 > itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::OriginalImageType
Definition at line 88 of file vtkALBADeformableSimplexMeshFilter.h.
OriginalImageIndexType
template<class TInputMesh , class TOutputMesh > typedef OriginalImageType::IndexType itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::OriginalImageIndexType
Definition at line 89 of file vtkALBADeformableSimplexMeshFilter.h.
ImageIndexValueType
template<class TInputMesh , class TOutputMesh > typedef OriginalImageIndexType::IndexValueType itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::ImageIndexValueType
Definition at line 90 of file vtkALBADeformableSimplexMeshFilter.h.
OriginalImagePointer
template<class TInputMesh , class TOutputMesh > typedef OriginalImageType::ConstPointer itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::OriginalImagePointer
Definition at line 91 of file vtkALBADeformableSimplexMeshFilter.h.
Strut
template<class TInputMesh , class TOutputMesh > typedef vtkALBAStentModelSource::Strut itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::Strut
Definition at line 93 of file vtkALBADeformableSimplexMeshFilter.h.
StrutIterator
template<class TInputMesh , class TOutputMesh > typedef std::vector<Strut>::const_iterator itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::StrutIterator
Definition at line 94 of file vtkALBADeformableSimplexMeshFilter.h.
VectorType
template<class TInputMesh , class TOutputMesh > typedef itk::Vector< double, 3 > itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::VectorType
Definition at line 95 of file vtkALBADeformableSimplexMeshFilter.h.
Constructor & Destructor Documentation
vtkALBADeformableSimplexMeshFilter() [1/2]
template<typename TInputMesh , typename TOutputMesh > itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::vtkALBADeformableSimplexMeshFilter protected
Definition at line 26 of file vtkALBADeformableSimplexMeshFilter_Impl.h.
~vtkALBADeformableSimplexMeshFilter()
template<typename TInputMesh , typename TOutputMesh > itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::~vtkALBADeformableSimplexMeshFilter protected
Definition at line 43 of file vtkALBADeformableSimplexMeshFilter_Impl.h.
vtkALBADeformableSimplexMeshFilter() [2/2]
template<class TInputMesh , class TOutputMesh > itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::vtkALBADeformableSimplexMeshFilter (const Self &) inline protected
Definition at line 158 of file vtkALBADeformableSimplexMeshFilter.h.
Member Function Documentation
itkNewMacro()
template<class TInputMesh , class TOutputMesh > itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::itkNewMacro (Self)
Method for creation through the object factory.
itkTypeMacro()
template<class TInputMesh , class TOutputMesh > itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::itkTypeMacro (vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh > , DeformableSimplexMesh3DFilter)
Run-time type information (and related methods).
SetStrutLength()
template<class TInputMesh , class TOutputMesh > void itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::SetStrutLength (double len) inline
Definition at line 104 of file vtkALBADeformableSimplexMeshFilter.h.
References itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::m_StrutLength.
GetStrutLength()
template<class TInputMesh , class TOutputMesh > double itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::GetStrutLength () const inline
Definition at line 105 of file vtkALBADeformableSimplexMeshFilter.h.
References itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::m_StrutLength.
SetLinkLength()
template<class TInputMesh , class TOutputMesh > void itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::SetLinkLength (double len) inline
Definition at line 107 of file vtkALBADeformableSimplexMeshFilter.h.
References itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::m_LinkLength.
GetLinkLength()
template<class TInputMesh , class TOutputMesh > double itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::GetLinkLength () const inline
Definition at line 108 of file vtkALBADeformableSimplexMeshFilter.h.
References itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::m_LinkLength.
SetCurrentStepNum()
template<class TInputMesh , class TOutputMesh > void itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::SetCurrentStepNum (double n) inline
Definition at line 110 of file vtkALBADeformableSimplexMeshFilter.h.
GetCurrentStepNum()
template<class TInputMesh , class TOutputMesh > int itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::GetCurrentStepNum () const inline
Definition at line 111 of file vtkALBADeformableSimplexMeshFilter.h.
SetEpsilon()
template<class TInputMesh , class TOutputMesh > void itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::SetEpsilon (double len) inline
Definition at line 113 of file vtkALBADeformableSimplexMeshFilter.h.
GetEpsilon()
template<class TInputMesh , class TOutputMesh > double itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::GetEpsilon () const inline
Definition at line 114 of file vtkALBADeformableSimplexMeshFilter.h.
SetStrutLinkIter()
template<typename TInputMesh , typename TOutputMesh > void itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::SetStrutLinkIter (StrutIterator StrutStart, StrutIterator StrutEnd, StrutIterator LinkStart, StrutIterator LinkEnd)
Definition at line 137 of file vtkALBADeformableSimplexMeshFilter_Impl.h.
SetStrutLinkFromCellArray()
template<typename TInputMesh , typename TOutputMesh > void itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::SetStrutLinkFromCellArray (vtkCellArray * strut, vtkCellArray * link)
Definition at line 68 of file vtkALBADeformableSimplexMeshFilter_Impl.h.
SetVesselPointsKDTreeFromPolyData()
template<typename TInputMesh , typename TOutputMesh > void itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::SetVesselPointsKDTreeFromPolyData (vtkPolyData * surface)
Definition at line 194 of file vtkALBADeformableSimplexMeshFilter_Impl.h.
References kd_create(), and kd_insert3().
IsPointInsideVessel1()
template<typename TInputMesh , typename TOutputMesh > int itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::IsPointInsideVessel1 (const double * stentPoint, double * surfacePoint) const
Check if point is inside the vessel: 1 inside, outside
This version uses the surrounding cells of the nearest point.
Definition at line 368 of file vtkALBADeformableSimplexMeshFilter.h.
IsPointInsideVessel2() [1/2]
template<typename TInputMesh , typename TOutputMesh > int itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::IsPointInsideVessel2 (const double * stentPoint, double * surfacePoint) const
Check if point is inside the vessel: 1 inside, outside.
This version uses the polydata normals.
Definition at line 394 of file vtkALBADeformableSimplexMeshFilter.h.
IsPointInsideVessel2() [2/2]
template<typename TInputMesh , typename TOutputMesh > int itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::IsPointInsideVessel2 (const double * stentPoint, int surfacePtId) const
Check if point is inside the vessel: 1 inside, outside.
This version uses the polydata normals.
Definition at line 416 of file vtkALBADeformableSimplexMeshFilter.h.
computeDirectionFromPoint2Face()
template<typename TInputMesh , typename TOutputMesh > double itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::computeDirectionFromPoint2Face (double * stentPoint, vtkIdType p1, vtkIdType p2, vtkIdType p3)
Definition at line 230 of file vtkALBADeformableSimplexMeshFilter_Impl.h.
SetCenterLocationIdx()
template<typename TInputMesh , typename TOutputMesh > void itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::SetCenterLocationIdx (std::vector< int >::const_iterator centerLocationIndex)
Definition at line 276 of file vtkALBADeformableSimplexMeshFilter_Impl.h.
SetCenterLocationIdxRef()
template<typename TInputMesh , typename TOutputMesh > void itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::SetCenterLocationIdxRef (std::vector< int > const & ve)
Definition at line 283 of file vtkALBADeformableSimplexMeshFilter_Impl.h.
SetTestValue()
template<class TInputMesh , class TOutputMesh > void itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::SetTestValue (int value) inline
Definition at line 139 of file vtkALBADeformableSimplexMeshFilter.h.
vectorSubtract()
template<typename TInputMesh , typename TOutputMesh > void itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::vectorSubtract (double * endPoint, double * startPoint, double * result)
Definition at line 217 of file vtkALBADeformableSimplexMeshFilter_Impl.h.
GetCatheterCalculator() [1/2]
template<class TInputMesh , class TOutputMesh > const CatheterCalculator * itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::GetCatheterCalculator () const inline
Get catheter position calculator.
Definition at line 144 of file vtkALBADeformableSimplexMeshFilter.h.
GetCatheterCalculator() [2/2]
template<class TInputMesh , class TOutputMesh > CatheterCalculator * itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::GetCatheterCalculator () inline
Get catheter position calculator.
Definition at line 147 of file vtkALBADeformableSimplexMeshFilter.h.
GetDeformationHistory() [1/2]
template<class TInputMesh , class TOutputMesh > const DeformationHistory * itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::GetDeformationHistory () const inline
Get deformation info.
Definition at line 150 of file vtkALBADeformableSimplexMeshFilter.h.
GetDeformationHistory() [2/2]
template<class TInputMesh , class TOutputMesh > DeformationHistory * itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::GetDeformationHistory () inline
Definition at line 151 of file vtkALBADeformableSimplexMeshFilter.h.
SetMinDistanceToVessel()
template<class TInputMesh , class TOutputMesh > void itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::SetMinDistanceToVessel (double dist) inline
Definition at line 153 of file vtkALBADeformableSimplexMeshFilter.h.
operator=()
template<class TInputMesh , class TOutputMesh > void itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::operator= (const Self &) inline protected
Definition at line 159 of file vtkALBADeformableSimplexMeshFilter.h.
ComputeDisplacement()
template<typename TInputMesh , typename TOutputMesh > void itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::ComputeDisplacement protected virtual
Definition at line 299 of file vtkALBADeformableSimplexMeshFilter_Impl.h.
References kd_nearest3(), and kd_res_item().
ComputeExternalForce()
template<typename TInputMesh , typename TOutputMesh > void itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::ComputeExternalForce (SimplexMeshGeometry * data) protected virtual
Definition at line 432 of file vtkALBADeformableSimplexMeshFilter_Impl.h.
Member Data Documentation
m_StrutLength
template<class TInputMesh , class TOutputMesh > double itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::m_StrutLength protected
Definition at line 164 of file vtkALBADeformableSimplexMeshFilter.h.
Referenced by itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::GetStrutLength(), and itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::SetStrutLength().
m_LinkLength
template<class TInputMesh , class TOutputMesh > double itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::m_LinkLength protected
Definition at line 165 of file vtkALBADeformableSimplexMeshFilter.h.
Referenced by itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::GetLinkLength(), and itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::SetLinkLength().
The documentation for this class was generated from the following files:
vtkALBADeformableSimplexMeshFilter.h
vtkALBADeformableSimplexMeshFilter_Impl.h