ALBA 2: vtkALBAPolyDataDeformation_M1::CSkeletonVertex Class Reference
vtkALBAPolyDataDeformation_M1::CSkeletonVertex Class Reference
#include <vtkALBAPolyDataDeformation_M1.h>
Classes
struct LOCAL_FRAME
Public Types
typedef struct vtkALBAPolyDataDeformation_M1::CSkeletonVertex::LOCAL_FRAME LOCAL_FRAME
Public Member Functions
CSkeletonVertex ()
CSkeletonVertex (double coords[3])
int GetDegree ()
bool IsInPositiveHalfspace (double coords[3])
Public Attributes
int m_Id
double m_Coords [3]
LOCAL_FRAME m_LF
CSkeletonVertex * m_pMatch
std::vector< CSkeletonEdge * > m_OneRingEdges
double m_WT
int m_nMark
Detailed Description
Definition at line 116 of file vtkALBAPolyDataDeformation_M1.h.
Member Typedef Documentation
LOCAL_FRAME
typedef struct vtkALBAPolyDataDeformation_M1::CSkeletonVertex::LOCAL_FRAME vtkALBAPolyDataDeformation_M1::CSkeletonVertex::LOCAL_FRAME
Constructor & Destructor Documentation
CSkeletonVertex() [1/2]
vtkALBAPolyDataDeformation_M1::CSkeletonVertex::CSkeletonVertex () inline
Definition at line 138 of file vtkALBAPolyDataDeformation_M1.h.
CSkeletonVertex() [2/2]
vtkALBAPolyDataDeformation_M1::CSkeletonVertex::CSkeletonVertex (double coords[3]) inline
Definition at line 148 of file vtkALBAPolyDataDeformation_M1.h.
Member Function Documentation
GetDegree()
int vtkALBAPolyDataDeformation_M1::CSkeletonVertex::GetDegree () inline
Gets the degree of this vertex.
Definition at line 162 of file vtkALBAPolyDataDeformation_M1.h.
Referenced by vtkALBAPolyDataDeformation_M1::GetNextCurveEdge(), vtkALBAPolyDataDeformation_M1::CSkeletonEdge::GetNumberOfConnectedEdges(), vtkALBAPolyDataDeformation_M1::GetPreviousCurveEdge(), vtkALBAPolyDataDeformation_M1::GetPreviousCurveVertex(), and vtkALBAPolyDataDeformation_M1::CSkeletonEdge::IsInternal().
IsInPositiveHalfspace()
bool vtkALBAPolyDataDeformation_M1::CSkeletonVertex::IsInPositiveHalfspace (double coords[3]) inline
Returns true, if the given point lies in the direction LF.u of the half-space defined by the LF.v, LF.w and m_Coords
Definition at line 169 of file vtkALBAPolyDataDeformation_M1.h.
References vtkALBAPolyDataDeformation_M1::CSkeletonVertex::LOCAL_FRAME::u.
Member Data Documentation
m_Id
int vtkALBAPolyDataDeformation_M1::CSkeletonVertex::m_Id
Definition at line 119 of file vtkALBAPolyDataDeformation_M1.h.
m_Coords
double vtkALBAPolyDataDeformation_M1::CSkeletonVertex::m_Coords[3]
Definition at line 120 of file vtkALBAPolyDataDeformation_M1.h.
m_LF
LOCAL_FRAME vtkALBAPolyDataDeformation_M1::CSkeletonVertex::m_LF
Definition at line 129 of file vtkALBAPolyDataDeformation_M1.h.
m_pMatch
CSkeletonVertex* vtkALBAPolyDataDeformation_M1::CSkeletonVertex::m_pMatch
Definition at line 130 of file vtkALBAPolyDataDeformation_M1.h.
m_OneRingEdges
std::vector< CSkeletonEdge* > vtkALBAPolyDataDeformation_M1::CSkeletonVertex::m_OneRingEdges
Definition at line 132 of file vtkALBAPolyDataDeformation_M1.h.
Referenced by vtkALBAPolyDataDeformation_M1::GetNextCurveEdge(), vtkALBAPolyDataDeformation_M1::GetNextCurveVertex(), vtkALBAPolyDataDeformation_M1::GetPreviousCurveEdge(), and vtkALBAPolyDataDeformation_M1::GetPreviousCurveVertex().
m_WT
double vtkALBAPolyDataDeformation_M1::CSkeletonVertex::m_WT
Definition at line 134 of file vtkALBAPolyDataDeformation_M1.h.
m_nMark
int vtkALBAPolyDataDeformation_M1::CSkeletonVertex::m_nMark
Definition at line 135 of file vtkALBAPolyDataDeformation_M1.h.
The documentation for this class was generated from the following file:
vtkALBAPolyDataDeformation_M1.h