ALBA: albaCurvilinearAbscissaOnSkeletonHelper Class Reference
albaCurvilinearAbscissaOnSkeletonHelper Class Reference
#include <albaCurvilinearAbscissaOnSkeletonHelper.h>
Public Member Functions
albaCurvilinearAbscissaOnSkeletonHelper (albaVME *inputVME, albaObserver *listener=NULL, bool testMode=false)
void SetConstraintPolylineGraph (albaVMEPolylineGraph *constraintPolylineGraph)
albaVMEPolylineGraph * GetSetConstraintPolylineGraph ()
int SetCurvilinearAbscissa (vtkIdType branchId, double s)
double GetCurvilinearAbscissa ()
vtkIdType GetActiveBranchId ()
void MoveOnSkeleton (albaEvent *mouseEvent)
~albaCurvilinearAbscissaOnSkeletonHelper ()
virtual void OnEvent (albaEventBase *alba_event)
albaGUI * GetGui ()
virtual void EnableWidgets (bool enable)
Detailed Description
Decorate input vme with curvilinear abscissa interface for albaVMEPolylineGraph constrained interaction.
Definition at line 38 of file albaCurvilinearAbscissaOnSkeletonHelper.h.
Constructor & Destructor Documentation
albaCurvilinearAbscissaOnSkeletonHelper()
albaCurvilinearAbscissaOnSkeletonHelper::albaCurvilinearAbscissaOnSkeletonHelper (albaVME * inputVME, albaObserver * listener = NULL, bool testMode = false)
Pass the vme you want to decorate with curvilinear abscissa interface.
~albaCurvilinearAbscissaOnSkeletonHelper()
albaCurvilinearAbscissaOnSkeletonHelper::~albaCurvilinearAbscissaOnSkeletonHelper ()
Member Function Documentation
SetConstraintPolylineGraph()
void albaCurvilinearAbscissaOnSkeletonHelper::SetConstraintPolylineGraph (albaVMEPolylineGraph * constraintPolylineGraph)
Set the polyline graph constraint.
Referenced by albaGizmoPolylineGraph::SetConstraintPolylineGraph().
GetSetConstraintPolylineGraph()
albaVMEPolylineGraph * albaCurvilinearAbscissaOnSkeletonHelper::GetSetConstraintPolylineGraph () inline
Get the polyline graph constraint.
Definition at line 49 of file albaCurvilinearAbscissaOnSkeletonHelper.h.
SetCurvilinearAbscissa()
int albaCurvilinearAbscissaOnSkeletonHelper::SetCurvilinearAbscissa (vtkIdType branchId, double s)
Set the curvilinear abscissa value s on branchId branch, return ALBA_OK or ALBA_ERROR.
Referenced by albaGizmoPolylineGraph::SetCurvilinearAbscissa().
GetCurvilinearAbscissa()
double albaCurvilinearAbscissaOnSkeletonHelper::GetCurvilinearAbscissa () inline
Get the curvilinear abscissa.
Definition at line 55 of file albaCurvilinearAbscissaOnSkeletonHelper.h.
Referenced by albaGizmoPolylineGraph::GetCurvilinearAbscissa().
GetActiveBranchId()
vtkIdType albaCurvilinearAbscissaOnSkeletonHelper::GetActiveBranchId () inline
Get the active branch ie the branch to which inputVME is currently constrained.
Definition at line 58 of file albaCurvilinearAbscissaOnSkeletonHelper.h.
Referenced by albaGizmoPolylineGraph::GetActiveBranchId().
MoveOnSkeleton()
void albaCurvilinearAbscissaOnSkeletonHelper::MoveOnSkeleton (albaEvent * mouseEvent)
Move input vme constrained to skeleton in response to mouse events: use in your client as:
Client::OnEvent(e) { case ID_TRANSFORM: { m_CurvilinearAbscissaHelper->MoveOnSkeleton(e); } }
where e is mouse move event coming from the vme interactor. See albaGizmoInteractionDebugger and albaOpInteractionDebugger for example usage.
OnEvent()
virtual void albaCurvilinearAbscissaOnSkeletonHelper::OnEvent (albaEventBase * alba_event) virtual
GUI Stuff.
Implements albaObserver.
GetGui()
albaGUI * albaCurvilinearAbscissaOnSkeletonHelper::GetGui () inline
Return the gui to be plugged.
Definition at line 83 of file albaCurvilinearAbscissaOnSkeletonHelper.h.
EnableWidgets()
virtual void albaCurvilinearAbscissaOnSkeletonHelper::EnableWidgets (bool enable) virtual
Enable-Disable the GUI's widgets.
The documentation for this class was generated from the following file:
albaCurvilinearAbscissaOnSkeletonHelper.h