ALBA 2: Triangulation< Real > Class Template Reference
Triangulation< Real > Class Template Reference
#include <vtkALBAPoissonSurfaceReconstruction.h>
Public Member Functions
int Factor (const int &tIndex, int &p1, int &p2, int &p3)
double Area (void)
double Area (const int &tIndex)
double Area (const int &p1, const int &p2, const int &p3)
int FlipMinimize (const int &eIndex)
int AddTriangle (const int &p1, const int &p2, const int &p3)
Public Attributes
std::vector< Point3D< Real > > points
std::vector< TriangulationEdge > edges
std::vector< TriangulationTriangle > triangles
Protected Member Functions
double Area (const Triangle &t)
Static Protected Member Functions
static long long EdgeIndex (const int &p1, const int &p2)
Protected Attributes
unordered_map< long long, int > edgeMap
Detailed Description
template<class Real>
class Triangulation< Real >
class name: Triangulation Handle the triangulation process
Definition at line 1179 of file vtkALBAPoissonSurfaceReconstruction.h.
Member Function Documentation
Factor()
template<class Real > int Triangulation< Real >::Factor (const int & tIndex, int & p1, int & p2, int & p3) inline
return 0 or 1 , modifying triangle points coordinate
Definition at line 1188 of file vtkALBAPoissonSurfaceReconstruction.h.
References Triangulation< Real >::edges, and Triangulation< Real >::triangles.
Referenced by Triangulation< Real >::Area(), and Triangulation< Real >::FlipMinimize().
Area() [1/4]
template<class Real > double Triangulation< Real >::Area (void) inline
calculate total area of triangles
Definition at line 1200 of file vtkALBAPoissonSurfaceReconstruction.h.
References Triangulation< Real >::Area(), and Triangulation< Real >::triangles.
Referenced by Triangulation< Real >::Area(), and Triangulation< Real >::FlipMinimize().
Area() [2/4]
template<class Real > double Triangulation< Real >::Area (const int & tIndex) inline
calculate area of the triangle
Definition at line 1206 of file vtkALBAPoissonSurfaceReconstruction.h.
References Triangulation< Real >::Area(), and Triangulation< Real >::Factor().
Area() [3/4]
template<class Real > double Triangulation< Real >::Area (const int & p1, const int & p2, const int & p3) inline
calculate area with cross product
Definition at line 1212 of file vtkALBAPoissonSurfaceReconstruction.h.
References Point3D< Real >::coords, CrossProduct(), Length(), and Triangulation< Real >::points.
FlipMinimize()
template<class Real > int Triangulation< Real >::FlipMinimize (const int & eIndex) inline
flip edges in order to minimize the area of the triangle
Definition at line 1222 of file vtkALBAPoissonSurfaceReconstruction.h.
References Triangulation< Real >::Area(), Triangulation< Real >::edgeMap, Triangulation< Real >::edges, Triangulation< Real >::Factor(), and Triangulation< Real >::triangles.
AddTriangle()
template<class Real > int Triangulation< Real >::AddTriangle (const int & p1, const int & p2, const int & p3) inline
insert new triangle in the structure
Definition at line 1283 of file vtkALBAPoissonSurfaceReconstruction.h.
References Triangulation< Real >::edgeMap, Triangulation< Real >::edges, TriangulationEdge::pIndex, and Triangulation< Real >::triangles.
EdgeIndex()
template<class Real > static long long Triangulation< Real >::EdgeIndex (const int & p1, const int & p2) inline static protected
Definition at line 1325 of file vtkALBAPoissonSurfaceReconstruction.h.
Area() [4/4]
template<class Real > double Triangulation< Real >::Area (const Triangle & t) protected
Member Data Documentation
points
template<class Real > std::vector<Point3D<Real> > Triangulation< Real >::points
Definition at line 1183 of file vtkALBAPoissonSurfaceReconstruction.h.
Referenced by Triangulation< Real >::Area().
edges
template<class Real > std::vector<TriangulationEdge> Triangulation< Real >::edges
Definition at line 1184 of file vtkALBAPoissonSurfaceReconstruction.h.
Referenced by Triangulation< Real >::AddTriangle(), Triangulation< Real >::Factor(), and Triangulation< Real >::FlipMinimize().
triangles
template<class Real > std::vector<TriangulationTriangle> Triangulation< Real >::triangles
Definition at line 1185 of file vtkALBAPoissonSurfaceReconstruction.h.
Referenced by Triangulation< Real >::AddTriangle(), Triangulation< Real >::Area(), Triangulation< Real >::Factor(), and Triangulation< Real >::FlipMinimize().
edgeMap
template<class Real > unordered_map<long long,int> Triangulation< Real >::edgeMap protected
Definition at line 1324 of file vtkALBAPoissonSurfaceReconstruction.h.
Referenced by Triangulation< Real >::AddTriangle(), and Triangulation< Real >::FlipMinimize().
The documentation for this class was generated from the following file:
vtkALBAPoissonSurfaceReconstruction.h