ALBA 2: albaScalarVector Class Reference
albaScalarVector Class Reference
#include <albaScalarVector.h>
Public Types
typedef albaTimeMapScalar< double >::TimeMapScalars::iterator Iterator
Public Types inherited from albaTimeMapScalar< double >
typedef std::map< albaTimeStamp, double > TimeMapScalars
typedef std::map< albaTimeStamp, double > TimeMapScalars
typedef std::pair< albaTimeStamp, double > mmuTimePairScalars
typedef std::pair< albaTimeStamp, double > mmuTimePairScalars
Public Member Functions
albaScalarVector ()
virtual ~albaScalarVector ()
albaTypeMacro (albaScalarVector, albaObject)
void AppendScalar (albaTimeStamp t, double s)
double GetScalar (int idx)
void GetScalarVector (std::vector< double > &svector)
int GetNumberOfScalars () const
double GetNearestScalar (albaTimeStamp t)
double GetScalarBefore (albaTimeStamp t)
double GetScalar (albaTimeStamp t)
void SetScalar (albaTimeStamp t, double sca)
Public Member Functions inherited from albaTimeMapScalar< double >
albaTimeMapScalar ()
albaTimeMapScalar (const albaTimeMapScalar< double > &)
albaTimeMapScalar ()
albaTimeMapScalar (const albaTimeMapScalar< double > &)
virtual ~albaTimeMapScalar ()
virtual ~albaTimeMapScalar ()
void operator= (const albaTimeMapScalar< double > &)
void operator= (const albaTimeMapScalar< double > &)
void SetItemTypeName (const char *tname)
void SetItemTypeName (const char *tname)
const char * GetItemTypeName ()
const char * GetItemTypeName ()
virtual void AppendItem (albaTimeStamp t, double m)
virtual void AppendItem (albaTimeStamp t, double m)
virtual void PrependItem (albaTimeStamp t, double m)
virtual void PrependItem (albaTimeStamp t, double m)
albaTimeMapScalar< double >::TimeMapScalars::iterator FindItemByValue (double m)
albaTimeMapScalar< double >::TimeMapScalars::iterator FindItemByValue (double m)
virtual void InsertItem (albaTimeStamp t, double m)
virtual void InsertItem (albaTimeStamp t, double m)
virtual void RemoveItem (typename albaTimeMapScalar< double >::TimeMapScalars::iterator it)
int RemoveItem (int idx)
virtual void RemoveItem (typename albaTimeMapScalar< double >::TimeMapScalars::iterator it)
int RemoveItem (int idx)
virtual void RemoveAllItems ()
virtual void RemoveAllItems ()
albaTimeStamp GetItemTime (int idx)
albaTimeStamp GetItemTime (int idx)
void GetTimeStamps (mmuTimeVectorScalars &kframes) const
void GetTimeStamps (mmuTimeVectorScalars &kframes) const
int GetNumberOfItems () const
int GetNumberOfItems () const
void GetTimeBounds (albaTimeStamp tbounds[2])
void GetTimeBounds (albaTimeStamp tbounds[2])
void DeepCopy (albaTimeMapScalar *vitem)
void DeepCopy (albaTimeMapScalar *vitem)
bool Equals (albaTimeMapScalar *vmat)
bool Equals (albaTimeMapScalar *vmat)
albaTimeMapScalar< double >::TimeMapScalars::iterator FindNearestItem (albaTimeStamp t)
albaTimeMapScalar< double >::TimeMapScalars::iterator FindNearestItem (albaTimeStamp t)
albaTimeMapScalar< double >::TimeMapScalars::iterator FindItemBefore (albaTimeStamp t)
albaTimeMapScalar< double >::TimeMapScalars::iterator FindItemBefore (albaTimeStamp t)
albaTimeMapScalar< double >::TimeMapScalars::iterator FindItem (albaTimeStamp t)
albaTimeMapScalar< double >::TimeMapScalars::iterator FindItem (albaTimeStamp t)
albaTimeMapScalar< double >::TimeMapScalars::iterator FindItemByIndex (int idx)
albaTimeMapScalar< double >::TimeMapScalars::iterator FindItemByIndex (int idx)
albaID FindItemIndex (albaTimeStamp t)
albaID FindItemIndex (albaTimeStamp t)
double GetItem (albaTimeStamp t)
double GetItem (albaTimeStamp t)
double GetNearestItem (albaTimeStamp t)
double GetNearestItem (albaTimeStamp t)
double GetItemBefore (albaTimeStamp t)
double GetItemBefore (albaTimeStamp t)
double GetItemByIndex (int idx)
double GetItemByIndex (int idx)
virtual void Print (std::ostream &os, const int tabs=0) const
virtual void Print (std::ostream &os, const int tabs=0) const
albaTimeMapScalar< double >::TimeMapScalars::iterator BeginScalarVector ()
albaTimeMapScalar< double >::TimeMapScalars::iterator BeginScalarVector ()
albaTimeMapScalar< double >::TimeMapScalars::iterator EndScalarVector ()
albaTimeMapScalar< double >::TimeMapScalars::iterator EndScalarVector ()
albaTimeMapScalar< double >::TimeMapScalars::iterator LastScalarVector ()
albaTimeMapScalar< double >::TimeMapScalars::iterator LastScalarVector ()
Public Member Functions inherited from albaObject
albaObject ()
virtual ~albaObject ()
virtual void Delete ()
virtual const char * GetTypeName () const
virtual bool IsA (const char *type_name) const
virtual bool IsA (const albaTypeID &type_id) const
virtual albaObject * NewObjectInstance () const =0
virtual const albaTypeID & GetTypeId () const
virtual void Print (std::ostream &os, const int indent=0) const
albaObject (const albaObject &c)
Public Member Functions inherited from albaTimeStamped
virtual void Modified ()
virtual unsigned long GetMTime ()
Public Member Functions inherited from albaStorable
albaStorable ()
int Store (albaStorageElement *element)
int Restore (albaStorageElement *element)
albaObject * CastToObject ()
bool IsStorable ()
Protected Member Functions
virtual int InternalStore (albaStorageElement *parent)
virtual int InternalRestore (albaStorageElement *node)
virtual int InternalStore (albaStorageElement *node)=0
virtual int InternalRestore (albaStorageElement *node)=0
Additional Inherited Members
Static Public Member Functions inherited from albaObject
static const char * GetStaticTypeName ()
static bool IsStaticType (const char *type_name)
static bool IsStaticType (const albaTypeID &type_id)
static const albaTypeID & GetStaticTypeId ()
static albaObject * SafeDownCast (albaObject *o)
Static Public Member Functions inherited from albaStorable
static albaStorable * SafeCastToObject (albaObject *o)
Protected Attributes inherited from albaTimeMapScalar< double >
TimeMapScalars m_TimeMap
albaString m_ItemTypeName
Protected Attributes inherited from albaObject
bool m_HeapFlag
Protected Attributes inherited from albaTimeStamped
albaMTime m_MTime
Protected Attributes inherited from albaStorable
bool m_Storable
Detailed Description
a dynamic associative sorted vector of scalar values indexed by their "timestamp".
Definition at line 39 of file albaScalarVector.h.
Member Typedef Documentation
Iterator
typedef albaTimeMapScalar<double>::TimeMapScalars::iterator albaScalarVector::Iterator
Definition at line 42 of file albaScalarVector.h.
Constructor & Destructor Documentation
albaScalarVector()
albaScalarVector::albaScalarVector ()
~albaScalarVector()
virtual albaScalarVector::~albaScalarVector () virtual
Member Function Documentation
albaTypeMacro()
albaScalarVector::albaTypeMacro (albaScalarVector , albaObject)
AppendScalar()
void albaScalarVector::AppendScalar (albaTimeStamp t, double s) inline
Append a scalar to the vector setting its timestamp to the highest one + 1 The scalar value is referenced and NOT copied.
same effect of AppendItem().
Definition at line 53 of file albaScalarVector.h.
References albaTimeMapScalar< T >::AppendItem().
GetScalar() [1/2]
double albaScalarVector::GetScalar (int idx) inline
Return a scalar in the vector, given its order index.
Return NULL if idx out of range. Beware this function take o(n) n = idx to return the scalar value
Definition at line 58 of file albaScalarVector.h.
References albaTimeMapScalar< T >::GetItemByIndex().
GetScalarVector()
void albaScalarVector::GetScalarVector (std::vector< double > & svector)
return a vector of key scalar.
GetNumberOfScalars()
int albaScalarVector::GetNumberOfScalars () const inline
Return the number of scalar values stored in this object.
Definition at line 64 of file albaScalarVector.h.
References albaTimeMapScalar< T >::GetNumberOfItems().
GetNearestScalar()
double albaScalarVector::GetNearestScalar (albaTimeStamp t) inline
return the scalar with the timestamp nearest to t
Definition at line 67 of file albaScalarVector.h.
References albaTimeMapScalar< T >::GetNearestItem().
GetScalarBefore()
double albaScalarVector::GetScalarBefore (albaTimeStamp t) inline
return the scalar with timestamp <=t
Definition at line 70 of file albaScalarVector.h.
References albaTimeMapScalar< T >::GetItemBefore().
GetScalar() [2/2]
double albaScalarVector::GetScalar (albaTimeStamp t) inline
return the scalar with the timestamp == t.
return NULL if not found.
Definition at line 73 of file albaScalarVector.h.
References albaTimeMapScalar< T >::GetItem().
SetScalar()
void albaScalarVector::SetScalar (albaTimeStamp t, double sca) inline
Set the scalar for a specified time.
If no key-scalar with the same time exist a new key-scalar is created. If a key-scalar with the same time exist, simply overwrite the old scalar value. The given scalar value is referenced and not copied.
Definition at line 80 of file albaScalarVector.h.
References albaTimeMapScalar< T >::InsertItem().
InternalStore()
virtual int albaScalarVector::InternalStore (albaStorageElement * node) protected virtual
This is called by Store() and must be reimplemented by subclasses.
The node element where the object should store itself is passed as argument.
Implements albaStorable.
InternalRestore()
virtual int albaScalarVector::InternalRestore (albaStorageElement * node) protected virtual
This is called by Restore() and must be reimplemented by subclasses The element from which the object should restore itself is passed as argument.
Implements albaStorable.
The documentation for this class was generated from the following file:
albaScalarVector.h