ALBA 2: vtkALBAPolyDataDeformation Class Reference
vtkALBAPolyDataDeformation Class Reference
#include <vtkALBAPolyDataDeformation.h>
Classes
class CMatrix
class CMeshVertexParametrization
class CMunkres
struct CONTROL_SKELETON
class CSkeleton
class CSkeletonEdge
class CSkeletonVertex
class CSuperSkeleton
Public Member Functions
vtkTypeRevisionMacro (vtkALBAPolyDataDeformation, vtkPolyDataToPolyDataFilter)
vtkGetMacro (MatchGeometryWeight, double)
vtkSetMacro (MatchGeometryWeight, double)
vtkGetMacro (MatchTopologyWeight, double)
vtkSetMacro (MatchTopologyWeight, double)
vtkGetMacro (MatchTolerance, double)
vtkSetMacro (MatchTolerance, double)
vtkGetMacro (DivideSkeletonEdges, int)
vtkSetMacro (DivideSkeletonEdges, int)
vtkBooleanMacro (DivideSkeletonEdges, int)
vtkGetMacro (PreserveVolume, int)
vtkSetMacro (PreserveVolume, int)
vtkBooleanMacro (PreserveVolume, int)
virtual int GetNumberOfSkeletons ()
virtual void SetNumberOfSkeletons (int nCount)
virtual void SetNthSkeleton (int idx, vtkPolyData *original, vtkPolyData *modified, vtkIdList *correspondence=NULL, double *original_rso=NULL, double *modified_rso=NULL)
unsigned long int GetMTime ()
Static Public Member Functions
static vtkALBAPolyDataDeformation * New ()
Protected Types
typedef vtkstd::vector< CMeshVertexParametrization > CMeshVertex
typedef struct vtkALBAPolyDataDeformation::CONTROL_SKELETON CONTROL_SKELETON
Protected Member Functions
vtkALBAPolyDataDeformation ()
virtual ~vtkALBAPolyDataDeformation ()
void ExecuteInformation ()
void ExecuteData (vtkDataObject *output)
bool CreateSuperSkeleton ()
void DestroySuperSkeleton ()
void CreateSuperSkeleton (vtkPolyData *pOC, vtkPolyData *pDC, vtkIdList *pCC, double dblEdgeFactor)
CSkeleton * CreateSkeleton (vtkPolyData *pPoly)
void DestroySkeleton (CSkeleton *pSkel)
vtkIdList * MatchSkeletons (CSkeleton *pOC, CSkeleton *pDC, vtkIdList *pCC)
int TraceSkeletonCurve (CSkeletonVertex *pStartVertex, int iDir, CSkeletonVertex **pOutBuf)
void MarkCurveEdges (CSkeletonVertex **pCurve, int nCount)
int MatchCurves (CSkeletonVertex **pOC, int nOCVerts, CSkeletonVertex **pDC, int nDCVerts)
void CreateCurveEdges (CSkeletonVertex **pVerts, int nVerts)
void RefineCurve (CSkeletonVertex *pCurve, double dblEdgeFactor)
void AddCurveToSuperSkeleton (CSkeletonVertex *pOCCurve)
double ComputeInputMeshAvgEdgeLength ()
CSkeletonVertex * GetPreviousCurveVertex (CSkeletonVertex *pCurve)
CSkeletonVertex * GetNextCurveVertex (CSkeletonVertex *pCurve)
CSkeletonEdge * GetPreviousCurveEdge (CSkeletonEdge *pCurve)
CSkeletonEdge * GetNextCurveEdge (CSkeletonEdge *pCurve)
void ComputeLFS (CSkeletonVertex *pOC, double *ROS_OC=NULL, double *ROS_DC=NULL)
double GetDistance (vtkIdType nPtStartId, double ptEnd[3], vtkCellLocator *cellLocator, double dblMaxDist)
double GetPathLength (vtkIdType nPtFrom, vtkIdType nPtTo, double dblMaxDist)
int GetNumberOfCurveVertices (CSkeletonVertex *pCurve)
void BuildGeneralRotationMatrix (double r[3], double cos_theta, double M[3][3])
void ComputeMeshParametrization ()
void DeformMesh (vtkPolyData *output)
void CreatePolyDataFromSkeleton (CSkeleton *pSkel, vtkPolyData *output)
Protected Attributes
CONTROL_SKELETON * Skeletons
int NumberOfSkeletons
CSuperSkeleton * SuperSkeleton
double MatchGeometryWeight
double MatchTopologyWeight
double MatchTolerance
int DivideSkeletonEdges
int PreserveVolume
CMeshVertex * MeshVertices
Friends
class CMatrixTest
class CSkeletonEdgeTest
class CSkeletonVertexTest
Detailed Description
Definition at line 71 of file vtkALBAPolyDataDeformation.h.
Member Typedef Documentation
CMeshVertex
typedef vtkstd::vector< CMeshVertexParametrization > vtkALBAPolyDataDeformation::CMeshVertex protected
Definition at line 109 of file vtkALBAPolyDataDeformation.h.
CONTROL_SKELETON
typedef struct vtkALBAPolyDataDeformation::CONTROL_SKELETON vtkALBAPolyDataDeformation::CONTROL_SKELETON protected
Constructor & Destructor Documentation
vtkALBAPolyDataDeformation()
vtkALBAPolyDataDeformation::vtkALBAPolyDataDeformation () protected
~vtkALBAPolyDataDeformation()
virtual vtkALBAPolyDataDeformation::~vtkALBAPolyDataDeformation () protected virtual
Member Function Documentation
New()
static vtkALBAPolyDataDeformation * vtkALBAPolyDataDeformation::New () static
vtkTypeRevisionMacro()
vtkALBAPolyDataDeformation::vtkTypeRevisionMacro (vtkALBAPolyDataDeformation , vtkPolyDataToPolyDataFilter)
vtkGetMacro() [1/5]
vtkALBAPolyDataDeformation::vtkGetMacro (MatchGeometryWeight , double)
Gets the weight using to match geometry of skeletons.
vtkSetMacro() [1/5]
vtkALBAPolyDataDeformation::vtkSetMacro (MatchGeometryWeight , double)
Sets the weight using to match geometry of skeletons The value must be in the interval (0,1)
vtkGetMacro() [2/5]
vtkALBAPolyDataDeformation::vtkGetMacro (MatchTopologyWeight , double)
Gets the weight using to match topology of skeletons.
vtkSetMacro() [2/5]
vtkALBAPolyDataDeformation::vtkSetMacro (MatchTopologyWeight , double)
Sets the weight using to match topology of skeletons The value must be in the interval (0,1)
vtkGetMacro() [3/5]
vtkALBAPolyDataDeformation::vtkGetMacro (MatchTolerance , double)
Gets the tolerance used to match vertices of two curves.
The tolerance is relative to the length of shortest edge of these curves.
vtkSetMacro() [3/5]
vtkALBAPolyDataDeformation::vtkSetMacro (MatchTolerance , double)
Sets the tolerance used to match vertices of two curves The tolerance is relative to the length of shortest edge of these curves.
The value must be in the interval (0,1).
vtkGetMacro() [4/5]
vtkALBAPolyDataDeformation::vtkGetMacro (DivideSkeletonEdges , int)
Returns 1, if large skeleton edges should be divided.
vtkSetMacro() [4/5]
vtkALBAPolyDataDeformation::vtkSetMacro (DivideSkeletonEdges , int)
Specifies whether large skeleton edges should be divided.
vtkBooleanMacro() [1/2]
vtkALBAPolyDataDeformation::vtkBooleanMacro (DivideSkeletonEdges , int)
Specifies whether large skeleton edges should be divided.
vtkGetMacro() [5/5]
vtkALBAPolyDataDeformation::vtkGetMacro (PreserveVolume , int)
Returns 1, if simple volume preservation technique is to be used.
vtkSetMacro() [5/5]
vtkALBAPolyDataDeformation::vtkSetMacro (PreserveVolume , int)
Specifies whether simple volume preservation technique is to be used.
vtkBooleanMacro() [2/2]
vtkALBAPolyDataDeformation::vtkBooleanMacro (PreserveVolume , int)
Specifies whether simple volume preservation technique is to be used.
GetNumberOfSkeletons()
virtual int vtkALBAPolyDataDeformation::GetNumberOfSkeletons () inline virtual
Get the number of control curves.
Definition at line 395 of file vtkALBAPolyDataDeformation.h.
SetNumberOfSkeletons()
virtual void vtkALBAPolyDataDeformation::SetNumberOfSkeletons (int nCount) virtual
Sets the number of control skeletons.
Old skeletons are copied (and preserved)
SetNthSkeleton()
virtual void vtkALBAPolyDataDeformation::SetNthSkeleton (int idx, vtkPolyData * original, vtkPolyData * modified, vtkIdList * correspondence = NULL, double * original_rso = NULL, double * modified_rso = NULL) virtual
Specifies the n-th control skeleton.
If RSO points are specified, they are used during the computation of LFs of curves of both skeletons. A local fame is defined by its origin point and three vectors u, v and w. Vector u is the tangent vector (it goes in the direction of polyline) and vectors v,w are perpendicular to this vector. As there is infinite number of u,v,w configurations, the algorithm uses the given RSO point to get a unique one (v lies in the plane defined by u and RSO). If RSO is not specified, v is chosen to lie in the plane closest to the u vector. When RSO points are not specified (or they are specified incorrectly), the deformed object might be unrealistically rotated against other objects in the scene, if the skeleton of object to deform tends to rotate (simple edge, or only one skeleton for object).
GetMTime()
unsigned long int vtkALBAPolyDataDeformation::GetMTime ()
Return this object's modified time.
ExecuteInformation()
void vtkALBAPolyDataDeformation::ExecuteInformation () protected
By default, UpdateInformation calls this method to copy information unmodified from the input to the output.
ExecuteData()
void vtkALBAPolyDataDeformation::ExecuteData (vtkDataObject * output) protected
This method is the one that should be used by subclasses, right now the default implementation is to call the backwards compatibility method.
CreateSuperSkeleton() [1/2]
bool vtkALBAPolyDataDeformation::CreateSuperSkeleton () protected
Creates a single skeleton that describes the deformation.
Returns false, if the construction failed.
DestroySuperSkeleton()
void vtkALBAPolyDataDeformation::DestroySuperSkeleton () inline protected
Destroys the super skeleton.
Definition at line 437 of file vtkALBAPolyDataDeformation.h.
CreateSuperSkeleton() [2/2]
void vtkALBAPolyDataDeformation::CreateSuperSkeleton (vtkPolyData * pOC, vtkPolyData * pDC, vtkIdList * pCC, double dblEdgeFactor) protected
Creates a single super skeleton for the given control skeleton.
It combines both skeletons together, matching their vertices and creating new vertices as needed. It also computes local frames. The combined information is then appended into super skeleton. If the super skeleton does not exist, it is created.
CreateSkeleton()
CSkeleton * vtkALBAPolyDataDeformation::CreateSkeleton (vtkPolyData * pPoly) protected
Creates the internal skeleton data structure for the given polydata.
DestroySkeleton()
void vtkALBAPolyDataDeformation::DestroySkeleton (CSkeleton * pSkel) inline protected
Releases memory allocated for the given skeleton (in CreateSkeleton)
Definition at line 454 of file vtkALBAPolyDataDeformation.h.
MatchSkeletons()
vtkIdList * vtkALBAPolyDataDeformation::MatchSkeletons (CSkeleton * pOC, CSkeleton * pDC, vtkIdList * pCC) protected
Compute the best match for skeleton vertices.
Only junctions and terminal nodes are matched. The caller can optionally specify some (or all) correspondences. The routine returns the list containing pairs of corresponding vertices.
TraceSkeletonCurve()
int vtkALBAPolyDataDeformation::TraceSkeletonCurve (CSkeletonVertex * pStartVertex, int iDir, CSkeletonVertex ** pOutBuf) protected
Traces the curve in the given direction starting from the given vertex.
Starting from the given vertex, the routine moves in the given direction (which actually defines the edge which to go) storing the visited vertices of the graph into the output buffer. The buffer must be capable to hold all vertices of the graph. The traversal process ends when a "junction" or end-point is reached (those vertices have mark >= 0). The routine returns the number of vertices stored in the buffer. N.B. this routine is supposed to be called from CreateSuperSkeleton
MarkCurveEdges()
void vtkALBAPolyDataDeformation::MarkCurveEdges (CSkeletonVertex ** pCurve, int nCount) protected
Marks every edge of the given skeleton curve.
MatchCurves()
int vtkALBAPolyDataDeformation::MatchCurves (CSkeletonVertex ** pOC, int nOCVerts, CSkeletonVertex ** pDC, int nDCVerts) protected
Matches two curves defined by two arrays of vertices.
It creates at least max(nOCVerts, nDCVerts) new vertices and those vertices are stored in pOC and pDC buffers. Note: both array buffers must be capable enough to hold nOCVerts + nDCVerts vertices. Returns the number of vertices in matched curves. It also creates edges between vertices and establishes links between both vertices and edges. The caller is responsible for deletion of all objects when they are no longer needed. N.B. the original vertices are not destroyed, the routine damages buffers only
CreateCurveEdges()
void vtkALBAPolyDataDeformation::CreateCurveEdges (CSkeletonVertex ** pVerts, int nVerts) protected
Create edges for the given array of vertices.
RefineCurve()
void vtkALBAPolyDataDeformation::RefineCurve (CSkeletonVertex * pCurve, double dblEdgeFactor) protected
Refines the given curve (and its corresponding one) by adding more vertices.
Every skeleton edge larger than sqrt(dblEdgeFactor) is split recursively into two shorter edges. The matching curve is split appropriately. N.B. the routine is intended to be called after CreateCurveEdges
AddCurveToSuperSkeleton()
void vtkALBAPolyDataDeformation::AddCurveToSuperSkeleton (CSkeletonVertex * pOCCurve) protected
Stores vertices and edges from the given curve and the matched one into the superskeleton The routine also constructs automatically joints for end-points of curves.
N.B. both curves must be compatible with curves constructed by CreateCurveEdges.
ComputeInputMeshAvgEdgeLength()
double vtkALBAPolyDataDeformation::ComputeInputMeshAvgEdgeLength () protected
Computes the average length of edges of the input mesh.
GetPreviousCurveVertex()
CSkeletonVertex * vtkALBAPolyDataDeformation::GetPreviousCurveVertex (CSkeletonVertex * pCurve) inline protected
Gets the previous vertex on the curve.
Returns NULL, if the given vertex is the first one.
Definition at line 510 of file vtkALBAPolyDataDeformation.h.
References vtkALBAPolyDataDeformation::CSkeletonVertex::GetDegree(), and vtkALBAPolyDataDeformation::CSkeletonVertex::OneRingEdges.
GetNextCurveVertex()
CSkeletonVertex * vtkALBAPolyDataDeformation::GetNextCurveVertex (CSkeletonVertex * pCurve) inline protected
Gets the next vertex on the curve.
Returns NULL, if the given vertex is the last one.
Definition at line 517 of file vtkALBAPolyDataDeformation.h.
References vtkALBAPolyDataDeformation::CSkeletonVertex::OneRingEdges.
GetPreviousCurveEdge()
CSkeletonEdge * vtkALBAPolyDataDeformation::GetPreviousCurveEdge (CSkeletonEdge * pCurve) inline protected
Gets the previous edge on the curve.
Returns NULL, if the given vertex is the first one.
Definition at line 525 of file vtkALBAPolyDataDeformation.h.
References vtkALBAPolyDataDeformation::CSkeletonVertex::GetDegree(), vtkALBAPolyDataDeformation::CSkeletonVertex::OneRingEdges, and vtkALBAPolyDataDeformation::CSkeletonEdge::Verts.
GetNextCurveEdge()
CSkeletonEdge * vtkALBAPolyDataDeformation::GetNextCurveEdge (CSkeletonEdge * pCurve) inline protected
Gets the next edge on the curve.
Returns NULL, if the given vertex is the last one.
Definition at line 535 of file vtkALBAPolyDataDeformation.h.
References vtkALBAPolyDataDeformation::CSkeletonVertex::GetDegree(), vtkALBAPolyDataDeformation::CSkeletonVertex::OneRingEdges, and vtkALBAPolyDataDeformation::CSkeletonEdge::Verts.
ComputeLFS()
void vtkALBAPolyDataDeformation::ComputeLFS (CSkeletonVertex * pOC, double * ROS_OC = NULL, double * ROS_DC = NULL) protected
Computes the local frame systems for both curves.
N.B. both curves must be compatible with curves constructed by CreateCurveEdges and the links must be established between them
The algorithm is based on the paper: Blanco FR, Oliveira MM: Instant mesh deformation. In: Proceedings of the 2008 symposium on Interactive 3D graphics and games, Redwood City, California, 2008, pp. 71-78
ROS_OC and ROS_DC defines the plane to compute the first LF - see SetNthSkeleton
GetDistance()
double vtkALBAPolyDataDeformation::GetDistance (vtkIdType nPtStartId, double ptEnd[3], vtkCellLocator * cellLocator, double dblMaxDist) protected
Computes an approximate geodesic distance between two points.
If the straight line between both points does not intersect the input mesh, the returned distance is the Euclidian distance between those two points; otherwise it is the sum of the length of the shortest (surface) path from nPtStartId to the surface point closest to the intersection and the distance that returned by GetDistance with the first parameter to be the surface point closest to the intersection. If the total distance during the computation exceeds the given dblMaxDist, the algorithm stops (and returns the distance measured so far) - this is to speed up the process. N.B. cellLocator must be initialized with the input mesh.
GetPathLength()
double vtkALBAPolyDataDeformation::GetPathLength (vtkIdType nPtFrom, vtkIdType nPtTo, double dblMaxDist) protected
Computes the length of the path between nPtFrom to nPtTo vertices.
The computation is not precise (because of speed). If there is no path, or the path would be too long, the routine returns dblMaxDist. N.B. the found path may not be the shortest one!
GetNumberOfCurveVertices()
int vtkALBAPolyDataDeformation::GetNumberOfCurveVertices (CSkeletonVertex * pCurve) protected
Gets the number of vertices belonging to the given curve.
N.B. curve must be compatible with curves constructed by CreateCurveEdges.
BuildGeneralRotationMatrix()
void vtkALBAPolyDataDeformation::BuildGeneralRotationMatrix (double r[3], double cos_theta, double M[3][3]) protected
Constructs the matrix for rotation of vectors around the vector r by the angle theta.
The angle is given indirectly as cos(theta). N.B. vector r must be normalized.
ComputeMeshParametrization()
void vtkALBAPolyDataDeformation::ComputeMeshParametrization () protected
Parametrize the input mesh using the super-skeleton.
N.B. edges ROI must be build and refined before this routine may be called.
DeformMesh()
void vtkALBAPolyDataDeformation::DeformMesh (vtkPolyData * output) protected
Computes new position of vertices in the output mesh.
In this last step, positions of vertices are modified according to their parametrization in respect to the superskeleton.
N.B. the given output polydata must be compatible with the input polydata
CreatePolyDataFromSkeleton()
void vtkALBAPolyDataDeformation::CreatePolyDataFromSkeleton (CSkeleton * pSkel, vtkPolyData * output) protected
Creates polydata from the given skeleton.
Friends And Related Function Documentation
CMatrixTest
friend class CMatrixTest friend
Definition at line 79 of file vtkALBAPolyDataDeformation.h.
CSkeletonEdgeTest
friend class CSkeletonEdgeTest friend
Definition at line 80 of file vtkALBAPolyDataDeformation.h.
CSkeletonVertexTest
friend class CSkeletonVertexTest friend
Definition at line 81 of file vtkALBAPolyDataDeformation.h.
Member Data Documentation
Skeletons
CONTROL_SKELETON* vtkALBAPolyDataDeformation::Skeletons protected
Definition at line 338 of file vtkALBAPolyDataDeformation.h.
NumberOfSkeletons
int vtkALBAPolyDataDeformation::NumberOfSkeletons protected
Definition at line 339 of file vtkALBAPolyDataDeformation.h.
SuperSkeleton
CSuperSkeleton* vtkALBAPolyDataDeformation::SuperSkeleton protected
Definition at line 341 of file vtkALBAPolyDataDeformation.h.
MatchGeometryWeight
double vtkALBAPolyDataDeformation::MatchGeometryWeight protected
Definition at line 343 of file vtkALBAPolyDataDeformation.h.
MatchTopologyWeight
double vtkALBAPolyDataDeformation::MatchTopologyWeight protected
Definition at line 344 of file vtkALBAPolyDataDeformation.h.
MatchTolerance
double vtkALBAPolyDataDeformation::MatchTolerance protected
Definition at line 345 of file vtkALBAPolyDataDeformation.h.
DivideSkeletonEdges
int vtkALBAPolyDataDeformation::DivideSkeletonEdges protected
Definition at line 347 of file vtkALBAPolyDataDeformation.h.
PreserveVolume
int vtkALBAPolyDataDeformation::PreserveVolume protected
Definition at line 348 of file vtkALBAPolyDataDeformation.h.
MeshVertices
CMeshVertex* vtkALBAPolyDataDeformation::MeshVertices protected
Definition at line 350 of file vtkALBAPolyDataDeformation.h.
The documentation for this class was generated from the following file:
vtkALBAPolyDataDeformation.h