ALBA 2: vtkBox Class Reference
vtkBox Class Reference
#include <vtkBox.h>
Public Member Functions
vtkTypeRevisionMacro (vtkBox, vtkImplicitFunction)
void PrintSelf (ostream &os, vtkIndent indent)
double EvaluateFunction (double x[3])
double EvaluateFunction (double x, double y, double z)
void EvaluateGradient (double x[3], double n[3])
void SetXMin (double p[3])
void SetXMin (double x, double y, double z)
void GetXMin (double p[3])
void GetXMin (double &x, double &y, double &z)
void SetXMax (double p[3])
void SetXMax (double x, double y, double z)
void GetXMax (double p[3])
void GetXMax (double &x, double &y, double &z)
void SetBounds (double xMin, double xMax, double yMin, double yMax, double zMin, double zMax)
void SetBounds (double bounds[6])
void GetBounds (double &xMin, double &xMax, double &yMin, double &yMax, double &zMin, double &zMax)
void GetBounds (double bounds[6])
double * GetBounds ()
void AddBounds (double bounds[6])
Static Public Member Functions
static vtkBox * New ()
static char IntersectBox (double bounds[6], double origin[3], double dir[3], double coord[3], double &t)
Protected Member Functions
vtkBox ()
~vtkBox ()
Protected Attributes
vtkBoundingBox * BBox
double Bounds [6]
Detailed Description
class name: vtkBox.
Optimized box ,which intersect method taken from Graphic Gems vol I.
Definition at line 49 of file vtkBox.h.
Constructor & Destructor Documentation
vtkBox()
vtkBox::vtkBox () protected
object constructor.
~vtkBox()
vtkBox::~vtkBox () protected
destructor constructor.
Member Function Documentation
vtkTypeRevisionMacro()
vtkBox::vtkTypeRevisionMacro (vtkBox , vtkImplicitFunction)
RTTI macro.
PrintSelf()
void vtkBox::PrintSelf (ostream & os, vtkIndent indent)
print information
New()
static vtkBox * vtkBox::New () static
Construct box with center at (0,0,0) and each side of length 1.0.
EvaluateFunction() [1/2]
double vtkBox::EvaluateFunction (double x[3])
Evaluate box defined by the two points (pMin,pMax).
EvaluateFunction() [2/2]
double vtkBox::EvaluateFunction (double x, double y, double z) inline
Evaluate box defined by the two points (pMin,pMax).
Definition at line 65 of file vtkBox.h.
EvaluateGradient()
void vtkBox::EvaluateGradient (double x[3], double n[3])
Evaluate the gradient of the box.
SetXMin() [1/2]
void vtkBox::SetXMin (double p[3]) inline
Set the bounding box.
Definition at line 141 of file vtkBox.h.
References SetXMin().
Referenced by SetXMin().
SetXMin() [2/2]
void vtkBox::SetXMin (double x, double y, double z)
Set the bounding box.
GetXMin() [1/2]
void vtkBox::GetXMin (double p[3])
Get the bounding box.
GetXMin() [2/2]
void vtkBox::GetXMin (double & x, double & y, double & z)
Get the bounding box.
SetXMax() [1/2]
void vtkBox::SetXMax (double p[3]) inline
Set the bounding box.
Definition at line 146 of file vtkBox.h.
References SetXMax().
Referenced by SetXMax().
SetXMax() [2/2]
void vtkBox::SetXMax (double x, double y, double z)
Set the bounding box.
GetXMax() [1/2]
void vtkBox::GetXMax (double p[3])
Get the bounding box.
GetXMax() [2/2]
void vtkBox::GetXMax (double & x, double & y, double & z)
Get the bounding box.
SetBounds() [1/2]
void vtkBox::SetBounds (double xMin, double xMax, double yMin, double yMax, double zMin, double zMax)
set bounds
SetBounds() [2/2]
void vtkBox::SetBounds (double bounds[6])
set bounds
GetBounds() [1/3]
void vtkBox::GetBounds (double & xMin, double & xMax, double & yMin, double & yMax, double & zMin, double & zMax)
retrieve bounds
GetBounds() [2/3]
void vtkBox::GetBounds (double bounds[6])
retrieve bounds C style
GetBounds() [3/3]
double * vtkBox::GetBounds ()
retrieve bounds
AddBounds()
void vtkBox::AddBounds (double bounds[6])
A special method that allows union set operation on bounding boxes.
Start with a SetBounds(). Subsequent AddBounds() methods are union set operations on the original bounds. Retrieve the final bounds with a GetBounds() method.
IntersectBox()
static char vtkBox::IntersectBox (double bounds[6], double origin[3], double dir[3], double coord[3], double & t) static
Bounding box intersection modified from Graphics Gems Vol I.
The method returns a non-zero value if the bounding box is hit. Origin[3] starts the ray, dir[3] is the vector components of the ray in the x-y-z directions, coord[3] is the location of hit, and t is the parametric coordinate along line. (Notes: the intersection ray dir[3] is NOT normalized. Valid intersections will only occur between 0<=t<=1.)
Member Data Documentation
BBox
vtkBoundingBox* vtkBox::BBox protected
Definition at line 129 of file vtkBox.h.
Bounds
double vtkBox::Bounds[6] protected
Definition at line 130 of file vtkBox.h.
The documentation for this class was generated from the following file:
vtkBox.h