ALBA 2: vtkALBAPolyDataDeformation_M1 Class Reference
vtkALBAPolyDataDeformation_M1 Class Reference
#include <vtkALBAPolyDataDeformation_M1.h>
Classes
class CMatrix
class CMeshVertex
class CMunkres
struct CONTROL_SKELETON
class CSkeleton
class CSkeletonEdge
class CSkeletonVertex
class CSuperSkeleton
Public Member Functions
vtkTypeRevisionMacro (vtkALBAPolyDataDeformation_M1, vtkPolyDataToPolyDataFilter)
void PrintSelf (ostream &os, vtkIndent indent)
vtkGetMacro (MatchGeometryWeight, double)
vtkSetMacro (MatchGeometryWeight, double)
vtkGetMacro (MatchTopologyWeight, double)
vtkSetMacro (MatchTopologyWeight, double)
vtkGetMacro (MatchTolerance, double)
vtkSetMacro (MatchTolerance, double)
vtkGetMacro (DivideSkeletonEdges, int)
vtkSetMacro (DivideSkeletonEdges, int)
vtkBooleanMacro (DivideSkeletonEdges, int)
vtkGetMacro (PreserveVolume, int)
vtkSetMacro (PreserveVolume, int)
vtkBooleanMacro (PreserveVolume, int)
virtual int GetNumberOfSkeletons ()
virtual void SetNumberOfSkeletons (int nCount)
virtual void SetNthSkeleton (int idx, vtkPolyData *original, vtkPolyData *modified, vtkIdList *correspondence)
unsigned long int GetMTime ()
Static Public Member Functions
static vtkALBAPolyDataDeformation_M1 * New ()
Protected Types
typedef struct vtkALBAPolyDataDeformation_M1::CONTROL_SKELETON CONTROL_SKELETON
Protected Member Functions
vtkALBAPolyDataDeformation_M1 ()
virtual ~vtkALBAPolyDataDeformation_M1 ()
void ExecuteInformation ()
void ExecuteData (vtkDataObject *output)
bool CreateSuperSkeleton ()
void DestroySuperSkeleton ()
void CreateSuperSkeleton (vtkPolyData *pOC, vtkPolyData *pDC, vtkIdList *pCC, double dblEdgeFactor)
CSkeleton * CreateSkeleton (vtkPolyData *pPoly)
void DestroySkeleton (CSkeleton *pSkel)
vtkIdList * MatchSkeletons (CSkeleton *pOC, CSkeleton *pDC, vtkIdList *pCC)
int TraceSkeletonCurve (CSkeletonVertex *pStartVertex, int iDir, CSkeletonVertex **pOutBuf)
void MarkCurveEdges (CSkeletonVertex **pCurve, int nCount)
int MatchCurves (CSkeletonVertex **pOC, int nOCVerts, CSkeletonVertex **pDC, int nDCVerts)
void CreateCurveEdges (CSkeletonVertex **pVerts, int nVerts)
void RefineCurve (CSkeletonVertex *pCurve, double dblEdgeFactor)
double ComputeInputMeshAvgEdgeLength ()
void AddCurveToSuperSkeleton (CSkeletonVertex *pCurve, bool bOriginal)
CSkeletonVertex * GetPreviousCurveVertex (CSkeletonVertex *pCurve)
CSkeletonVertex * GetNextCurveVertex (CSkeletonVertex *pCurve)
CSkeletonEdge * GetPreviousCurveEdge (CSkeletonEdge *pCurve)
CSkeletonEdge * GetNextCurveEdge (CSkeletonEdge *pCurve)
void ComputeLFS (CSkeletonVertex *pOC)
void ComputeROI (CSkeletonEdge *pEdge)
void RefineCurveROIs (vtkCellLocator *locator)
bool ValidateCurveROIs ()
bool CheckSelfIntersection (CSkeletonEdge *pEdge1, CSkeletonEdge *pEdge2)
int GetNumberOfCurveVertices (CSkeletonVertex *pCurve)
void BuildGeneralRotationMatrix (double r[3], double cos_theta, double M[3][3])
void ComputeMeshParametrization ()
void ComputeParametrization (vtkstd::vector< vtkIdType > &points, CSkeletonEdge *pEdge, int iWSkelEdge, double sigma2)
void DeformMesh (vtkPolyData *output)
Protected Attributes
CONTROL_SKELETON * m_Skeletons
int m_NumberOfSkeletons
CSuperSkeleton * m_SuperSkeleton
double MatchGeometryWeight
double MatchTopologyWeight
double MatchTolerance
int DivideSkeletonEdges
int PreserveVolume
std::vector< CMeshVertex > m_MeshVertices
Friends
class CMatrixTestM1
class CSkeletonEdgeM1Test
class CSkeletonVertexM1Test
Detailed Description
Definition at line 71 of file vtkALBAPolyDataDeformation_M1.h.
Member Typedef Documentation
CONTROL_SKELETON
typedef struct vtkALBAPolyDataDeformation_M1::CONTROL_SKELETON vtkALBAPolyDataDeformation_M1::CONTROL_SKELETON protected
Constructor & Destructor Documentation
vtkALBAPolyDataDeformation_M1()
vtkALBAPolyDataDeformation_M1::vtkALBAPolyDataDeformation_M1 () protected
~vtkALBAPolyDataDeformation_M1()
virtual vtkALBAPolyDataDeformation_M1::~vtkALBAPolyDataDeformation_M1 () protected virtual
Member Function Documentation
New()
static vtkALBAPolyDataDeformation_M1 * vtkALBAPolyDataDeformation_M1::New () static
vtkTypeRevisionMacro()
vtkALBAPolyDataDeformation_M1::vtkTypeRevisionMacro (vtkALBAPolyDataDeformation_M1 , vtkPolyDataToPolyDataFilter)
PrintSelf()
void vtkALBAPolyDataDeformation_M1::PrintSelf (ostream & os, vtkIndent indent)
vtkGetMacro() [1/5]
vtkALBAPolyDataDeformation_M1::vtkGetMacro (MatchGeometryWeight , double)
Gets the weight using to match geometry of skeletons.
vtkSetMacro() [1/5]
vtkALBAPolyDataDeformation_M1::vtkSetMacro (MatchGeometryWeight , double)
Sets the weight using to match geometry of skeletons The value must be in the interval (0,1)
vtkGetMacro() [2/5]
vtkALBAPolyDataDeformation_M1::vtkGetMacro (MatchTopologyWeight , double)
Gets the weight using to match topology of skeletons.
vtkSetMacro() [2/5]
vtkALBAPolyDataDeformation_M1::vtkSetMacro (MatchTopologyWeight , double)
Sets the weight using to match topology of skeletons The value must be in the interval (0,1)
vtkGetMacro() [3/5]
vtkALBAPolyDataDeformation_M1::vtkGetMacro (MatchTolerance , double)
Gets the tolerance used to match vertices of two curves.
The tolerance is relative to the length of shortest edge of these curves.
vtkSetMacro() [3/5]
vtkALBAPolyDataDeformation_M1::vtkSetMacro (MatchTolerance , double)
Sets the tolerance used to match vertices of two curves The tolerance is relative to the length of shortest edge of these curves.
The value must be in the interval (0,1).
vtkGetMacro() [4/5]
vtkALBAPolyDataDeformation_M1::vtkGetMacro (DivideSkeletonEdges , int)
Returns 1, if large skeleton edges should be divided.
vtkSetMacro() [4/5]
vtkALBAPolyDataDeformation_M1::vtkSetMacro (DivideSkeletonEdges , int)
Specifies whether large skeleton edges should be divided.
vtkBooleanMacro() [1/2]
vtkALBAPolyDataDeformation_M1::vtkBooleanMacro (DivideSkeletonEdges , int)
Specifies whether large skeleton edges should be divided.
vtkGetMacro() [5/5]
vtkALBAPolyDataDeformation_M1::vtkGetMacro (PreserveVolume , int)
Returns 1, if simple volume preservation technique is to be used.
vtkSetMacro() [5/5]
vtkALBAPolyDataDeformation_M1::vtkSetMacro (PreserveVolume , int)
Specifies whether simple volume preservation technique is to be used.
vtkBooleanMacro() [2/2]
vtkALBAPolyDataDeformation_M1::vtkBooleanMacro (PreserveVolume , int)
Specifies whether simple volume preservation technique is to be used.
GetNumberOfSkeletons()
virtual int vtkALBAPolyDataDeformation_M1::GetNumberOfSkeletons () inline virtual
Get the number of control curves.
Definition at line 387 of file vtkALBAPolyDataDeformation_M1.h.
SetNumberOfSkeletons()
virtual void vtkALBAPolyDataDeformation_M1::SetNumberOfSkeletons (int nCount) virtual
Sets the number of control skeletons.
Old skeletons are copied (and preserved)
SetNthSkeleton()
virtual void vtkALBAPolyDataDeformation_M1::SetNthSkeleton (int idx, vtkPolyData * original, vtkPolyData * modified, vtkIdList * correspondence) virtual
Specifies the n-th control skeleton.
GetMTime()
unsigned long int vtkALBAPolyDataDeformation_M1::GetMTime ()
Return this object's modified time.
ExecuteInformation()
void vtkALBAPolyDataDeformation_M1::ExecuteInformation () protected
By default, UpdateInformation calls this method to copy information unmodified from the input to the output.
ExecuteData()
void vtkALBAPolyDataDeformation_M1::ExecuteData (vtkDataObject * output) protected
This method is the one that should be used by subclasses, right now the default implementation is to call the backwards compatibility method.
CreateSuperSkeleton() [1/2]
bool vtkALBAPolyDataDeformation_M1::CreateSuperSkeleton () protected
Creates a single skeleton that describes the deformation.
Returns false, if the construction failed.
DestroySuperSkeleton()
void vtkALBAPolyDataDeformation_M1::DestroySuperSkeleton () inline protected
Destroys the super skeleton.
Definition at line 417 of file vtkALBAPolyDataDeformation_M1.h.
CreateSuperSkeleton() [2/2]
void vtkALBAPolyDataDeformation_M1::CreateSuperSkeleton (vtkPolyData * pOC, vtkPolyData * pDC, vtkIdList * pCC, double dblEdgeFactor) protected
Creates a single super skeleton for the given control skeleton.
It combines both skeletons together, matching their vertices and creating new vertices as needed. It also computes local frames. The combined information is then appended into super skeleton. If the super skeleton does not exist, it is created.
CreateSkeleton()
CSkeleton * vtkALBAPolyDataDeformation_M1::CreateSkeleton (vtkPolyData * pPoly) protected
Creates the internal skeleton data structure for the given polydata.
DestroySkeleton()
void vtkALBAPolyDataDeformation_M1::DestroySkeleton (CSkeleton * pSkel) inline protected
Releases memory allocated for the given skeleton (in CreateSkeleton)
Definition at line 434 of file vtkALBAPolyDataDeformation_M1.h.
MatchSkeletons()
vtkIdList * vtkALBAPolyDataDeformation_M1::MatchSkeletons (CSkeleton * pOC, CSkeleton * pDC, vtkIdList * pCC) protected
Compute the best match for skeleton vertices.
Only junctions and terminal nodes are matched. The caller can optionally specify some (or all) correspondences. The routine returns the list containing pairs of corresponding vertices.
TraceSkeletonCurve()
int vtkALBAPolyDataDeformation_M1::TraceSkeletonCurve (CSkeletonVertex * pStartVertex, int iDir, CSkeletonVertex ** pOutBuf) protected
Traces the curve in the given direction starting from the given vertex.
Starting from the given vertex, the routine moves in the given direction (which actually defines the edge which to go) storing the visited vertices of the graph into the output buffer. The buffer must be capable to hold all vertices of the graph. The traversal process ends when a "junction" or end-point is reached (those vertices have mark >= 0). The routine returns the number of vertices stored in the buffer. N.B. this routine is supposed to be called from CreateSuperSkeleton
MarkCurveEdges()
void vtkALBAPolyDataDeformation_M1::MarkCurveEdges (CSkeletonVertex ** pCurve, int nCount) protected
Marks every edge of the given skeleton curve.
MatchCurves()
int vtkALBAPolyDataDeformation_M1::MatchCurves (CSkeletonVertex ** pOC, int nOCVerts, CSkeletonVertex ** pDC, int nDCVerts) protected
Matches two curves defined by two arrays of vertices.
It creates at least max(nOCVerts, nDCVerts) new vertices and those vertices are stored in pOC and pDC buffers. Note: both array buffers must be capable enough to hold nOCVerts + nDCVerts vertices. Returns the number of vertices in matched curves. It also creates edges between vertices and establishes links between both vertices and edges. The caller is responsible for deletion of all objects when they are no longer needed. N.B. the original vertices are not destroyed, the routine damages buffers only
CreateCurveEdges()
void vtkALBAPolyDataDeformation_M1::CreateCurveEdges (CSkeletonVertex ** pVerts, int nVerts) protected
Create edges for the given array of vertices.
RefineCurve()
void vtkALBAPolyDataDeformation_M1::RefineCurve (CSkeletonVertex * pCurve, double dblEdgeFactor) protected
Refines the given curve (and its corresponding one) by adding more vertices.
Every skeleton edge larger than sqrt(dblEdgeFactor) is split recursively into two shorter edges. The matching curve is split appropriately. N.B. the routine is intended to be called after CreateCurveEdges
ComputeInputMeshAvgEdgeLength()
double vtkALBAPolyDataDeformation_M1::ComputeInputMeshAvgEdgeLength () protected
Computes the average length of edges of the input mesh.
AddCurveToSuperSkeleton()
void vtkALBAPolyDataDeformation_M1::AddCurveToSuperSkeleton (CSkeletonVertex * pCurve, bool bOriginal) protected
Stores vertices and edges from the given curve into superskeleton N.B.
curve must be compatible with curves constructed by CreateCurveEdges.
GetPreviousCurveVertex()
CSkeletonVertex * vtkALBAPolyDataDeformation_M1::GetPreviousCurveVertex (CSkeletonVertex * pCurve) inline protected
Gets the previous vertex on the curve.
Returns NULL, if the given vertex is the first one.
Definition at line 489 of file vtkALBAPolyDataDeformation_M1.h.
References vtkALBAPolyDataDeformation_M1::CSkeletonVertex::GetDegree(), and vtkALBAPolyDataDeformation_M1::CSkeletonVertex::m_OneRingEdges.
GetNextCurveVertex()
CSkeletonVertex * vtkALBAPolyDataDeformation_M1::GetNextCurveVertex (CSkeletonVertex * pCurve) inline protected
Gets the next vertex on the curve.
Returns NULL, if the given vertex is the last one.
Definition at line 496 of file vtkALBAPolyDataDeformation_M1.h.
References vtkALBAPolyDataDeformation_M1::CSkeletonVertex::m_OneRingEdges.
GetPreviousCurveEdge()
CSkeletonEdge * vtkALBAPolyDataDeformation_M1::GetPreviousCurveEdge (CSkeletonEdge * pCurve) inline protected
Gets the previous edge on the curve.
Returns NULL, if the given vertex is the first one.
Definition at line 504 of file vtkALBAPolyDataDeformation_M1.h.
References vtkALBAPolyDataDeformation_M1::CSkeletonVertex::GetDegree(), vtkALBAPolyDataDeformation_M1::CSkeletonVertex::m_OneRingEdges, and vtkALBAPolyDataDeformation_M1::CSkeletonEdge::Verts.
GetNextCurveEdge()
CSkeletonEdge * vtkALBAPolyDataDeformation_M1::GetNextCurveEdge (CSkeletonEdge * pCurve) inline protected
Gets the next edge on the curve.
Returns NULL, if the given vertex is the last one.
Definition at line 514 of file vtkALBAPolyDataDeformation_M1.h.
References vtkALBAPolyDataDeformation_M1::CSkeletonVertex::GetDegree(), vtkALBAPolyDataDeformation_M1::CSkeletonVertex::m_OneRingEdges, and vtkALBAPolyDataDeformation_M1::CSkeletonEdge::Verts.
ComputeLFS()
void vtkALBAPolyDataDeformation_M1::ComputeLFS (CSkeletonVertex * pOC) protected
Computes the local frame systems for both curves.
N.B. both curves must be compatible with curves constructed by CreateCurveEdges and the links must be established between them
The algorithm is based on the paper: Blanco FR, Oliveira MM: Instant mesh deformation. In: Proceedings of the 2008 symposium on Interactive 3D graphics and games, Redwood City, California, 2008, pp. 71-78
ComputeROI()
void vtkALBAPolyDataDeformation_M1::ComputeROI (CSkeletonEdge * pEdge) protected
Computes the region of interest (ROI) for the given edge of curve.
It detects every mesh vertex in the zone of influence of the given edge. Note: one of end-points of the edge may be NULL to specify half-space
RefineCurveROIs()
void vtkALBAPolyDataDeformation_M1::RefineCurveROIs (vtkCellLocator * locator) protected
Refines ROIs of curves.
Refines the mapping of vertices of the input mesh to edges in such a manner that every vertex is present only in one edge ROI. The routine requires locator for cells, initialized with the input mesh
ValidateCurveROIs()
bool vtkALBAPolyDataDeformation_M1::ValidateCurveROIs () protected
Validates ROIs of curves.
It checks whether the current LFs&ROIs configuration is safe enough not to lead into self-intersection of the deformed mesh (see Blanco paper). If the outcome of this test is negative, LFs of the skeleton vertex where the violation was detected is rotated and the routine returns false. The caller typically recomputes ROIs (as one of LFs has changed). The routine returns true, if there is no problem with the current configuration.
CheckSelfIntersection()
bool vtkALBAPolyDataDeformation_M1::CheckSelfIntersection (CSkeletonEdge * pEdge1, CSkeletonEdge * pEdge2) protected
Checks whether the part of mesh associated with given (adjacent) edges will not self intersect after the deformation.
If the outcome of the test is positive, the LFs at the point shared by those edges is modified to avoid such intersection and the routine returns false. It returns true, if everything is OK. The algorithm is based on Blanco's paper.
GetNumberOfCurveVertices()
int vtkALBAPolyDataDeformation_M1::GetNumberOfCurveVertices (CSkeletonVertex * pCurve) protected
Gets the number of vertices belonging to the given curve.
N.B. curve must be compatible with curves constructed by CreateCurveEdges.
BuildGeneralRotationMatrix()
void vtkALBAPolyDataDeformation_M1::BuildGeneralRotationMatrix (double r[3], double cos_theta, double M[3][3]) protected
Constructs the matrix for rotation of vectors around the vector r by the angle theta.
The angle is given indirectly as cos(theta). N.B. vector r must be normalized.
ComputeMeshParametrization()
void vtkALBAPolyDataDeformation_M1::ComputeMeshParametrization () protected
Parametrize the input mesh using the super-skeleton.
N.B. edges ROI must be build and refined before this routine may be called.
ComputeParametrization()
void vtkALBAPolyDataDeformation_M1::ComputeParametrization (vtkstd::vector< vtkIdType > & points, CSkeletonEdge * pEdge, int iWSkelEdge, double sigma2) protected
Parametrize the given points of the input mesh.
Points are given as indices. Parametrization is done for the given edge. If edge is infinite (only one end-point) or iWSkelEdge is -1, the parametrization of every vertex has the same weight (it is 1.0), otherwise it is computed as a function of the distance between the mesh vertex and skeleton vertex pEdge->m_Verts[iWSkelEdge] and sigma2. This function is (see Blanco's paper): e^-(dist2(x,skelvertex)/sigma2). sigma2 should be 2*dist2(skelvertex,centroid(skelvertex))
DeformMesh()
void vtkALBAPolyDataDeformation_M1::DeformMesh (vtkPolyData * output) protected
Computes new position of vertices in the output mesh.
In this last step, positions of vertices are modified according to their parametrization in respect to the superskeleton.
N.B. the given output polydata must be compatible with the input polydata
Friends And Related Function Documentation
CMatrixTestM1
friend class CMatrixTestM1 friend
Definition at line 80 of file vtkALBAPolyDataDeformation_M1.h.
CSkeletonEdgeM1Test
friend class CSkeletonEdgeM1Test friend
Definition at line 81 of file vtkALBAPolyDataDeformation_M1.h.
CSkeletonVertexM1Test
friend class CSkeletonVertexM1Test friend
Definition at line 82 of file vtkALBAPolyDataDeformation_M1.h.
Member Data Documentation
m_Skeletons
CONTROL_SKELETON* vtkALBAPolyDataDeformation_M1::m_Skeletons protected
Definition at line 330 of file vtkALBAPolyDataDeformation_M1.h.
m_NumberOfSkeletons
int vtkALBAPolyDataDeformation_M1::m_NumberOfSkeletons protected
Definition at line 331 of file vtkALBAPolyDataDeformation_M1.h.
m_SuperSkeleton
CSuperSkeleton* vtkALBAPolyDataDeformation_M1::m_SuperSkeleton protected
Definition at line 333 of file vtkALBAPolyDataDeformation_M1.h.
MatchGeometryWeight
double vtkALBAPolyDataDeformation_M1::MatchGeometryWeight protected
Definition at line 335 of file vtkALBAPolyDataDeformation_M1.h.
MatchTopologyWeight
double vtkALBAPolyDataDeformation_M1::MatchTopologyWeight protected
Definition at line 336 of file vtkALBAPolyDataDeformation_M1.h.
MatchTolerance
double vtkALBAPolyDataDeformation_M1::MatchTolerance protected
Definition at line 337 of file vtkALBAPolyDataDeformation_M1.h.
DivideSkeletonEdges
int vtkALBAPolyDataDeformation_M1::DivideSkeletonEdges protected
Definition at line 339 of file vtkALBAPolyDataDeformation_M1.h.
PreserveVolume
int vtkALBAPolyDataDeformation_M1::PreserveVolume protected
Definition at line 340 of file vtkALBAPolyDataDeformation_M1.h.
m_MeshVertices
std::vector< CMeshVertex > vtkALBAPolyDataDeformation_M1::m_MeshVertices protected
Definition at line 342 of file vtkALBAPolyDataDeformation_M1.h.
The documentation for this class was generated from the following file:
vtkALBAPolyDataDeformation_M1.h