ALBA 2: albaICPUtility Class Reference
albaICPUtility Class Reference
#include <albaICPUtility.h>
Classes
struct RegResult
Public Member Functions
vtkTypeRevisionMacro (albaICPUtility, vtkObject)
vnl_matrix< double > PolyData2VnlFilter (vtkPolyData *Shape)
void Vtk2Vnl (vtkPolyData *Shape, double *MatrixData)
RegResult SVD_Registration (vnl_matrix< double > &MS, vnl_matrix< double > &DS)
void Vnl2PolyDataFilter (vnl_matrix< double > M, vtkPolyData *Shape)
void Rows_randperm (vnl_matrix< double > &M)
vnl_matrix_fixed< double, 3, 3 > Theta2R (const vnl_vector_fixed< double, 3 > &th)
vnl_matrix_fixed< double, 4, 4 > R_t_2_Tr (const vnl_matrix_fixed< double, 3, 3 > &R, const vnl_vector_fixed< double, 3 > &t)
void FindPointLocator (vtkPoints *MS_vtkpoints, vtkPointLocator *pointLocator, double *DS_data, int DScols, vnl_matrix< double > &closest_pts)
RegResult ICP_vtkPointLocator (vnl_matrix< double > &MS, vnl_matrix< double > &DS, int cycle_lim)
RegResult ICP_vtkPointLocator (vnl_matrix< double > &MS, vnl_matrix< double > &DS, vcl_ifstream &ml_read_file, float var_threshold, int cycle_lim)
RegResult ICP_vtkPointLocator (vnl_matrix< double > &MS, vnl_matrix< double > &DS, vcl_multimap< double, int > &mm, const char *ml_filepath, float var_threshold, int cycle_lim)
vnl_matrix_fixed< double, 3, 3 > Rpy2R (const vnl_vector_fixed< double, 3 > v)
vnl_matrix_fixed< double, 3, 3 > Rpy2R (const double *row)
vnl_matrix< double > RpyOnShape (const vnl_matrix< double > &Shape, const double *row)
vnl_vector_fixed< double, 3 > Centroid (const vnl_matrix< double > &S)
vnl_vector< double > Center (const vnl_matrix< double > &S)
void Neg_translation (vnl_matrix< double > &S, const vnl_vector< double > c)
void Pos_translation (vnl_matrix< double > &S, const vnl_vector< double > c)
void Rotation_classif (vcl_multimap< double, int > &mm, const vnl_matrix< double > &DS, vnl_matrix< double > &MS)
RegResult FFRegistration (vnl_matrix< double > &MS, vnl_matrix< double > &DS, const char *knownMinLocalFile, float VarianceThrshold, int MaximumNumberOfIterations)
void Target_on_Source (vnl_matrix_fixed< double, 3, 3 > &R, vnl_vector_fixed< double, 3 > &p)
RegResult StandardRegistration (vnl_matrix< double > &MS, vnl_matrix< double > &DS, float Convergence)
Static Public Member Functions
static albaICPUtility * New ()
Public Attributes
wxString RotationFixedFile
wxString RotationFixedIndexFile
wxString KnownMinLocalPositionFile
bool KnownMinLocalFlag
bool RotationFixedFlag
Protected Member Functions
albaICPUtility ()
~albaICPUtility ()
Detailed Description
class name: albaICPUtility Implementation of the ICP algorithm utility.
Definition at line 52 of file albaICPUtility.h.
Constructor & Destructor Documentation
albaICPUtility()
albaICPUtility::albaICPUtility () inline protected
Definition at line 105 of file albaICPUtility.h.
~albaICPUtility()
albaICPUtility::~albaICPUtility () inline protected
Definition at line 106 of file albaICPUtility.h.
Member Function Documentation
New()
static albaICPUtility * albaICPUtility::New () static
vtkTypeRevisionMacro()
albaICPUtility::vtkTypeRevisionMacro (albaICPUtility , vtkObject)
PolyData2VnlFilter()
vnl_matrix< double > albaICPUtility::PolyData2VnlFilter (vtkPolyData * Shape) inline
Definition at line 112 of file albaICPUtility.h.
References Vtk2Vnl().
Vtk2Vnl()
void albaICPUtility::Vtk2Vnl (vtkPolyData * Shape, double * MatrixData) inline
Definition at line 122 of file albaICPUtility.h.
Referenced by PolyData2VnlFilter().
SVD_Registration()
albaICPUtility::RegResult albaICPUtility::SVD_Registration (vnl_matrix< double > & MS, vnl_matrix< double > & DS) inline
Definition at line 139 of file albaICPUtility.h.
References Centroid(), Neg_translation(), Pos_translation(), albaICPUtility::RegResult::R, and albaICPUtility::RegResult::t.
Vnl2PolyDataFilter()
void albaICPUtility::Vnl2PolyDataFilter (vnl_matrix< double > M, vtkPolyData * Shape) inline
Definition at line 177 of file albaICPUtility.h.
Rows_randperm()
void albaICPUtility::Rows_randperm (vnl_matrix< double > & M) inline
Definition at line 186 of file albaICPUtility.h.
Theta2R()
vnl_matrix_fixed< double, 3, 3 > albaICPUtility::Theta2R (const vnl_vector_fixed< double, 3 > & th) inline
Definition at line 201 of file albaICPUtility.h.
Referenced by ICP_vtkPointLocator(), and StandardRegistration().
R_t_2_Tr()
vnl_matrix_fixed< double, 4, 4 > albaICPUtility::R_t_2_Tr (const vnl_matrix_fixed< double, 3, 3 > & R, const vnl_vector_fixed< double, 3 > & t) inline
Definition at line 222 of file albaICPUtility.h.
FindPointLocator()
void albaICPUtility::FindPointLocator (vtkPoints * MS_vtkpoints, vtkPointLocator * pointLocator, double * DS_data, int DScols, vnl_matrix< double > & closest_pts) inline
Definition at line 233 of file albaICPUtility.h.
Referenced by ICP_vtkPointLocator(), Rotation_classif(), and StandardRegistration().
ICP_vtkPointLocator() [1/3]
albaICPUtility::RegResult albaICPUtility::ICP_vtkPointLocator (vnl_matrix< double > & MS, vnl_matrix< double > & DS, int cycle_lim) inline
Definition at line 251 of file albaICPUtility.h.
References albaICPUtility::RegResult::cov_matrix, albaICPUtility::RegResult::err, FindPointLocator(), albaICPUtility::RegResult::R, albaICPUtility::RegResult::t, albaICPUtility::RegResult::test, Theta2R(), and albaICPUtility::RegResult::var.
Referenced by FFRegistration().
ICP_vtkPointLocator() [2/3]
albaICPUtility::RegResult albaICPUtility::ICP_vtkPointLocator (vnl_matrix< double > & MS, vnl_matrix< double > & DS, vcl_ifstream & ml_read_file, float var_threshold, int cycle_lim) inline
Definition at line 463 of file albaICPUtility.h.
References albaICPUtility::RegResult::cov_matrix, albaICPUtility::RegResult::err, FindPointLocator(), albaICPUtility::RegResult::R, Rpy2R(), RpyOnShape(), albaICPUtility::RegResult::t, albaICPUtility::RegResult::test, Theta2R(), and albaICPUtility::RegResult::var.
ICP_vtkPointLocator() [3/3]
albaICPUtility::RegResult albaICPUtility::ICP_vtkPointLocator (vnl_matrix< double > & MS, vnl_matrix< double > & DS, vcl_multimap< double, int > & mm, const char * ml_filepath, float var_threshold, int cycle_lim) inline
Definition at line 785 of file albaICPUtility.h.
References albaICPUtility::RegResult::cov_matrix, albaICPUtility::RegResult::err, FindPointLocator(), albaICPUtility::RegResult::R, RotationFixedFile, Rpy2R(), RpyOnShape(), albaICPUtility::RegResult::t, albaICPUtility::RegResult::test, Theta2R(), and albaICPUtility::RegResult::var.
Rpy2R() [1/2]
vnl_matrix_fixed< double, 3, 3 > albaICPUtility::Rpy2R (const vnl_vector_fixed< double, 3 > v) inline
Definition at line 382 of file albaICPUtility.h.
Referenced by ICP_vtkPointLocator(), and Rotation_classif().
Rpy2R() [2/2]
vnl_matrix_fixed< double, 3, 3 > albaICPUtility::Rpy2R (const double * row) inline
Definition at line 408 of file albaICPUtility.h.
RpyOnShape()
vnl_matrix< double > albaICPUtility::RpyOnShape (const vnl_matrix< double > & Shape, const double * row) inline
Definition at line 434 of file albaICPUtility.h.
Referenced by ICP_vtkPointLocator().
Centroid()
vnl_vector_fixed< double, 3 > albaICPUtility::Centroid (const vnl_matrix< double > & S) inline
Definition at line 647 of file albaICPUtility.h.
Referenced by FFRegistration(), and SVD_Registration().
Center()
vnl_vector< double > albaICPUtility::Center (const vnl_matrix< double > & S) inline
Definition at line 662 of file albaICPUtility.h.
Neg_translation()
void albaICPUtility::Neg_translation (vnl_matrix< double > & S, const vnl_vector< double > c) inline
Definition at line 676 of file albaICPUtility.h.
Referenced by FFRegistration(), and SVD_Registration().
Pos_translation()
void albaICPUtility::Pos_translation (vnl_matrix< double > & S, const vnl_vector< double > c) inline
Definition at line 687 of file albaICPUtility.h.
Referenced by FFRegistration(), and SVD_Registration().
Rotation_classif()
void albaICPUtility::Rotation_classif (vcl_multimap< double, int > & mm, const vnl_matrix< double > & DS, vnl_matrix< double > & MS) inline
Definition at line 698 of file albaICPUtility.h.
References FindPointLocator(), RotationFixedIndexFile, and Rpy2R().
Referenced by FFRegistration().
FFRegistration()
albaICPUtility::RegResult albaICPUtility::FFRegistration (vnl_matrix< double > & MS, vnl_matrix< double > & DS, const char * knownMinLocalFile, float VarianceThrshold, int MaximumNumberOfIterations) inline
Definition at line 989 of file albaICPUtility.h.
References Centroid(), albaICPUtility::RegResult::cov_matrix, albaICPUtility::RegResult::err, ICP_vtkPointLocator(), KnownMinLocalFlag, Neg_translation(), Pos_translation(), albaICPUtility::RegResult::R, Rotation_classif(), RotationFixedFlag, albaICPUtility::RegResult::t, albaICPUtility::RegResult::test, and albaICPUtility::RegResult::var.
Target_on_Source()
void albaICPUtility::Target_on_Source (vnl_matrix_fixed< double, 3, 3 > & R, vnl_vector_fixed< double, 3 > & p) inline
Definition at line 1215 of file albaICPUtility.h.
StandardRegistration()
albaICPUtility::RegResult albaICPUtility::StandardRegistration (vnl_matrix< double > & MS, vnl_matrix< double > & DS, float Convergence) inline
Definition at line 1055 of file albaICPUtility.h.
References albaICPUtility::RegResult::err, FindPointLocator(), albaICPUtility::RegResult::pose, albaICPUtility::RegResult::R, albaICPUtility::RegResult::t, albaICPUtility::RegResult::test, albaICPUtility::RegResult::th, and Theta2R().
Member Data Documentation
RotationFixedFile
wxString albaICPUtility::RotationFixedFile
Definition at line 98 of file albaICPUtility.h.
Referenced by ICP_vtkPointLocator().
RotationFixedIndexFile
wxString albaICPUtility::RotationFixedIndexFile
Definition at line 99 of file albaICPUtility.h.
Referenced by Rotation_classif().
KnownMinLocalPositionFile
wxString albaICPUtility::KnownMinLocalPositionFile
Definition at line 100 of file albaICPUtility.h.
KnownMinLocalFlag
bool albaICPUtility::KnownMinLocalFlag
Definition at line 101 of file albaICPUtility.h.
Referenced by FFRegistration().
RotationFixedFlag
bool albaICPUtility::RotationFixedFlag
Definition at line 102 of file albaICPUtility.h.
Referenced by FFRegistration().
The documentation for this class was generated from the following file:
albaICPUtility.h