ALBA 2: SparseMatrix< T > Class Template Reference
SparseMatrix< T > Class Template Reference
#include <vtkALBAPoissonSurfaceReconstruction.h>
Public Member Functions
SparseMatrix ()
SparseMatrix (int nrows)
void Resize (int r)
void SetRowSize (int row, int count)
int Entries (void)
SparseMatrix (const SparseMatrix &M)
~SparseMatrix ()
void SetZero ()
void SetIdentity ()
SparseMatrix< T > & operator= (const SparseMatrix< T > &M)
SparseMatrix< T > operator* (const T &V) const
SparseMatrix< T > & operator*= (const T &V)
SparseMatrix< T > operator* (const SparseMatrix< T > &M) const
SparseMatrix< T > Multiply (const SparseMatrix< T > &M) const
SparseMatrix< T > MultiplyTranspose (const SparseMatrix< T > &Mt) const
template<class T2 >
Vector< T2 > operator* (const Vector< T2 > &V) const
template<class T2 >
Vector< T2 > Multiply (const Vector< T2 > &V) const
template<class T2 >
void Multiply (const Vector< T2 > &In, Vector< T2 > &Out) const
SparseMatrix< T > Transpose () const
Static Public Member Functions
static int UseAllocator (void)
static void SetAllocator (const int &blockSize)
static int Solve (const SparseMatrix< T > &M, const Vector< T > &b, const int &iters, Vector< T > &solution, const T eps=1e-8)
template<class T2 >
static int SolveSymmetric (const SparseMatrix< T > &M, const Vector< T2 > &b, const int &iters, Vector< T2 > &solution, const T2 eps=1e-8, const int &reset=1)
Public Attributes
int rows
int * rowSizes
MatrixEntry< T > ** m_ppElements
Static Public Attributes
static Allocator< MatrixEntry< T > > Allocator
Detailed Description
template<class T>
class SparseMatrix< T >
class name: SparseMatrix sparse matrix is a matrix populated primarily with zeros
Definition at line 2097 of file vtkALBAPoissonSurfaceReconstruction.h.
Constructor & Destructor Documentation
SparseMatrix() [1/3]
template<class T > SparseMatrix< T >::SparseMatrix () inline
constructor
Definition at line 2119 of file vtkALBAPoissonSurfaceReconstruction.h.
References SparseMatrix< T >::m_ppElements, SparseMatrix< T >::rows, and SparseMatrix< T >::rowSizes.
SparseMatrix() [2/3]
template<class T > SparseMatrix< T >::SparseMatrix (int nrows) inline
overloaded constructor
Definition at line 2125 of file vtkALBAPoissonSurfaceReconstruction.h.
References SparseMatrix< T >::m_ppElements, SparseMatrix< T >::Resize(), SparseMatrix< T >::rows, and SparseMatrix< T >::rowSizes.
SparseMatrix() [3/3]
template<class T > SparseMatrix< T >::SparseMatrix (const SparseMatrix< T > & M) inline
overloaded constructor
Definition at line 2166 of file vtkALBAPoissonSurfaceReconstruction.h.
References SparseMatrix< T >::m_ppElements, SparseMatrix< T >::Resize(), SparseMatrix< T >::rows, SparseMatrix< T >::rowSizes, and SparseMatrix< T >::SetRowSize().
~SparseMatrix()
template<class T > SparseMatrix< T >::~SparseMatrix () inline
destructor
Definition at line 2177 of file vtkALBAPoissonSurfaceReconstruction.h.
References SparseMatrix< T >::Resize().
Member Function Documentation
UseAllocator()
template<class T > static int SparseMatrix< T >::UseAllocator (void) inline static
return allocator for sparse matrix
Definition at line 2104 of file vtkALBAPoissonSurfaceReconstruction.h.
SetAllocator()
template<class T > static void SparseMatrix< T >::SetAllocator (const int & blockSize) inline static
use allocator , allocating block size
Definition at line 2106 of file vtkALBAPoissonSurfaceReconstruction.h.
References Allocator< T >::Set().
Resize()
template<class T > void SparseMatrix< T >::Resize (int r) inline
resize the matrix
Definition at line 2132 of file vtkALBAPoissonSurfaceReconstruction.h.
References SparseMatrix< T >::m_ppElements, SparseMatrix< T >::rows, and SparseMatrix< T >::rowSizes.
Referenced by SparseMatrix< T >::operator=(), SparseMatrix< T >::SetZero(), SparseMatrix< T >::SparseMatrix(), and SparseMatrix< T >::~SparseMatrix().
SetRowSize()
template<class T > void SparseMatrix< T >::SetRowSize (int row, int count) inline
change row size
Definition at line 2148 of file vtkALBAPoissonSurfaceReconstruction.h.
References SparseMatrix< T >::m_ppElements, Allocator< T >::NewElements(), SparseMatrix< T >::rows, and SparseMatrix< T >::rowSizes.
Referenced by SparseMatrix< T >::operator=(), and SparseMatrix< T >::SparseMatrix().
Entries()
template<class T > int SparseMatrix< T >::Entries (void) inline
retrieve total number of entries summing each rowsize
Definition at line 2159 of file vtkALBAPoissonSurfaceReconstruction.h.
References SparseMatrix< T >::rows, and SparseMatrix< T >::rowSizes.
SetZero()
template<class T > void SparseMatrix< T >::SetZero () inline
set elements to zero
Definition at line 2180 of file vtkALBAPoissonSurfaceReconstruction.h.
References SparseMatrix< T >::Resize().
Referenced by SparseMatrix< T >::SetIdentity().
SetIdentity()
template<class T > void SparseMatrix< T >::SetIdentity () inline
set matrix as identity
Definition at line 2184 of file vtkALBAPoissonSurfaceReconstruction.h.
References SparseMatrix< T >::SetZero().
operator=()
template<class T > SparseMatrix< T > & SparseMatrix< T >::operator= (const SparseMatrix< T > & M) inline
operload operator for math operations
Definition at line 2191 of file vtkALBAPoissonSurfaceReconstruction.h.
References SparseMatrix< T >::m_ppElements, SparseMatrix< T >::Resize(), SparseMatrix< T >::rows, SparseMatrix< T >::rowSizes, and SparseMatrix< T >::SetRowSize().
operator*() [1/3]
template<class T > SparseMatrix< T > SparseMatrix< T >::operator* (const T & V) const inline
operload operator for math operations
Definition at line 2201 of file vtkALBAPoissonSurfaceReconstruction.h.
operator*=()
template<class T > SparseMatrix< T > & SparseMatrix< T >::operator*= (const T & V) inline
operload operator for math operations
Definition at line 2207 of file vtkALBAPoissonSurfaceReconstruction.h.
References SparseMatrix< T >::m_ppElements, SparseMatrix< T >::rows, and SparseMatrix< T >::rowSizes.
operator*() [2/3]
template<class T > SparseMatrix< T > SparseMatrix< T >::operator* (const SparseMatrix< T > & M) const inline
operload operator for math operations
Definition at line 2219 of file vtkALBAPoissonSurfaceReconstruction.h.
References SparseMatrix< T >::Multiply().
Multiply() [1/3]
template<class T > SparseMatrix< T > SparseMatrix< T >::Multiply (const SparseMatrix< T > & M) const inline
multiplication with another sparse matrix
Definition at line 2223 of file vtkALBAPoissonSurfaceReconstruction.h.
References SparseMatrix< T >::m_ppElements.
Referenced by SparseMatrix< T >::operator*(), and SparseMatrix< T >::SolveSymmetric().
MultiplyTranspose()
template<class T > SparseMatrix< T > SparseMatrix< T >::MultiplyTranspose (const SparseMatrix< T > & Mt) const
multiplication with another transpose sparse matrix
operator*() [3/3]
template<class T > template<class T2 > Vector< T2 > SparseMatrix< T >::operator* (const Vector< T2 > & V) const inline
operload operator for math operations
Definition at line 2241 of file vtkALBAPoissonSurfaceReconstruction.h.
References SparseMatrix< T >::Multiply().
Multiply() [2/3]
template<class T > template<class T2 > Vector< T2 > SparseMatrix< T >::Multiply (const Vector< T2 > & V) const inline
Multiply with a vector and return the result.
Definition at line 2246 of file vtkALBAPoissonSurfaceReconstruction.h.
References SparseMatrix< T >::m_ppElements, Vector< T >::m_pV, SparseMatrix< T >::rows, and SparseMatrix< T >::rowSizes.
Multiply() [3/3]
template<class T > template<class T2 > void SparseMatrix< T >::Multiply (const Vector< T2 > & In, Vector< T2 > & Out) const inline
Multiply sparse matrix and vector and retrieve result.
Definition at line 2262 of file vtkALBAPoissonSurfaceReconstruction.h.
References SparseMatrix< T >::m_ppElements, Vector< T >::m_pV, SparseMatrix< T >::rows, and SparseMatrix< T >::rowSizes.
Transpose()
template<class T > SparseMatrix< T > SparseMatrix< T >::Transpose () const inline
transpose sparse matrix
Definition at line 2271 of file vtkALBAPoissonSurfaceReconstruction.h.
References SparseMatrix< T >::m_ppElements.
Referenced by SparseMatrix< T >::Solve().
Solve()
template<class T > static int SparseMatrix< T >::Solve (const SparseMatrix< T > & M, const Vector< T > & b, const int & iters, Vector< T > & solution, const T eps = 1e-8) inline static
Solve for x s.t.
M(x)=b by solving for x s.t. M^tM(x)=M^t(b)
Definition at line 2283 of file vtkALBAPoissonSurfaceReconstruction.h.
References Vector< T >::Dot(), Vector< T >::Resize(), Vector< T >::SetZero(), and SparseMatrix< T >::Transpose().
SolveSymmetric()
template<class T > template<class T2 > static int SparseMatrix< T >::SolveSymmetric (const SparseMatrix< T > & M, const Vector< T2 > & b, const int & iters, Vector< T2 > & solution, const T2 eps = 1e-8, const int & reset = 1) inline static
reduced as symmetric sparse matrix and solve
Definition at line 2312 of file vtkALBAPoissonSurfaceReconstruction.h.
References Vector< T >::Add(), Vector< T >::AddScaled(), Vector< T >::Dimensions(), Vector< T >::Dot(), SparseMatrix< T >::Multiply(), Vector< T >::Resize(), Vector< T >::SetZero(), and Vector< T >::SubtractScaled().
Member Data Documentation
Allocator
template<class T > Allocator< MatrixEntry< T > > SparseMatrix< T >::Allocator static
Definition at line 2102 of file vtkALBAPoissonSurfaceReconstruction.h.
rows
template<class T > int SparseMatrix< T >::rows
Definition at line 2114 of file vtkALBAPoissonSurfaceReconstruction.h.
Referenced by SparseMatrix< T >::Entries(), SparseMatrix< T >::Multiply(), SparseMatrix< T >::operator*=(), SparseMatrix< T >::operator=(), SparseMatrix< T >::Resize(), SparseMatrix< T >::SetRowSize(), and SparseMatrix< T >::SparseMatrix().
rowSizes
template<class T > int* SparseMatrix< T >::rowSizes
Definition at line 2115 of file vtkALBAPoissonSurfaceReconstruction.h.
Referenced by SparseMatrix< T >::Entries(), SparseMatrix< T >::Multiply(), SparseMatrix< T >::operator*=(), SparseMatrix< T >::operator=(), SparseMatrix< T >::Resize(), SparseMatrix< T >::SetRowSize(), and SparseMatrix< T >::SparseMatrix().
m_ppElements
template<class T > MatrixEntry<T>** SparseMatrix< T >::m_ppElements
Definition at line 2116 of file vtkALBAPoissonSurfaceReconstruction.h.
Referenced by SparseMatrix< T >::Multiply(), SparseMatrix< T >::operator*=(), SparseMatrix< T >::operator=(), SparseMatrix< T >::Resize(), SparseMatrix< T >::SetRowSize(), SparseMatrix< T >::SparseMatrix(), and SparseMatrix< T >::Transpose().
The documentation for this class was generated from the following file:
vtkALBAPoissonSurfaceReconstruction.h