ALBA 2: albaVMELandmarkCloud Class Reference
albaVMELandmarkCloud Class Reference
#include <albaVMELandmarkCloud.h>
Public Types
enum LANDMAERK_CLOUD_WIDGET_ID { ID_LM_RADIUS = Superclass::ID_LAST , ID_LM_SPHERE_RESOLUTION , ID_LAST }
Public Types inherited from albaVMEGeneric
enum DATA_REFERENCE_TYPE { ALBA_VME_COPY_DATA , ALBA_VME_REFERENCE_DATA , ALBA_VME_DETACH_DATA }
Public Types inherited from albaVMEGenericAbstract
enum VME_GUI_ID { ID_VME_CRYPTING = Superclass::ID_LAST , ID_LAST }
Public Types inherited from albaVME
enum VME_WIDGET_ID { ID_NAME = MINID , ID_PRINT_INFO , ID_HELP , ID_LAST }
enum VME_VISUAL_MODE { DEFAULT_VISUAL_MODE = 0 , NO_DATA_VISUAL_MODE }
typedef std::vector< albaAutoPointer< albaVME > > albaChildrenVector
typedef std::map< albaString, albaAutoPointer< albaAttribute > > albaAttributesMap
typedef std::map< albaString, albaVMELink > albaLinksMap
typedef std::set< albaVME * > albaVMESet
typedef std::vector< albaVMEBackLink > albaVMEBackLinks
Public Member Functions
albaTypeMacro (albaVMELandmarkCloud, albaVMEPointSet)
virtual void OnEvent (albaEventBase *alba_event)
virtual int DeepCopy (albaVME *a)
void CopyLandmarks (albaVMELandmarkCloud *lmc)
virtual bool Equals (albaVME *vme)
virtual unsigned long GetMTime ()
int AppendLandmark (double x, double y, double z, const char *name)
int AppendLandmark (double *pos, const char *name)
int AppendLandmark (const char *name)
int SetLandmark (int idx, double x, double y, double z, albaTimeStamp t=0)
int SetLandmark (const char *name, double x, double y, double z, albaTimeStamp t=0)
int SetLandmark (albaVMELandmark *lm, double x, double y, double z, albaTimeStamp t=0)
int GetLandmark (int idx, double &x, double &y, double &z, albaTimeStamp t=0)
int GetLandmark (const char *name, double &x, double &y, double &z, albaTimeStamp t=0)
int GetLandmark (int idx, double xyz[3], albaTimeStamp t=0)
int GetLandmark (const char *name, double xyz[3], albaTimeStamp t=0)
albaVMELandmark * GetLandmark (const char *name)
albaVMELandmark * GetLandmark (int idx)
int GetLandmarkIndex (albaVMELandmark *lm)
int GetLandmarkIndex (const char *name)
void GetLandmarkPosition (int idx, double pos[3], albaTimeStamp t=-1)
int RemoveLandmark (int idx)
int GetNumberOfLandmarks ()
virtual int SetNumberOfLandmarks (int num)
virtual const char * GetLandmarkName (int idx)
virtual void SetLandmarkName (int idx, const char *name)
virtual void SetRadius (double rad, bool force_update=false)
virtual double GetRadius ()
virtual void SetSphereResolution (int res, bool force_update=false)
virtual int GetSphereResolution ()
virtual int SetLandmarkVisibility (int idx, bool a, albaTimeStamp t=0)
int SetLandmarkVisibility (const char *name, bool a, albaTimeStamp t=0)
virtual bool GetLandmarkVisibility (int idx, albaTimeStamp t=0)
bool GetLandmarkVisibility (const char *name, albaTimeStamp t=0)
void SetDefaultVisibility (int v)
int GetDefaultVisibility ()
void DefaultVisibilityOn ()
void DefaultVisibilityOff ()
int GetNumberOfVisibleLandmarks (albaTimeStamp t=0)
bool IsRigid ()
mmaMaterial * GetMaterial ()
virtual albaString GetVisualPipe ()
void Print (std::ostream &os, const int tabs=0)
virtual bool IsDataAvailable ()
virtual int AddChild (albaVME *node)
virtual void RemoveChild (albaVME *node)
void ShowLandmark (albaVMELandmark *lm, bool show)
void ShowAllLandmarks (bool show=true)
bool IsLandmarkShow (albaVMELandmark *lm)
int GetLandmarkShowNumber ()
void CreateLMStructureFromDataVector ()
albaVMELandmark * GetNearestLandmark (double pos[3], bool SerchOnlyVisible)
ALBA_ID_DEC (CLOUD_RADIUS_MODIFIED)
ALBA_ID_DEC (CLOUD_SPHERE_RES)
Public Member Functions inherited from albaVMEPointSet
albaTypeMacro (albaVMEPointSet, albaVMEGeneric)
virtual int SetData (vtkPolyData *data, albaTimeStamp t, int mode=ALBA_VME_COPY_DATA)
virtual albaVMEOutput * GetOutput ()
albaVMEOutputPointSet * GetPointSetOutput ()
virtual int AppendPoint (double x, double y, double z, albaTimeStamp t=-1)
virtual int RemovePoint (int idx, albaTimeStamp t=-1)
virtual int SetPoint (int idx, double x, double y, double z, albaTimeStamp t=-1)
virtual int SetPoint (int idx, double xyz[3], albaTimeStamp t=-1)
virtual int GetPoint (int idx, double &x, double &y, double &z, albaTimeStamp t=-1)
virtual int GetPoint (int idx, double xyz[3], albaTimeStamp t=-1)
virtual int GetNumberOfPoints (albaTimeStamp t=-1)
virtual void SetNumberOfPoints (int num, albaTimeStamp t=-1)
mmaMaterial * GetMaterial ()
Public Member Functions inherited from albaVMEGeneric
albaTypeMacro (albaVMEGeneric, albaVMEGenericAbstract)
virtual int SetData (vtkDataSet *data, albaTimeStamp t, int mode=ALBA_VME_COPY_DATA)
int SetDataByReference (vtkDataSet *data, albaTimeStamp t)
int SetDataByDetaching (vtkDataSet *data, albaTimeStamp t)
albaVMEOutputVTK * GetVTKOutput ()
virtual albaVMEOutput * GetOutput ()
virtual albaString GetVisualPipe ()
Public Member Functions inherited from albaVMEGenericAbstract
albaTypeMacro (albaVMEGenericAbstract, albaVME)
virtual void Print (std::ostream &os, const int tabs=0)
virtual int DeepCopy (albaVME *a)
virtual int DeepCopyVmeLarge (albaVME *a)
virtual int ShallowCopy (albaVME *a)
virtual bool Equals (albaVME *vme)
virtual int ReparentTo (albaVME *parent)
albaMatrixVector * GetMatrixVector ()
void SetMatrix (const albaMatrix &mat)
albaDataVector * GetDataVector ()
virtual void GetDataTimeStamps (std::vector< albaTimeStamp > &kframes)
void GetMatrixTimeStamps (std::vector< albaTimeStamp > &kframes)
virtual void GetLocalTimeStamps (std::vector< albaTimeStamp > &kframes)
void GetLocalTimeBounds (albaTimeStamp tbounds[2])
virtual bool IsAnimated ()
virtual bool IsDataAvailable ()
virtual void OnEvent (albaEventBase *alba_event)
bool GetStoreDataVector () const
Public Member Functions inherited from albaVME
albaAbstractTypeMacro (albaVME, albaReferenceCounted)
virtual albaObject * NewObjectInstance () const
albaVME * NewInstance ()
int Initialize ()
void Shutdown ()
int IsInitialized ()
int Store ()
int Restore ()
const char * GetName ()
virtual void SetName (const char *name)
virtual bool CanCopy (albaVME *vme)
albaVME * MakeCopy ()
albaVME * CopyTree ()
albaVME * GetChild (albaID idx, bool onlyVisible=false)
albaVME * GetFirstChild (bool onlyVisible=false)
albaVME * GetLastChild (bool onlyVisible=false)
albaVME * GetByPath (const char *path, bool onlyVisible=true)
virtual int AddChild (albaVME *node)
virtual void RemoveChild (const albaID idx, bool onlyVisible=false)
virtual void RemoveChild (albaVME *node)
int FindNodeIdx (albaVME *a, bool onlyVisible=false)
int FindNodeIdx (const char *name, bool onlyVisible=false)
albaVME * FindInTreeByTag (const char *name, const char *value="", int type=ALBA_STRING_TAG)
albaVME * FindInTreeByName (const char *name, bool match_case=true, bool whole_word=true)
albaVME * FindInTreeById (const albaID id)
virtual int ReparentTo (albaVME *parent)
void Import (albaVME *tree)
bool IsAChild (albaVME *a)
bool IsInTree (albaVME *a)
albaVME * GetRoot ()
bool IsEmpty () const
bool IsValid ()
unsigned long GetNumberOfChildren () const
unsigned long GetNumberOfChildren (bool onlyVisible)
void CleanTree ()
void RemoveAllChildren ()
albaVMEIterator * NewIterator ()
void SetVisibleToTraverse (bool flag)
bool GetVisibleToTraverse ()
bool IsVisible ()
bool CompareTree (albaVME *vme)
virtual void UnRegister (void *o)
virtual void OnEvent (albaEventBase *e)
const albaChildrenVector * GetChildren ()
albaAttributesMap * GetAttributes ()
void SetAttribute (const char *name, albaAttribute *a)
albaAttribute * GetAttribute (const char *name)
void RemoveAttribute (const char *name)
void RemoveAllAttributes ()
albaTagArray * GetTagArray ()
albaVME * GetLink (const char *name)
void SetLink (const char *name, albaVME *node)
void SetMandatoryLink (const char *name, albaVME *node)
void SetLink (const char *name, albaVME *node, LinkType type)
void AddBackLink (const char *name, albaVME *node)
void RemoveBackLink (const char *name, albaVME *node)
void SetOldSubIdLink (albaString link_name, albaID link_node_id, albaID link_node_subid)
void RemoveLink (const char *name)
albaID GetNumberOfLinks ()
albaID GetNumberOfBackLinks ()
albaVMEBackLinks GetBackLinks ()
void RemoveAllLinks ()
void RemoveAllBackLinks ()
albaVMESet GetDependenciesVMEs ()
void RemoveDependenciesVMEs ()
bool WillBeRemovedWithDependencies (albaVME *vme)
albaLinksMap * GetLinks ()
void ForwardUpEvent (albaEventBase *alba_event)
void ForwardUpEvent (albaEventBase &alba_event)
void ForwardDownEvent (albaEventBase *alba_event)
void ForwardDownEvent (albaEventBase &alba_event)
albaGUI * GetGui ()
void DeleteGui ()
albaID GetId () const
void UpdateId ()
virtual unsigned long GetMTime ()
void DependsOnLinkedNodeOn ()
void DependsOnLinkedNodeOff ()
virtual void Print (std::ostream &os, const int tabs=0)
albaVME * GetParent () const
virtual int DeepCopy (albaVME *a)
virtual int ShallowCopy (albaVME *a)
virtual bool Equals (albaVME *vme)
virtual void SetTimeStamp (albaTimeStamp t)
virtual albaTimeStamp GetTimeStamp ()
void SetTreeTime (albaTimeStamp t)
virtual void SetMatrix (const albaMatrix &mat)=0
void SetPose (const albaMatrix &mat, albaTimeStamp t)
void SetPose (double x, double y, double z, double rx, double ry, double rz, albaTimeStamp t)
void SetPose (double xyz[3], double rxyz[3], albaTimeStamp t)
void ApplyMatrix (const albaMatrix &matrix, int premultiply, albaTimeStamp t=-1)
void SetAbsPose (double x, double y, double z, double rx, double ry, double rz, albaTimeStamp t=-1)
void SetAbsPose (double xyz[3], double rxyz[3], albaTimeStamp t=-1)
void SetAbsMatrix (const albaMatrix &matrix, albaTimeStamp t)
virtual void SetAbsMatrix (const albaMatrix &matrix)
void ApplyAbsMatrix (const albaMatrix &matrix, int premultiply, albaTimeStamp t=-1)
virtual bool CanReparentTo (albaVME *parent)
albaMatrixPipe * GetMatrixPipe ()
albaAbsMatrixPipe * GetAbsMatrixPipe ()
albaDataPipe * GetDataPipe ()
virtual void Update ()
virtual void GetLocalTimeStamps (std::vector< albaTimeStamp > &kframes)=0
virtual void GetLocalTimeBounds (albaTimeStamp tbounds[2])
virtual void GetAbsTimeStamps (std::vector< albaTimeStamp > &kframes)
virtual void GetTimeStamps (std::vector< albaTimeStamp > &kframes)
int GetNumberOfTimeStamps ()
int GetNumberOfLocalTimeStamps ()
virtual bool IsAnimated ()
virtual bool IsDataAvailable ()
void SetCrypting (int crypting)
int GetCrypting ()
virtual albaVMEOutput * GetOutput ()
virtual albaString GetVisualPipe ()
virtual albaString GetVisualPipeSlice ()
void SetVisualMode (int mode)
int GetVisualMode ()
albaInteractor * GetBehavior ()
void SetBehavior (albaInteractor *bh)
void TestModeOn ()
void TestModeOff ()
bool GetTestMode ()
Public Member Functions inherited from albaReferenceCounted
albaReferenceCounted ()
virtual ~albaReferenceCounted ()
albaAbstractTypeMacro (albaReferenceCounted, albaObject)
virtual void Delete ()
void Register (void *obj)
virtual void UnRegister (void *obj)
int GetReferenceCount ()
void SetReferenceCount (int)
Public Member Functions inherited from albaObject
albaObject ()
virtual ~albaObject ()
virtual void Delete ()
virtual const char * GetTypeName () const
virtual bool IsA (const char *type_name) const
virtual bool IsA (const albaTypeID &type_id) const
virtual albaObject * NewObjectInstance () const =0
virtual const albaTypeID & GetTypeId () const
virtual void Print (std::ostream &os, const int indent=0) const
albaObject (const albaObject &c)
Public Member Functions inherited from albaEventBroadcaster
albaEventBroadcaster (void *owner=NULL)
virtual ~albaEventBroadcaster ()
albaEventBroadcaster (const albaEventBroadcaster &c)
void AddObserver (albaObserver *obj)
void AddObserver (albaObserver &obj)
albaObserverCallback * AddObserverCallback (void(*f)(void *sender, albaID eid, void *clientdata, void *calldata))
bool RemoveObserver (albaObserver *obj)
void RemoveAllObservers ()
bool IsObserver (albaObserver *obj)
bool HasObservers ()
void GetObservers (std::vector< albaObserver * > &olist)
void InvokeEvent (albaEventBase &e)
void InvokeEvent (albaEventBase *e)
void InvokeEvent (void *sender, albaID id=ID_NO_EVENT, void *data=NULL)
void SetChannel (albaID ch)
albaID GetChannel ()
virtual void SetListener (albaObserver *o)
Public Member Functions inherited from albaEventSender
albaEventSender ()
virtual void SetListener (albaObserver *o)
virtual albaObserver * GetListener ()
virtual bool HasListener ()
virtual void InvokeEvent (albaEventBase &e)
virtual void InvokeEvent (albaEventBase *e)
virtual void InvokeEvent (void *sender, albaID id=ID_NO_EVENT, void *data=NULL)
Public Member Functions inherited from albaStorable
albaStorable ()
int Store (albaStorageElement *element)
int Restore (albaStorageElement *element)
albaObject * CastToObject ()
bool IsStorable ()
Public Member Functions inherited from albaObserver
albaObserver ()
virtual ~albaObserver ()
virtual void OnEvent (albaEventBase *e)=0
Public Member Functions inherited from albaTimeStamped
virtual void Modified ()
virtual unsigned long GetMTime ()
Static Public Member Functions
static char ** GetIcon ()
Static Public Member Functions inherited from albaVMEPointSet
static char ** GetIcon ()
Static Public Member Functions inherited from albaVMEGeneric
static char ** GetIcon ()
Static Public Member Functions inherited from albaVMEGenericAbstract
static char ** GetIcon ()
Static Public Member Functions inherited from albaVME
static albaVME * MakeCopy (albaVME *a)
static albaVME * CopyTree (albaVME *vme, albaVME *parent=NULL)
static char ** GetIcon ()
Static Public Member Functions inherited from albaObject
static const char * GetStaticTypeName ()
static bool IsStaticType (const char *type_name)
static bool IsStaticType (const albaTypeID &type_id)
static const albaTypeID & GetStaticTypeId ()
static albaObject * SafeDownCast (albaObject *o)
Static Public Member Functions inherited from albaStorable
static albaStorable * SafeCastToObject (albaObject *o)
Protected Member Functions
albaVMELandmarkCloud ()
virtual ~albaVMELandmarkCloud ()
virtual int InternalStore (albaStorageElement *parent)
virtual int InternalRestore (albaStorageElement *node)
virtual int InternalInitialize ()
virtual vtkPolyData * NewPolyData (albaTimeStamp t)
virtual int AppendPoint (vtkPolyData *polydata, double x, double y, double z, int num=1)
virtual int SetLandmarkVisibility (vtkPolyData *polydata, int idx, bool a)
virtual bool GetLandmarkVisibility (vtkPolyData *polydata, int idx)
int SetLandmarkToPolydata (int idx, double x, double y, double z, bool visibility, albaTimeStamp &t)
virtual albaGUI * CreateGui ()
Protected Member Functions inherited from albaVMEPointSet
albaVMEPointSet ()
virtual ~albaVMEPointSet ()
virtual int InternalInitialize ()
vtkPolyData * GetPolyData (albaTimeStamp t)
int GetPoint (vtkPolyData *polydata, int idx, double xyz[3])
virtual vtkPolyData * NewPolyData (albaTimeStamp t)
virtual int AppendPoint (vtkPolyData *polydata, double x, double y, double z, int num=1)
virtual int RemovePoint (vtkPolyData *polydata, int idx)
int SetPoint (vtkPolyData *polydata, int idx, double x, double y, double z)
Protected Member Functions inherited from albaVMEGeneric
albaVMEGeneric ()
virtual ~albaVMEGeneric ()
Protected Member Functions inherited from albaVMEGenericAbstract
albaVMEGenericAbstract ()
virtual ~albaVMEGenericAbstract ()
virtual int InternalStore (albaStorageElement *parent)
virtual int InternalRestore (albaStorageElement *node)
virtual albaGUI * CreateGui ()
Protected Member Functions inherited from albaVME
albaVME ()
virtual ~albaVME ()
void SetId (albaID id)
virtual int InternalStore (albaStorageElement *parent)
virtual int InternalRestore (albaStorageElement *node)
virtual void InternalShutdown ()
virtual int SetParent (albaVME *parent)
void OnNodeDetachedFromTree (albaEventBase *e)
void OnNodeAttachedToTree (albaEventBase *e)
void OnNodeDestroyed (albaEventBase *e)
void GetDependenciesVMEs (albaVMESet &dependencies, albaVME *vme)
virtual int InternalInitialize ()
virtual void InternalPreUpdate ()
virtual void InternalUpdate ()
virtual void InternalSetTimeStamp (albaTimeStamp t)
void SetOutput (albaVMEOutput *output)
virtual int SetDataPipe (albaDataPipe *dpipe)
int SetMatrixPipe (albaMatrixPipe *pipe)
albaString GetTypeNameFromType (albaString typeName)
void SetAbsMatrixPipe (albaAbsMatrixPipe *pipe)
virtual albaGUI * CreateGui ()
void NodeOnEvent (albaEventBase *e)
virtual int InternalStore (albaStorageElement *node)=0
virtual int InternalRestore (albaStorageElement *node)=0
Protected Attributes
int m_SingleFile
int m_NumberOfLandmarks
int m_DefaultVisibility
int m_SphereResolution
double m_Radius
int m_LanfmarkShowNumber
std::vector< albaVMELandmark * > m_LMChildren
std::vector< bool > m_LMChildrenShow
std::map< albaVMELandmark *, int > m_LMIndexesMap
Protected Attributes inherited from albaVMEGenericAbstract
albaMatrixVector * m_MatrixVector
albaDataVector * m_DataVector
bool m_StoreDataVector
Protected Attributes inherited from albaVME
albaGUI * m_Gui
albaChildrenVector m_Children
albaVME * m_Parent
albaAttributesMap m_Attributes
albaLinksMap m_Links
albaVMEBackLinks m_BackLinks
std::vector< albaOldSubIdLink > m_OldSubIdLinks
albaString m_Name
albaString m_GuiName
albaID m_Id
bool m_VisibleToTraverse
bool m_Initialized
bool m_DependsOnLinkedNode
bool m_TestMode
albaAutoPointer< albaDataPipe > m_DataPipe
albaAutoPointer< albaMatrixPipe > m_MatrixPipe
albaAutoPointer< albaAbsMatrixPipe > m_AbsMatrixPipe
albaVMEOutput * m_Output
albaTimeStamp m_CurrentTime
int m_Crypting
albaInteractor * m_Behavior
int m_VisualMode
Protected Attributes inherited from albaReferenceCounted
int m_ReferenceCount
Protected Attributes inherited from albaObject
bool m_HeapFlag
Protected Attributes inherited from albaEventBroadcaster
albaObserversList m_Observers
albaID m_Channel
Protected Attributes inherited from albaEventSender
albaObserver * m_Listener
Protected Attributes inherited from albaStorable
bool m_Storable
Protected Attributes inherited from albaTimeStamped
albaMTime m_MTime
Additional Inherited Members
Protected Types inherited from albaEventBroadcaster
typedef std::list< albaObserver * > albaObserversList
Static Protected Member Functions inherited from albaVME
static albaVME * InternalCopyTree (albaVME *vme, albaVME *parent)
Detailed Description
albaVMELandmarkCloud - this class represents a cloud of landmarks albaVMELandmarkRigidCloud is a concrete VME object storing a cloud of landmarks whose relative position can change along time.
This VME is a specialization of albaVMEPointSet with all time frames having the same number of points (thus each point exist in all time frames) and a table of names assigned to each point. This table are stored into the VME TagArray with tag names "LM_NAME". This class also supports time-varying visibility for landmarks: for any timestamp can be defined a visibility. Notice that for each time stamp for which is defined a position is also defined a default visibility (see SetDefaultVisibility) and vice versa for each time stamp for which a visibility is defined also a position is automatically set eventually copying the position returned by interpolator if not. This is due to internal data representation, and defines that time base for positions and visibility attributes are the same. The cloud manage also children VMELandmarks, when a landmark is reparent to the cloud the landmark is added to the out but is visibility is set to false. On the show operations the visibility of the landmark is changed. The landmarks vme communicate with this cloud through parent variable, and some special management is defined on albaLogicWithManagers
See also
albaVME albaPointSet albaLandmark albaLogicWithManagers.
Definition at line 49 of file albaVMELandmarkCloud.h.
Member Enumeration Documentation
LANDMAERK_CLOUD_WIDGET_ID
enum albaVMELandmarkCloud::LANDMAERK_CLOUD_WIDGET_ID
Enumerator
ID_LM_RADIUS
ID_LM_SPHERE_RESOLUTION
ID_LAST
Definition at line 147 of file albaVMELandmarkCloud.h.
Constructor & Destructor Documentation
albaVMELandmarkCloud()
albaVMELandmarkCloud::albaVMELandmarkCloud () protected
~albaVMELandmarkCloud()
virtual albaVMELandmarkCloud::~albaVMELandmarkCloud () protected virtual
Member Function Documentation
albaTypeMacro()
albaVMELandmarkCloud::albaTypeMacro (albaVMELandmarkCloud , albaVMEPointSet)
OnEvent()
virtual void albaVMELandmarkCloud::OnEvent (albaEventBase * alba_event) virtual
Precess events coming from other objects.
Reimplemented from albaVMEGenericAbstract.
DeepCopy()
virtual int albaVMELandmarkCloud::DeepCopy (albaVME * a) virtual
Copy the contents of another landmarkcloud into this one.
Reimplemented from albaVMEGenericAbstract.
CopyLandmarks()
void albaVMELandmarkCloud::CopyLandmarks (albaVMELandmarkCloud * lmc)
Copy landmarks form a specified landmark cloud.
Equals()
virtual bool albaVMELandmarkCloud::Equals (albaVME * vme) virtual
Compare with another landmarkcloud.
Reimplemented from albaVMEGenericAbstract.
GetMTime()
virtual unsigned long albaVMELandmarkCloud::GetMTime () virtual
Return the modification time.
Reimplemented from albaVME.
AppendLandmark() [1/3]
int albaVMELandmarkCloud::AppendLandmark (double x, double y, double z, const char * name)
Add a new landmark an returns its index.
BEWARE: landmark is added to all the VME-items, and its position should for each time frame by means SetPoint() The second syntax is used to add points in t=0, and is used in place of corresponding function of ex. RigidLandmarkClouds. The check for duplicates flag is used to inhibit append if the cloud contains a landmark with the same name already. Set this flag to false for faster appending.
AppendLandmark() [2/3]
int albaVMELandmarkCloud::AppendLandmark (double * pos, const char * name) inline
Definition at line 88 of file albaVMELandmarkCloud.h.
References AppendLandmark().
Referenced by AppendLandmark().
AppendLandmark() [3/3]
int albaVMELandmarkCloud::AppendLandmark (const char * name) inline
Definition at line 89 of file albaVMELandmarkCloud.h.
References AppendLandmark().
Referenced by AppendLandmark().
SetLandmark() [1/3]
int albaVMELandmarkCloud::SetLandmark (int idx, double x, double y, double z, albaTimeStamp t = 0)
Set/Get a landmark.
In case the specified idx is invalid return ALBA_ERROR
SetLandmark() [2/3]
int albaVMELandmarkCloud::SetLandmark (const char * name, double x, double y, double z, albaTimeStamp t = 0) inline
Definition at line 94 of file albaVMELandmarkCloud.h.
References SetLandmark().
Referenced by SetLandmark().
SetLandmark() [3/3]
int albaVMELandmarkCloud::SetLandmark (albaVMELandmark * lm, double x, double y, double z, albaTimeStamp t = 0) inline
Definition at line 95 of file albaVMELandmarkCloud.h.
References SetLandmark().
Referenced by SetLandmark().
GetLandmark() [1/6]
int albaVMELandmarkCloud::GetLandmark (int idx, double & x, double & y, double & z, albaTimeStamp t = 0)
GetLandmark() [2/6]
int albaVMELandmarkCloud::GetLandmark (const char * name, double & x, double & y, double & z, albaTimeStamp t = 0) inline
Definition at line 99 of file albaVMELandmarkCloud.h.
References GetLandmark().
Referenced by GetLandmark().
GetLandmark() [3/6]
int albaVMELandmarkCloud::GetLandmark (int idx, double xyz[3], albaTimeStamp t = 0)
GetLandmark() [4/6]
int albaVMELandmarkCloud::GetLandmark (const char * name, double xyz[3], albaTimeStamp t = 0) inline
Definition at line 101 of file albaVMELandmarkCloud.h.
References GetLandmark().
Referenced by GetLandmark().
GetLandmark() [5/6]
albaVMELandmark * albaVMELandmarkCloud::GetLandmark (const char * name)
Find the index of a landmark given its name.
GetLandmark() [6/6]
albaVMELandmark * albaVMELandmarkCloud::GetLandmark (int idx)
Get the landmark by index.
GetLandmarkIndex() [1/2]
int albaVMELandmarkCloud::GetLandmarkIndex (albaVMELandmark * lm)
Get index for specified LM.
GetLandmarkIndex() [2/2]
int albaVMELandmarkCloud::GetLandmarkIndex (const char * name)
Find the index of a landmark given its name.
GetLandmarkPosition()
void albaVMELandmarkCloud::GetLandmarkPosition (int idx, double pos[3], albaTimeStamp t = -1)
Return the position of the landmark number 'idx' at the timestamp t.
RemoveLandmark()
int albaVMELandmarkCloud::RemoveLandmark (int idx)
Remove a landmark.
In case the id is invalid return ALBA_ERROR BEWARE: landmark is removed from all the VME-items
GetNumberOfLandmarks()
int albaVMELandmarkCloud::GetNumberOfLandmarks ()
Set/Get the number of landmarks stored in this VME.
BEWARE the number of landmarks is the same for all the time frames (items)
SetNumberOfLandmarks()
virtual int albaVMELandmarkCloud::SetNumberOfLandmarks (int num) virtual
GetLandmarkName()
virtual const char * albaVMELandmarkCloud::GetLandmarkName (int idx) virtual
Set/get the name for idx-th landmark.
Return null in case no landmark name was defined for that index.
SetLandmarkName()
virtual void albaVMELandmarkCloud::SetLandmarkName (int idx, const char * name) virtual
SetRadius()
virtual void albaVMELandmarkCloud::SetRadius (double rad, bool force_update = false) virtual
Set/Get the m_Radius of this landmark.
The radius is stored as an TAG item: "LM_RADIUS". If no radius has been ever set, the default value is "1".
GetRadius()
virtual double albaVMELandmarkCloud::GetRadius () virtual
SetSphereResolution()
virtual void albaVMELandmarkCloud::SetSphereResolution (int res, bool force_update = false) virtual
Set/Get the resolution of the landmarks' spheres.
The resolution is stored as an TAG item: "LM_SPHERE_RESOLUTION". If no resolution has been ever set, default value is "15".
GetSphereResolution()
virtual int albaVMELandmarkCloud::GetSphereResolution () virtual
SetLandmarkVisibility() [1/3]
virtual int albaVMELandmarkCloud::SetLandmarkVisibility (int idx, bool a, albaTimeStamp t = 0) virtual
Set/Get the visibility property for a given landmark for a given time stamp.
The visibility is stored as a scalar attribute of the associated polydata's point. Notice that visibility is implicitly defined as 'm_DefaultVisibility' when a position is specified for a timestamp nd nothing is specified for the visibility at that time. On the other hand, if visibility is defined for some time a position is implicitly defined for that time stamp.
SetLandmarkVisibility() [2/3]
int albaVMELandmarkCloud::SetLandmarkVisibility (const char * name, bool a, albaTimeStamp t = 0) inline
Definition at line 162 of file albaVMELandmarkCloud.h.
References SetLandmarkVisibility().
Referenced by SetLandmarkVisibility().
GetLandmarkVisibility() [1/3]
virtual bool albaVMELandmarkCloud::GetLandmarkVisibility (int idx, albaTimeStamp t = 0) virtual
GetLandmarkVisibility() [2/3]
bool albaVMELandmarkCloud::GetLandmarkVisibility (const char * name, albaTimeStamp t = 0) inline
Definition at line 164 of file albaVMELandmarkCloud.h.
References GetLandmarkVisibility().
Referenced by GetLandmarkVisibility().
SetDefaultVisibility()
void albaVMELandmarkCloud::SetDefaultVisibility (int v) inline
Set/Get the default visibility attribute.
When default visibility is set to true, the creation of a new time frame (by setting a landmark position for a given timestamp), makes all the other landmarks to be also visible at the same timestamp. If false, the visibility of the others landmark is automatically set to false for the other landmarks. Notice currently this is not a persistent attribute.
Definition at line 171 of file albaVMELandmarkCloud.h.
References albaTimeStamped::Modified().
GetDefaultVisibility()
int albaVMELandmarkCloud::GetDefaultVisibility () inline
Definition at line 172 of file albaVMELandmarkCloud.h.
DefaultVisibilityOn()
void albaVMELandmarkCloud::DefaultVisibilityOn () inline
Definition at line 173 of file albaVMELandmarkCloud.h.
DefaultVisibilityOff()
void albaVMELandmarkCloud::DefaultVisibilityOff () inline
Definition at line 174 of file albaVMELandmarkCloud.h.
GetNumberOfVisibleLandmarks()
int albaVMELandmarkCloud::GetNumberOfVisibleLandmarks (albaTimeStamp t = 0)
Return number of visible landmarks.
IsRigid()
bool albaVMELandmarkCloud::IsRigid ()
Return true if it's a rigid landmark cloud (i.e.
it has a single time frame)
GetIcon()
static char ** albaVMELandmarkCloud::GetIcon () static
Return icon.
GetMaterial()
mmaMaterial * albaVMELandmarkCloud::GetMaterial ()
Return pointer to material attribute.
GetVisualPipe()
virtual albaString albaVMELandmarkCloud::GetVisualPipe () inline virtual
Return the suggested pipe-typename for the visualization of this vme.
Reimplemented from albaVMEGeneric.
Definition at line 189 of file albaVMELandmarkCloud.h.
Print()
void albaVMELandmarkCloud::Print (std::ostream & os, const int tabs = 0) virtual
print a dump of this object
Reimplemented from albaVMEGenericAbstract.
IsDataAvailable()
virtual bool albaVMELandmarkCloud::IsDataAvailable () virtual
Return true if the data associated with the VME is present and updated at the current time.
Reimplemented from albaVMEGenericAbstract.
AddChild()
virtual int albaVMELandmarkCloud::AddChild (albaVME * node) virtual
Remove a child node.
Reimplemented from albaVME.
RemoveChild()
virtual void albaVMELandmarkCloud::RemoveChild (albaVME * node) virtual
Remove a child node.
Reimplemented from albaVME.
ShowLandmark()
void albaVMELandmarkCloud::ShowLandmark (albaVMELandmark * lm, bool show)
ShowAllLandmarks()
void albaVMELandmarkCloud::ShowAllLandmarks (bool show = true)
IsLandmarkShow()
bool albaVMELandmarkCloud::IsLandmarkShow (albaVMELandmark * lm)
GetLandmarkShowNumber()
int albaVMELandmarkCloud::GetLandmarkShowNumber ()
CreateLMStructureFromDataVector()
void albaVMELandmarkCloud::CreateLMStructureFromDataVector ()
GetNearestLandmark()
albaVMELandmark * albaVMELandmarkCloud::GetNearestLandmark (double pos[3], bool SerchOnlyVisible)
InternalStore()
virtual int albaVMELandmarkCloud::InternalStore (albaStorageElement * node) protected virtual
This is called by Store() and must be reimplemented by subclasses.
The node element where the object should store itself is passed as argument.
Reimplemented from albaVMEGenericAbstract.
InternalRestore()
virtual int albaVMELandmarkCloud::InternalRestore (albaStorageElement * node) protected virtual
This is called by Restore() and must be reimplemented by subclasses The element from which the object should restore itself is passed as argument.
Reimplemented from albaVMEGenericAbstract.
InternalInitialize()
virtual int albaVMELandmarkCloud::InternalInitialize () protected virtual
used to initialize and create the material attribute if not yet present
Reimplemented from albaVMEPointSet.
NewPolyData()
virtual vtkPolyData * albaVMELandmarkCloud::NewPolyData (albaTimeStamp t) protected virtual
Internal function to instantiate a VMEItem with for timestamp t containing a new polydata.
Reimplemented from albaVMEPointSet.
AppendPoint()
virtual int albaVMELandmarkCloud::AppendPoint (vtkPolyData * polydata, double x, double y, double z, int num = 1) protected virtual
Internal functions redefined to support cells.
Reimplemented from albaVMEPointSet.
SetLandmarkVisibility() [3/3]
virtual int albaVMELandmarkCloud::SetLandmarkVisibility (vtkPolyData * polydata, int idx, bool a) protected virtual
Internal functions used to set/get visibility for point idx of the given polydata.
GetLandmarkVisibility() [3/3]
virtual bool albaVMELandmarkCloud::GetLandmarkVisibility (vtkPolyData * polydata, int idx) protected virtual
SetLandmarkToPolydata()
int albaVMELandmarkCloud::SetLandmarkToPolydata (int idx, double x, double y, double z, bool visibility, albaTimeStamp & t) protected
CreateGui()
virtual albaGUI * albaVMELandmarkCloud::CreateGui () protected virtual
Internally used to create a new instance of the GUI.
Reimplemented from albaVMEGenericAbstract.
Member Data Documentation
m_SingleFile
int albaVMELandmarkCloud::m_SingleFile protected
Definition at line 242 of file albaVMELandmarkCloud.h.
m_NumberOfLandmarks
int albaVMELandmarkCloud::m_NumberOfLandmarks protected
Definition at line 243 of file albaVMELandmarkCloud.h.
m_DefaultVisibility
int albaVMELandmarkCloud::m_DefaultVisibility protected
Definition at line 244 of file albaVMELandmarkCloud.h.
m_SphereResolution
int albaVMELandmarkCloud::m_SphereResolution protected
Definition at line 245 of file albaVMELandmarkCloud.h.
m_Radius
double albaVMELandmarkCloud::m_Radius protected
Definition at line 246 of file albaVMELandmarkCloud.h.
m_LanfmarkShowNumber
int albaVMELandmarkCloud::m_LanfmarkShowNumber protected
Definition at line 248 of file albaVMELandmarkCloud.h.
m_LMChildren
std::vector<albaVMELandmark *> albaVMELandmarkCloud::m_LMChildren protected
Definition at line 249 of file albaVMELandmarkCloud.h.
m_LMChildrenShow
std::vector<bool> albaVMELandmarkCloud::m_LMChildrenShow protected
Definition at line 250 of file albaVMELandmarkCloud.h.
m_LMIndexesMap
std::map<albaVMELandmark *, int> albaVMELandmarkCloud::m_LMIndexesMap protected
Definition at line 251 of file albaVMELandmarkCloud.h.
The documentation for this class was generated from the following file:
albaVMELandmarkCloud.h