ALBA: codeproject::sorted_vector< K, bNoDuplicates, Pr, A > Class Template Reference
codeproject::sorted_vector< K, bNoDuplicates, Pr, A > Class Template Reference
#include <sorted_vector.h>
Public Types
typedef sorted_vector< K, bNoDuplicates, Pr, A > Myt_
typedef std::vector< K, A > Cont
typedef Cont::allocator_type allocator_type
typedef Cont::size_type size_type
typedef Cont::difference_type difference_type
typedef Cont::reference reference
typedef Cont::const_reference const_reference
typedef Cont::value_type value_type
typedef K key_type
typedef Cont::iterator iterator
typedef Cont::const_iterator const_iterator
typedef Pr key_compare
typedef Pr value_compare
typedef Cont::const_reverse_iterator const_reverse_iterator
typedef Cont::reverse_iterator reverse_iterator
typedef std::pair< iterator, iterator > Pairii_
typedef std::pair< const_iterator, const_iterator > Paircc_
typedef std::pair< iterator, bool > Pairib_
Public Member Functions
sorted_vector (const Pr &pred=Pr(), const A &al=A())
sorted_vector (const_iterator first, const_iterator beyond, const Pr &pred=Pr(), const A &al=A())
sorted_vector (const Myt_ &x)
~sorted_vector ()
Myt_ & operator= (const Myt_ &x)
Myt_ & operator= (const Cont &x)
void reserve (size_type n)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size () const
size_type max_size () const
bool empty () const
A get_allocator () const
const_reference at (size_type p) const
reference at (size_type p)
const_reference operator[] (size_type p) const
reference operator[] (size_type p)
reference front ()
const_reference front () const
reference back ()
const_reference back () const
void pop_back ()
void assign (const_iterator first, const_iterator beyond)
void assign (size_type n, const K &x=K())
Pairib_ insert (const value_type &x)
iterator insert (iterator it, const value_type &x)
void insert (const_iterator first, const_iterator beyond)
iterator erase (iterator p)
iterator erase (iterator first, iterator beyond)
size_type erase (const K &key)
void clear ()
bool Eq_ (const Myt_ &x) const
bool Lt_ (const Myt_ &x) const
void swap (Myt_ &x)
key_compare key_comp () const
value_compare value_comp () const
iterator find (const K &k)
const_iterator find (const K &k) const
size_type count (const K &k) const
iterator lower_bound (const K &k)
const_iterator lower_bound (const K &k) const
iterator upper_bound (const K &k)
const_iterator upper_bound (const K &k) const
Pairii_ equal_range (const K &k)
Paircc_ equal_range (const K &k) const
Cont & get_container ()
void sort ()
void stable_sort ()
Protected Member Functions
iterator Unique_ ()
iterator InsertImpl_ (iterator p, const value_type &x)
bool KeyCompare_Leq_ (const K &ty0, const K &ty1)
bool KeyCompare_Geq_ (const K &ty0, const K &ty1)
bool KeyCompare_Gt_ (const K &ty0, const K &ty1)
Protected Attributes
key_compare key_compare_
Cont vec_
Friends
void swap (Myt_ &x, Myt_ &Y_)
Detailed Description
template<class K, bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>>
class codeproject::sorted_vector< K, bNoDuplicates, Pr, A >
Definition at line 41 of file sorted_vector.h.
Member Typedef Documentation
Myt_
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> typedef sorted_vector<K,bNoDuplicates,Pr,A> codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::Myt_
Definition at line 43 of file sorted_vector.h.
Cont
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> typedef std::vector<K,A> codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::Cont
Definition at line 44 of file sorted_vector.h.
allocator_type
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> typedef Cont::allocator_type codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::allocator_type
Definition at line 45 of file sorted_vector.h.
size_type
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> typedef Cont::size_type codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::size_type
Definition at line 46 of file sorted_vector.h.
difference_type
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> typedef Cont::difference_type codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::difference_type
Definition at line 47 of file sorted_vector.h.
reference
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> typedef Cont::reference codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::reference
Definition at line 48 of file sorted_vector.h.
const_reference
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> typedef Cont::const_reference codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::const_reference
Definition at line 49 of file sorted_vector.h.
value_type
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> typedef Cont::value_type codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::value_type
Definition at line 50 of file sorted_vector.h.
key_type
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> typedef K codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_type
Definition at line 51 of file sorted_vector.h.
iterator
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> typedef Cont::iterator codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::iterator
Definition at line 52 of file sorted_vector.h.
const_iterator
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> typedef Cont::const_iterator codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::const_iterator
Definition at line 53 of file sorted_vector.h.
key_compare
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> typedef Pr codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_compare
Definition at line 54 of file sorted_vector.h.
value_compare
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> typedef Pr codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::value_compare
Definition at line 55 of file sorted_vector.h.
const_reverse_iterator
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> typedef Cont::const_reverse_iterator codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::const_reverse_iterator
Definition at line 58 of file sorted_vector.h.
reverse_iterator
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> typedef Cont::reverse_iterator codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::reverse_iterator
Definition at line 59 of file sorted_vector.h.
Pairii_
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> typedef std::pair<iterator, iterator> codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::Pairii_
Definition at line 61 of file sorted_vector.h.
Paircc_
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> typedef std::pair<const_iterator, const_iterator> codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::Paircc_
Definition at line 62 of file sorted_vector.h.
Pairib_
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> typedef std::pair<iterator, bool> codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::Pairib_
Definition at line 63 of file sorted_vector.h.
Constructor & Destructor Documentation
sorted_vector() [1/3]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::sorted_vector (const Pr & pred = Pr(), const A & al = A()) inline explicit
Definition at line 64 of file sorted_vector.h.
sorted_vector() [2/3]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::sorted_vector (const_iterator first, const_iterator beyond, const Pr & pred = Pr(), const A & al = A()) inline
Definition at line 73 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::stable_sort().
sorted_vector() [3/3]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::sorted_vector (const Myt_ & x) inline
Definition at line 78 of file sorted_vector.h.
~sorted_vector()
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::~sorted_vector () inline
Definition at line 81 of file sorted_vector.h.
Member Function Documentation
operator=() [1/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> Myt_ & codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::operator= (const Myt_ & x) inline
Definition at line 82 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_compare_, and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
operator=() [2/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> Myt_ & codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::operator= (const Cont & x) inline
Definition at line 85 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::sort(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
reserve()
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> void codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::reserve (size_type n) inline
Definition at line 88 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
Referenced by codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::insert().
begin() [1/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> iterator codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::begin () inline
Definition at line 89 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
Referenced by codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::Eq_(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::equal_range(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::lower_bound(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::Lt_(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::upper_bound().
begin() [2/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> const_iterator codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::begin () const inline
Definition at line 90 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
end() [1/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> iterator codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::end () inline
Definition at line 91 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
Referenced by codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::Eq_(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::equal_range(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::find(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::insert(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::lower_bound(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::Lt_(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::stable_sort(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::upper_bound().
end() [2/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> const_iterator codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::end () const inline
Definition at line 92 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
rbegin() [1/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> reverse_iterator codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::rbegin () inline
Definition at line 93 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
rbegin() [2/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> const_reverse_iterator codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::rbegin () const inline
Definition at line 94 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
rend() [1/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> reverse_iterator codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::rend () inline
Definition at line 97 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
rend() [2/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> const_reverse_iterator codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::rend () const inline
Definition at line 98 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
size()
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> size_type codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::size () const inline
Definition at line 102 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
Referenced by codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::Eq_(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::insert().
max_size()
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> size_type codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::max_size () const inline
Definition at line 103 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
empty()
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> bool codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::empty () const inline
Definition at line 104 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
get_allocator()
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> A codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::get_allocator () const inline
Definition at line 105 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
at() [1/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> const_reference codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::at (size_type p) const inline
Definition at line 106 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
at() [2/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> reference codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::at (size_type p) inline
Definition at line 107 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
operator[]() [1/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> const_reference codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::operator[] (size_type p) const inline
Definition at line 108 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
operator[]() [2/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> reference codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::operator[] (size_type p) inline
Definition at line 111 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
front() [1/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> reference codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::front () inline
Definition at line 112 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
front() [2/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> const_reference codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::front () const inline
Definition at line 113 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
back() [1/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> reference codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::back () inline
Definition at line 114 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
back() [2/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> const_reference codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::back () const inline
Definition at line 115 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
pop_back()
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> void codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::pop_back () inline
Definition at line 116 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
assign() [1/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> void codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::assign (const_iterator first, const_iterator beyond) inline
Definition at line 118 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
assign() [2/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> void codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::assign (size_type n, const K & x = K()) inline
Definition at line 120 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
insert() [1/3]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> Pairib_ codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::insert (const value_type & x) inline
Definition at line 123 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::end(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::InsertImpl_(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_compare_, codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::lower_bound(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::upper_bound().
Referenced by codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::insert().
insert() [2/3]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> iterator codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::insert (iterator it, const value_type & x) inline
Definition at line 137 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::end(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::insert(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::InsertImpl_(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_compare_, codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::KeyCompare_Geq_(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::KeyCompare_Gt_(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::KeyCompare_Leq_().
insert() [3/3]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> void codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::insert (const_iterator first, const_iterator beyond) inline
Definition at line 168 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::insert(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::reserve(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::size().
erase() [1/3]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> iterator codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::erase (iterator p) inline
Definition at line 177 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
Referenced by codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::erase(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::stable_sort().
erase() [2/3]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> iterator codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::erase (iterator first, iterator beyond) inline
Definition at line 178 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
erase() [3/3]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> size_type codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::erase (const K & key) inline
Definition at line 180 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::equal_range(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::erase().
clear()
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> void codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::clear () inline
Definition at line 187 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
Eq_()
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> bool codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::Eq_ (const Myt_ & x) const inline
Definition at line 189 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::begin(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::end(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::size().
Referenced by codeproject::operator==().
Lt_()
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> bool codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::Lt_ (const Myt_ & x) const inline
Definition at line 192 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::begin(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::end().
Referenced by codeproject::operator<().
swap()
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> void codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::swap (Myt_ & x) inline
Definition at line 195 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_compare_, and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
key_comp()
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> key_compare codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_comp () const inline
Definition at line 201 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_compare_.
Referenced by codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::value_comp().
value_comp()
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> value_compare codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::value_comp () const inline
Definition at line 202 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_comp().
find() [1/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> iterator codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::find (const K & k) inline
Definition at line 203 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::end(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_compare_, and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::lower_bound().
find() [2/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> const_iterator codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::find (const K & k) const inline
Definition at line 207 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::end(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_compare_, and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::lower_bound().
count()
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> size_type codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::count (const K & k) const inline
Definition at line 210 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::equal_range().
lower_bound() [1/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> iterator codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::lower_bound (const K & k) inline
Definition at line 214 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::begin(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::end(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_compare_.
Referenced by codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::find(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::insert().
lower_bound() [2/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> const_iterator codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::lower_bound (const K & k) const inline
Definition at line 216 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::begin(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::end(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_compare_.
upper_bound() [1/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> iterator codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::upper_bound (const K & k) inline
Definition at line 218 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::begin(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::end(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_compare_.
Referenced by codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::insert().
upper_bound() [2/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> const_iterator codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::upper_bound (const K & k) const inline
Definition at line 220 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::begin(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::end(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_compare_.
equal_range() [1/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> Pairii_ codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::equal_range (const K & k) inline
Definition at line 222 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::begin(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::end(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_compare_.
Referenced by codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::count(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::erase().
equal_range() [2/2]
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> Paircc_ codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::equal_range (const K & k) const inline
Definition at line 224 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::begin(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::end(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_compare_.
get_container()
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> Cont & codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::get_container () inline
Definition at line 228 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
sort()
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> void codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::sort () inline
Definition at line 230 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_compare_, codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::Unique_(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
Referenced by codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::operator=().
stable_sort()
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> void codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::stable_sort () inline
Definition at line 236 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::end(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::erase(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_compare_, codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::Unique_(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
Referenced by codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::sorted_vector().
Unique_()
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> iterator codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::Unique_ () inline protected
Definition at line 243 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_compare_, and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
Referenced by codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::sort(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::stable_sort().
InsertImpl_()
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> iterator codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::InsertImpl_ (iterator p, const value_type & x) inline protected
Definition at line 258 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_.
Referenced by codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::insert().
KeyCompare_Leq_()
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> bool codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::KeyCompare_Leq_ (const K & ty0, const K & ty1) inline protected
Definition at line 260 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_compare_.
Referenced by codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::insert().
KeyCompare_Geq_()
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> bool codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::KeyCompare_Geq_ (const K & ty0, const K & ty1) inline protected
Definition at line 262 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_compare_.
Referenced by codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::insert().
KeyCompare_Gt_()
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> bool codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::KeyCompare_Gt_ (const K & ty0, const K & ty1) inline protected
Definition at line 264 of file sorted_vector.h.
References codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_compare_.
Referenced by codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::insert().
Friends And Related Function Documentation
swap
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> void swap (Myt_ & x, Myt_ & Y_) friend
Definition at line 198 of file sorted_vector.h.
Member Data Documentation
key_compare_
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> key_compare codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_compare_ protected
Definition at line 267 of file sorted_vector.h.
Referenced by codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::equal_range(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::find(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::insert(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::key_comp(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::KeyCompare_Geq_(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::KeyCompare_Gt_(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::KeyCompare_Leq_(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::lower_bound(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::operator=(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::sort(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::stable_sort(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::swap(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::Unique_(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::upper_bound().
vec_
template<class K , bool bNoDuplicates = false, class Pr = std::less<K>, class A = std::allocator<K>> Cont codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::vec_ protected
Definition at line 268 of file sorted_vector.h.
Referenced by codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::assign(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::at(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::back(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::begin(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::clear(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::empty(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::end(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::erase(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::front(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::get_allocator(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::get_container(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::InsertImpl_(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::max_size(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::operator=(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::operator[](), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::pop_back(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::rbegin(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::rend(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::reserve(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::size(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::sort(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::stable_sort(), codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::swap(), and codeproject::sorted_vector< K, bNoDuplicates, Pr, A >::Unique_().
The documentation for this class was generated from the following file:
sorted_vector.h