ALBA: albaAvatar3D Class Reference
albaAvatar3D Class Reference
#include <albaAvatar3D.h>
Public Types
enum AVATAR_3D_GUI_ID {
ID_FITTING_COMBO = albaAvatar::ID_LAST , ID_WBOX_BOOL , ID_DEBUG_TEXT , ID_DEBUG_TEXT_POSITION ,
ID_COORDS_COMBO , ID_LAST
}
enum AVATAR_COORDS_TYPE { TRACKER_COORDS =0 , CANONICAL_COORDS , WORLD_COORDS }
enum AVATAR_COORDS_SCALING { NO_SCALE =0 , TRACKER_TO_WORLD_SCALE , CANONICAL_TO_WORLD_SCALE }
Public Types inherited from albaAvatar
enum AVATAR_GUI_ID { ID_NAME =MINID , ID_LAST }
enum AvatarModality { MODE_2D =0 , MODE_3D }
Public Types inherited from albaInteractor
enum modalities { SINGLE_BUTTON_MODE =0 , MULTI_BUTTON_MODE }
Public Member Functions
albaAbstractTypeMacro (albaAvatar3D, albaAvatar)
virtual void SetRendererAndView (vtkRenderer *ren, albaView *view)
virtual void Hide ()
virtual void Show ()
vtkALBARayCast3DPicker * GetPicker3D ()
vtkCellPicker * GetPicker2D ()
virtual vtkAbstractPropPicker * GetPicker ()
void SetDisplayWorkingBox (int vis)
int GetDisplayWorkingBox ()
void DisplayWorkingBoxOn ()
void DisplayWorkingBoxOff ()
void SetDisplayDebugText (int vis)
int GetDisplayDebugText ()
void SetDebugTextPosition (double *pos)
void SetDebugTextPosition (double posx, double posy)
double * GetDebugTextPosition ()
void SetCoordsFrame (int frame)
int GetCoordsFrame ()
virtual void OnEvent (albaEventBase *event)
virtual void SetTracker (albaDeviceButtonsPadTracker *tracker)
void CanonicalToWorld (const albaMatrix &pose, albaMatrix &dest)
void CanonicalToWorld (albaMatrix &pose)
void CanonicalToWorld (albaTransform *trans)
void WorldToCanonical (const albaMatrix &pose, albaMatrix &dest)
void WorldToCanonical (albaMatrix &pose)
void WorldToCanonical (albaTransform *trans)
void TrackerToWorld (albaMatrix &tracker_pose, albaMatrix &world_pose, int use_scale=1, int use_rot=1, int use_trans=1)
void WorldToTracker (albaMatrix &world_pose, albaMatrix &tracker_pose, int use_scale=1, int use_rot=1, int use_trans=1)
void TrackerToDisplay (albaMatrix &tracker_pose, double xy[2])
void WorldToDisplay (albaMatrix &world_pose, double xy[2])
void WorldToNormalizedDisplay (albaMatrix &world_pose, double xy[2])
albaCameraTransform * GetCanonicalToWorldTransform ()
void SetFittingMode (int type)
int GetFittingMode ()
albaMatrix & GetLastPoseMatrix ()
virtual void CreateGui ()
Public Member Functions inherited from albaAvatar
albaAbstractTypeMacro (albaAvatar, albaInteractor)
virtual void SetRendererAndView (vtkRenderer *ren, albaView *view)
void SetActor3D (vtkProp3D *avatar)
vtkProp3D * GetActor3D ()
void SetActor2D (vtkActor2D *avatar)
vtkActor2D * GetActor2D ()
virtual void Hide ()
virtual void Show ()
virtual void HideCursor3D ()
virtual void ShowCursor3D ()
virtual void HideCursor2D ()
virtual void ShowCursor2D ()
virtual int Pick (albaMatrix &pose)
virtual int Pick (double X, double Y)
virtual void OnEvent (albaEventBase *event)
albaDeviceButtonsPadTracker * GetTracker ()
virtual void SetTracker (albaDeviceButtonsPadTracker *tracker)
void SetMode (int mode)
int GetMode ()
void SetModeTo2D ()
void SetModeTo3D ()
virtual vtkAbstractPropPicker * GetPicker ()
albaGUI * GetGui ()
virtual void CreateGui ()
virtual void UpdateGui ()
ALBA_ID_DEC (AVATAR_SCREEN_PLANE_SETTINGS)
ALBA_ID_DEC (AVATAR_WORKING_BOX_SETTINGS)
Public Member Functions inherited from albaInteractor
albaInteractor ()
virtual ~albaInteractor ()
ALBA_ID_DEC (INTERACTION_STARTED)
ALBA_ID_DEC (INTERACTION_STOPPED)
ALBA_ID_DEC (BUTTON_DOWN)
ALBA_ID_DEC (BUTTON_UP)
albaAbstractTypeMacro (albaInteractor, albaAgent)
virtual void SetRendererAndView (vtkRenderer *ren, albaView *view)
vtkRenderer * GetRenderer ()
albaView * GetView ()
albaDevice * GetDevice ()
virtual void SetDevice (albaDevice *)
virtual void SetVME (albaVME *vme)
void SetProp (vtkProp3D *prop)
void SetIgnoreTriggerEvents (bool flag)
int GetIgnoreTriggerEvents (bool flag)
void IgnoreTriggerEventsOn ()
void IgnoreTriggerEventsOff ()
void SetStartInteractionEvent (albaID event)
albaID GetStartInteractionEvent ()
void SetStopInteractionEvent (albaID event)
albaID GetStopInteractionEvent ()
void SetStartButton (int btn)
int GetStartButton ()
void SetModifiers (int mod)
int GetModifiers ()
int GetCurrentButton ()
unsigned long GetCurrentModifier ()
virtual int StartInteraction (albaDevice *device)
virtual int StopInteraction (albaDevice *device)
virtual bool IsInteracting ()
virtual bool IsInteracting (albaDevice *device)
void SetButtonMode (int mode)
int GetButtonMode ()
void SetButtonModeToSingleButton ()
void SetButtonModeToMultiButton ()
virtual void OnEvent (albaEventBase *event)
void TestModeOn ()
void TestModeOff ()
bool GetTestMode ()
Public Member Functions inherited from albaAgent
albaAbstractTypeMacro (albaAgent, albaReferenceCounted)
ALBA_ID_DEC (AGENT_INITIALIZE)
void AddObserver (albaObserver *listener, albaID channel=MCH_UP)
void RemoveObserver (albaObserver *listener)
void RemoveAllObservers ()
virtual void OnEvent (albaEventBase *event)
bool HasObservers (albaID channel)
void GetObservers (albaID channel, std::vector< albaObserver * > &olist)
int Initialize ()
void Shutdown ()
int IsInitialized ()
virtual void SetName (const char *name)
const char * GetName ()
Public Member Functions inherited from albaReferenceCounted
albaReferenceCounted ()
virtual ~albaReferenceCounted ()
albaAbstractTypeMacro (albaReferenceCounted, albaObject)
virtual void Delete ()
void Register (void *obj)
virtual void UnRegister (void *obj)
int GetReferenceCount ()
void SetReferenceCount (int)
Public Member Functions inherited from albaObject
albaObject ()
virtual ~albaObject ()
virtual void Delete ()
virtual const char * GetTypeName () const
virtual bool IsA (const char *type_name) const
virtual bool IsA (const albaTypeID &type_id) const
virtual albaObject * NewObjectInstance () const =0
virtual const albaTypeID & GetTypeId () const
virtual void Print (std::ostream &os, const int indent=0) const
albaObject (const albaObject &c)
Public Member Functions inherited from albaObserver
albaObserver ()
virtual ~albaObserver ()
virtual void OnEvent (albaEventBase *e)=0
Public Member Functions inherited from albaEventBroadcaster
albaEventBroadcaster (void *owner=NULL)
virtual ~albaEventBroadcaster ()
albaEventBroadcaster (const albaEventBroadcaster &c)
void AddObserver (albaObserver *obj)
void AddObserver (albaObserver &obj)
albaObserverCallback * AddObserverCallback (void(*f)(void *sender, albaID eid, void *clientdata, void *calldata))
bool RemoveObserver (albaObserver *obj)
void RemoveAllObservers ()
bool IsObserver (albaObserver *obj)
bool HasObservers ()
void GetObservers (std::vector< albaObserver * > &olist)
void InvokeEvent (albaEventBase &e)
void InvokeEvent (albaEventBase *e)
void InvokeEvent (void *sender, albaID id=ID_NO_EVENT, void *data=NULL)
void SetChannel (albaID ch)
albaID GetChannel ()
virtual void SetListener (albaObserver *o)
Public Member Functions inherited from albaEventSender
albaEventSender ()
virtual void SetListener (albaObserver *o)
virtual albaObserver * GetListener ()
virtual bool HasListener ()
virtual void InvokeEvent (albaEventBase &e)
virtual void InvokeEvent (albaEventBase *e)
virtual void InvokeEvent (void *sender, albaID id=ID_NO_EVENT, void *data=NULL)
Public Member Functions inherited from albaStorable
albaStorable ()
int Store (albaStorageElement *element)
int Restore (albaStorageElement *element)
albaObject * CastToObject ()
bool IsStorable ()
Protected Member Functions
albaAvatar3D ()
virtual ~albaAvatar3D ()
void SetLastPoseMatrix (albaMatrix &matrix)
virtual int InternalStore (albaStorageElement *node)
virtual int InternalRestore (albaStorageElement *node)
virtual int InternalInitialize ()
virtual void InternalShutdown ()
virtual void UpdateDebugText (const char *title, albaMatrix &pose)
virtual void OnMove3DEvent (albaEventInteraction *e)
void OnUpdateBoundsEvent (albaDeviceButtonsPadTracker *tracker)
virtual void OnPostResetCamera (albaEventBase *event)
void SetPicker3D (vtkALBARayCast3DPicker *picker)
Protected Member Functions inherited from albaAvatar
albaAvatar ()
virtual ~albaAvatar ()
virtual int InternalStore (albaStorageElement *node)
virtual int InternalRestore (albaStorageElement *node)
virtual int InternalInitialize ()
virtual void InternalShutdown ()
virtual void OnPreResetCamera (albaEventBase *event)
virtual void OnPostResetCamera (albaEventBase *event)
virtual void OnViewSelected (albaEvent *e)
Protected Member Functions inherited from albaInteractor
virtual int OnStartInteraction (albaEventInteraction *e)
virtual int OnStopInteraction (albaEventInteraction *e)
virtual void OnButtonDown (albaEventInteraction *e)
virtual void OnButtonUp (albaEventInteraction *e)
void ComputeDisplayToWorld (double x, double y, double z, double worldPt[4])
void ComputeWorldToDisplay (double x, double y, double z, double displayPt[3])
Protected Member Functions inherited from albaAgent
albaAgent ()
virtual ~albaAgent ()
virtual int InternalInitialize ()
virtual void InternalShutdown ()
void InvokeEvent (albaEventBase &event, albaID channel=-1)
void InvokeEvent (albaEventBase *event, albaID channel=-1)
void InvokeEvent (void *sender, int id, albaID channel=MCH_UP, void *data=NULL)
virtual int InternalStore (albaStorageElement *node)=0
virtual int InternalRestore (albaStorageElement *node)=0
Protected Attributes
vtkProp3D * m_WorkingBoxActor
vtkOutlineSource * m_WorkingBox
vtkTextMapper * m_DebugTextMapper
vtkActor2D * m_DebugTextActor
albaMatrix m_LastPoseMatrix
vtkALBARayCast3DPicker * m_Picker3D
vtkCellPicker * m_Picker2D
albaCameraTransform * m_CanonicalToWorldTransform
int m_FittingMode
int m_DisplayWorkingBox
int m_DisplayDebugText
int m_CoordsFrame
double * m_DebugTextPosition
Protected Attributes inherited from albaAvatar
vtkALBASmartPointer< vtkProp3D > m_Actor3D
vtkALBASmartPointer< vtkActor2D > m_Actor2D
albaGUI * m_Gui
int m_Mode
int m_Cursor3DHideCounter
int m_Cursor2DHideCounter
Protected Attributes inherited from albaInteractor
albaDevice * m_Device
bool m_DeviceIsSet
albaID m_StartInteractionEvent
albaID m_StopInteractionEvent
int m_IgnoreTriggerEvents
int m_InteractionFlag
int m_StartButton
unsigned long m_Modifiers
int m_CurrentButton
unsigned long m_CurrentModifier
int m_ButtonMode
int m_ButtonsCounter
albaVME * m_VME
albaView * m_View
vtkALBASmartPointer< vtkRenderer > m_Renderer
vtkALBASmartPointer< vtkProp3D > m_Prop
bool m_TestMode
Protected Attributes inherited from albaAgent
albaString m_Name
bool m_Initialized
std::vector< albaEventBroadcaster * > m_Channels
Protected Attributes inherited from albaReferenceCounted
int m_ReferenceCount
Protected Attributes inherited from albaObject
bool m_HeapFlag
Protected Attributes inherited from albaEventBroadcaster
albaObserversList m_Observers
albaID m_Channel
Protected Attributes inherited from albaEventSender
albaObserver * m_Listener
Protected Attributes inherited from albaStorable
bool m_Storable
Additional Inherited Members
Static Public Member Functions inherited from albaObject
static const char * GetStaticTypeName ()
static bool IsStaticType (const char *type_name)
static bool IsStaticType (const albaTypeID &type_id)
static const albaTypeID & GetStaticTypeId ()
static albaObject * SafeDownCast (albaObject *o)
Static Public Member Functions inherited from albaStorable
static albaStorable * SafeCastToObject (albaObject *o)
Protected Types inherited from albaEventBroadcaster
typedef std::list< albaObserver * > albaObserversList
Detailed Description
Avatars are entities moving in the virtual world according to user's movements, and thus representing thier presence in the virtual world.
Specialized classes must set the Avatar variable with a vtkProp3D, this class will take care of adding it to the current renderer, moving, hiding and showing it at the right time. The Avatar moves according to an interactor, which must also be set by subclasses.
Todo:
implement rendering by means of a CameraUpdate event sent to the interaction manager
make the avatar have its own GUI plugged into the device gui settings
refactoring to have the avatar picking nodes (VME)
Definition at line 56 of file albaAvatar3D.h.
Member Enumeration Documentation
AVATAR_3D_GUI_ID
enum albaAvatar3D::AVATAR_3D_GUI_ID
Enumerator
ID_FITTING_COMBO
ID_WBOX_BOOL
ID_DEBUG_TEXT
ID_DEBUG_TEXT_POSITION
ID_COORDS_COMBO
ID_LAST
Definition at line 62 of file albaAvatar3D.h.
AVATAR_COORDS_TYPE
enum albaAvatar3D::AVATAR_COORDS_TYPE
Enumerator
TRACKER_COORDS
CANONICAL_COORDS
WORLD_COORDS
Definition at line 72 of file albaAvatar3D.h.
AVATAR_COORDS_SCALING
enum albaAvatar3D::AVATAR_COORDS_SCALING
Enumerator
NO_SCALE
TRACKER_TO_WORLD_SCALE
CANONICAL_TO_WORLD_SCALE
Definition at line 79 of file albaAvatar3D.h.
Constructor & Destructor Documentation
albaAvatar3D()
albaAvatar3D::albaAvatar3D () protected
~albaAvatar3D()
virtual albaAvatar3D::~albaAvatar3D () protected virtual
Member Function Documentation
albaAbstractTypeMacro()
albaAvatar3D::albaAbstractTypeMacro (albaAvatar3D , albaAvatar)
SetRendererAndView()
virtual void albaAvatar3D::SetRendererAndView (vtkRenderer * ren, albaView * view) virtual
Set/Get the renderer this avatar is attached to.
When the rederer is changed, all props created by this avatar are moved to the new renderer and the interaction is changed accordingly
Reimplemented from albaAvatar.
Hide()
virtual void albaAvatar3D::Hide () virtual
Hide the 3D cursor, i.e.
remove actor from renderer's list. This is usually used to compute bounding box without considering avatars
Reimplemented from albaAvatar.
Show()
virtual void albaAvatar3D::Show () virtual
Show the 3D cursor.
This function is conditional, in the sense the old visibility state is retained when showing back.
Reimplemented from albaAvatar.
GetPicker3D()
vtkALBARayCast3DPicker * albaAvatar3D::GetPicker3D ()
Return picker 3D used by 3DAvatar for picking.
GetPicker2D()
vtkCellPicker * albaAvatar3D::GetPicker2D ()
Return picker 2D used by 3DAvatar for 2D picking.
GetPicker()
virtual vtkAbstractPropPicker * albaAvatar3D::GetPicker () virtual
return the picker used by this avatar: from the picker is possible to obtain information about the picked object.
Reimplemented from albaAvatar.
SetDisplayWorkingBox()
void albaAvatar3D::SetDisplayWorkingBox (int vis)
Display a box showing where input coords are mapped.
This can be used for debug to understand if the tracker's settings and the mapping function are correct
GetDisplayWorkingBox()
int albaAvatar3D::GetDisplayWorkingBox () inline
Definition at line 118 of file albaAvatar3D.h.
DisplayWorkingBoxOn()
void albaAvatar3D::DisplayWorkingBoxOn () inline
Definition at line 119 of file albaAvatar3D.h.
DisplayWorkingBoxOff()
void albaAvatar3D::DisplayWorkingBoxOff () inline
Definition at line 120 of file albaAvatar3D.h.
SetDisplayDebugText()
void albaAvatar3D::SetDisplayDebugText (int vis)
Display the debug text showing trackers coordinate.
This can be used to debug the code.
GetDisplayDebugText()
int albaAvatar3D::GetDisplayDebugText () inline
Definition at line 126 of file albaAvatar3D.h.
SetDebugTextPosition() [1/2]
void albaAvatar3D::SetDebugTextPosition (double * pos) inline
where to display the text
Definition at line 129 of file albaAvatar3D.h.
References SetDebugTextPosition().
Referenced by SetDebugTextPosition().
SetDebugTextPosition() [2/2]
void albaAvatar3D::SetDebugTextPosition (double posx, double posy)
GetDebugTextPosition()
double * albaAvatar3D::GetDebugTextPosition () inline
Definition at line 131 of file albaAvatar3D.h.
SetCoordsFrame()
void albaAvatar3D::SetCoordsFrame (int frame) inline
Display the original tracker's coords in the debug text area.
This can be used to know the tracked volume size to be set in the trackers' settings.
Definition at line 137 of file albaAvatar3D.h.
GetCoordsFrame()
int albaAvatar3D::GetCoordsFrame () inline
Definition at line 138 of file albaAvatar3D.h.
OnEvent()
virtual void albaAvatar3D::OnEvent (albaEventBase * event) virtual
Process events coming from tracker.
Reimplemented from albaAvatar.
SetTracker()
virtual void albaAvatar3D::SetTracker (albaDeviceButtonsPadTracker * tracker) virtual
return the tracker this avatar is the tracker attached to this avatar
Reimplemented from albaAvatar.
CanonicalToWorld() [1/3]
void albaAvatar3D::CanonicalToWorld (const albaMatrix & pose, albaMatrix & dest)
Transform a matrix from Canonical to World space.
CanonicalToWorld() [2/3]
void albaAvatar3D::CanonicalToWorld (albaMatrix & pose) inline
Definition at line 149 of file albaAvatar3D.h.
References CanonicalToWorld().
Referenced by CanonicalToWorld().
CanonicalToWorld() [3/3]
void albaAvatar3D::CanonicalToWorld (albaTransform * trans)
WorldToCanonical() [1/3]
void albaAvatar3D::WorldToCanonical (const albaMatrix & pose, albaMatrix & dest)
WorldToCanonical() [2/3]
void albaAvatar3D::WorldToCanonical (albaMatrix & pose) inline
Definition at line 153 of file albaAvatar3D.h.
References WorldToCanonical().
Referenced by WorldToCanonical().
WorldToCanonical() [3/3]
void albaAvatar3D::WorldToCanonical (albaTransform * trans)
TrackerToWorld()
void albaAvatar3D::TrackerToWorld (albaMatrix & tracker_pose, albaMatrix & world_pose, int use_scale = 1, int use_rot = 1, int use_trans = 1)
Transform a matrix from Tracker frame to World frame, the function can optionally avoid to map on the destination matrix some of the 6DOF: e.g.
not using the scale or the rotational matrix
WorldToTracker()
void albaAvatar3D::WorldToTracker (albaMatrix & world_pose, albaMatrix & tracker_pose, int use_scale = 1, int use_rot = 1, int use_trans = 1)
TrackerToDisplay()
void albaAvatar3D::TrackerToDisplay (albaMatrix & tracker_pose, double xy[2])
map tracker coords to display normalized coords
WorldToDisplay()
void albaAvatar3D::WorldToDisplay (albaMatrix & world_pose, double xy[2])
map world coords to tracker coords
WorldToNormalizedDisplay()
void albaAvatar3D::WorldToNormalizedDisplay (albaMatrix & world_pose, double xy[2])
map world coords to normalized display coords
GetCanonicalToWorldTransform()
albaCameraTransform * albaAvatar3D::GetCanonicalToWorldTransform () inline
return transform between canonical and world space
Definition at line 176 of file albaAvatar3D.h.
SetFittingMode()
void albaAvatar3D::SetFittingMode (int type)
Set mapping rule, i.e.
the policy to be used for scaling the tracked volume to the world volume.
GetFittingMode()
int albaAvatar3D::GetFittingMode () inline
return the mapping rule currently in use
Definition at line 184 of file albaAvatar3D.h.
GetLastPoseMatrix()
albaMatrix & albaAvatar3D::GetLastPoseMatrix () inline
return the last pose matrix of the avatar's 3d actor in world coordinates.
Definition at line 189 of file albaAvatar3D.h.
CreateGui()
virtual void albaAvatar3D::CreateGui () virtual
Create the dialog that show the interface for settings.
Reimplemented from albaAvatar.
SetLastPoseMatrix()
void albaAvatar3D::SetLastPoseMatrix (albaMatrix & matrix) protected
Internally used to set the last pose matrix.
Todo:
: Why should we use this instead of using the tracker's one? I'd like to remove this Marco. 28-10-2004:
InternalStore()
virtual int albaAvatar3D::InternalStore (albaStorageElement * node) protected virtual
This is used to allow nested serialization of subclasses.
This function is called by Store and is reimplemented in subclasses. Each subclass can Open/Close its own subelements which are closed inside the "Device" XML element.
Reimplemented from albaAvatar.
InternalRestore()
virtual int albaAvatar3D::InternalRestore (albaStorageElement * node) protected virtual
This is called by Restore() and must be reimplemented by subclasses The element from which the object should restore itself is passed as argument.
Reimplemented from albaAvatar.
InternalInitialize()
virtual int albaAvatar3D::InternalInitialize () protected virtual
redefined to add the Cursor actor into the selected renderer
Reimplemented from albaAvatar.
InternalShutdown()
virtual void albaAvatar3D::InternalShutdown () protected virtual
redefined to remove Cursor from renderer
Reimplemented from albaAvatar.
UpdateDebugText()
virtual void albaAvatar3D::UpdateDebugText (const char * title, albaMatrix & pose) protected virtual
internally used to update debug text on the screen
OnMove3DEvent()
virtual void albaAvatar3D::OnMove3DEvent (albaEventInteraction * e) protected virtual
process a move event
OnUpdateBoundsEvent()
void albaAvatar3D::OnUpdateBoundsEvent (albaDeviceButtonsPadTracker * tracker) protected
process an event signaling a change of the tracked bounds
OnPostResetCamera()
virtual void albaAvatar3D::OnPostResetCamera (albaEventBase * event) protected virtual
process event sent after a camera reset
Reimplemented from albaAvatar.
SetPicker3D()
void albaAvatar3D::SetPicker3D (vtkALBARayCast3DPicker * picker) protected
Internally used to redefine the 3D picker class.
Member Data Documentation
m_WorkingBoxActor
vtkProp3D* albaAvatar3D::m_WorkingBoxActor protected
Prop3D of the working box.
Definition at line 227 of file albaAvatar3D.h.
m_WorkingBox
vtkOutlineSource* albaAvatar3D::m_WorkingBox protected
Working box the tracker coords are mapped to.
Definition at line 228 of file albaAvatar3D.h.
m_DebugTextMapper
vtkTextMapper* albaAvatar3D::m_DebugTextMapper protected
Definition at line 230 of file albaAvatar3D.h.
m_DebugTextActor
vtkActor2D* albaAvatar3D::m_DebugTextActor protected
Definition at line 231 of file albaAvatar3D.h.
m_LastPoseMatrix
albaMatrix albaAvatar3D::m_LastPoseMatrix protected
Definition at line 233 of file albaAvatar3D.h.
m_Picker3D
vtkALBARayCast3DPicker* albaAvatar3D::m_Picker3D protected
Used to pick in a VTK Render window.
Definition at line 235 of file albaAvatar3D.h.
m_Picker2D
vtkCellPicker* albaAvatar3D::m_Picker2D protected
Definition at line 236 of file albaAvatar3D.h.
m_CanonicalToWorldTransform
albaCameraTransform* albaAvatar3D::m_CanonicalToWorldTransform protected
Definition at line 239 of file albaAvatar3D.h.
m_FittingMode
int albaAvatar3D::m_FittingMode protected
specify the current mapping rule from canonical to world
Definition at line 241 of file albaAvatar3D.h.
m_DisplayWorkingBox
int albaAvatar3D::m_DisplayWorkingBox protected
Whether display the working box.
Definition at line 243 of file albaAvatar3D.h.
m_DisplayDebugText
int albaAvatar3D::m_DisplayDebugText protected
Whether display Debug text.
Definition at line 244 of file albaAvatar3D.h.
m_CoordsFrame
int albaAvatar3D::m_CoordsFrame protected
Whether to display the original tracker's coords.
Definition at line 245 of file albaAvatar3D.h.
m_DebugTextPosition
double* albaAvatar3D::m_DebugTextPosition protected
Definition at line 247 of file albaAvatar3D.h.
The documentation for this class was generated from the following file:
albaAvatar3D.h