ALBA: albaTimeStamped Class Reference
albaTimeStamped Class Reference
#include <albaTimeStamped.h>
Public Member Functions
virtual void Modified ()
virtual unsigned long GetMTime ()
Protected Attributes
albaMTime m_MTime
Detailed Description
class acting as an interface for timestamped objects This object simply defines few methods for managing a modification time to be used in for process objects.
See also
albaMTime
Definition at line 31 of file albaTimeStamped.h.
Member Function Documentation
Modified()
virtual void albaTimeStamped::Modified () virtual
Update this objects modification time.
The modification time is just a monotonically increasing unsigned long integer. It is possible for this number to wrap around back to zero. This should only happen for processes that have been running for a very long time, while constantly changing objects within the program. When this does occur, the typical consequence should be that some process objects will update themselves when really they don't need to.
Referenced by albaVMERoot::GetNextItemId(), albaMatrix3x3::Identity(), albaMatrix3x3::Invert(), albaMatrix3x3::Orthogonalize(), albaDataPipe::SetDependOnAbsPose(), albaDataPipe::SetDependOnPose(), albaDataPipe::SetDependOnVMETime(), albaVMERoot::SetMaxItemId(), albaMatrix3x3::Transpose(), and albaMatrix3x3::Zero().
GetMTime()
virtual unsigned long albaTimeStamped::GetMTime () virtual
return modification time
Reimplemented in albaDataPipe, and albaVME.
Member Data Documentation
m_MTime
albaMTime albaTimeStamped::m_MTime protected
Last modification time.
Definition at line 49 of file albaTimeStamped.h.
The documentation for this class was generated from the following file:
albaTimeStamped.h