ALBA: albaGUI Class Reference
albaGUI Class Reference
#include <albaGUI.h>
Public Member Functions
albaGUI (albaObserver *listener)
virtual ~albaGUI ()
void SetListener (albaObserver *listener)
void Divider (long style=0)
void Label (albaString label, bool bold=false, bool multiline=false)
void Label (albaString *var, bool bold=false, bool multiline=false)
void Label (albaString label1, albaString label2, bool bold_label=false, bool bold_var=false, double customSizer=1.0)
void Label (albaString label1, albaString *var, bool bold_label=false, bool bold_var=false, bool multiline=false, double customSizer=1.0)
void HintBox (int id, wxString label, wxString title="Hint", int mode=0, bool showIcon=true)
void String (int id, wxString label, wxString *var, wxString tooltip="", bool multiline=false, bool password=false, bool interactive=false, double customSizer=1.0)
void String (int id, albaString label, albaString *var, albaString tooltip="", bool multiline=false, bool password=false, bool interactive=false, double customSizer=1.0)
void Integer (int id, albaString label, int *var, int min=MININT, int max=MAXINT, albaString tooltip="", bool labelAlwaysEnable=false, double customSizer=1.0)
void Float (int id, albaString label, float *var, float min=MINFLOAT, float max=MAXFLOAT, int flag=0, int decimal_digit=-1, albaString tooltip="", double customSizer=1.0)
void Double (int id, albaString label, double *var, double min=MINDOUBLE, double max=MAXDOUBLE, int decimal_digit=-1, albaString tooltip="", bool labelAlwaysEnable=false, double customSizer=1.0, wxColour fontColor=wxColour(0, 0, 0))
void Vector (int id, wxString label, int var[3], int min=MININT, int max=MAXINT, wxString tooltip="", wxColour *bg_colour=NULL)
void Vector (int id, wxString label, int var[3], int minx, int maxx, int miny, int maxy, int minz, int maxz, wxString tooltip="", wxColour *bg_colour=NULL)
void Vector (int id, wxString label, float var[3], float min=MINFLOAT, float max=MAXFLOAT, int decimal_digit=-1, wxString tooltip="", wxColour *bg_colour=NULL)
void Vector (int id, wxString label, float var[3], float minx, float maxx, float miny, float maxy, float minz, float maxz, int decimal_digit=-1, wxString tooltip="", wxColour *bg_colour=NULL)
void Vector (int id, wxString label, double var[3], double min=MINFLOAT, double max=MAXFLOAT, int decimal_digit=-1, wxString tooltip="", wxColour *bg_colour=NULL)
void Vector (int id, wxString label, double var[3], double minx, double maxx, double miny, double maxy, double minz, double maxz, int decimal_digit=-1, wxString tooltip="", wxColour *bg_colour=NULL)
void VectorN (int id, wxString label, double *var, int num_elem=3, double min=MINFLOAT, double max=MAXFLOAT, int decimal_digit=-1, wxString tooltip="")
void VectorN (int id, wxString label, int *var, int num_elem=3, int min=MININT, int max=MAXINT, wxString tooltip="")
void Bool (int id, albaString label, int *var, int flag=0, albaString tooltip="")
void BoolGrid (int numRows, int numColumns, std::vector< int > &ids, std::vector< const char * > &labelsRows, std::vector< const char * > &labelsColumns, int *var, albaString tooltip="")
void Radio (int id, wxString label, int *var, int numchoices=0, const wxString choices[]=NULL, int dim=1, wxString tooltip="", int style=wxRA_SPECIFY_COLS)
void RadioButton (int id, wxString label, int selected=true, wxString tooltip="")
wxComboBox * Combo (int id, albaString label, int *var, int numchoices=0, const wxString choices[]=NULL, albaString tooltip="", double customSizer=1.0)
void FileOpen (int id, albaString label, albaString *var, const albaString wildcard="", albaString tooltip="")
void FileSave (int id, albaString label, albaString *var, const albaString wildcard="", albaString tooltip="", bool enableTextCtrl=true)
void DirOpen (int id, albaString label, albaString *var, albaString tooltip="")
void Color (int id, wxString label, wxColour *var, wxString tooltip="")
void Button (int id, albaString button_text, albaString label="", albaString tooltip="")
void Button (int id, albaString *label, albaString button_text, albaString tooltip="")
albaGUICrossIncremental * CrossIncremental (int id, const char *label, double *stepVariable, double *topBottomVariable, double *leftRightVariable, int modality, wxString tooltip="", bool boldLabel=true, bool comboStep=false, int digits=-1, albaString *buttonUpDown_text=NULL, albaString *buttonLeftRight_text=NULL)
void TwoButtons (int firstID, int secondID, const char *label1, const char *label2, int alignment=wxALL, int width=-1)
void DoubleUpDown (int labelID, int firstID, int secondID, albaString label, double *var, double min=MINDOUBLE, double max=MAXDOUBLE, int decimal_digit=-1, albaString tooltip="", bool labelAlwaysEnable=false)
void ImageButton (int id, const char *label, wxBitmap bitmap, albaString tooltip)
void ButtonAndHelp (int firstID, int secondID, const char *label1, albaString tooltip="", int alignment=wxALL, int width=-1)
void MultipleButtons (int numButtons, int numColumns, std::vector< int > &ids, std::vector< const char * > &labels, int alignment=wxALL)
void MultipleImageButtons (int numButtons, int numColumns, std::vector< int > &ids, std::vector< const char * > &labels, std::vector< const char * > &images, int alignment)
void OkCancel ()
wxSlider * Slider (int id, wxString label, int *var, int min=MININT, int max=MAXINT, wxString tooltip="", bool showText=true)
albaGUIFloatSlider * FloatSlider (int id, wxString label, double *var, double min, double max, wxSize size=wxDefaultSize, wxString tooltip="", bool textBoxEnable=true)
albaGUIFloatSlider * FloatExpandedSlider (int id, wxString label, double *var, double min, double max, wxSize size=wxDefaultSize, wxString tooltip="", bool textBoxEnable=true)
albaGUIFloatSlider * FloatSlider (int id, double *var, double min, double max, wxString minLab, wxString maxLab, wxSize size=wxDefaultSize, wxString tooltip="", bool textBoxEnable=true)
albaGUICheckListBox * CheckList (int id, wxString label="", int height=60, wxString tooltip="")
wxListBox * ListBox (int id, wxString label="", int height=60, wxString tooltip="", long lbox_style=0, int width=-1)
wxListCtrl * ListCtrl (int id, wxString label="", int height=60, wxString tooltip="", long lbox_style=0, int width=-1)
wxGrid * Grid (int id, wxString label="", int height=60, int row=2, int cols=2, wxString tooltip="")
albaGUIRollOut * RollOut (int id, albaString title, albaGUI *roll_gui, bool rollOutOpen=true)
void Add (wxWindow *window, int option=0, int flag=wxEXPAND, int border=0)
void Add (wxSizer *sizer, int option=0, int flag=wxEXPAND, int border=0)
void AddGui (albaGUI *gui, int option=0, int flag=wxEXPAND, int border=0)
bool Remove (wxWindow *window)
bool Remove (wxSizer *sizer)
void FitGui ()
void Update ()
void Enable (int mod_id, bool enable)
wxFont GetBoldFont ()
wxFont GetGuiFont ()
int GetMetrics (int id)
void OnEvent (albaEventBase *alba_event)
int GetWidgetId (int mod_id)
int * GetALBAWidgetId ()
void GetWidgetValue (long widget_id, WidgetDataType &widget_data)
void SetWidgetValue (int id, WidgetDataType &widget_data)
void Reparent (wxWindow *parent)
Public Member Functions inherited from albaGUIPanel
albaGUIPanel (wxWindow *parent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL, const wxString &name="panel")
Public Member Functions inherited from albaObserver
albaObserver ()
virtual ~albaObserver ()
virtual void OnEvent (albaEventBase *e)=0
Static Public Member Functions
static void AddMenuItem (wxMenu *menu, int id, wxString label, char **icon=NULL)
Protected Member Functions
int GetModuleId (int w_id)
void OnSlider (wxCommandEvent &event)
void OnListBox (wxCommandEvent &event)
void OnListCtrl (wxCommandEvent &event)
void OnCheckListBox (wxCommandEvent &event)
void OnRadioButton (wxCommandEvent &event)
void OnMouseWheel (wxMouseEvent &event)
Protected Attributes
albaObserver * m_Listener
wxBoxSizer * m_Sizer
wxColour m_BackgroundColor
bool m_UseBackgroundColor
long m_EntryStyle
wxFont m_BoldFont
wxFont m_Font
std::map< int, int > m_WidgetTableID
Additional Inherited Members
Public Attributes inherited from albaGUIPanel
albaGUIPanel * m_NextPanel
Detailed Description
albaGUI is a panel with function to easily create GUI.
The user calls function like Vector,String,Color ecc.. . albaGUI take care of:
creating and Layout the widgets,
filter and validate user input, widget are constrained in range and type.
manage widget initialization user variables updates.
notify the user of gui-events by sending albaEvents to a albaObserver.
implementation details:
On creation of widget, the user passes an ID that will be used by the widget when sending notification back. One command may cause the creation of more than one widget, ex: the Vector create 3 wxTextCtrl, and I can't use the same ID for every widget. So user-ID are translated into widgets-ID using two member functions : GetModuleID and GetWidgetId. GetWidgetId increments an internal ID_counter.
See also
GetWidgetId GetModuleId ALBAWidgetId m_WidgetTableID
Definition at line 109 of file albaGUI.h.
Constructor & Destructor Documentation
albaGUI()
albaGUI::albaGUI (albaObserver * listener)
~albaGUI()
virtual albaGUI::~albaGUI () virtual
Member Function Documentation
SetListener()
void albaGUI::SetListener (albaObserver * listener) inline
Set the Listener that will receive event-notification, the Listener can be changed any time
Definition at line 116 of file albaGUI.h.
Divider()
void albaGUI::Divider (long style = 0)
Separator widget.
Label() [1/4]
void albaGUI::Label (albaString label, bool bold = false, bool multiline = false)
Label widget.
Label() [2/4]
void albaGUI::Label (albaString * var, bool bold = false, bool multiline = false)
Label widget.
Label() [3/4]
void albaGUI::Label (albaString label1, albaString label2, bool bold_label = false, bool bold_var = false, double customSizer = 1.0)
Double label widget.
Label() [4/4]
void albaGUI::Label (albaString label1, albaString * var, bool bold_label = false, bool bold_var = false, bool multiline = false, double customSizer = 1.0)
Double label widget.
HintBox()
void albaGUI::HintBox (int id, wxString label, wxString title = "Hint", int mode = 0, bool showIcon = true)
Hint Box widget.
String() [1/2]
void albaGUI::String (int id, wxString label, wxString * var, wxString tooltip = "", bool multiline = false, bool password = false, bool interactive = false, double customSizer = 1.0)
String entry widget.
String() [2/2]
void albaGUI::String (int id, albaString label, albaString * var, albaString tooltip = "", bool multiline = false, bool password = false, bool interactive = false, double customSizer = 1.0)
String entry widget.
Integer()
void albaGUI::Integer (int id, albaString label, int * var, int min = MININT, int max = MAXINT, albaString tooltip = "", bool labelAlwaysEnable = false, double customSizer = 1.0)
Integer entry widget.
Float()
void albaGUI::Float (int id, albaString label, float * var, float min = MINFLOAT, float max = MAXFLOAT, int flag = 0, int decimal_digit = -1, albaString tooltip = "", double customSizer = 1.0)
Float entry widget.
Double()
void albaGUI::Double (int id, albaString label, double * var, double min = MINDOUBLE, double max = MAXDOUBLE, int decimal_digit = -1, albaString tooltip = "", bool labelAlwaysEnable = false, double customSizer = 1.0, wxColour fontColor = wxColour(0, 0, 0))
Double entry widget.
Vector() [1/6]
void albaGUI::Vector (int id, wxString label, int var[3], int min = MININT, int max = MAXINT, wxString tooltip = "", wxColour * bg_colour = NULL)
Integer vector3 entry widget.
Vector() [2/6]
void albaGUI::Vector (int id, wxString label, int var[3], int minx, int maxx, int miny, int maxy, int minz, int maxz, wxString tooltip = "", wxColour * bg_colour = NULL)
Integer vector3 entry widget.
Vector() [3/6]
void albaGUI::Vector (int id, wxString label, float var[3], float min = MINFLOAT, float max = MAXFLOAT, int decimal_digit = -1, wxString tooltip = "", wxColour * bg_colour = NULL)
Float vector3 entry widget.
Vector() [4/6]
void albaGUI::Vector (int id, wxString label, float var[3], float minx, float maxx, float miny, float maxy, float minz, float maxz, int decimal_digit = -1, wxString tooltip = "", wxColour * bg_colour = NULL)
Float vector3 entry widget.
Vector() [5/6]
void albaGUI::Vector (int id, wxString label, double var[3], double min = MINFLOAT, double max = MAXFLOAT, int decimal_digit = -1, wxString tooltip = "", wxColour * bg_colour = NULL)
Double vector3 entry widget.
Vector() [6/6]
void albaGUI::Vector (int id, wxString label, double var[3], double minx, double maxx, double miny, double maxy, double minz, double maxz, int decimal_digit = -1, wxString tooltip = "", wxColour * bg_colour = NULL)
Double vector3 entry widget.
VectorN() [1/2]
void albaGUI::VectorN (int id, wxString label, double * var, int num_elem = 3, double min = MINFLOAT, double max = MAXFLOAT, int decimal_digit = -1, wxString tooltip = "")
Double vectorN entry widget.
VectorN() [2/2]
void albaGUI::VectorN (int id, wxString label, int * var, int num_elem = 3, int min = MININT, int max = MAXINT, wxString tooltip = "")
Int vectorN entry widget.
Bool()
void albaGUI::Bool (int id, albaString label, int * var, int flag = 0, albaString tooltip = "")
Checkbutton widget.
BoolGrid()
void albaGUI::BoolGrid (int numRows, int numColumns, std::vector< int > & ids, std::vector< const char * > & labelsRows, std::vector< const char * > & labelsColumns, int * var, albaString tooltip = "")
Checkbutton grid widget.
Radio()
void albaGUI::Radio (int id, wxString label, int * var, int numchoices = 0, const wxString choices[] = NULL, int dim = 1, wxString tooltip = "", int style = wxRA_SPECIFY_COLS)
RadioBox widget.
RadioButton()
void albaGUI::RadioButton (int id, wxString label, int selected = true, wxString tooltip = "")
Radiobutton widget.
Combo()
wxComboBox * albaGUI::Combo (int id, albaString label, int * var, int numchoices = 0, const wxString choices[] = NULL, albaString tooltip = "", double customSizer = 1.0)
Combo widget.
FileOpen()
void albaGUI::FileOpen (int id, albaString label, albaString * var, const albaString wildcard = "", albaString tooltip = "")
File open dialog widget.
FileSave()
void albaGUI::FileSave (int id, albaString label, albaString * var, const albaString wildcard = "", albaString tooltip = "", bool enableTextCtrl = true)
File save dialog widget.
DirOpen()
void albaGUI::DirOpen (int id, albaString label, albaString * var, albaString tooltip = "")
Dir Open dialog widget.
Color()
void albaGUI::Color (int id, wxString label, wxColour * var, wxString tooltip = "")
Color dialog widget.
Button() [1/2]
void albaGUI::Button (int id, albaString button_text, albaString label = "", albaString tooltip = "")
Button widget.
Button() [2/2]
void albaGUI::Button (int id, albaString * label, albaString button_text, albaString tooltip = "")
Button widget with variable label.
CrossIncremental()
albaGUICrossIncremental * albaGUI::CrossIncremental (int id, const char * label, double * stepVariable, double * topBottomVariable, double * leftRightVariable, int modality, wxString tooltip = "", bool boldLabel = true, bool comboStep = false, int digits = -1, albaString * buttonUpDown_text = NULL, albaString * buttonLeftRight_text = NULL)
Widget with 4 buttons and a text array disposed like a cross.
TwoButtons()
void albaGUI::TwoButtons (int firstID, int secondID, const char * label1, const char * label2, int alignment = wxALL, int width = -1)
two generic Buttons widget.
DoubleUpDown()
void albaGUI::DoubleUpDown (int labelID, int firstID, int secondID, albaString label, double * var, double min = MINDOUBLE, double max = MAXDOUBLE, int decimal_digit = -1, albaString tooltip = "", bool labelAlwaysEnable = false)
Double entry widget and two generic Buttons widget.
ImageButton()
void albaGUI::ImageButton (int id, const char * label, wxBitmap bitmap, albaString tooltip)
ButtonAndHelp()
void albaGUI::ButtonAndHelp (int firstID, int secondID, const char * label1, albaString tooltip = "", int alignment = wxALL, int width = -1)
two generic Buttons widget.
MultipleButtons()
void albaGUI::MultipleButtons (int numButtons, int numColumns, std::vector< int > & ids, std::vector< const char * > & labels, int alignment = wxALL)
Multiple Generic Buttons widget.
MultipleImageButtons()
void albaGUI::MultipleImageButtons (int numButtons, int numColumns, std::vector< int > & ids, std::vector< const char * > & labels, std::vector< const char * > & images, int alignment)
Multiple Image Buttons widget.
OkCancel()
void albaGUI::OkCancel ()
Ok-Cancel Button widget.
Slider()
wxSlider * albaGUI::Slider (int id, wxString label, int * var, int min = MININT, int max = MAXINT, wxString tooltip = "", bool showText = true)
Integer slider widget.
FloatSlider() [1/2]
albaGUIFloatSlider * albaGUI::FloatSlider (int id, wxString label, double * var, double min, double max, wxSize size = wxDefaultSize, wxString tooltip = "", bool textBoxEnable = true)
Float slider widget.
FloatExpandedSlider()
albaGUIFloatSlider * albaGUI::FloatExpandedSlider (int id, wxString label, double * var, double min, double max, wxSize size = wxDefaultSize, wxString tooltip = "", bool textBoxEnable = true)
Float Expanded slider widget.
FloatSlider() [2/2]
albaGUIFloatSlider * albaGUI::FloatSlider (int id, double * var, double min, double max, wxString minLab, wxString maxLab, wxSize size = wxDefaultSize, wxString tooltip = "", bool textBoxEnable = true)
Float slider widget.
CheckList()
albaGUICheckListBox * albaGUI::CheckList (int id, wxString label = "", int height = 60, wxString tooltip = "")
Checked listbox widget.
ListBox()
wxListBox * albaGUI::ListBox (int id, wxString label = "", int height = 60, wxString tooltip = "", long lbox_style = 0, int width = -1)
Listbox widget.
ListCtrl()
wxListCtrl * albaGUI::ListCtrl (int id, wxString label = "", int height = 60, wxString tooltip = "", long lbox_style = 0, int width = -1)
ListCtrl widget.
Grid()
wxGrid * albaGUI::Grid (int id, wxString label = "", int height = 60, int row = 2, int cols = 2, wxString tooltip = "")
Grid widget.
RollOut()
albaGUIRollOut * albaGUI::RollOut (int id, albaString title, albaGUI * roll_gui, bool rollOutOpen = true)
Create a roll out gui.
Add() [1/2]
void albaGUI::Add (wxWindow * window, int option = 0, int flag = wxEXPAND, int border = 0) inline
Add window to gui sizer.
Definition at line 265 of file albaGUI.h.
Add() [2/2]
void albaGUI::Add (wxSizer * sizer, int option = 0, int flag = wxEXPAND, int border = 0) inline
Add sizer to gui sizer.
Definition at line 268 of file albaGUI.h.
AddGui()
void albaGUI::AddGui (albaGUI * gui, int option = 0, int flag = wxEXPAND, int border = 0)
Add gui to gui sizer.
Remove() [1/2]
bool albaGUI::Remove (wxWindow * window) inline
Remove window from gui sizer.
Definition at line 274 of file albaGUI.h.
References albaGetFrame().
Remove() [2/2]
bool albaGUI::Remove (wxSizer * sizer) inline
Remove sizer from gui sizer.
Definition at line 277 of file albaGUI.h.
FitGui()
void albaGUI::FitGui ()
Recalculate 'this' Gui Size and MinSize considering the space required by the children widgets.
FitGui is called implicitly when a gui is inserted in a albaGUIHolder or albaGUIPanel. FitGui must call explicitly when children widget are changed dynamically.
Referenced by albaGUIDialog::Add().
Update()
void albaGUI::Update ()
Update gui widget.
Enable()
void albaGUI::Enable (int mod_id, bool enable)
Enable/Disable gui widget.
GetBoldFont()
wxFont albaGUI::GetBoldFont () inline
Return the font used for bold label.
Definition at line 291 of file albaGUI.h.
GetGuiFont()
wxFont albaGUI::GetGuiFont () inline
Definition at line 293 of file albaGUI.h.
GetMetrics()
int albaGUI::GetMetrics (int id)
Return the measure used to layout the widgets - pass one of the GUI_xxx constants.
OnEvent()
void albaGUI::OnEvent (albaEventBase * e) virtual
process the events sent by subjects
Implements albaObserver.
GetWidgetId()
int albaGUI::GetWidgetId (int mod_id)
implementation details:
GetWidgetId is used to obtain a new/unique widget_ID. As a side effect a new pair widget_ID->module_ID is stored in m_WidgetTableID
See also
GetWidgetId GetModuleId ALBAWidgetId m_WidgetTableID
GetALBAWidgetId()
int * albaGUI::GetALBAWidgetId ()
GetWidgetValue()
void albaGUI::GetWidgetValue (long widget_id, WidgetDataType & widget_data)
SetWidgetValue()
void albaGUI::SetWidgetValue (int id, WidgetDataType & widget_data)
Reparent()
void albaGUI::Reparent (wxWindow * parent)
place the GUI on a different parent, and perform the required Resize/Stretch/ and Show
Referenced by albaGUIDialog::Add().
AddMenuItem()
static void albaGUI::AddMenuItem (wxMenu * menu, int id, wxString label, char ** icon = NULL) static
GetModuleId()
int albaGUI::GetModuleId (int w_id) inline protected
implementation details:
translate a widget_ID in it's module_ID, accessing m_WidgetTableID
See also
GetWidgetId GetModuleId ALBAWidgetId m_WidgetTableID
Definition at line 344 of file albaGUI.h.
References MINID.
OnSlider()
void albaGUI::OnSlider (wxCommandEvent & event) inline protected
Definition at line 346 of file albaGUI.h.
OnListBox()
void albaGUI::OnListBox (wxCommandEvent & event) protected
OnListCtrl()
void albaGUI::OnListCtrl (wxCommandEvent & event) protected
OnCheckListBox()
void albaGUI::OnCheckListBox (wxCommandEvent & event) protected
OnRadioButton()
void albaGUI::OnRadioButton (wxCommandEvent & event) protected
OnMouseWheel()
void albaGUI::OnMouseWheel (wxMouseEvent & event) protected
Member Data Documentation
m_Listener
albaObserver* albaGUI::m_Listener protected
Definition at line 319 of file albaGUI.h.
m_Sizer
wxBoxSizer* albaGUI::m_Sizer protected
Definition at line 320 of file albaGUI.h.
m_BackgroundColor
wxColour albaGUI::m_BackgroundColor protected
Definition at line 322 of file albaGUI.h.
m_UseBackgroundColor
bool albaGUI::m_UseBackgroundColor protected
Definition at line 323 of file albaGUI.h.
m_EntryStyle
long albaGUI::m_EntryStyle protected
Definition at line 324 of file albaGUI.h.
m_BoldFont
wxFont albaGUI::m_BoldFont protected
implementation details:
m_BoldFont is the font used for the Bold labels
Definition at line 328 of file albaGUI.h.
m_Font
wxFont albaGUI::m_Font protected
Definition at line 329 of file albaGUI.h.
m_WidgetTableID
std::map<int,int> albaGUI::m_WidgetTableID protected
implementation details:
m_WidgetTableID is an std::map holding a table of conversion widget_id -> user_id. The range of widget_IDs is between MINID and MAXID (created widget_IDs are <= then ALBAWidgetId)
To obtain the Module ID, widget_ID are shifted by MINID and used to index the array
See also
GetWidgetId GetModuleId ALBAWidgetId m_WidgetTableID
Definition at line 337 of file albaGUI.h.
The documentation for this class was generated from the following file:
albaGUI.h