ALBA 2: albaPlugVME< T > Class Template Reference
albaPlugVME< T > Class Template Reference
#include <albaVMEFactory.h>
Public Member Functions
albaPlugVME (const char *typeName)
Detailed Description
template<class T>
class albaPlugVME< T >
Plug a node in the main ALBA Node factory.
Definition at line 87 of file albaVMEFactory.h.
Constructor & Destructor Documentation
albaPlugVME()
template<class T > albaPlugVME< T >::albaPlugVME (const char * typeName)
Plug a new Node class into the Node factory.
Definition at line 97 of file albaVMEFactory.h.
References albaPictureFactory::AddVmePic(), albaVMEFactory::GetInstance(), albaPictureFactory::GetPicsInitialized(), albaPictureFactory::GetPictureFactory(), and albaVMEFactory::RegisterNewVME().
The documentation for this class was generated from the following file:
albaVMEFactory.h