ALBA 2: Allocator< T > Class Template Reference
Allocator< T > Class Template Reference
#include <vtkALBAPoissonSurfaceReconstruction.h>
Public Member Functions
Allocator (void)
~Allocator (void)
void Reset (void)
AllocatorState getState (void) const
void RollBack (void)
void Set (const int &blockSize)
T * NewElements (const int &elements=1)
Detailed Description
template<class T>
class Allocator< T >
class name: Allocator memory handler
Definition at line 145 of file vtkALBAPoissonSurfaceReconstruction.h.
Constructor & Destructor Documentation
Allocator()
template<class T > Allocator< T >::Allocator (void) inline
constructor
Definition at line 151 of file vtkALBAPoissonSurfaceReconstruction.h.
~Allocator()
template<class T > Allocator< T >::~Allocator (void) inline
destructor
Definition at line 155 of file vtkALBAPoissonSurfaceReconstruction.h.
References Allocator< T >::Reset().
Member Function Documentation
Reset()
template<class T > void Allocator< T >::Reset (void) inline
This method is the allocators destructor.
It frees up any of the memory that it has allocated.
Definition at line 161 of file vtkALBAPoissonSurfaceReconstruction.h.
Referenced by Allocator< T >::Set(), and Allocator< T >::~Allocator().
getState()
template<class T > AllocatorState Allocator< T >::getState (void) const inline
This method returns the memory state of the allocator.
Definition at line 167 of file vtkALBAPoissonSurfaceReconstruction.h.
References AllocatorState::index, and AllocatorState::remains.
RollBack()
template<class T > void Allocator< T >::RollBack (void) inline
This method rolls back the allocator so that it makes all of the memory previously allocated available for re-allocation.
Note that it does it not call the constructor again, so after this method has been called, assumptions about the state of the values in memory are no longer valid.
Definition at line 179 of file vtkALBAPoissonSurfaceReconstruction.h.
Set()
template<class T > void Allocator< T >::Set (const int & blockSize) inline
This method rolls back the allocator to the previous memory state and makes all of the memory previously allocated available for re-allocation.
Note that it does it not call the constructor again, so after this method has been called, assumptions about the state of the values in memory are no longer valid. IT DOESN'T WORK! bugged unused code :(IT DOESN'T WORK! bugged unused code :(This method initializes the constructor and the blockSize variable specifies the the number of objects that should be pre-allocated at a time.
Definition at line 228 of file vtkALBAPoissonSurfaceReconstruction.h.
References Allocator< T >::Reset().
Referenced by SparseMatrix< T >::SetAllocator().
NewElements()
template<class T > T * Allocator< T >::NewElements (const int & elements = 1) inline
This method returns a pointer to an array of elements objects.
If there is left over pre-allocated memory, this method simply returns a pointer to the next free piece of memory, otherwise it pre-allocates more memory. Note that if the number of objects requested is larger than the value blockSize with which the allocator was initialized, the request for memory will fail.
Definition at line 240 of file vtkALBAPoissonSurfaceReconstruction.h.
Referenced by SparseMatrix< T >::SetRowSize().
The documentation for this class was generated from the following file:
vtkALBAPoissonSurfaceReconstruction.h