ALBA 2: vtkALBAXYPlotActor Class Reference
vtkALBAXYPlotActor Class Reference
#include <vtkALBAXYPlotActor.h>
Public Member Functions
vtkTypeRevisionMacro (vtkALBAXYPlotActor, vtkActor2D)
void PrintSelf (ostream &os, vtkIndent indent)
void AddInput (vtkDataSet *in, const char *arrayName, int component)
void AddInput (vtkDataSet *in)
void RemoveInput (vtkDataSet *in, const char *arrayName, int component)
void RemoveInput (vtkDataSet *in)
void RemoveAllInputs ()
vtkDataSetCollection * GetInputList ()
void SetPointComponent (int i, int comp)
int GetPointComponent (int i)
vtkSetClampMacro (XValues, int, VTK_XYPLOT_INDEX, VTK_XYPLOT_VALUE)
vtkGetMacro (XValues, int)
void SetXValuesToIndex ()
void SetXValuesToArcLength ()
void SetXValuesToNormalizedArcLength ()
void SetXValuesToValue ()
const char * GetXValuesAsString ()
void AddDataObjectInput (vtkDataObject *in)
void RemoveDataObjectInput (vtkDataObject *in)
vtkDataObjectCollection * GetDataObjectInputList ()
vtkSetClampMacro (DataObjectPlotMode, int, VTK_XYPLOT_COLUMN, VTK_XYPLOT_ROW)
vtkGetMacro (DataObjectPlotMode, int)
void SetDataObjectPlotModeToRows ()
void SetDataObjectPlotModeToColumns ()
const char * GetDataObjectPlotModeAsString ()
void SetDataObjectXComponent (int i, int comp)
int GetDataObjectXComponent (int i)
void SetDataObjectYComponent (int i, int comp)
int GetDataObjectYComponent (int i)
void SetPlotColor (int i, double r, double g, double b)
void SetPlotColor (int i, const double color[3])
double * GetPlotColor (int i)
void SetPlotSymbol (int i, vtkPolyData *input)
vtkPolyData * GetPlotSymbol (int i)
void SetPlotLabel (int i, const char *label)
const char * GetPlotLabel (int i)
vtkGetMacro (PlotCurvePoints, int)
vtkSetMacro (PlotCurvePoints, int)
vtkBooleanMacro (PlotCurvePoints, int)
vtkGetMacro (PlotCurveLines, int)
vtkSetMacro (PlotCurveLines, int)
vtkBooleanMacro (PlotCurveLines, int)
void SetPlotLines (int i, int)
int GetPlotLines (int i)
void SetPlotPoints (int i, int)
int GetPlotPoints (int i)
vtkSetMacro (ExchangeAxes, int)
vtkGetMacro (ExchangeAxes, int)
vtkBooleanMacro (ExchangeAxes, int)
vtkSetMacro (ReverseXAxis, int)
vtkGetMacro (ReverseXAxis, int)
vtkBooleanMacro (ReverseXAxis, int)
vtkSetMacro (ReverseYAxis, int)
vtkGetMacro (ReverseYAxis, int)
vtkBooleanMacro (ReverseYAxis, int)
vtkLegendBoxActor * GetLegendBoxActor ()
vtkGlyphSource2D * GetGlyphSource ()
vtkSetStringMacro (Title)
vtkGetStringMacro (Title)
vtkSetStringMacro (XTitle)
vtkGetStringMacro (XTitle)
vtkSetStringMacro (YTitle)
vtkGetStringMacro (YTitle)
vtkAxisActor2D * GetXAxisActor2D ()
vtkAxisActor2D * GetYAxisActor2D ()
vtkSetVector2Macro (XRange, double)
vtkGetVectorMacro (XRange, double, 2)
vtkSetVector2Macro (YRange, double)
vtkGetVectorMacro (YRange, double, 2)
void SetPlotRange (double xmin, double ymin, double xmax, double ymax)
vtkSetClampMacro (NumberOfXLabels, int, 0, 50)
vtkGetMacro (NumberOfXLabels, int)
vtkSetClampMacro (NumberOfYLabels, int, 0, 50)
vtkGetMacro (NumberOfYLabels, int)
void SetNumberOfLabels (int num)
vtkSetMacro (Legend, int)
vtkGetMacro (Legend, int)
vtkBooleanMacro (Legend, int)
vtkSetVector2Macro (LegendPosition, double)
vtkGetVector2Macro (LegendPosition, double)
vtkSetVector2Macro (LegendPosition2, double)
vtkGetVector2Macro (LegendPosition2, double)
virtual void SetTitleTextProperty (vtkTextProperty *p)
vtkGetObjectMacro (TitleTextProperty, vtkTextProperty)
virtual void SetAxisTitleTextProperty (vtkTextProperty *p)
vtkGetObjectMacro (AxisTitleTextProperty, vtkTextProperty)
virtual void SetAxisLabelTextProperty (vtkTextProperty *p)
vtkGetObjectMacro (AxisLabelTextProperty, vtkTextProperty)
vtkSetMacro (Logx, int)
vtkGetMacro (Logx, int)
vtkBooleanMacro (Logx, int)
virtual void SetLabelFormat (const char *_arg)
vtkGetStringMacro (LabelFormat)
vtkSetClampMacro (Border, int, 0, 50)
vtkGetMacro (Border, int)
vtkGetMacro (PlotPoints, int)
vtkSetMacro (PlotPoints, int)
vtkBooleanMacro (PlotPoints, int)
vtkGetMacro (PlotLines, int)
vtkSetMacro (PlotLines, int)
vtkBooleanMacro (PlotLines, int)
vtkSetClampMacro (GlyphSize, double, 0.0, 0.2)
vtkGetMacro (GlyphSize, double)
void ViewportToPlotCoordinate (vtkViewport *viewport, double &u, double &v)
void ViewportToPlotCoordinate (vtkViewport *viewport)
vtkSetVector2Macro (PlotCoordinate, double)
vtkGetVector2Macro (PlotCoordinate, double)
void PlotToViewportCoordinate (vtkViewport *viewport, double &u, double &v)
void PlotToViewportCoordinate (vtkViewport *viewport)
vtkSetVector2Macro (ViewportCoordinate, double)
vtkGetVector2Macro (ViewportCoordinate, double)
int IsInPlot (vtkViewport *viewport, double u, double v)
unsigned long GetMTime ()
int RenderOpaqueGeometry (vtkViewport *)
int RenderOverlay (vtkViewport *)
int RenderTranslucentGeometry (vtkViewport *)
void ReleaseGraphicsResources (vtkWindow *)
Static Public Member Functions
static vtkALBAXYPlotActor * New ()
Protected Member Functions
vtkALBAXYPlotActor ()
~vtkALBAXYPlotActor ()
void InitializeEntries ()
void ComputeXRange (double range[2], double *lengths)
void ComputeYRange (double range[2])
void ComputeDORange (double xrange[2], double yrange[2], double *lengths)
virtual void CreatePlotData (int *pos, int *pos2, double xRange[2], double yRange[2], double *norms, int numDS, int numDO)
void PlaceAxes (vtkViewport *viewport, int *size, int pos[2], int pos2[2])
void GenerateClipPlanes (int *pos, int *pos2)
double ComputeGlyphScale (int i, int *pos, int *pos2)
void ClipPlotData (int *pos, int *pos2, vtkPolyData *pd)
double * TransformPoint (int pos[2], int pos2[2], double x[3], double xNew[3])
Protected Attributes
vtkDataSetCollection * InputList
char ** SelectedInputScalars
vtkIntArray * SelectedInputScalarsComponent
vtkDataObjectCollection * DataObjectInputList
char * Title
char * XTitle
char * YTitle
int XValues
int NumberOfXLabels
int NumberOfYLabels
int Logx
char * LabelFormat
double XRange [2]
double YRange [2]
double XComputedRange [2]
double YComputedRange [2]
int Border
int PlotLines
int PlotPoints
int PlotCurveLines
int PlotCurvePoints
int ExchangeAxes
int ReverseXAxis
int ReverseYAxis
vtkTextMapper * TitleMapper
vtkActor2D * TitleActor
vtkTextProperty * TitleTextProperty
vtkAxisActor2D * XAxis
vtkAxisActor2D * YAxis
vtkTextProperty * AxisTitleTextProperty
vtkTextProperty * AxisLabelTextProperty
double ViewportCoordinate [2]
double PlotCoordinate [2]
int DataObjectPlotMode
vtkIntArray * XComponent
vtkIntArray * YComponent
vtkIntArray * LinesOn
vtkIntArray * PointsOn
int NumberOfInputs
vtkPolyData ** PlotData
vtkGlyph2D ** PlotGlyph
vtkAppendPolyData ** PlotAppend
vtkPolyDataMapper2D ** PlotMapper
vtkActor2D ** PlotActor
int Legend
double LegendPosition [2]
double LegendPosition2 [2]
vtkLegendBoxActor * LegendActor
vtkGlyphSource2D * GlyphSource
vtkPlanes * ClipPlanes
double GlyphSize
int CachedSize [2]
vtkTimeStamp BuildTime
Detailed Description
This class is a modification of vtkXYPlotActor whit some bug correction about plot rendering.
The original vtk class have some problems when a line intersect the render area, but both ending points are outside that area. In this case the original class will render bad lines.
Definition at line 55 of file vtkALBAXYPlotActor.h.
Constructor & Destructor Documentation
vtkALBAXYPlotActor()
vtkALBAXYPlotActor::vtkALBAXYPlotActor () protected
~vtkALBAXYPlotActor()
vtkALBAXYPlotActor::~vtkALBAXYPlotActor () protected
Member Function Documentation
vtkTypeRevisionMacro()
vtkALBAXYPlotActor::vtkTypeRevisionMacro (vtkALBAXYPlotActor , vtkActor2D)
PrintSelf()
void vtkALBAXYPlotActor::PrintSelf (ostream & os, vtkIndent indent)
New()
static vtkALBAXYPlotActor * vtkALBAXYPlotActor::New () static
AddInput() [1/2]
void vtkALBAXYPlotActor::AddInput (vtkDataSet * in, const char * arrayName, int component)
AddInput() [2/2]
void vtkALBAXYPlotActor::AddInput (vtkDataSet * in) inline
Definition at line 79 of file vtkALBAXYPlotActor.h.
References AddInput().
Referenced by AddInput().
RemoveInput() [1/2]
void vtkALBAXYPlotActor::RemoveInput (vtkDataSet * in, const char * arrayName, int component)
RemoveInput() [2/2]
void vtkALBAXYPlotActor::RemoveInput (vtkDataSet * in) inline
Definition at line 84 of file vtkALBAXYPlotActor.h.
References RemoveInput().
Referenced by RemoveInput().
RemoveAllInputs()
void vtkALBAXYPlotActor::RemoveAllInputs ()
GetInputList()
vtkDataSetCollection * vtkALBAXYPlotActor::GetInputList () inline
Definition at line 93 of file vtkALBAXYPlotActor.h.
SetPointComponent()
void vtkALBAXYPlotActor::SetPointComponent (int i, int comp)
GetPointComponent()
int vtkALBAXYPlotActor::GetPointComponent (int i)
vtkSetClampMacro() [1/6]
vtkALBAXYPlotActor::vtkSetClampMacro (XValues , int , VTK_XYPLOT_INDEX , VTK_XYPLOT_VALUE)
vtkGetMacro() [1/15]
vtkALBAXYPlotActor::vtkGetMacro (XValues , int)
SetXValuesToIndex()
void vtkALBAXYPlotActor::SetXValuesToIndex () inline
Definition at line 113 of file vtkALBAXYPlotActor.h.
References VTK_XYPLOT_INDEX.
SetXValuesToArcLength()
void vtkALBAXYPlotActor::SetXValuesToArcLength () inline
Definition at line 114 of file vtkALBAXYPlotActor.h.
References VTK_XYPLOT_ARC_LENGTH.
SetXValuesToNormalizedArcLength()
void vtkALBAXYPlotActor::SetXValuesToNormalizedArcLength () inline
Definition at line 115 of file vtkALBAXYPlotActor.h.
References VTK_XYPLOT_NORMALIZED_ARC_LENGTH.
SetXValuesToValue()
void vtkALBAXYPlotActor::SetXValuesToValue () inline
Definition at line 117 of file vtkALBAXYPlotActor.h.
References VTK_XYPLOT_VALUE.
GetXValuesAsString()
const char * vtkALBAXYPlotActor::GetXValuesAsString ()
AddDataObjectInput()
void vtkALBAXYPlotActor::AddDataObjectInput (vtkDataObject * in)
RemoveDataObjectInput()
void vtkALBAXYPlotActor::RemoveDataObjectInput (vtkDataObject * in)
GetDataObjectInputList()
vtkDataObjectCollection * vtkALBAXYPlotActor::GetDataObjectInputList () inline
Definition at line 135 of file vtkALBAXYPlotActor.h.
vtkSetClampMacro() [2/6]
vtkALBAXYPlotActor::vtkSetClampMacro (DataObjectPlotMode , int , VTK_XYPLOT_COLUMN , VTK_XYPLOT_ROW)
vtkGetMacro() [2/15]
vtkALBAXYPlotActor::vtkGetMacro (DataObjectPlotMode , int)
SetDataObjectPlotModeToRows()
void vtkALBAXYPlotActor::SetDataObjectPlotModeToRows () inline
Definition at line 144 of file vtkALBAXYPlotActor.h.
References VTK_XYPLOT_ROW.
SetDataObjectPlotModeToColumns()
void vtkALBAXYPlotActor::SetDataObjectPlotModeToColumns () inline
Definition at line 146 of file vtkALBAXYPlotActor.h.
References VTK_XYPLOT_COLUMN.
GetDataObjectPlotModeAsString()
const char * vtkALBAXYPlotActor::GetDataObjectPlotModeAsString ()
SetDataObjectXComponent()
void vtkALBAXYPlotActor::SetDataObjectXComponent (int i, int comp)
GetDataObjectXComponent()
int vtkALBAXYPlotActor::GetDataObjectXComponent (int i)
SetDataObjectYComponent()
void vtkALBAXYPlotActor::SetDataObjectYComponent (int i, int comp)
GetDataObjectYComponent()
int vtkALBAXYPlotActor::GetDataObjectYComponent (int i)
SetPlotColor() [1/2]
void vtkALBAXYPlotActor::SetPlotColor (int i, double r, double g, double b)
SetPlotColor() [2/2]
void vtkALBAXYPlotActor::SetPlotColor (int i, const double color[3]) inline
Definition at line 177 of file vtkALBAXYPlotActor.h.
GetPlotColor()
double * vtkALBAXYPlotActor::GetPlotColor (int i)
SetPlotSymbol()
void vtkALBAXYPlotActor::SetPlotSymbol (int i, vtkPolyData * input)
GetPlotSymbol()
vtkPolyData * vtkALBAXYPlotActor::GetPlotSymbol (int i)
SetPlotLabel()
void vtkALBAXYPlotActor::SetPlotLabel (int i, const char * label)
GetPlotLabel()
const char * vtkALBAXYPlotActor::GetPlotLabel (int i)
vtkGetMacro() [3/15]
vtkALBAXYPlotActor::vtkGetMacro (PlotCurvePoints , int)
vtkSetMacro() [1/9]
vtkALBAXYPlotActor::vtkSetMacro (PlotCurvePoints , int)
vtkBooleanMacro() [1/9]
vtkALBAXYPlotActor::vtkBooleanMacro (PlotCurvePoints , int)
vtkGetMacro() [4/15]
vtkALBAXYPlotActor::vtkGetMacro (PlotCurveLines , int)
vtkSetMacro() [2/9]
vtkALBAXYPlotActor::vtkSetMacro (PlotCurveLines , int)
vtkBooleanMacro() [2/9]
vtkALBAXYPlotActor::vtkBooleanMacro (PlotCurveLines , int)
SetPlotLines()
void vtkALBAXYPlotActor::SetPlotLines (int i, int)
GetPlotLines()
int vtkALBAXYPlotActor::GetPlotLines (int i)
SetPlotPoints()
void vtkALBAXYPlotActor::SetPlotPoints (int i, int)
GetPlotPoints()
int vtkALBAXYPlotActor::GetPlotPoints (int i)
vtkSetMacro() [3/9]
vtkALBAXYPlotActor::vtkSetMacro (ExchangeAxes , int)
vtkGetMacro() [5/15]
vtkALBAXYPlotActor::vtkGetMacro (ExchangeAxes , int)
vtkBooleanMacro() [3/9]
vtkALBAXYPlotActor::vtkBooleanMacro (ExchangeAxes , int)
vtkSetMacro() [4/9]
vtkALBAXYPlotActor::vtkSetMacro (ReverseXAxis , int)
vtkGetMacro() [6/15]
vtkALBAXYPlotActor::vtkGetMacro (ReverseXAxis , int)
vtkBooleanMacro() [4/9]
vtkALBAXYPlotActor::vtkBooleanMacro (ReverseXAxis , int)
vtkSetMacro() [5/9]
vtkALBAXYPlotActor::vtkSetMacro (ReverseYAxis , int)
vtkGetMacro() [7/15]
vtkALBAXYPlotActor::vtkGetMacro (ReverseYAxis , int)
vtkBooleanMacro() [5/9]
vtkALBAXYPlotActor::vtkBooleanMacro (ReverseYAxis , int)
GetLegendBoxActor()
vtkLegendBoxActor * vtkALBAXYPlotActor::GetLegendBoxActor () inline
Definition at line 231 of file vtkALBAXYPlotActor.h.
GetGlyphSource()
vtkGlyphSource2D * vtkALBAXYPlotActor::GetGlyphSource () inline
Definition at line 233 of file vtkALBAXYPlotActor.h.
vtkSetStringMacro() [1/3]
vtkALBAXYPlotActor::vtkSetStringMacro (Title)
vtkGetStringMacro() [1/4]
vtkALBAXYPlotActor::vtkGetStringMacro (Title)
vtkSetStringMacro() [2/3]
vtkALBAXYPlotActor::vtkSetStringMacro (XTitle)
vtkGetStringMacro() [2/4]
vtkALBAXYPlotActor::vtkGetStringMacro (XTitle)
vtkSetStringMacro() [3/3]
vtkALBAXYPlotActor::vtkSetStringMacro (YTitle)
vtkGetStringMacro() [3/4]
vtkALBAXYPlotActor::vtkGetStringMacro (YTitle)
GetXAxisActor2D()
vtkAxisActor2D * vtkALBAXYPlotActor::GetXAxisActor2D () inline
Definition at line 249 of file vtkALBAXYPlotActor.h.
GetYAxisActor2D()
vtkAxisActor2D * vtkALBAXYPlotActor::GetYAxisActor2D () inline
Definition at line 251 of file vtkALBAXYPlotActor.h.
vtkSetVector2Macro() [1/6]
vtkALBAXYPlotActor::vtkSetVector2Macro (XRange , double)
vtkGetVectorMacro() [1/2]
vtkALBAXYPlotActor::vtkGetVectorMacro (XRange , double , 2)
vtkSetVector2Macro() [2/6]
vtkALBAXYPlotActor::vtkSetVector2Macro (YRange , double)
vtkGetVectorMacro() [2/2]
vtkALBAXYPlotActor::vtkGetVectorMacro (YRange , double , 2)
SetPlotRange()
void vtkALBAXYPlotActor::SetPlotRange (double xmin, double ymin, double xmax, double ymax) inline
Definition at line 265 of file vtkALBAXYPlotActor.h.
vtkSetClampMacro() [3/6]
vtkALBAXYPlotActor::vtkSetClampMacro (NumberOfXLabels , int , 0 , 50)
vtkGetMacro() [8/15]
vtkALBAXYPlotActor::vtkGetMacro (NumberOfXLabels , int)
vtkSetClampMacro() [4/6]
vtkALBAXYPlotActor::vtkSetClampMacro (NumberOfYLabels , int , 0 , 50)
vtkGetMacro() [9/15]
vtkALBAXYPlotActor::vtkGetMacro (NumberOfYLabels , int)
SetNumberOfLabels()
void vtkALBAXYPlotActor::SetNumberOfLabels (int num) inline
Definition at line 277 of file vtkALBAXYPlotActor.h.
vtkSetMacro() [6/9]
vtkALBAXYPlotActor::vtkSetMacro (Legend , int)
vtkGetMacro() [10/15]
vtkALBAXYPlotActor::vtkGetMacro (Legend , int)
vtkBooleanMacro() [6/9]
vtkALBAXYPlotActor::vtkBooleanMacro (Legend , int)
vtkSetVector2Macro() [3/6]
vtkALBAXYPlotActor::vtkSetVector2Macro (LegendPosition , double)
vtkGetVector2Macro() [1/4]
vtkALBAXYPlotActor::vtkGetVector2Macro (LegendPosition , double)
vtkSetVector2Macro() [4/6]
vtkALBAXYPlotActor::vtkSetVector2Macro (LegendPosition2 , double)
vtkGetVector2Macro() [2/4]
vtkALBAXYPlotActor::vtkGetVector2Macro (LegendPosition2 , double)
SetTitleTextProperty()
virtual void vtkALBAXYPlotActor::SetTitleTextProperty (vtkTextProperty * p) virtual
vtkGetObjectMacro() [1/3]
vtkALBAXYPlotActor::vtkGetObjectMacro (TitleTextProperty , vtkTextProperty)
SetAxisTitleTextProperty()
virtual void vtkALBAXYPlotActor::SetAxisTitleTextProperty (vtkTextProperty * p) virtual
vtkGetObjectMacro() [2/3]
vtkALBAXYPlotActor::vtkGetObjectMacro (AxisTitleTextProperty , vtkTextProperty)
SetAxisLabelTextProperty()
virtual void vtkALBAXYPlotActor::SetAxisLabelTextProperty (vtkTextProperty * p) virtual
vtkGetObjectMacro() [3/3]
vtkALBAXYPlotActor::vtkGetObjectMacro (AxisLabelTextProperty , vtkTextProperty)
vtkSetMacro() [7/9]
vtkALBAXYPlotActor::vtkSetMacro (Logx , int)
vtkGetMacro() [11/15]
vtkALBAXYPlotActor::vtkGetMacro (Logx , int)
vtkBooleanMacro() [7/9]
vtkALBAXYPlotActor::vtkBooleanMacro (Logx , int)
SetLabelFormat()
virtual void vtkALBAXYPlotActor::SetLabelFormat (const char * _arg) virtual
vtkGetStringMacro() [4/4]
vtkALBAXYPlotActor::vtkGetStringMacro (LabelFormat)
vtkSetClampMacro() [5/6]
vtkALBAXYPlotActor::vtkSetClampMacro (Border , int , 0 , 50)
vtkGetMacro() [12/15]
vtkALBAXYPlotActor::vtkGetMacro (Border , int)
vtkGetMacro() [13/15]
vtkALBAXYPlotActor::vtkGetMacro (PlotPoints , int)
vtkSetMacro() [8/9]
vtkALBAXYPlotActor::vtkSetMacro (PlotPoints , int)
vtkBooleanMacro() [8/9]
vtkALBAXYPlotActor::vtkBooleanMacro (PlotPoints , int)
vtkGetMacro() [14/15]
vtkALBAXYPlotActor::vtkGetMacro (PlotLines , int)
vtkSetMacro() [9/9]
vtkALBAXYPlotActor::vtkSetMacro (PlotLines , int)
vtkBooleanMacro() [9/9]
vtkALBAXYPlotActor::vtkBooleanMacro (PlotLines , int)
vtkSetClampMacro() [6/6]
vtkALBAXYPlotActor::vtkSetClampMacro (GlyphSize , double , 0. 0, 0. 2)
vtkGetMacro() [15/15]
vtkALBAXYPlotActor::vtkGetMacro (GlyphSize , double)
ViewportToPlotCoordinate() [1/2]
void vtkALBAXYPlotActor::ViewportToPlotCoordinate (vtkViewport * viewport, double & u, double & v)
ViewportToPlotCoordinate() [2/2]
void vtkALBAXYPlotActor::ViewportToPlotCoordinate (vtkViewport * viewport)
vtkSetVector2Macro() [5/6]
vtkALBAXYPlotActor::vtkSetVector2Macro (PlotCoordinate , double)
vtkGetVector2Macro() [3/4]
vtkALBAXYPlotActor::vtkGetVector2Macro (PlotCoordinate , double)
PlotToViewportCoordinate() [1/2]
void vtkALBAXYPlotActor::PlotToViewportCoordinate (vtkViewport * viewport, double & u, double & v)
PlotToViewportCoordinate() [2/2]
void vtkALBAXYPlotActor::PlotToViewportCoordinate (vtkViewport * viewport)
vtkSetVector2Macro() [6/6]
vtkALBAXYPlotActor::vtkSetVector2Macro (ViewportCoordinate , double)
vtkGetVector2Macro() [4/4]
vtkALBAXYPlotActor::vtkGetVector2Macro (ViewportCoordinate , double)
IsInPlot()
int vtkALBAXYPlotActor::IsInPlot (vtkViewport * viewport, double u, double v)
GetMTime()
unsigned long vtkALBAXYPlotActor::GetMTime ()
RenderOpaqueGeometry()
int vtkALBAXYPlotActor::RenderOpaqueGeometry (vtkViewport *)
RenderOverlay()
int vtkALBAXYPlotActor::RenderOverlay (vtkViewport *)
RenderTranslucentGeometry()
int vtkALBAXYPlotActor::RenderTranslucentGeometry (vtkViewport *) inline
Definition at line 399 of file vtkALBAXYPlotActor.h.
ReleaseGraphicsResources()
void vtkALBAXYPlotActor::ReleaseGraphicsResources (vtkWindow *)
InitializeEntries()
void vtkALBAXYPlotActor::InitializeEntries () protected
ComputeXRange()
void vtkALBAXYPlotActor::ComputeXRange (double range[2], double * lengths) protected
ComputeYRange()
void vtkALBAXYPlotActor::ComputeYRange (double range[2]) protected
ComputeDORange()
void vtkALBAXYPlotActor::ComputeDORange (double xrange[2], double yrange[2], double * lengths) protected
CreatePlotData()
virtual void vtkALBAXYPlotActor::CreatePlotData (int * pos, int * pos2, double xRange[2], double yRange[2], double * norms, int numDS, int numDO) protected virtual
PlaceAxes()
void vtkALBAXYPlotActor::PlaceAxes (vtkViewport * viewport, int * size, int pos[2], int pos2[2]) protected
GenerateClipPlanes()
void vtkALBAXYPlotActor::GenerateClipPlanes (int * pos, int * pos2) protected
ComputeGlyphScale()
double vtkALBAXYPlotActor::ComputeGlyphScale (int i, int * pos, int * pos2) protected
ClipPlotData()
void vtkALBAXYPlotActor::ClipPlotData (int * pos, int * pos2, vtkPolyData * pd) protected
TransformPoint()
double * vtkALBAXYPlotActor::TransformPoint (int pos[2], int pos2[2], double x[3], double xNew[3]) protected
Member Data Documentation
InputList
vtkDataSetCollection* vtkALBAXYPlotActor::InputList protected
Definition at line 412 of file vtkALBAXYPlotActor.h.
SelectedInputScalars
char** vtkALBAXYPlotActor::SelectedInputScalars protected
Definition at line 413 of file vtkALBAXYPlotActor.h.
SelectedInputScalarsComponent
vtkIntArray* vtkALBAXYPlotActor::SelectedInputScalarsComponent protected
Definition at line 414 of file vtkALBAXYPlotActor.h.
DataObjectInputList
vtkDataObjectCollection* vtkALBAXYPlotActor::DataObjectInputList protected
Definition at line 415 of file vtkALBAXYPlotActor.h.
Title
char* vtkALBAXYPlotActor::Title protected
Definition at line 416 of file vtkALBAXYPlotActor.h.
XTitle
char* vtkALBAXYPlotActor::XTitle protected
Definition at line 417 of file vtkALBAXYPlotActor.h.
YTitle
char* vtkALBAXYPlotActor::YTitle protected
Definition at line 418 of file vtkALBAXYPlotActor.h.
XValues
int vtkALBAXYPlotActor::XValues protected
Definition at line 419 of file vtkALBAXYPlotActor.h.
NumberOfXLabels
int vtkALBAXYPlotActor::NumberOfXLabels protected
Definition at line 420 of file vtkALBAXYPlotActor.h.
NumberOfYLabels
int vtkALBAXYPlotActor::NumberOfYLabels protected
Definition at line 421 of file vtkALBAXYPlotActor.h.
Logx
int vtkALBAXYPlotActor::Logx protected
Definition at line 422 of file vtkALBAXYPlotActor.h.
LabelFormat
char* vtkALBAXYPlotActor::LabelFormat protected
Definition at line 423 of file vtkALBAXYPlotActor.h.
XRange
double vtkALBAXYPlotActor::XRange[2] protected
Definition at line 424 of file vtkALBAXYPlotActor.h.
YRange
double vtkALBAXYPlotActor::YRange[2] protected
Definition at line 425 of file vtkALBAXYPlotActor.h.
XComputedRange
double vtkALBAXYPlotActor::XComputedRange[2] protected
Definition at line 426 of file vtkALBAXYPlotActor.h.
YComputedRange
double vtkALBAXYPlotActor::YComputedRange[2] protected
Definition at line 427 of file vtkALBAXYPlotActor.h.
Border
int vtkALBAXYPlotActor::Border protected
Definition at line 428 of file vtkALBAXYPlotActor.h.
PlotLines
int vtkALBAXYPlotActor::PlotLines protected
Definition at line 429 of file vtkALBAXYPlotActor.h.
PlotPoints
int vtkALBAXYPlotActor::PlotPoints protected
Definition at line 430 of file vtkALBAXYPlotActor.h.
PlotCurveLines
int vtkALBAXYPlotActor::PlotCurveLines protected
Definition at line 431 of file vtkALBAXYPlotActor.h.
PlotCurvePoints
int vtkALBAXYPlotActor::PlotCurvePoints protected
Definition at line 432 of file vtkALBAXYPlotActor.h.
ExchangeAxes
int vtkALBAXYPlotActor::ExchangeAxes protected
Definition at line 433 of file vtkALBAXYPlotActor.h.
ReverseXAxis
int vtkALBAXYPlotActor::ReverseXAxis protected
Definition at line 434 of file vtkALBAXYPlotActor.h.
ReverseYAxis
int vtkALBAXYPlotActor::ReverseYAxis protected
Definition at line 435 of file vtkALBAXYPlotActor.h.
TitleMapper
vtkTextMapper* vtkALBAXYPlotActor::TitleMapper protected
Definition at line 437 of file vtkALBAXYPlotActor.h.
TitleActor
vtkActor2D* vtkALBAXYPlotActor::TitleActor protected
Definition at line 438 of file vtkALBAXYPlotActor.h.
TitleTextProperty
vtkTextProperty* vtkALBAXYPlotActor::TitleTextProperty protected
Definition at line 439 of file vtkALBAXYPlotActor.h.
XAxis
vtkAxisActor2D* vtkALBAXYPlotActor::XAxis protected
Definition at line 441 of file vtkALBAXYPlotActor.h.
YAxis
vtkAxisActor2D* vtkALBAXYPlotActor::YAxis protected
Definition at line 442 of file vtkALBAXYPlotActor.h.
AxisTitleTextProperty
vtkTextProperty* vtkALBAXYPlotActor::AxisTitleTextProperty protected
Definition at line 444 of file vtkALBAXYPlotActor.h.
AxisLabelTextProperty
vtkTextProperty* vtkALBAXYPlotActor::AxisLabelTextProperty protected
Definition at line 445 of file vtkALBAXYPlotActor.h.
ViewportCoordinate
double vtkALBAXYPlotActor::ViewportCoordinate[2] protected
Definition at line 447 of file vtkALBAXYPlotActor.h.
PlotCoordinate
double vtkALBAXYPlotActor::PlotCoordinate[2] protected
Definition at line 448 of file vtkALBAXYPlotActor.h.
DataObjectPlotMode
int vtkALBAXYPlotActor::DataObjectPlotMode protected
Definition at line 451 of file vtkALBAXYPlotActor.h.
XComponent
vtkIntArray* vtkALBAXYPlotActor::XComponent protected
Definition at line 452 of file vtkALBAXYPlotActor.h.
YComponent
vtkIntArray* vtkALBAXYPlotActor::YComponent protected
Definition at line 453 of file vtkALBAXYPlotActor.h.
LinesOn
vtkIntArray* vtkALBAXYPlotActor::LinesOn protected
Definition at line 454 of file vtkALBAXYPlotActor.h.
PointsOn
vtkIntArray* vtkALBAXYPlotActor::PointsOn protected
Definition at line 455 of file vtkALBAXYPlotActor.h.
NumberOfInputs
int vtkALBAXYPlotActor::NumberOfInputs protected
Definition at line 460 of file vtkALBAXYPlotActor.h.
PlotData
vtkPolyData** vtkALBAXYPlotActor::PlotData protected
Definition at line 461 of file vtkALBAXYPlotActor.h.
PlotGlyph
vtkGlyph2D** vtkALBAXYPlotActor::PlotGlyph protected
Definition at line 462 of file vtkALBAXYPlotActor.h.
PlotAppend
vtkAppendPolyData** vtkALBAXYPlotActor::PlotAppend protected
Definition at line 463 of file vtkALBAXYPlotActor.h.
PlotMapper
vtkPolyDataMapper2D** vtkALBAXYPlotActor::PlotMapper protected
Definition at line 464 of file vtkALBAXYPlotActor.h.
PlotActor
vtkActor2D** vtkALBAXYPlotActor::PlotActor protected
Definition at line 465 of file vtkALBAXYPlotActor.h.
Legend
int vtkALBAXYPlotActor::Legend protected
Definition at line 470 of file vtkALBAXYPlotActor.h.
LegendPosition
double vtkALBAXYPlotActor::LegendPosition[2] protected
Definition at line 471 of file vtkALBAXYPlotActor.h.
LegendPosition2
double vtkALBAXYPlotActor::LegendPosition2[2] protected
Definition at line 472 of file vtkALBAXYPlotActor.h.
LegendActor
vtkLegendBoxActor* vtkALBAXYPlotActor::LegendActor protected
Definition at line 473 of file vtkALBAXYPlotActor.h.
GlyphSource
vtkGlyphSource2D* vtkALBAXYPlotActor::GlyphSource protected
Definition at line 474 of file vtkALBAXYPlotActor.h.
ClipPlanes
vtkPlanes* vtkALBAXYPlotActor::ClipPlanes protected
Definition at line 475 of file vtkALBAXYPlotActor.h.
GlyphSize
double vtkALBAXYPlotActor::GlyphSize protected
Definition at line 476 of file vtkALBAXYPlotActor.h.
CachedSize
int vtkALBAXYPlotActor::CachedSize[2] protected
Definition at line 479 of file vtkALBAXYPlotActor.h.
BuildTime
vtkTimeStamp vtkALBAXYPlotActor::BuildTime protected
Definition at line 480 of file vtkALBAXYPlotActor.h.
The documentation for this class was generated from the following file:
vtkALBAXYPlotActor.h