ALBA: albaDeviceButtonsPadTracker Class Reference
albaDeviceButtonsPadTracker Class Reference
#include <albaDeviceButtonsPadTracker.h>
Public Types
enum TRACKER_WIDGET_ID {
ID_TB_X_EXTENT =Superclass::ID_LAST , ID_TB_Y_EXTENT , ID_TB_Z_EXTENT , ID_TB_POSITION ,
ID_TB_ORIENTATION , ID_AVATAR_CHECK , ID_AVATAR_SELECT , ID_LAST
}
Public Types inherited from albaDevice
enum DEVICE_MINIMUM_ID { MIN_DEVICE_ID =1000000 }
enum DEVICE_WIDGET_ID {
ID_NAME =MINID , ID_ACTIVATE , ID_SHUTDOWN , ID_AUTO_START ,
ID_LAST
}
Public Types inherited from albaAgentEventQueue
enum DispatchModalities { SelfProcessMode = 0 , BroadcastMode }
enum PopModalities { SingleEventMode = 0 , MultipleEventMode }
enum PushModalities { DispatchEventMode =0 , PollingMode }
Public Member Functions
albaTypeMacro (albaDeviceButtonsPadTracker, albaDeviceButtonsPad)
virtual void OnEvent (albaEventBase *event)
void SetLastPoseMatrix (const albaMatrix &matrix)
albaMatrix & GetLastPoseMatrix ()
void SetMoveEventTimeOut (albaTimeStamp t)
albaTimeStamp GetMoveEventTimeOut ()
void SetTrackerToCanonicalTransform (albaTransform *trans)
albaTransform * GetTrackerToCanonicalTransform ()
void TrackerToCanonical (const albaMatrix &pose, albaMatrix &dest)
void TrackerToCanonical (albaMatrix &pose)
void TrackerToCanonical (albaTransform *trans)
void CanonicalToTracker (const albaMatrix &pose, albaMatrix &dest)
void CanonicalToTracker (albaMatrix &pose)
void CanonicalToTracker (albaTransform *trans)
void SetAvatar (albaAvatar *avatar)
albaAvatar * GetAvatar ()
void SetDefaultAvatar (albaAvatar *avatar)
albaAvatar * GetDefaultAvatar ()
void RestoreDefaultAvatar ()
void ComputeTrackerToCanonicalTansform ()
albaOBB & GetCanonicalBounds ()
albaOBB & GetTrackedBounds ()
double * GetTrackedBoxOrientation ()
double GetMax (double x, double y)
double GetMax3 (double x, double y, double z)
virtual void CreateGui ()
virtual void UpdateGui ()
Public Member Functions inherited from albaDeviceButtonsPad
albaTypeMacro (albaDeviceButtonsPad, albaDevice)
void SetButtonState (int num, bool value, unsigned long modifiers=0)
bool GetButtonState (int num)
int GetNumberOfButtons ()
void SetNumberOfButtons (int num)
Public Member Functions inherited from albaDevice
albaTypeMacro (albaDevice, albaAgentThreaded)
unsigned long GetID ()
void SetID (unsigned long id)
virtual void SetName (const char *name)
void SetAutoStart (bool flag)
bool GetAutoStart ()
void AutoStartOn ()
void AutoStartOff ()
virtual int Start ()
virtual void Stop ()
virtual int StartUp ()
void SetPersistentFlag (bool flag)
bool GetPersistentFlag ()
bool IsPersistent ()
albaGUI * GetGui ()
virtual void UpdateGui ()
virtual void OnEvent (albaEventBase *event)
ALBA_ID_DEC (DEVICE_STARTED)
ALBA_ID_DEC (DEVICE_STOPPED)
Public Member Functions inherited from albaAgentThreaded
ALBA_ID_DEC (AGENT_ASYNC_DISPATCH)
albaTypeMacro (albaAgentThreaded, albaAgentEventQueue)
int GetThreaded ()
void SetThreaded (int flag)
int Update ()
virtual void OnEvent (albaEventBase *event)
void AsyncSendEvent (albaObserver *target, albaEventBase *event, albaID channel=MCH_UP)
void AsyncSendEvent (albaObserver *target, void *sender, albaID id, albaID channel=MCH_UP, void *data=NULL)
void AsyncInvokeEvent (albaEventBase *event, albaID channel=MCH_UP)
void AsyncInvokeEvent (albaID id, albaID channel=MCH_UP, void *data=NULL)
Public Member Functions inherited from albaAgentEventQueue
ALBA_ID_DEC (EVENT_DISPATCH)
albaTypeMacro (albaAgentEventQueue, albaAgent)
bool PushEvent (albaEventBase &event)
virtual bool PushEvent (albaEventBase *event)
bool PushEvent (albaID event_id, void *sender, void *data=NULL)
albaEventBase * PeekEvent ()
albaEventBase * PeekLastEvent ()
int GetQueueSize ()
bool IsQueueEmpty ()
virtual bool DispatchEvents ()
void SetDequeueMode (int mode)
int GetDequeueMode ()
void SetDequeueModeToMultipleEvent ()
void SetDequeueModeToSingleEvent ()
void SetDispatchMode (int mode)
int GetDispatchMode ()
void SetDispatchModeToSelfProcess ()
void SetDispatchModeToBroadcast ()
void SetPushMode (int mode)
int GetPushMode ()
void SetPushModeToDispatchEvent ()
void SetPushModeToPolling ()
Public Member Functions inherited from albaAgent
albaAbstractTypeMacro (albaAgent, albaReferenceCounted)
ALBA_ID_DEC (AGENT_INITIALIZE)
void AddObserver (albaObserver *listener, albaID channel=MCH_UP)
void RemoveObserver (albaObserver *listener)
void RemoveAllObservers ()
virtual void OnEvent (albaEventBase *event)
bool HasObservers (albaID channel)
void GetObservers (albaID channel, std::vector< albaObserver * > &olist)
int Initialize ()
void Shutdown ()
int IsInitialized ()
virtual void SetName (const char *name)
const char * GetName ()
Public Member Functions inherited from albaReferenceCounted
albaReferenceCounted ()
virtual ~albaReferenceCounted ()
albaAbstractTypeMacro (albaReferenceCounted, albaObject)
virtual void Delete ()
void Register (void *obj)
virtual void UnRegister (void *obj)
int GetReferenceCount ()
void SetReferenceCount (int)
Public Member Functions inherited from albaObject
albaObject ()
virtual ~albaObject ()
virtual void Delete ()
virtual const char * GetTypeName () const
virtual bool IsA (const char *type_name) const
virtual bool IsA (const albaTypeID &type_id) const
virtual albaObject * NewObjectInstance () const =0
virtual const albaTypeID & GetTypeId () const
virtual void Print (std::ostream &os, const int indent=0) const
albaObject (const albaObject &c)
Public Member Functions inherited from albaObserver
albaObserver ()
virtual ~albaObserver ()
virtual void OnEvent (albaEventBase *e)=0
Public Member Functions inherited from albaEventBroadcaster
albaEventBroadcaster (void *owner=NULL)
virtual ~albaEventBroadcaster ()
albaEventBroadcaster (const albaEventBroadcaster &c)
void AddObserver (albaObserver *obj)
void AddObserver (albaObserver &obj)
albaObserverCallback * AddObserverCallback (void(*f)(void *sender, albaID eid, void *clientdata, void *calldata))
bool RemoveObserver (albaObserver *obj)
void RemoveAllObservers ()
bool IsObserver (albaObserver *obj)
bool HasObservers ()
void GetObservers (std::vector< albaObserver * > &olist)
void InvokeEvent (albaEventBase &e)
void InvokeEvent (albaEventBase *e)
void InvokeEvent (void *sender, albaID id=ID_NO_EVENT, void *data=NULL)
void SetChannel (albaID ch)
albaID GetChannel ()
virtual void SetListener (albaObserver *o)
Public Member Functions inherited from albaEventSender
albaEventSender ()
virtual void SetListener (albaObserver *o)
virtual albaObserver * GetListener ()
virtual bool HasListener ()
virtual void InvokeEvent (albaEventBase &e)
virtual void InvokeEvent (albaEventBase *e)
virtual void InvokeEvent (void *sender, albaID id=ID_NO_EVENT, void *data=NULL)
Public Member Functions inherited from albaStorable
albaStorable ()
int Store (albaStorageElement *element)
int Restore (albaStorageElement *element)
albaObject * CastToObject ()
bool IsStorable ()
Static Public Member Functions
static albaID GetTracker3DMoveId ()
static albaID GetTrackerBoundsUpdatedId ()
Static Public Member Functions inherited from albaDeviceButtonsPad
static albaID GetButtonDownId ()
static albaID GetButtonUpId ()
static albaID GetWheelId ()
Static Public Member Functions inherited from albaObject
static const char * GetStaticTypeName ()
static bool IsStaticType (const char *type_name)
static bool IsStaticType (const albaTypeID &type_id)
static const albaTypeID & GetStaticTypeId ()
static albaObject * SafeDownCast (albaObject *o)
Static Public Member Functions inherited from albaStorable
static albaStorable * SafeCastToObject (albaObject *o)
Protected Member Functions
albaDeviceButtonsPadTracker ()
virtual ~albaDeviceButtonsPadTracker ()
virtual int InternalStore (albaStorageElement *node)
virtual int InternalRestore (albaStorageElement *node)
virtual int InternalInitialize ()
virtual void InternalShutdown ()
virtual void SendButtonEvent (albaEventInteraction *event)
int AvatarChooser (wxString &avatar_name, wxString &avatar_type)
Protected Member Functions inherited from albaDeviceButtonsPad
albaDeviceButtonsPad ()
virtual ~albaDeviceButtonsPad ()
virtual void SendButtonEvent (albaEventInteraction *event)
int FlagCheck (bool event, bool &flag)
Protected Member Functions inherited from albaDevice
albaDevice ()
virtual ~albaDevice ()
virtual int InternalInitialize ()
virtual void CreateGui ()
virtual int InternalStore (albaStorageElement *node)
virtual int InternalRestore (albaStorageElement *node)
Protected Member Functions inherited from albaAgentThreaded
albaAgentThreaded ()
virtual ~albaAgentThreaded ()
virtual void RequestForDispatching ()
void StopThread ()
virtual int InternalInitialize ()
virtual void InternalShutdown ()
virtual int InternalUpdate ()
int GetActiveFlag ()
void SignalNewMessage ()
void WaitForNewMessage ()
Protected Member Functions inherited from albaAgentEventQueue
albaAgentEventQueue ()
virtual ~albaAgentEventQueue ()
albaEventBase * PopEvent ()
int PopEvent (albaEventBase &event)
virtual int PopEvent (albaEventBase *&event)
bool GetDispatched ()
void SetDispatched (bool value=true)
virtual void RequestForDispatching ()
Protected Member Functions inherited from albaAgent
albaAgent ()
virtual ~albaAgent ()
virtual int InternalInitialize ()
virtual void InternalShutdown ()
void InvokeEvent (albaEventBase &event, albaID channel=-1)
void InvokeEvent (albaEventBase *event, albaID channel=-1)
void InvokeEvent (void *sender, int id, albaID channel=MCH_UP, void *data=NULL)
virtual int InternalStore (albaStorageElement *node)=0
virtual int InternalRestore (albaStorageElement *node)=0
Protected Attributes
albaMatrix * m_LastPoseMatrix
int m_LastPose
albaTimeStamp m_LastMoveTime
albaMutexLock m_LastPoseMutex
albaTimeStamp m_MoveEventTimeOut
albaTransform * m_TrackerToCanonicalTransform
albaAutoPointer< albaAvatar > m_Avatar
albaAutoPointer< albaAvatar > m_DefaultAvatar
albaOBB m_CanonicalBounds
int m_AvatarFlag
albaOBB m_TrackedBounds
double m_TrackedBoxOrientation [3]
double m_TBPosition [3]
Protected Attributes inherited from albaDeviceButtonsPad
bool * m_ButtonState
int m_NumberOfButtons
Protected Attributes inherited from albaDevice
albaGUI * m_Gui
albaID m_ID
int m_AutoStart
int m_Start
bool m_Locked
bool m_PersistentFalg
Protected Attributes inherited from albaAgentThreaded
albaMultiThreader * m_Threader
mmuThreadInfoStruct * m_ThreadData
int m_ThreadId
int m_Threaded
int m_ActiveFlag
albaMutexLock * m_Gate
Protected Attributes inherited from albaAgentEventQueue
InternalEventQueue * m_EventQueue
albaMutexLock * m_Mutex
int m_DispatchMode
int m_DequeueMode
int m_PushMode
bool m_Dispatched
Protected Attributes inherited from albaAgent
albaString m_Name
bool m_Initialized
std::vector< albaEventBroadcaster * > m_Channels
Protected Attributes inherited from albaReferenceCounted
int m_ReferenceCount
Protected Attributes inherited from albaObject
bool m_HeapFlag
Protected Attributes inherited from albaEventBroadcaster
albaObserversList m_Observers
albaID m_Channel
Protected Attributes inherited from albaEventSender
albaObserver * m_Listener
Protected Attributes inherited from albaStorable
bool m_Storable
Additional Inherited Members
Protected Types inherited from albaEventBroadcaster
typedef std::list< albaObserver * > albaObserversList
Static Protected Member Functions inherited from albaAgentThreaded
static void UpdateLoop (mmuThreadInfoStruct *data)
Detailed Description
Generic spatial position tracking device.
albaDeviceButtonsPadTracker is a class providing basic functionalities for space trackers, i.e. devices which track an object in space. Specialized classes for specific devices should add their own data structures and reimplemented InternalInitialize and InternalShutdow to activate/stop the device. Tracked pose is expressed by means of a 4x4 matrix. This class issues events each time a new coordinate is available, but if a new coordinate arrives and the last pose has not been consumed (i.e. the last MoveEvent has not been dispatched yet, no event is issued, but the LastPoseMatrix is overwritten. This allows consumer classes to always have last tracked pose. MoveEvent's are albaActionEvent objects, which stores a pose and state of buttons. This class also gives support to transforming from the tracker coordinate system into a canonical coordinate system. The canonical frame is computed by ComputeTrackerToCanonicalTansform() which take as input the tracked volume definition. TrackedVolume is defined as a Oriented Bounding Box, whose bounds is defined by the TrackedBounds member, while the Orientation is defined by the TrackedBoxOrientation member(expressed as Cardan angles according to VTK convention on orientation). The canonical space is related to the tracked volume by TrackerToCanonicalTransform which transforms the TrackedBox into a box centered in the origin, zero rotation and isotropically scaled to normalize max input dimension (e.g. a box of size [-.5,.5,-2,2,-.1,.1] would be scaled to [-.25,.25,-1,1,-.05,.05]. Each tracker can be assigned an avatar (albaAvatar) showing a graphical object moved by tracker's input. The albaDeviceButtonsPadTracker class has a specialized settings class which implements gui for setting the avatar and the tracker's tracked volume. The albaDeviceButtonsPadTracker is also a albaDeviceButtonsPad supporting buttons.
See also
albaDeviceButtonsPad albaGUITrackerSettings albaAvatar
Todo:
manage fusion of position matrices (not working any more)
manage multiple button press (rewrite mflActionEvent)
use an action event also for move events (rewrite SetLastPoseMatrix()).
Definition at line 67 of file albaDeviceButtonsPadTracker.h.
Constructor & Destructor Documentation
albaDeviceButtonsPadTracker()
albaDeviceButtonsPadTracker::albaDeviceButtonsPadTracker () protected
~albaDeviceButtonsPadTracker()
virtual albaDeviceButtonsPadTracker::~albaDeviceButtonsPadTracker () protected virtual
Member Function Documentation
albaTypeMacro()
albaDeviceButtonsPadTracker::albaTypeMacro (albaDeviceButtonsPadTracker , albaDeviceButtonsPad)
GetTracker3DMoveId()
static albaID albaDeviceButtonsPadTracker::GetTracker3DMoveId () static
return the tracker 3d move id
GetTrackerBoundsUpdatedId()
static albaID albaDeviceButtonsPadTracker::GetTrackerBoundsUpdatedId () static
return th tracker bounds updated id
OnEvent()
virtual void albaDeviceButtonsPadTracker::OnEvent (albaEventBase * event) virtual
Reimplemented to manage fusion of move events.
Reimplemented from albaDevice.
SetLastPoseMatrix()
void albaDeviceButtonsPadTracker::SetLastPoseMatrix (const albaMatrix & matrix)
Internally used to set the last pose matrix.
This function make a copy of the matrix, and in case of vtkMatrix4x4 attach a time stamp with the current time. Finally a MoveEvent is rosed. Notice that old MoveEvent's are overwritten by new ones if not yet served.
GetLastPoseMatrix()
albaMatrix & albaDeviceButtonsPadTracker::GetLastPoseMatrix ()
SetMoveEventTimeOut()
void albaDeviceButtonsPadTracker::SetMoveEventTimeOut (albaTimeStamp t) inline
set the timeout after which the event is discarded (in seconds)
Definition at line 114 of file albaDeviceButtonsPadTracker.h.
GetMoveEventTimeOut()
albaTimeStamp albaDeviceButtonsPadTracker::GetMoveEventTimeOut () inline
Definition at line 115 of file albaDeviceButtonsPadTracker.h.
SetTrackerToCanonicalTransform()
void albaDeviceButtonsPadTracker::SetTrackerToCanonicalTransform (albaTransform * trans)
Set the transform to be used to map coordinates between tracker and canonical frames.
GetTrackerToCanonicalTransform()
albaTransform * albaDeviceButtonsPadTracker::GetTrackerToCanonicalTransform ()
return the transform mapping coordinates from tracker to canonical frame.
TrackerToCanonical() [1/3]
void albaDeviceButtonsPadTracker::TrackerToCanonical (const albaMatrix & pose, albaMatrix & dest)
This is used to map the RAW transform in tracker's frame into the canonical frame.
TrackerToCanonical() [2/3]
void albaDeviceButtonsPadTracker::TrackerToCanonical (albaMatrix & pose) inline
Definition at line 130 of file albaDeviceButtonsPadTracker.h.
References TrackerToCanonical().
Referenced by TrackerToCanonical().
TrackerToCanonical() [3/3]
void albaDeviceButtonsPadTracker::TrackerToCanonical (albaTransform * trans)
CanonicalToTracker() [1/3]
void albaDeviceButtonsPadTracker::CanonicalToTracker (const albaMatrix & pose, albaMatrix & dest)
This is used to map a pose in canonical frame into tracker's frame.
CanonicalToTracker() [2/3]
void albaDeviceButtonsPadTracker::CanonicalToTracker (albaMatrix & pose) inline
Definition at line 136 of file albaDeviceButtonsPadTracker.h.
References CanonicalToTracker().
Referenced by CanonicalToTracker().
CanonicalToTracker() [3/3]
void albaDeviceButtonsPadTracker::CanonicalToTracker (albaTransform * trans)
SetAvatar()
void albaDeviceButtonsPadTracker::SetAvatar (albaAvatar * avatar)
Set/Get the avatar assigned to this device.
GetAvatar()
albaAvatar * albaDeviceButtonsPadTracker::GetAvatar () inline
Definition at line 142 of file albaDeviceButtonsPadTracker.h.
SetDefaultAvatar()
void albaDeviceButtonsPadTracker::SetDefaultAvatar (albaAvatar * avatar)
Set the default avatar, i.e.
the avatar to be used as default one. An application module can set the avatar to a transient one and then restore the default one. The default avatar is made persistent and will be recreated by means of the object factory when restarting the application. Setting the default avatar automatically calls the SetAvatar() too.
GetDefaultAvatar()
albaAvatar * albaDeviceButtonsPadTracker::GetDefaultAvatar () inline
Definition at line 151 of file albaDeviceButtonsPadTracker.h.
RestoreDefaultAvatar()
void albaDeviceButtonsPadTracker::RestoreDefaultAvatar ()
Restore the avatar to the default one.
An application module can set the avatar to a transient one and then restore the default one.
ComputeTrackerToCanonicalTansform()
void albaDeviceButtonsPadTracker::ComputeTrackerToCanonicalTansform ()
Update the Tracker to Canonical transform.
This transform maps the tracked working box into the canonical working box, which is a working box with no orientation and centered around the origin (i.e. a identical pose matrix) and isotropically scaled to fit the [-1,1,-1,1,-1,1] box.
GetCanonicalBounds()
albaOBB & albaDeviceButtonsPadTracker::GetCanonicalBounds ()
return bounds of canonical space
GetTrackedBounds()
albaOBB & albaDeviceButtonsPadTracker::GetTrackedBounds () inline
return bounds of tracked volume.
Tracked volume is expessed as an oriented bounding box. For orientation see GetTrackedBoxOrientation()
Definition at line 174 of file albaDeviceButtonsPadTracker.h.
GetTrackedBoxOrientation()
double * albaDeviceButtonsPadTracker::GetTrackedBoxOrientation () inline
return orientation of tracked volume.
Tracked volume is expessed as an oriented bounding box. For box extents see orientation see GetTrackedBounds()
Definition at line 180 of file albaDeviceButtonsPadTracker.h.
GetMax()
double albaDeviceButtonsPadTracker::GetMax (double x, double y) inline
utility function for finding maximum among 2 values
Definition at line 236 of file albaDeviceButtonsPadTracker.h.
GetMax3()
double albaDeviceButtonsPadTracker::GetMax3 (double x, double y, double z) inline
utility function for finding maximum among 3 values
Definition at line 244 of file albaDeviceButtonsPadTracker.h.
CreateGui()
virtual void albaDeviceButtonsPadTracker::CreateGui () virtual
internal function to create device GUI for settings
Reimplemented from albaDevice.
UpdateGui()
virtual void albaDeviceButtonsPadTracker::UpdateGui () virtual
force GUI update
Reimplemented from albaDevice.
InternalStore()
virtual int albaDeviceButtonsPadTracker::InternalStore (albaStorageElement * node) protected virtual
This is used to allow nested serialization of subclasses.
This function is called by Store and is reimplemented in subclasses. Each subclass can store its own subelements which are closed inside the "Device" element. Reimplemented functions should first call Superclass implementation.
Reimplemented from albaDevice.
InternalRestore()
virtual int albaDeviceButtonsPadTracker::InternalRestore (albaStorageElement * node) protected virtual
This function fills in the device with settings restored from the node.
Subclasses should reimplement it to restore custom settings. Reimplemented functions should first call Superclass implementation.
Reimplemented from albaDevice.
InternalInitialize()
virtual int albaDeviceButtonsPadTracker::InternalInitialize () protected virtual
start device
Reimplemented from albaDevice.
Reimplemented in albaDeviceButtonsPadTrackerP5Glove, and albaDeviceTrackerWIIMote.
InternalShutdown()
virtual void albaDeviceButtonsPadTracker::InternalShutdown () protected virtual
to be redefined by subclasses to define the shutdown actions
Reimplemented from albaAgentThreaded.
Reimplemented in albaDeviceButtonsPadTrackerP5Glove, and albaDeviceTrackerWIIMote.
SendButtonEvent()
virtual void albaDeviceButtonsPadTracker::SendButtonEvent (albaEventInteraction * event) protected virtual
add pose matrix to the event
Reimplemented from albaDeviceButtonsPad.
AvatarChooser()
int albaDeviceButtonsPadTracker::AvatarChooser (wxString & avatar_name, wxString & avatar_type) protected
Member Data Documentation
m_LastPoseMatrix
albaMatrix* albaDeviceButtonsPadTracker::m_LastPoseMatrix protected
stores the last pose matrix
Definition at line 209 of file albaDeviceButtonsPadTracker.h.
m_LastPose
int albaDeviceButtonsPadTracker::m_LastPose protected
Flag used when last pose has not been served yet.
Definition at line 210 of file albaDeviceButtonsPadTracker.h.
m_LastMoveTime
albaTimeStamp albaDeviceButtonsPadTracker::m_LastMoveTime protected
Time stamp of last MoveEvent.
Definition at line 211 of file albaDeviceButtonsPadTracker.h.
m_LastPoseMutex
albaMutexLock albaDeviceButtonsPadTracker::m_LastPoseMutex protected
Definition at line 212 of file albaDeviceButtonsPadTracker.h.
m_MoveEventTimeOut
albaTimeStamp albaDeviceButtonsPadTracker::m_MoveEventTimeOut protected
Definition at line 214 of file albaDeviceButtonsPadTracker.h.
m_TrackerToCanonicalTransform
albaTransform* albaDeviceButtonsPadTracker::m_TrackerToCanonicalTransform protected
Definition at line 216 of file albaDeviceButtonsPadTracker.h.
m_Avatar
albaAutoPointer<albaAvatar> albaDeviceButtonsPadTracker::m_Avatar protected
the current avatar
Definition at line 218 of file albaDeviceButtonsPadTracker.h.
m_DefaultAvatar
albaAutoPointer<albaAvatar> albaDeviceButtonsPadTracker::m_DefaultAvatar protected
the avatar set thorugh the GUI
Definition at line 219 of file albaDeviceButtonsPadTracker.h.
m_CanonicalBounds
albaOBB albaDeviceButtonsPadTracker::m_CanonicalBounds protected
Bounds of canonical space.
Definition at line 223 of file albaDeviceButtonsPadTracker.h.
m_AvatarFlag
int albaDeviceButtonsPadTracker::m_AvatarFlag protected
used for the GUI
Definition at line 224 of file albaDeviceButtonsPadTracker.h.
m_TrackedBounds
albaOBB albaDeviceButtonsPadTracker::m_TrackedBounds protected
Stores tracked volume bounds (xmin,xmax,ymin,ymax,zmin,zmax)
Definition at line 225 of file albaDeviceButtonsPadTracker.h.
m_TrackedBoxOrientation
double albaDeviceButtonsPadTracker::m_TrackedBoxOrientation[3] protected
Used to store the tracked box orientation (VTK's convention: cardan angles)
Definition at line 226 of file albaDeviceButtonsPadTracker.h.
m_TBPosition
double albaDeviceButtonsPadTracker::m_TBPosition[3] protected
Used to store the tracked box center.
Definition at line 227 of file albaDeviceButtonsPadTracker.h.
The documentation for this class was generated from the following file:
albaDeviceButtonsPadTracker.h