ALBA 2: albaOpMeshDeformation Class Reference
albaOpMeshDeformation Class Reference
#include <albaOpMeshDeformation.h>
Classes
struct CONTROL_CURVE
struct MESH
struct UNDO_ITEM
Public Member Functions
albaOpMeshDeformation (const wxString &label="Mesh deformation")
~albaOpMeshDeformation ()
void OnEvent (albaEventBase *alba_event)
albaTypeMacro (albaOpMeshDeformation, albaOp)
albaOp * Copy ()
void OpRun ()
void OpDo ()
void OpUndo ()
virtual int GetNumberOfControlCurves ()
virtual void SetNumberOfControlCurves (int nCount)
virtual void SetNthControlCurve (int num, albaVME *original, albaVME *modified, vtkIdList *correspondence)
virtual void SetNthOriginalControlCurve (int num, albaVME *input)
virtual void SetNthDeformedControlCurve (int num, albaVME *input)
virtual void SetNthControlCurveCorrespondence (int num, vtkIdList *matchlist)
virtual albaVME ** GetOriginalControlCurves ()
virtual albaVME ** GetDeformedControlCurves ()
virtual vtkIdList ** GetControlCurvesCorrespondence ()
Public Member Functions inherited from albaOp
albaTypeMacro (albaOp, albaObject)
albaOp ()
albaOp (const wxString &label)
virtual ~albaOp ()
void SetListener (albaObserver *Listener)
int GetType ()
virtual void OnEvent (albaEventBase *alba_event)
virtual albaOp * Copy ()
virtual void OpRun ()
virtual void SetParameters (void *param)
virtual albaString GetParameters ()
virtual void OpDo ()
virtual void OpUndo ()
virtual albaGUI * GetGui ()
virtual void SetInput (albaVME *vme)
virtual albaVME * GetInput ()
virtual albaVME * GetOutput ()
virtual void SetOutput (albaVME *output)
bool Accept (albaVME *vme)
void EnableAccept (bool enable=true)
virtual bool CanUndo ()
bool IsInputPreserving ()
void ShowGui ()
void HideGui ()
virtual bool OkEnabled ()
virtual void ForceStopWithOk ()
virtual void ForceStopWithCancel ()
bool IsCompatible (long state)
virtual const char ** GetActions ()
void SetMouse (albaDeviceButtonsPadMouse *mouse)
albaDeviceButtonsPadMouse * GetMouse ()
void TestModeOn ()
void TestModeOff ()
bool GetTestMode ()
void SetCanundo (bool can_undo=true)
bool GetCanundo ()
void SetSetting (albaGUISettings *setting)
albaGUISettings * GetSetting ()
virtual char ** GetIcon ()
Public Member Functions inherited from albaObserver
albaObserver ()
virtual ~albaObserver ()
virtual void OnEvent (albaEventBase *e)=0
Public Member Functions inherited from albaObject
albaObject ()
virtual ~albaObject ()
virtual void Delete ()
virtual const char * GetTypeName () const
virtual bool IsA (const char *type_name) const
virtual bool IsA (const albaTypeID &type_id) const
virtual albaObject * NewObjectInstance () const =0
virtual const albaTypeID & GetTypeId () const
virtual void Print (std::ostream &os, const int indent=0) const
albaObject (const albaObject &c)
Protected Types
enum GUI_IDS {
ID_RESET = MINID , ID_UNDO , ID_PREVIEW , ID_CREATE_CURVES ,
ID_SELECT_OC , ID_SELECT_DC , ID_CORRESPONDENCE , ID_RESETCURVE ,
ID_ADDCURVE , ID_EDITMODE , ID_EDITMODE_HELP , ID_EDITMODE_INFO ,
ID_ENABLE_OC_EDIT , ID_SHOW_OC , ID_SHOW_DC , ID_SHOW_CC ,
ID_SHOW_OM , ID_SHOW_DM , ID_SHOW_XX_CHANGE , ID_SAVEOC ,
ID_SAVEDC , ID_DEFORMATIONMODE , ID_DEFORMATIONMODE_HELP , ID_OK ,
ID_CANCEL
}
enum EDIT_MODES {
EDM_ADD_CURVE = -1 , EDM_SELECT = 0 , EDM_MOVE_POINTS , EDM_ADD_POINT ,
EDM_DELETE_POINT , EDM_ADD_CORRESPONDENCE , EDM_DELETE_CORRESPONDENCE , EDM_DELETE_CURVE ,
EDM_SELECT_MESH_VERTEX
}
enum DEFORMATION_MODES { DEM_BLANCO , DEM_SEPPLANES , DEM_WARPING }
typedef struct albaOpMeshDeformation::UNDO_ITEM UNDO_ITEM
typedef struct albaOpMeshDeformation::CONTROL_CURVE CONTROL_CURVE
typedef struct albaOpMeshDeformation::MESH MESH
Protected Member Functions
bool InternalAccept (albaVME *node)
void OpStop (int result)
virtual bool CreateInternalStructures ()
virtual void DeleteInternalStructures ()
void CreateOpDialog ()
void DeleteOpDialog ()
MESH * CreateMesh (vtkPolyData *pMesh)
CONTROL_CURVE * CreateControlCurve (albaPolylineGraph *pOC, albaPolylineGraph *pDC, vtkIdList *pCC)
void UpdateMesh (MESH *pMesh)
void UpdateControlCurve (CONTROL_CURVE *pCurve, int flags=-1)
void UpdateControlCurveVisibility (CONTROL_CURVE *pCurve)
void UpdateVisibility ()
void UpdateSelectionVisibility ()
void RemoveAllActors ()
void DeformMesh ()
template<class T >
void DeformMeshT ()
void AddControlCurve (albaPolylineGraph *pOC, albaPolylineGraph *pDC, vtkIdList *pCC)
void DeleteControlCurve (int index)
int FindPoint (CONTROL_CURVE *pCurve, int iType, double pos[3])
void SelectControlCurve (CONTROL_CURVE *pCurve, int iType, double pos[3])
void BeginMovePoint (int index, int iType, double pos[3])
void EndMovePoint ()
void MovePoint (double pos[3])
void AddPoint (int index, int iType, double pos[3])
void DeletePoint (int index, int iType, double pos[3])
void CreateUndo (int index, int nAction, int nFlags)
void BeginAddCorrespondence (int index, int iType, double pos[3])
void EndAddCorrespondence (int index, int iType, double pos[3])
int FindCorrespondence (vtkIdList *pCL, int ptIndex, int iCurve)
void DeleteCorrespondence (vtkIdList *&pCL, int index)
void DeleteCorrespondence (int index, double pos[3])
virtual void OnCreateCurves ()
virtual void OnSelectOC ()
virtual void OnSelectDC ()
virtual void OnResetCurve ()
virtual void OnAddCurve ()
virtual void OnEditMode ()
virtual void OnDeformationMode ()
virtual void OnPick (vtkCellPicker *cellPicker)
virtual void OnReset ()
virtual void OnUndo ()
virtual void OnPreview ()
virtual void OnOk ()
virtual albaVME * SelectCurveVME ()
albaPolylineGraph * CreatePolylineGraph (albaVME *vme)
albaPolylineGraph * CreateCopyOfPolylineGraph (albaPolylineGraph *input)
virtual bool InternalAccept (albaVME *vme)
virtual void OpStop (int result)
Static Protected Member Functions
static bool SelectCurveVMECallback (albaVME *vme)
Protected Attributes
int m_NumberOfCurves
albaVME ** m_OriginalCurves
albaVME ** m_DeformedCurves
vtkIdList ** m_CurvesCorrespondence
albaGUIDialog * m_Dialog
albaRWI * m_Rwi
mmiVTKPicker * m_Picker
vtkSphereSource * m_Spheres [2]
double m_SphereRadius [2]
MESH * m_Meshes [2]
std::vector< CONTROL_CURVE * > m_Curves
std::vector< UNDO_ITEM * > m_UndoStack
CONTROL_CURVE * m_SelectedCurve
int m_SelectedObjType
int m_SelectedObjId
vtkSphereSource * m_SelPointGlyph
vtkActor * m_SelPointActor
albaVME * m_OCToAdd
albaVME * m_DCToAdd
int m_EditMode
int m_MeshesVisibility [2]
int m_CurvesVisibility [3]
int m_DeformationMode
int m_SaveODC [2]
bool m_BPointMoveActive
double m_PointMoveCorrection [3]
bool m_BCorrespondenceActive
bool m_BDoNotCreateUndo
wxButton * m_BttnReset
wxButton * m_BttnUndo
wxButton * m_BttnPreview
wxStaticText * m_OCNameCtrl
wxStaticText * m_DCNameCtrl
wxButton * m_BttnSelDC
wxTextCtrl * m_CCCtrl
wxButton * m_BttnGenCurves
wxButton * m_BttnResetCurve
wxButton * m_BttnAddCurve
wxTextCtrl * m_EditModeHelp
wxStaticText * m_EditModeInfo
wxCheckBox * m_ChckEditOC
wxTextCtrl * m_DeformationModeHelp
wxButton * m_BttnOK
Protected Attributes inherited from albaOp
albaVME * m_Input
albaVME * m_Output
albaGUI * m_Gui
albaGUIHolder * m_Guih
bool m_Canundo
int m_OpType
bool m_InputPreserving
albaObserver * m_Listener
albaDeviceButtonsPadMouse * m_Mouse
albaGUISettings * m_SettingPanel
bool m_TestMode
bool m_EnableAccept
Protected Attributes inherited from albaObject
bool m_HeapFlag
Additional Inherited Members
Public Types inherited from albaOp
enum ALBAOP_ID { ID_HELP = MINID , MINID }
Static Public Member Functions inherited from albaObject
static const char * GetStaticTypeName ()
static bool IsStaticType (const char *type_name)
static bool IsStaticType (const albaTypeID &type_id)
static const albaTypeID & GetStaticTypeId ()
static albaObject * SafeDownCast (albaObject *o)
Public Attributes inherited from albaOp
wxString m_Label
int m_Id
albaOp * m_Next
long m_Compatibility
wxMenuItem * m_MenuItem
wxString m_OpMenuPath
Detailed Description
Definition at line 47 of file albaOpMeshDeformation.h.
Member Typedef Documentation
UNDO_ITEM
typedef struct albaOpMeshDeformation::UNDO_ITEM albaOpMeshDeformation::UNDO_ITEM protected
CONTROL_CURVE
typedef struct albaOpMeshDeformation::CONTROL_CURVE albaOpMeshDeformation::CONTROL_CURVE protected
MESH
typedef struct albaOpMeshDeformation::MESH albaOpMeshDeformation::MESH protected
Member Enumeration Documentation
GUI_IDS
enum albaOpMeshDeformation::GUI_IDS protected
Enumerator
ID_RESET
ID_UNDO
ID_PREVIEW
ID_CREATE_CURVES
ID_SELECT_OC
ID_SELECT_DC
ID_CORRESPONDENCE
ID_RESETCURVE
ID_ADDCURVE
ID_EDITMODE
ID_EDITMODE_HELP
ID_EDITMODE_INFO
ID_ENABLE_OC_EDIT
ID_SHOW_OC
ID_SHOW_DC
ID_SHOW_CC
ID_SHOW_OM
ID_SHOW_DM
ID_SHOW_XX_CHANGE
ID_SAVEOC
ID_SAVEDC
ID_DEFORMATIONMODE
ID_DEFORMATIONMODE_HELP
ID_OK
ID_CANCEL
Definition at line 53 of file albaOpMeshDeformation.h.
EDIT_MODES
enum albaOpMeshDeformation::EDIT_MODES protected
Enumerator
EDM_ADD_CURVE
EDM_SELECT
EDM_MOVE_POINTS
EDM_ADD_POINT
EDM_DELETE_POINT
EDM_ADD_CORRESPONDENCE
EDM_DELETE_CORRESPONDENCE
EDM_DELETE_CURVE
EDM_SELECT_MESH_VERTEX
Definition at line 83 of file albaOpMeshDeformation.h.
DEFORMATION_MODES
enum albaOpMeshDeformation::DEFORMATION_MODES protected
Enumerator
DEM_BLANCO
DEM_SEPPLANES
DEM_WARPING
Definition at line 99 of file albaOpMeshDeformation.h.
Constructor & Destructor Documentation
albaOpMeshDeformation()
albaOpMeshDeformation::albaOpMeshDeformation (const wxString & label = "Mesh deformation")
~albaOpMeshDeformation()
albaOpMeshDeformation::~albaOpMeshDeformation ()
Member Function Documentation
OnEvent()
void albaOpMeshDeformation::OnEvent (albaEventBase * e) virtual
process the events sent by subjects
Reimplemented from albaOp.
albaTypeMacro()
albaOpMeshDeformation::albaTypeMacro (albaOpMeshDeformation , albaOp)
Copy()
albaOp * albaOpMeshDeformation::Copy () virtual
Reimplemented from albaOp.
OpRun()
void albaOpMeshDeformation::OpRun () virtual
Builds operation's interface.
Reimplemented from albaOp.
OpDo()
void albaOpMeshDeformation::OpDo () virtual
Execute the operation.
Reimplemented from albaOp.
OpUndo()
void albaOpMeshDeformation::OpUndo () virtual
Makes the undo for the operation.
Reimplemented from albaOp.
GetNumberOfControlCurves()
virtual int albaOpMeshDeformation::GetNumberOfControlCurves () inline virtual
Get the number of control curves.
Definition at line 161 of file albaOpMeshDeformation.h.
SetNumberOfControlCurves()
virtual void albaOpMeshDeformation::SetNumberOfControlCurves (int nCount) virtual
Sets the number of control curves.
Sets the number of control VMEs (polylines or polylinegraphs). Old VMEs are copied (and preserved)
SetNthControlCurve()
void albaOpMeshDeformation::SetNthControlCurve (int num, albaVME * original, albaVME * modified, vtkIdList * correspondence) inline virtual
Specifies the n-th control curve.
See: SetNthOriginalControlCurve, SetNthDeformedControlCurve and SetNthControlCurveCorrespondence for detailed information
Definition at line 466 of file albaOpMeshDeformation.h.
References SetNthControlCurveCorrespondence(), SetNthDeformedControlCurve(), and SetNthOriginalControlCurve().
SetNthOriginalControlCurve()
virtual void albaOpMeshDeformation::SetNthOriginalControlCurve (int num, albaVME * input) virtual
Specifies the n-th control curve in its original (undeformed) state.
Referenced by SetNthControlCurve().
SetNthDeformedControlCurve()
virtual void albaOpMeshDeformation::SetNthDeformedControlCurve (int num, albaVME * input) virtual
Specifies the n-th control curve in its deformed state.
Referenced by SetNthControlCurve().
SetNthControlCurveCorrespondence()
virtual void albaOpMeshDeformation::SetNthControlCurveCorrespondence (int num, vtkIdList * matchlist) virtual
Sets the correspondence between the n-th original and deformed curve.
The list contains pairs of indices of vertices of original-deformed curve that correspond to each other. N.B. if not specified, it is assumed that first vertices correspond.
Referenced by SetNthControlCurve().
GetOriginalControlCurves()
virtual albaVME ** albaOpMeshDeformation::GetOriginalControlCurves () inline virtual
Returns an array with all control curves in their original state.
Definition at line 189 of file albaOpMeshDeformation.h.
GetDeformedControlCurves()
virtual albaVME ** albaOpMeshDeformation::GetDeformedControlCurves () inline virtual
Returns an array with all control curves in their deformed state.
Definition at line 194 of file albaOpMeshDeformation.h.
GetControlCurvesCorrespondence()
virtual vtkIdList ** albaOpMeshDeformation::GetControlCurvesCorrespondence () inline virtual
Returns an array with all correspondences for control curves.
Definition at line 199 of file albaOpMeshDeformation.h.
InternalAccept()
bool albaOpMeshDeformation::InternalAccept (albaVME * node) protected virtual
Return true for the acceptable vme type.
Reimplemented from albaOp.
OpStop()
void albaOpMeshDeformation::OpStop (int result) protected virtual
This method is called at the end of the operation and result contain the wxOK or wxCANCEL.
Reimplemented from albaOp.
CreateInternalStructures()
virtual bool albaOpMeshDeformation::CreateInternalStructures () protected virtual
Creates internal data structures used in the editor.
Returns false, if an error occurs (e.g. unsupported input)
DeleteInternalStructures()
virtual void albaOpMeshDeformation::DeleteInternalStructures () protected virtual
Destroys internal data structures created by CreateInternalStructures.
CreateOpDialog()
void albaOpMeshDeformation::CreateOpDialog () protected
Creates GUI including renderer window.
DeleteOpDialog()
void albaOpMeshDeformation::DeleteOpDialog () protected
Destroys GUI.
CreateMesh()
MESH * albaOpMeshDeformation::CreateMesh (vtkPolyData * pMesh) protected
This method creates the internal mesh structure.
It constructs also the VTK pipeline.
CreateControlCurve()
CONTROL_CURVE * albaOpMeshDeformation::CreateControlCurve (albaPolylineGraph * pOC, albaPolylineGraph * pDC, vtkIdList * pCC) protected
Creates the control curve structure.
It constructs also the VTK pipeline.
UpdateMesh()
void albaOpMeshDeformation::UpdateMesh (MESH * pMesh) protected
Updates the VTK pipeline for the given curve.
N.B. It does not connects actors into the renderer.
UpdateControlCurve()
void albaOpMeshDeformation::UpdateControlCurve (CONTROL_CURVE * pCurve, int flags = -1) protected
Updates the VTK pipeline for the given curve.
Flags define what needs to be updated, bit 0 corresponds to the original curve, 1 to deformed and 2 to correspondence N.B. It does not connects actors into the renderer.
UpdateControlCurveVisibility()
void albaOpMeshDeformation::UpdateControlCurveVisibility (CONTROL_CURVE * pCurve) protected
Updates the visibility of the given control curve.
It adds/removes actors from the renderer according to the status of curves and the visual options specified by the user in the GUI. N.B. This is typically called when curve was updated.
UpdateVisibility()
void albaOpMeshDeformation::UpdateVisibility () protected
Updates the visibility of meshes and control curves.
It adds/removes actors from the renderer according to the status of their associated data and the visual options specified by the user in the GUI. This method is typically calls after UpdateMesh or UpdateControlCurve is finished
UpdateSelectionVisibility()
void albaOpMeshDeformation::UpdateSelectionVisibility () protected
Updates the visibility of the selected items.
Called automatically from UpdateVisibility and UpdateControlCurveVisibility
RemoveAllActors()
void albaOpMeshDeformation::RemoveAllActors () protected
Removes all actors from the renderer.
DeformMesh()
void albaOpMeshDeformation::DeformMesh () protected
Deforms the input mesh producing output mesh.
DeformMeshT()
template<class T > void albaOpMeshDeformation::DeformMeshT () protected
Template for various methods.
AddControlCurve()
void albaOpMeshDeformation::AddControlCurve (albaPolylineGraph * pOC, albaPolylineGraph * pDC, vtkIdList * pCC) protected
Adds a new control curve.
N.B. this does everything. It creates VTK pipeline, internal structures, undo item for this operation and also updates the visibility.
DeleteControlCurve()
void albaOpMeshDeformation::DeleteControlCurve (int index) protected
Deletes the control curve at the given index.
N.B. this does everything. It destroys VTK pipeline and creates undo item for this operation.
FindPoint()
int albaOpMeshDeformation::FindPoint (CONTROL_CURVE * pCurve, int iType, double pos[3]) protected
Finds the point on iType curve (0 for OC, 1 for DC) closest to the given position.
Returns -1, if there is no point within the glyph tolerance
SelectControlCurve()
void albaOpMeshDeformation::SelectControlCurve (CONTROL_CURVE * pCurve, int iType, double pos[3]) protected
Selects an original curve, a deformed curve, a vertex or a correspondence.
The selection is done for the given control curve and iType is 0 for OC, 1 for DC and 2 for CC; pos is the position where the pick event happened
BeginMovePoint()
void albaOpMeshDeformation::BeginMovePoint (int index, int iType, double pos[3]) protected
Initializes the movement of the point denoted by pos.
The curve is defined by its index and iType is 0 for OC, 1 for DC After the calling of this routine, any number of MovePoint routines is called to move the point. The process ends when EndMovePoint is called
EndMovePoint()
void albaOpMeshDeformation::EndMovePoint () protected
Finalizes the movement of the point N.B.
see BeginMovePoint
MovePoint()
void albaOpMeshDeformation::MovePoint (double pos[3]) protected
Moves the current point into the new position N.B.
see BeginMovePoint
AddPoint()
void albaOpMeshDeformation::AddPoint (int index, int iType, double pos[3]) protected
Adds a new point with the specified coordinates on a curve.
The curve is defined by its index and iType is 0 for OC, 1 for DC The point is inserted into the closest segment
DeletePoint()
void albaOpMeshDeformation::DeletePoint (int index, int iType, double pos[3]) protected
Removes the existing point with the specified coordinates from a curve The curve is defined by its index and iType is 0 for OC, 1 for DC.
CreateUndo()
void albaOpMeshDeformation::CreateUndo (int index, int nAction, int nFlags) protected
Creates an undo item for the given curve.
BeginAddCorrespondence()
void albaOpMeshDeformation::BeginAddCorrespondence (int index, int iType, double pos[3]) protected
Initializes the correspondence construction.
EndAddCorrespondence()
void albaOpMeshDeformation::EndAddCorrespondence (int index, int iType, double pos[3]) protected
Finalizes the correspondence construction.
FindCorrespondence()
int albaOpMeshDeformation::FindCorrespondence (vtkIdList * pCL, int ptIndex, int iCurve) protected
Finds a correspondence for the given point from the specified curve It returns -1, if there is no such correspondence; index to CC list otherwise.
DeleteCorrespondence() [1/2]
void albaOpMeshDeformation::DeleteCorrespondence (vtkIdList *& pCL, int index) protected
Deletes the correspondence at the given index.
DeleteCorrespondence() [2/2]
void albaOpMeshDeformation::DeleteCorrespondence (int index, double pos[3]) protected
Deletes the correspondence close to the given point coordinates The control curve to be modified is denoted by the given index.
OnCreateCurves()
virtual void albaOpMeshDeformation::OnCreateCurves () protected virtual
Generates control curves for the mesh.
All existing control curves are removed
OnSelectOC()
virtual void albaOpMeshDeformation::OnSelectOC () protected virtual
Opens VMEChoose dialog and selects new original curve.
OnSelectDC()
virtual void albaOpMeshDeformation::OnSelectDC () protected virtual
Opens VMEChoose dialog and selects new deformed curve.
OnResetCurve()
virtual void albaOpMeshDeformation::OnResetCurve () protected virtual
Clears everything form OC, DC and CC edits.
OnAddCurve()
virtual void albaOpMeshDeformation::OnAddCurve () protected virtual
Adds new control curve.
OnEditMode()
virtual void albaOpMeshDeformation::OnEditMode () protected virtual
Called when the edit mode changes.
Updates the EditModeHelp text
OnDeformationMode()
virtual void albaOpMeshDeformation::OnDeformationMode () protected virtual
Called when the deformation mode changes.
Updates the DeformationModeHelp text
OnPick()
virtual void albaOpMeshDeformation::OnPick (vtkCellPicker * cellPicker) protected virtual
Called when the user picks something.
OnReset()
virtual void albaOpMeshDeformation::OnReset () protected virtual
Undoes every action performed after the last adding/deletion of control curve It undoes movement of points, adding/deletion of vertices and correspondences N.B.
The default implementation calls OnUndo
OnUndo()
virtual void albaOpMeshDeformation::OnUndo () protected virtual
Undoes the last action.
OnPreview()
virtual void albaOpMeshDeformation::OnPreview () protected virtual
Performs the deformation using the current settings.
OnOk()
virtual void albaOpMeshDeformation::OnOk () protected virtual
Performs the deformation and creates outputs.
SelectCurveVME()
virtual albaVME * albaOpMeshDeformation::SelectCurveVME () protected virtual
Selects VME of supported type for control curve Returns NULL, if the user cancels the selection.
SelectCurveVMECallback()
static bool albaOpMeshDeformation::SelectCurveVMECallback (albaVME * vme) static protected
Callback for VME_CHOOSE that accepts polylines only.
CreatePolylineGraph()
albaPolylineGraph * albaOpMeshDeformation::CreatePolylineGraph (albaVME * vme) protected
Creates albaPolyLineGraph for the given vme.
CreateCopyOfPolylineGraph()
albaPolylineGraph * albaOpMeshDeformation::CreateCopyOfPolylineGraph (albaPolylineGraph * input) protected
Creates a deep copy of polylinegraph
Member Data Documentation
m_NumberOfCurves
int albaOpMeshDeformation::m_NumberOfCurves protected
Definition at line 398 of file albaOpMeshDeformation.h.
m_OriginalCurves
albaVME** albaOpMeshDeformation::m_OriginalCurves protected
Definition at line 399 of file albaOpMeshDeformation.h.
m_DeformedCurves
albaVME** albaOpMeshDeformation::m_DeformedCurves protected
Definition at line 400 of file albaOpMeshDeformation.h.
m_CurvesCorrespondence
vtkIdList** albaOpMeshDeformation::m_CurvesCorrespondence protected
Definition at line 401 of file albaOpMeshDeformation.h.
m_Dialog
albaGUIDialog* albaOpMeshDeformation::m_Dialog protected
Definition at line 405 of file albaOpMeshDeformation.h.
m_Rwi
albaRWI* albaOpMeshDeformation::m_Rwi protected
Definition at line 406 of file albaOpMeshDeformation.h.
m_Picker
mmiVTKPicker* albaOpMeshDeformation::m_Picker protected
Definition at line 407 of file albaOpMeshDeformation.h.
m_Spheres
vtkSphereSource* albaOpMeshDeformation::m_Spheres[2] protected
Definition at line 409 of file albaOpMeshDeformation.h.
m_SphereRadius
double albaOpMeshDeformation::m_SphereRadius[2] protected
Definition at line 410 of file albaOpMeshDeformation.h.
m_Meshes
MESH* albaOpMeshDeformation::m_Meshes[2] protected
Definition at line 412 of file albaOpMeshDeformation.h.
m_Curves
std::vector< CONTROL_CURVE* > albaOpMeshDeformation::m_Curves protected
Definition at line 413 of file albaOpMeshDeformation.h.
m_UndoStack
std::vector< UNDO_ITEM* > albaOpMeshDeformation::m_UndoStack protected
Definition at line 414 of file albaOpMeshDeformation.h.
m_SelectedCurve
CONTROL_CURVE* albaOpMeshDeformation::m_SelectedCurve protected
Definition at line 416 of file albaOpMeshDeformation.h.
m_SelectedObjType
int albaOpMeshDeformation::m_SelectedObjType protected
Definition at line 417 of file albaOpMeshDeformation.h.
m_SelectedObjId
int albaOpMeshDeformation::m_SelectedObjId protected
Definition at line 418 of file albaOpMeshDeformation.h.
m_SelPointGlyph
vtkSphereSource* albaOpMeshDeformation::m_SelPointGlyph protected
Definition at line 420 of file albaOpMeshDeformation.h.
m_SelPointActor
vtkActor* albaOpMeshDeformation::m_SelPointActor protected
Definition at line 421 of file albaOpMeshDeformation.h.
m_OCToAdd
albaVME* albaOpMeshDeformation::m_OCToAdd protected
Definition at line 423 of file albaOpMeshDeformation.h.
m_DCToAdd
albaVME* albaOpMeshDeformation::m_DCToAdd protected
Definition at line 424 of file albaOpMeshDeformation.h.
m_EditMode
int albaOpMeshDeformation::m_EditMode protected
Definition at line 426 of file albaOpMeshDeformation.h.
m_MeshesVisibility
int albaOpMeshDeformation::m_MeshesVisibility[2] protected
Definition at line 427 of file albaOpMeshDeformation.h.
m_CurvesVisibility
int albaOpMeshDeformation::m_CurvesVisibility[3] protected
Definition at line 428 of file albaOpMeshDeformation.h.
m_DeformationMode
int albaOpMeshDeformation::m_DeformationMode protected
Definition at line 430 of file albaOpMeshDeformation.h.
m_SaveODC
int albaOpMeshDeformation::m_SaveODC[2] protected
Definition at line 431 of file albaOpMeshDeformation.h.
m_BPointMoveActive
bool albaOpMeshDeformation::m_BPointMoveActive protected
Definition at line 433 of file albaOpMeshDeformation.h.
m_PointMoveCorrection
double albaOpMeshDeformation::m_PointMoveCorrection[3] protected
Definition at line 434 of file albaOpMeshDeformation.h.
m_BCorrespondenceActive
bool albaOpMeshDeformation::m_BCorrespondenceActive protected
Definition at line 436 of file albaOpMeshDeformation.h.
m_BDoNotCreateUndo
bool albaOpMeshDeformation::m_BDoNotCreateUndo protected
Definition at line 438 of file albaOpMeshDeformation.h.
m_BttnReset
wxButton* albaOpMeshDeformation::m_BttnReset protected
Definition at line 441 of file albaOpMeshDeformation.h.
m_BttnUndo
wxButton* albaOpMeshDeformation::m_BttnUndo protected
Definition at line 442 of file albaOpMeshDeformation.h.
m_BttnPreview
wxButton* albaOpMeshDeformation::m_BttnPreview protected
Definition at line 443 of file albaOpMeshDeformation.h.
m_OCNameCtrl
wxStaticText* albaOpMeshDeformation::m_OCNameCtrl protected
Definition at line 444 of file albaOpMeshDeformation.h.
m_DCNameCtrl
wxStaticText* albaOpMeshDeformation::m_DCNameCtrl protected
Definition at line 445 of file albaOpMeshDeformation.h.
m_BttnSelDC
wxButton* albaOpMeshDeformation::m_BttnSelDC protected
Definition at line 446 of file albaOpMeshDeformation.h.
m_CCCtrl
wxTextCtrl* albaOpMeshDeformation::m_CCCtrl protected
Definition at line 447 of file albaOpMeshDeformation.h.
m_BttnGenCurves
wxButton* albaOpMeshDeformation::m_BttnGenCurves protected
Definition at line 448 of file albaOpMeshDeformation.h.
m_BttnResetCurve
wxButton* albaOpMeshDeformation::m_BttnResetCurve protected
Definition at line 449 of file albaOpMeshDeformation.h.
m_BttnAddCurve
wxButton* albaOpMeshDeformation::m_BttnAddCurve protected
Definition at line 450 of file albaOpMeshDeformation.h.
m_EditModeHelp
wxTextCtrl* albaOpMeshDeformation::m_EditModeHelp protected
Definition at line 451 of file albaOpMeshDeformation.h.
m_EditModeInfo
wxStaticText* albaOpMeshDeformation::m_EditModeInfo protected
Definition at line 452 of file albaOpMeshDeformation.h.
m_ChckEditOC
wxCheckBox* albaOpMeshDeformation::m_ChckEditOC protected
Definition at line 453 of file albaOpMeshDeformation.h.
m_DeformationModeHelp
wxTextCtrl* albaOpMeshDeformation::m_DeformationModeHelp protected
Definition at line 454 of file albaOpMeshDeformation.h.
m_BttnOK
wxButton* albaOpMeshDeformation::m_BttnOK protected
Definition at line 456 of file albaOpMeshDeformation.h.
The documentation for this class was generated from the following file:
albaOpMeshDeformation.h