ALBA: albaMTime Class Reference
albaMTime Class Reference
#include <albaMTime.h>
Public Member Functions
albaMTime ()
virtual const char * GetTypeName ()
void Modified ()
unsigned long int GetMTime () const
int operator> (albaMTime &ts)
int operator< (albaMTime &ts)
operator unsigned long ()
Detailed Description
albaMTime - record modification timestamp.
albaMTime records a unique time stamp when the method Modified() is called. This time is guaranteed to be monotonically increasing. If ALBA is build with VTK compilation enabled (ALBA_USE_VTK) this object uses a vtkTimeStamp as counter to have a unique time stamp against the two libraries.
Todo:
fix the InterlockedIncrement - which was temporary commented out (sil)
Definition at line 37 of file albaMTime.h.
Constructor & Destructor Documentation
albaMTime()
albaMTime::albaMTime () inline
Definition at line 40 of file albaMTime.h.
Member Function Documentation
GetTypeName()
virtual const char * albaMTime::GetTypeName () inline virtual
Definition at line 44 of file albaMTime.h.
Modified()
void albaMTime::Modified ()
Update this object modification time.
The modification time is just a monotonically increasing unsigned long integer. It is possible for this number to wrap around back to zero. This should only happen for processes that have been running for a very long time, while constantly changing objects within the program. When this does occur, the typical consequence should be that some filters will update themselves when really they don't need to.
Referenced by albaTransformBase::Modified().
GetMTime()
unsigned long int albaMTime::GetMTime () const
Return this object's Modified time.
Referenced by operator<(), and operator>().
operator>()
int albaMTime::operator> (albaMTime & ts) inline
Support comparisons of time stamp objects directly.
Definition at line 61 of file albaMTime.h.
References GetMTime().
operator<()
int albaMTime::operator< (albaMTime & ts) inline
Definition at line 62 of file albaMTime.h.
References GetMTime().
operator unsigned long()
albaMTime::operator unsigned long () inline
Allow for typecasting to unsigned long.
Definition at line 65 of file albaMTime.h.
The documentation for this class was generated from the following file:
albaMTime.h