ALBA 2: albaMatrixVector Class Reference
albaMatrixVector Class Reference
#include <albaMatrixVector.h>
Public Types
typedef albaTimeMap< albaMatrix >::TimeMap::iterator Iterator
Public Types inherited from albaTimeMap< albaMatrix >
typedef std::map< albaTimeStamp, albaAutoPointer< albaMatrix > > TimeMap
typedef std::map< albaTimeStamp, albaAutoPointer< albaMatrix > > TimeMap
typedef std::pair< albaTimeStamp, albaAutoPointer< albaMatrix > > mmuTimePair
typedef std::pair< albaTimeStamp, albaAutoPointer< albaMatrix > > mmuTimePair
Public Member Functions
albaMatrixVector ()
virtual ~albaMatrixVector ()
albaTypeMacro (albaMatrixVector, albaObject)
void AppendKeyMatrix (const albaMatrix &m)
void AppendKeyMatrix (albaMatrix *m)
albaMatrix * GetKeyMatrix (int idx)
void GetKeyMatrixVector (std::vector< albaMatrix * > &mvector)
int GetNumberOfMatrices () const
albaMatrix * GetNearestMatrix (albaTimeStamp t)
albaMatrix * GetMatrixBefore (albaTimeStamp t)
albaMatrix * GetMatrix (albaTimeStamp t)
void SetMatrix (const albaMatrix &mat)
void SetMatrix (albaMatrix *mat)
Public Member Functions inherited from albaTimeMap< albaMatrix >
albaTimeMap ()
albaTimeMap (const albaTimeMap< albaMatrix > &)
albaTimeMap ()
albaTimeMap (const albaTimeMap< albaMatrix > &)
virtual ~albaTimeMap ()
virtual ~albaTimeMap ()
void operator= (const albaTimeMap< albaMatrix > &)
void operator= (const albaTimeMap< albaMatrix > &)
void SetItemTypeName (const char *tname)
void SetItemTypeName (const char *tname)
const char * GetItemTypeName ()
const char * GetItemTypeName ()
virtual void AppendItem (albaMatrix *m)
virtual void AppendItem (albaMatrix *m)
virtual void AppendAndSetItem (albaMatrix *m)
virtual void AppendAndSetItem (albaMatrix *m)
virtual void PrependItem (albaMatrix *m)
virtual void PrependItem (albaMatrix *m)
albaTimeMap< albaMatrix >::TimeMap::iterator FindItem (albaMatrix *m)
albaTimeMap< albaMatrix >::TimeMap::iterator FindItem (albaTimeStamp t)
albaTimeMap< albaMatrix >::TimeMap::iterator FindItem (albaMatrix *m)
albaTimeMap< albaMatrix >::TimeMap::iterator FindItem (albaTimeStamp t)
virtual void InsertItem (albaMatrix *m)
virtual void InsertItem (albaMatrix *m)
virtual void RemoveItem (typename albaTimeMap< albaMatrix >::TimeMap::iterator it)
int RemoveItem (int idx)
virtual void RemoveItem (typename albaTimeMap< albaMatrix >::TimeMap::iterator it)
int RemoveItem (int idx)
virtual void RemoveAllItems ()
virtual void RemoveAllItems ()
albaTimeStamp GetItemTime (int idx)
albaTimeStamp GetItemTime (int idx)
void GetTimeStamps (mmuTimeVector &kframes) const
void GetTimeStamps (mmuTimeVector &kframes) const
int GetNumberOfItems () const
int GetNumberOfItems () const
void GetTimeBounds (albaTimeStamp tbounds[2])
void GetTimeBounds (albaTimeStamp tbounds[2])
void DeepCopy (albaTimeMap *vitem)
void DeepCopy (albaTimeMap *vitem)
bool Equals (albaTimeMap *vmat)
bool Equals (albaTimeMap *vmat)
albaTimeMap< albaMatrix >::TimeMap::iterator FindNearestItem (albaTimeStamp t)
albaTimeMap< albaMatrix >::TimeMap::iterator FindNearestItem (albaTimeStamp t)
albaTimeMap< albaMatrix >::TimeMap::iterator FindItemBefore (albaTimeStamp t)
albaTimeMap< albaMatrix >::TimeMap::iterator FindItemBefore (albaTimeStamp t)
albaTimeMap< albaMatrix >::TimeMap::iterator FindItemByIndex (int idx)
albaTimeMap< albaMatrix >::TimeMap::iterator FindItemByIndex (int idx)
albaID FindItemIndex (albaTimeStamp t)
albaID FindItemIndex (albaTimeStamp t)
albaMatrix * GetItem (albaTimeStamp t)
albaMatrix * GetItem (albaTimeStamp t)
albaMatrix * GetNearestItem (albaTimeStamp t)
albaMatrix * GetNearestItem (albaTimeStamp t)
albaMatrix * GetItemBefore (albaTimeStamp t)
albaMatrix * GetItemBefore (albaTimeStamp t)
albaMatrix * GetItemByIndex (int idx)
albaMatrix * GetItemByIndex (int idx)
virtual void Print (std::ostream &os, const int tabs=0) const
virtual void Print (std::ostream &os, const int tabs=0) const
albaTimeMap< albaMatrix >::TimeMap::iterator Begin ()
albaTimeMap< albaMatrix >::TimeMap::iterator Begin ()
albaTimeMap< albaMatrix >::TimeMap::iterator End ()
albaTimeMap< albaMatrix >::TimeMap::iterator End ()
albaTimeMap< albaMatrix >::TimeMap::iterator Last ()
albaTimeMap< albaMatrix >::TimeMap::iterator Last ()
Public Member Functions inherited from albaObject
albaObject ()
virtual ~albaObject ()
virtual void Delete ()
virtual const char * GetTypeName () const
virtual bool IsA (const char *type_name) const
virtual bool IsA (const albaTypeID &type_id) const
virtual albaObject * NewObjectInstance () const =0
virtual const albaTypeID & GetTypeId () const
virtual void Print (std::ostream &os, const int indent=0) const
albaObject (const albaObject &c)
Public Member Functions inherited from albaTimeStamped
virtual void Modified ()
virtual unsigned long GetMTime ()
Public Member Functions inherited from albaStorable
albaStorable ()
int Store (albaStorageElement *element)
int Restore (albaStorageElement *element)
albaObject * CastToObject ()
bool IsStorable ()
Protected Member Functions
virtual int InternalStore (albaStorageElement *parent)
virtual int InternalRestore (albaStorageElement *node)
virtual int InternalStore (albaStorageElement *node)=0
virtual int InternalRestore (albaStorageElement *node)=0
Additional Inherited Members
Static Public Member Functions inherited from albaObject
static const char * GetStaticTypeName ()
static bool IsStaticType (const char *type_name)
static bool IsStaticType (const albaTypeID &type_id)
static const albaTypeID & GetStaticTypeId ()
static albaObject * SafeDownCast (albaObject *o)
Static Public Member Functions inherited from albaStorable
static albaStorable * SafeCastToObject (albaObject *o)
Protected Attributes inherited from albaTimeMap< albaMatrix >
TimeMap m_TimeMap
albaString m_ItemTypeName
Protected Attributes inherited from albaObject
bool m_HeapFlag
Protected Attributes inherited from albaTimeStamped
albaMTime m_MTime
Protected Attributes inherited from albaStorable
bool m_Storable
Detailed Description
a dynamic associative sorted vector of 4x4 matrices indexed by their "timestamp".
Todo:
Definition at line 39 of file albaMatrixVector.h.
Member Typedef Documentation
Iterator
typedef albaTimeMap<albaMatrix>::TimeMap::iterator albaMatrixVector::Iterator
Definition at line 42 of file albaMatrixVector.h.
Constructor & Destructor Documentation
albaMatrixVector()
albaMatrixVector::albaMatrixVector ()
~albaMatrixVector()
virtual albaMatrixVector::~albaMatrixVector () virtual
Member Function Documentation
albaTypeMacro()
albaMatrixVector::albaTypeMacro (albaMatrixVector , albaObject)
AppendKeyMatrix() [1/2]
void albaMatrixVector::AppendKeyMatrix (const albaMatrix & m)
Append a matrix to the vector setting its timestamp to the highest one + 1 The matrix content is copied and not referenced.
AppendKeyMatrix() [2/2]
void albaMatrixVector::AppendKeyMatrix (albaMatrix * m) inline
Append a matrix to the vector setting its timestamp to the highest one + 1 The matrix object is referenced and NOT copied.
same effect of AppendItem().
Definition at line 57 of file albaMatrixVector.h.
References albaTimeMap< T >::AppendItem().
GetKeyMatrix()
albaMatrix * albaMatrixVector::GetKeyMatrix (int idx) inline
Return a matrix in the vector, given its order index.
Return NULL if idx out of range. Beware this function take o(n) n=idx to return the matrix
Definition at line 62 of file albaMatrixVector.h.
References albaTimeMap< T >::GetItemByIndex().
GetKeyMatrixVector()
void albaMatrixVector::GetKeyMatrixVector (std::vector< albaMatrix * > & mvector)
return a vector of key matrices.
GetNumberOfMatrices()
int albaMatrixVector::GetNumberOfMatrices () const inline
Return the number of matrixes stored in this object.
Definition at line 68 of file albaMatrixVector.h.
References albaTimeMap< T >::GetNumberOfItems().
GetNearestMatrix()
albaMatrix * albaMatrixVector::GetNearestMatrix (albaTimeStamp t) inline
return the matrix with the timestamp nearest to t
Definition at line 71 of file albaMatrixVector.h.
References albaTimeMap< T >::GetNearestItem().
GetMatrixBefore()
albaMatrix * albaMatrixVector::GetMatrixBefore (albaTimeStamp t) inline
return the matrix with timestamp <=t
Definition at line 73 of file albaMatrixVector.h.
References albaTimeMap< T >::GetItemBefore().
GetMatrix()
albaMatrix * albaMatrixVector::GetMatrix (albaTimeStamp t) inline
return the matrix with the timestamp==t.
return NULL if not found.
Definition at line 75 of file albaMatrixVector.h.
References albaTimeMap< T >::GetItem().
SetMatrix() [1/2]
void albaMatrixVector::SetMatrix (const albaMatrix & mat)
Set the matrix for a specified time.
If no key-matrix with the same time exist a new key-matrix is created. If a key-matrix with the same time exist, simply overwrite the old 4x4 Matrix value. The matrix content is always copied and NOT referenced.
SetMatrix() [2/2]
void albaMatrixVector::SetMatrix (albaMatrix * mat) inline
Set the matrix for a specified time.
If no key-matrix with the same time exist a new key-matrix is created. If a key-matrix with the same time exist, simply overwrite the old 4x4 Matrix value. The given matrix object is referenced and not copied.
Definition at line 89 of file albaMatrixVector.h.
References albaTimeMap< T >::InsertItem().
InternalStore()
virtual int albaMatrixVector::InternalStore (albaStorageElement * node) protected virtual
This is called by Store() and must be reimplemented by subclasses.
The node element where the object should store itself is passed as argument.
Implements albaStorable.
InternalRestore()
virtual int albaMatrixVector::InternalRestore (albaStorageElement * node) protected virtual
This is called by Restore() and must be reimplemented by subclasses The element from which the object should restore itself is passed as argument.
Implements albaStorable.
The documentation for this class was generated from the following file:
albaMatrixVector.h