ALBA: albaGizmoPolylineGraph Class Reference
albaGizmoPolylineGraph Class Reference
#include <albaGizmoPolylineGraph.h>
Public Member Functions
virtual void Delete ()
void SetConstraintPolylineGraph (albaVMEPolylineGraph *constraintPolylineGraph)
virtual void SetCurvilinearAbscissa (vtkIdType branchId, double s)
double GetCurvilinearAbscissa ()
vtkIdType GetActiveBranchId ()
virtual void SetGizmoLength (double lineLength)
virtual void Show (bool show)
void OnEvent (albaEventBase *alba_event)
void SetInput (albaVME *vme)
virtual void SetColor (double col[3])
albaVMEGizmo * GetOutput ()
Public Member Functions inherited from albaGizmoInterface
void SetName (albaString name)
albaString GetName ()
virtual void SetInput (albaVME *vme)
albaVME * GetInput ()
void SetMediator (albaObserver *mediator)
albaObserver * GetMediator ()
void SetAutoscale (bool autoscale)
bool GetAutoscale ()
void SetRenderWindowHeightPercentage (double percentage)
double GetRenderWindowHeightPercentage ()
void SetAlwaysVisible (bool alwaysVisible)
bool GetAlwaysVisible ()
void SetListener (albaObserver *listener)
albaObserver * GetListener ()
virtual void OnEvent (albaEventBase *alba_event)
virtual void Show (bool show)
void SetModalityToLocal ()
void SetModalityToGlobal ()
int GetModality ()
virtual void SetAbsPose (albaMatrix *absPose)
virtual albaMatrix * GetAbsPose ()
virtual albaGUI * GetGui ()
Public Member Functions inherited from albaObserver
albaObserver ()
virtual ~albaObserver ()
virtual void OnEvent (albaEventBase *e)=0
Static Public Member Functions
static albaGizmoPolylineGraph * New (albaVME *inputVme, albaObserver *Listener=NULL, const char *name="GizmoPath", bool showOnlyDirectionAxis=false, bool testMode=false)
Protected Types
enum CONSTRAINT_MODALITY_ID { FREE = 0 , BOUNDS , SNAP_VERTEX , CONSTRAINT_MODALITY_NUMBERS }
Protected Member Functions
albaGizmoPolylineGraph (albaVME *inputVme, albaObserver *Listener=NULL, const char *name="GizmoPath", bool showOnlyDirectionAxis=false, bool testMode=false)
virtual void InternalInitInstance ()
virtual void InternalRelease ()
virtual void CreateVMEGizmo ()
virtual void DestroyVMEGizmo ()
virtual void CreateGizmoVTKData ()
virtual void DestroyGizmoVTKData ()
virtual void CreateInteractor ()
virtual void DestroyInteractor ()
virtual void OnTransform (albaEvent *e)
void LogTransformEvent (albaEvent *e)
Protected Member Functions inherited from albaGizmoInterface
albaGizmoInterface ()
virtual ~albaGizmoInterface ()
void SendTransformMatrix (albaMatrix *matrix, int eventId, long arg)
virtual void OnEventGizmoGui (albaEventBase *alba_event)
virtual void OnEventGizmoComponents (albaEventBase *alba_event)
Protected Attributes
albaString m_Name
albaVMEGizmo * m_VmeGizmo
albaInteractorCompositorMouse * m_GizmoInteractor
albaInteractorGenericMouse * m_LeftMouseInteractor
vtkSphereSource * m_SphereSource
vtkArrowSource * m_AxisSource [3]
vtkTransformPolyDataFilter * m_Axis [3]
vtkPlaneSource * m_PlaneSource
vtkAppendPolyData * m_AppendPolyData
bool m_ShowOnlyDirectionAxis
bool m_TestMode
albaCurvilinearAbscissaOnSkeletonHelper * m_CurvilinearAbscissaHelper
Protected Attributes inherited from albaGizmoInterface
albaObserver * m_Mediator
albaString m_Name
albaVME * m_InputVME
int m_Modality
albaObserver * m_Listener
albaVME * m_RefSysVME
bool m_Visibility
double m_RenderWindowHeightPercentage
bool m_AlwaysVisible
bool m_Autoscale
Additional Inherited Members
Public Types inherited from albaGizmoInterface
enum MODALITY { G_LOCAL = 0 , G_GLOBAL }
Detailed Description
Gizmo Helper Object for interaction stuff debug: this class should be expanded and refactored incrementally to ease interaction stuff debug.
See also albaOpInteractionDebugger
Definition at line 53 of file albaGizmoPolylineGraph.h.
Member Enumeration Documentation
CONSTRAINT_MODALITY_ID
enum albaGizmoPolylineGraph::CONSTRAINT_MODALITY_ID protected
Enumerator
FREE
BOUNDS
SNAP_VERTEX
CONSTRAINT_MODALITY_NUMBERS
Definition at line 160 of file albaGizmoPolylineGraph.h.
Constructor & Destructor Documentation
albaGizmoPolylineGraph()
albaGizmoPolylineGraph::albaGizmoPolylineGraph (albaVME * inputVme, albaObserver * Listener = NULL, const char * name = "GizmoPath", bool showOnlyDirectionAxis = false, bool testMode = false) protected
Member Function Documentation
New()
static albaGizmoPolylineGraph * albaGizmoPolylineGraph::New (albaVME * inputVme, albaObserver * Listener = NULL, const char * name = "GizmoPath", bool showOnlyDirectionAxis = false, bool testMode = false) inline static
The only way to construct correctly the instance.
Definition at line 57 of file albaGizmoPolylineGraph.h.
References InternalInitInstance().
Delete()
virtual void albaGizmoPolylineGraph::Delete () inline virtual
The only way to destruct correctly the instance.
Definition at line 66 of file albaGizmoPolylineGraph.h.
InternalInitInstance()
virtual void albaGizmoPolylineGraph::InternalInitInstance () protected virtual
Initializes the object.
May not be called twice (unless Done method was called).
Referenced by New().
InternalRelease()
virtual void albaGizmoPolylineGraph::InternalRelease () protected virtual
Finalizes the object.
May not be called twice (unless Init method was called).
SetConstraintPolylineGraph()
void albaGizmoPolylineGraph::SetConstraintPolylineGraph (albaVMEPolylineGraph * constraintPolylineGraph) inline
Set the constraint polyline graph.
Definition at line 172 of file albaGizmoPolylineGraph.h.
References m_CurvilinearAbscissaHelper, and albaCurvilinearAbscissaOnSkeletonHelper::SetConstraintPolylineGraph().
SetCurvilinearAbscissa()
void albaGizmoPolylineGraph::SetCurvilinearAbscissa (vtkIdType branchId, double s) inline virtual
Set curvilinear abscissa along given constraint skeleton branch.
Definition at line 193 of file albaGizmoPolylineGraph.h.
References m_CurvilinearAbscissaHelper, and albaCurvilinearAbscissaOnSkeletonHelper::SetCurvilinearAbscissa().
GetCurvilinearAbscissa()
double albaGizmoPolylineGraph::GetCurvilinearAbscissa () inline
Get curvilinear abscissa along given constraint skeleton branch.
Definition at line 186 of file albaGizmoPolylineGraph.h.
References albaCurvilinearAbscissaOnSkeletonHelper::GetCurvilinearAbscissa(), and m_CurvilinearAbscissaHelper.
GetActiveBranchId()
vtkIdType albaGizmoPolylineGraph::GetActiveBranchId () inline
Get the active branch ie the branch to which gizmo is currently constrained.
Definition at line 179 of file albaGizmoPolylineGraph.h.
References albaCurvilinearAbscissaOnSkeletonHelper::GetActiveBranchId(), and m_CurvilinearAbscissaHelper.
SetGizmoLength()
virtual void albaGizmoPolylineGraph::SetGizmoLength (double lineLength) virtual
Set the length of the gizmo.
Show()
virtual void albaGizmoPolylineGraph::Show (bool show) virtual
Show/Hide the gizmos using actor visibility instead of pipe creation/destruction: this is used for faster rendering.
Reimplemented from albaGizmoInterface.
OnEvent()
void albaGizmoPolylineGraph::OnEvent (albaEventBase * alba_event) virtual
Events handling method.
Reimplemented from albaGizmoInterface.
SetInput()
void albaGizmoPolylineGraph::SetInput (albaVME * vme) inline virtual
Not used since this gizmo is not moving anything.
Reimplemented from albaGizmoInterface.
Definition at line 108 of file albaGizmoPolylineGraph.h.
SetColor()
virtual void albaGizmoPolylineGraph::SetColor (double col[3]) virtual
Set the gizmo color.
GetOutput()
albaVMEGizmo * albaGizmoPolylineGraph::GetOutput () inline
Definition at line 113 of file albaGizmoPolylineGraph.h.
CreateVMEGizmo()
virtual void albaGizmoPolylineGraph::CreateVMEGizmo () protected virtual
Creates the gizmo.
Called from Init.
DestroyVMEGizmo()
virtual void albaGizmoPolylineGraph::DestroyVMEGizmo () protected virtual
Destroys the gizmo.
Called from Done.
CreateGizmoVTKData()
virtual void albaGizmoPolylineGraph::CreateGizmoVTKData () protected virtual
Creates VTK pipeline for the gizmo.
Called from CreateVMEGizmo.
DestroyGizmoVTKData()
virtual void albaGizmoPolylineGraph::DestroyGizmoVTKData () protected virtual
Destroys VTK pipeline for the gizmo.
Called from DestroyVMEGizmo.
CreateInteractor()
virtual void albaGizmoPolylineGraph::CreateInteractor () protected virtual
Creates the interactor for the gizmo.
Called from Init.
DestroyInteractor()
virtual void albaGizmoPolylineGraph::DestroyInteractor () protected virtual
Destroys the interactor of the gizmo.
Called from Done.
OnTransform()
virtual void albaGizmoPolylineGraph::OnTransform (albaEvent * e) protected virtual
Handles ID_TRANSFORM event.
LogTransformEvent()
void albaGizmoPolylineGraph::LogTransformEvent (albaEvent * e) protected
Member Data Documentation
m_Name
albaString albaGizmoPolylineGraph::m_Name protected
Definition at line 141 of file albaGizmoPolylineGraph.h.
m_VmeGizmo
albaVMEGizmo* albaGizmoPolylineGraph::m_VmeGizmo protected
Definition at line 142 of file albaGizmoPolylineGraph.h.
m_GizmoInteractor
albaInteractorCompositorMouse* albaGizmoPolylineGraph::m_GizmoInteractor protected
Definition at line 144 of file albaGizmoPolylineGraph.h.
m_LeftMouseInteractor
albaInteractorGenericMouse* albaGizmoPolylineGraph::m_LeftMouseInteractor protected
Definition at line 145 of file albaGizmoPolylineGraph.h.
m_SphereSource
vtkSphereSource* albaGizmoPolylineGraph::m_SphereSource protected
Definition at line 147 of file albaGizmoPolylineGraph.h.
m_AxisSource
vtkArrowSource* albaGizmoPolylineGraph::m_AxisSource[3] protected
Definition at line 148 of file albaGizmoPolylineGraph.h.
m_Axis
vtkTransformPolyDataFilter* albaGizmoPolylineGraph::m_Axis[3] protected
Definition at line 149 of file albaGizmoPolylineGraph.h.
m_PlaneSource
vtkPlaneSource* albaGizmoPolylineGraph::m_PlaneSource protected
Definition at line 151 of file albaGizmoPolylineGraph.h.
m_AppendPolyData
vtkAppendPolyData* albaGizmoPolylineGraph::m_AppendPolyData protected
Definition at line 152 of file albaGizmoPolylineGraph.h.
m_ShowOnlyDirectionAxis
bool albaGizmoPolylineGraph::m_ShowOnlyDirectionAxis protected
Definition at line 154 of file albaGizmoPolylineGraph.h.
m_TestMode
bool albaGizmoPolylineGraph::m_TestMode protected
Definition at line 155 of file albaGizmoPolylineGraph.h.
m_CurvilinearAbscissaHelper
albaCurvilinearAbscissaOnSkeletonHelper* albaGizmoPolylineGraph::m_CurvilinearAbscissaHelper protected
Definition at line 158 of file albaGizmoPolylineGraph.h.
Referenced by GetActiveBranchId(), GetCurvilinearAbscissa(), SetConstraintPolylineGraph(), and SetCurvilinearAbscissa().
The documentation for this class was generated from the following file:
albaGizmoPolylineGraph.h