ALBA 2: albaOpMMLContourWidget Class Reference
albaOpMMLContourWidget Class Reference
#include <albaOpMMLContourWidget.h>
Public Member Functions
void SetPH (albaOpMMLParameterView *PH)
void SetPV (albaOpMMLParameterView *PV)
void SetTH (albaOpMMLParameterView *TH)
void SetTV (albaOpMMLParameterView *TV)
void SetRA (albaOpMMLParameterView *RA)
void SetSN (albaOpMMLParameterView *SN)
void SetSS (albaOpMMLParameterView *SS)
void SetSE (albaOpMMLParameterView *SE)
void SetSW (albaOpMMLParameterView *SW)
void SetModel (albaOpMMLModelView *Model)
void SetNextOperationId (int n)
int GetNextOperationId ()
void SetRotationHandleVisibility ()
void RotationHandleOff ()
void RotationHandleOn ()
void UpdateScalingHandles ()
void UpdateRotationHandle ()
void UpdateWidgetTransform ()
void ComputeCenter (double *c)
void ComputeBounds (double b[6])
void Place (double *p1, double *p2)
void ScaleWest (double *p1, double *p2)
void ScaleEast (double *p1, double *p2)
void ScaleNorth (double *p1, double *p2)
void ScaleSouth (double *p1, double *p2)
float GetHandleRadius ()
void SetHandleRadius (float r)
vtkActor * GetWestScalingHandleActor ()
vtkActor * GetEastScalingHandleActor ()
vtkActor * GetSouthScalingHandleActor ()
vtkActor * GetNorthScalingHandleActor ()
vtkActor * GetRotationalHandleActor ()
vtkActor * GetCenterHandleActor ()
void SetCenterHandle (double *xyz)
void SetCenterHandle (double x, double y, double z)
void CenterModeOff ()
void CenterModeOn ()
BOOL GetCenterMode ()
void PositionHandles (float X, float Y)
void ScalingHandlesOff ()
void ScalingHandlesOn ()
void SetRotationalHandle (double *xyz)
void SetRotationalHandle (double x, double y, double z)
BOOL GetScalingMode ()
BOOL GetRotationMode ()
BOOL GetTranslationMode ()
void SetHandle3 (double x, double y, double z)
void SetHandle2 (double x, double y, double z)
void SetHandle1 (double x, double y, double z)
void SetHandle0 (double x, double y, double z)
void SetHandle3 (double *xyz)
void SetHandle2 (double *xyz)
void SetHandle1 (double *xyz)
void SetHandle0 (double *xyz)
void ScalingModeOff ()
void ScalingModeOn ()
void RotationModeOff ()
void RotationModeOn ()
void TranslationModeOff ()
void TranslationModeOn ()
vtkTypeRevisionMacro (albaOpMMLContourWidget, vtkPolyDataSourceWidget)
void PrintSelf (ostream &os, vtkIndent indent)
virtual void SetEnabled (int)
virtual void PlaceWidget (double bounds[6])
void PlaceWidget ()
void SetResolution (int r)
int GetResolution ()
void SetOrigin (double x, double y, double z)
void SetOrigin (double x[3])
double * GetOrigin ()
void GetOrigin (double xyz[3])
void SetPoint1 (double x, double y, double z)
void SetPoint1 (double x[3])
double * GetPoint1 ()
void GetPoint1 (double xyz[3])
void SetPoint2 (double x, double y, double z)
void SetPoint2 (double x[3])
double * GetPoint2 ()
void GetPoint2 (double xyz[3])
void SetCenter (double x, double y, double z)
void SetCenter (double x[3])
double * GetCenter ()
void GetCenter (double xyz[3])
void SetNormal (double x, double y, double z)
void SetNormal (double x[3])
double * GetNormal ()
void GetNormal (double xyz[3])
void SetMotionVector (float x, float y, float z)
void SetMotionVector (float m[3])
float * GetMotionVector ()
void GetMotionVector (float xyz[3])
virtual void SetRepresentation (int representation)
virtual int GetRepresentationMinValue ()
virtual int GetRepresentationMaxValue ()
virtual int GetRepresentation ()
void SetRepresentationToOff ()
void SetRepresentationToOutline ()
void SetRepresentationToWireframe ()
void SetRepresentationToSurface ()
void GetPolyData (vtkPolyData *pd)
void GetPlane (vtkPlane *plane)
vtkPolyDataSource * GetPolyDataSource ()
void UpdatePlacement (void)
virtual void Setm_PlaneProperty (vtkProperty *)
virtual vtkProperty * GetPlaneProperty ()
virtual vtkProperty * GetSelectedPlaneProperty ()
Static Public Member Functions
static albaOpMMLContourWidget * New ()
Public Attributes
int m_OperationID
float m_HandleRadius
vtkPlaneSource * m_PlaneSource
BOOL m_BRotatingMode
BOOL m_BScalingMode
BOOL m_BTranslatingMode
BOOL m_BCenterMode
float m_Bounds [6]
albaOpMMLModelView * m_M
albaOpMMLParameterView * m_CH
albaOpMMLParameterView * m_CV
albaOpMMLParameterView * m_T
albaOpMMLParameterView * m_H
albaOpMMLParameterView * m_V
albaOpMMLParameterView * m_N
albaOpMMLParameterView * m_S
albaOpMMLParameterView * m_E
albaOpMMLParameterView * m_W
Protected Types
enum WidgetOperation {
Placement , Translation , Rotation , NorthScale ,
SouthScale , EastScale , WestScale
}
enum WidgetState {
Start =0 , Moving , Scaling , Pushing ,
Rotating , Centralising , Outside
}
Protected Member Functions
albaOpMMLContourWidget ()
~albaOpMMLContourWidget ()
void OnLeftButtonDown ()
void OnLeftButtonUp ()
void OnMiddleButtonDown ()
void OnMiddleButtonUp ()
void OnRightButtonDown ()
void OnRightButtonUp ()
void OnMouseMove ()
void SelectRepresentation ()
void HighlightPlane (int highlight)
void HandlesOn (double length)
void HandlesOff ()
int HighlightHandle (vtkProp *prop)
virtual void SizeHandles ()
void HighlightNormal (int highlight)
void Rotate (double *p1, double *p2)
void Scale (double *p1, double *p2, int X, int Y)
void Translate (double *p1, double *p2)
void Push (double *p1, double *p2)
void CreateDefaultProperties ()
void GeneratePlane ()
Static Protected Member Functions
static void ProcessEvents (vtkObject *object, unsigned long event, void *clientdata, void *calldata)
Protected Attributes
int m_Operation
int m_State
float m_Motion [3]
int m_NormalToXAxis
int m_NormalToYAxis
int m_NormalToZAxis
int m_Representation
vtkActor * m_PlaneActor
vtkPolyDataMapper * m_PlaneMapper
vtkTubeFilter * m_PlaneOutlineTubes
vtkPolyData * m_PlaneOutline
vtkActor ** m_Handle
vtkPolyDataMapper ** m_HandleMapper
vtkSphereSource ** m_HandleGeometry
vtkActor * m_RotationalHandle
vtkPolyDataMapper * m_RotationalHandleMapper
vtkSphereSource * m_RotationalHandleGeometry
vtkActor * m_CenterHandle
vtkPolyDataMapper * m_CenterHandleMapper
vtkSphereSource * m_CenterHandleGeometry
vtkActor * m_ConeActor
vtkPolyDataMapper * m_ConeMapper
vtkConeSource * m_ConeSource
vtkActor * m_LineActor
vtkPolyDataMapper * m_LineMapper
vtkLineSource * m_LineSource
vtkActor * m_ConeActor2
vtkPolyDataMapper * m_ConeMapper2
vtkConeSource * m_ConeSource2
vtkActor * m_LineActor2
vtkPolyDataMapper * m_LineMapper2
vtkLineSource * m_LineSource2
vtkCellPicker * m_HandlePicker
vtkCellPicker * m_PlanePicker
vtkActor * m_CurrentHandle
float m_Normal [3]
vtkTransform * m_Transform
vtkProperty * m_HandleProperty
vtkProperty * m_SelectedHandleProperty
vtkProperty * m_PlaneProperty
vtkProperty * m_SelectedPlaneProperty
Detailed Description
Definition at line 55 of file albaOpMMLContourWidget.h.
Member Enumeration Documentation
WidgetOperation
enum albaOpMMLContourWidget::WidgetOperation protected
Enumerator
Placement
Translation
Rotation
NorthScale
SouthScale
EastScale
WestScale
Definition at line 295 of file albaOpMMLContourWidget.h.
WidgetState
enum albaOpMMLContourWidget::WidgetState protected
Enumerator
Start
Moving
Scaling
Pushing
Rotating
Centralising
Outside
Definition at line 309 of file albaOpMMLContourWidget.h.
Constructor & Destructor Documentation
albaOpMMLContourWidget()
albaOpMMLContourWidget::albaOpMMLContourWidget () protected
~albaOpMMLContourWidget()
albaOpMMLContourWidget::~albaOpMMLContourWidget () protected
Member Function Documentation
SetPH()
void albaOpMMLContourWidget::SetPH (albaOpMMLParameterView * PH)
SetPV()
void albaOpMMLContourWidget::SetPV (albaOpMMLParameterView * PV)
SetTH()
void albaOpMMLContourWidget::SetTH (albaOpMMLParameterView * TH)
SetTV()
void albaOpMMLContourWidget::SetTV (albaOpMMLParameterView * TV)
SetRA()
void albaOpMMLContourWidget::SetRA (albaOpMMLParameterView * RA)
SetSN()
void albaOpMMLContourWidget::SetSN (albaOpMMLParameterView * SN)
SetSS()
void albaOpMMLContourWidget::SetSS (albaOpMMLParameterView * SS)
SetSE()
void albaOpMMLContourWidget::SetSE (albaOpMMLParameterView * SE)
SetSW()
void albaOpMMLContourWidget::SetSW (albaOpMMLParameterView * SW)
SetModel()
void albaOpMMLContourWidget::SetModel (albaOpMMLModelView * Model)
SetNextOperationId()
void albaOpMMLContourWidget::SetNextOperationId (int n)
GetNextOperationId()
int albaOpMMLContourWidget::GetNextOperationId ()
SetRotationHandleVisibility()
void albaOpMMLContourWidget::SetRotationHandleVisibility ()
RotationHandleOff()
void albaOpMMLContourWidget::RotationHandleOff ()
RotationHandleOn()
void albaOpMMLContourWidget::RotationHandleOn ()
UpdateScalingHandles()
void albaOpMMLContourWidget::UpdateScalingHandles ()
UpdateRotationHandle()
void albaOpMMLContourWidget::UpdateRotationHandle ()
UpdateWidgetTransform()
void albaOpMMLContourWidget::UpdateWidgetTransform ()
ComputeCenter()
void albaOpMMLContourWidget::ComputeCenter (double * c)
ComputeBounds()
void albaOpMMLContourWidget::ComputeBounds (double b[6])
Place()
void albaOpMMLContourWidget::Place (double * p1, double * p2)
ScaleWest()
void albaOpMMLContourWidget::ScaleWest (double * p1, double * p2)
ScaleEast()
void albaOpMMLContourWidget::ScaleEast (double * p1, double * p2)
ScaleNorth()
void albaOpMMLContourWidget::ScaleNorth (double * p1, double * p2)
ScaleSouth()
void albaOpMMLContourWidget::ScaleSouth (double * p1, double * p2)
GetHandleRadius()
float albaOpMMLContourWidget::GetHandleRadius ()
SetHandleRadius()
void albaOpMMLContourWidget::SetHandleRadius (float r)
GetWestScalingHandleActor()
vtkActor * albaOpMMLContourWidget::GetWestScalingHandleActor ()
GetEastScalingHandleActor()
vtkActor * albaOpMMLContourWidget::GetEastScalingHandleActor ()
GetSouthScalingHandleActor()
vtkActor * albaOpMMLContourWidget::GetSouthScalingHandleActor ()
GetNorthScalingHandleActor()
vtkActor * albaOpMMLContourWidget::GetNorthScalingHandleActor ()
GetRotationalHandleActor()
vtkActor * albaOpMMLContourWidget::GetRotationalHandleActor ()
GetCenterHandleActor()
vtkActor * albaOpMMLContourWidget::GetCenterHandleActor ()
SetCenterHandle() [1/2]
void albaOpMMLContourWidget::SetCenterHandle (double * xyz)
SetCenterHandle() [2/2]
void albaOpMMLContourWidget::SetCenterHandle (double x, double y, double z)
CenterModeOff()
void albaOpMMLContourWidget::CenterModeOff ()
CenterModeOn()
void albaOpMMLContourWidget::CenterModeOn ()
GetCenterMode()
BOOL albaOpMMLContourWidget::GetCenterMode ()
PositionHandles()
void albaOpMMLContourWidget::PositionHandles (float X, float Y)
ScalingHandlesOff()
void albaOpMMLContourWidget::ScalingHandlesOff ()
ScalingHandlesOn()
void albaOpMMLContourWidget::ScalingHandlesOn ()
SetRotationalHandle() [1/2]
void albaOpMMLContourWidget::SetRotationalHandle (double * xyz)
SetRotationalHandle() [2/2]
void albaOpMMLContourWidget::SetRotationalHandle (double x, double y, double z)
GetScalingMode()
BOOL albaOpMMLContourWidget::GetScalingMode ()
GetRotationMode()
BOOL albaOpMMLContourWidget::GetRotationMode ()
GetTranslationMode()
BOOL albaOpMMLContourWidget::GetTranslationMode ()
SetHandle3() [1/2]
void albaOpMMLContourWidget::SetHandle3 (double x, double y, double z)
SetHandle2() [1/2]
void albaOpMMLContourWidget::SetHandle2 (double x, double y, double z)
SetHandle1() [1/2]
void albaOpMMLContourWidget::SetHandle1 (double x, double y, double z)
SetHandle0() [1/2]
void albaOpMMLContourWidget::SetHandle0 (double x, double y, double z)
SetHandle3() [2/2]
void albaOpMMLContourWidget::SetHandle3 (double * xyz)
SetHandle2() [2/2]
void albaOpMMLContourWidget::SetHandle2 (double * xyz)
SetHandle1() [2/2]
void albaOpMMLContourWidget::SetHandle1 (double * xyz)
SetHandle0() [2/2]
void albaOpMMLContourWidget::SetHandle0 (double * xyz)
ScalingModeOff()
void albaOpMMLContourWidget::ScalingModeOff ()
ScalingModeOn()
void albaOpMMLContourWidget::ScalingModeOn ()
RotationModeOff()
void albaOpMMLContourWidget::RotationModeOff ()
RotationModeOn()
void albaOpMMLContourWidget::RotationModeOn ()
TranslationModeOff()
void albaOpMMLContourWidget::TranslationModeOff ()
TranslationModeOn()
void albaOpMMLContourWidget::TranslationModeOn ()
New()
static albaOpMMLContourWidget * albaOpMMLContourWidget::New () static
vtkTypeRevisionMacro()
albaOpMMLContourWidget::vtkTypeRevisionMacro (albaOpMMLContourWidget , vtkPolyDataSourceWidget)
PrintSelf()
void albaOpMMLContourWidget::PrintSelf (ostream & os, vtkIndent indent)
SetEnabled()
virtual void albaOpMMLContourWidget::SetEnabled (int) virtual
PlaceWidget() [1/2]
virtual void albaOpMMLContourWidget::PlaceWidget (double bounds[6]) virtual
PlaceWidget() [2/2]
void albaOpMMLContourWidget::PlaceWidget () inline
Definition at line 138 of file albaOpMMLContourWidget.h.
SetResolution()
void albaOpMMLContourWidget::SetResolution (int r)
GetResolution()
int albaOpMMLContourWidget::GetResolution ()
SetOrigin() [1/2]
void albaOpMMLContourWidget::SetOrigin (double x, double y, double z)
SetOrigin() [2/2]
void albaOpMMLContourWidget::SetOrigin (double x[3])
GetOrigin() [1/2]
double * albaOpMMLContourWidget::GetOrigin ()
GetOrigin() [2/2]
void albaOpMMLContourWidget::GetOrigin (double xyz[3])
SetPoint1() [1/2]
void albaOpMMLContourWidget::SetPoint1 (double x, double y, double z)
SetPoint1() [2/2]
void albaOpMMLContourWidget::SetPoint1 (double x[3])
GetPoint1() [1/2]
double * albaOpMMLContourWidget::GetPoint1 ()
GetPoint1() [2/2]
void albaOpMMLContourWidget::GetPoint1 (double xyz[3])
SetPoint2() [1/2]
void albaOpMMLContourWidget::SetPoint2 (double x, double y, double z)
SetPoint2() [2/2]
void albaOpMMLContourWidget::SetPoint2 (double x[3])
GetPoint2() [1/2]
double * albaOpMMLContourWidget::GetPoint2 ()
GetPoint2() [2/2]
void albaOpMMLContourWidget::GetPoint2 (double xyz[3])
SetCenter() [1/2]
void albaOpMMLContourWidget::SetCenter (double x, double y, double z)
SetCenter() [2/2]
void albaOpMMLContourWidget::SetCenter (double x[3])
GetCenter() [1/2]
double * albaOpMMLContourWidget::GetCenter ()
GetCenter() [2/2]
void albaOpMMLContourWidget::GetCenter (double xyz[3])
SetNormal() [1/2]
void albaOpMMLContourWidget::SetNormal (double x, double y, double z)
SetNormal() [2/2]
void albaOpMMLContourWidget::SetNormal (double x[3])
GetNormal() [1/2]
double * albaOpMMLContourWidget::GetNormal ()
GetNormal() [2/2]
void albaOpMMLContourWidget::GetNormal (double xyz[3])
SetMotionVector() [1/2]
void albaOpMMLContourWidget::SetMotionVector (float x, float y, float z)
SetMotionVector() [2/2]
void albaOpMMLContourWidget::SetMotionVector (float m[3])
GetMotionVector() [1/2]
float * albaOpMMLContourWidget::GetMotionVector ()
GetMotionVector() [2/2]
void albaOpMMLContourWidget::GetMotionVector (float xyz[3])
SetRepresentation()
virtual void albaOpMMLContourWidget::SetRepresentation (int representation) virtual
Referenced by SetRepresentationToOff(), SetRepresentationToOutline(), SetRepresentationToSurface(), and SetRepresentationToWireframe().
GetRepresentationMinValue()
virtual int albaOpMMLContourWidget::GetRepresentationMinValue () inline virtual
Definition at line 201 of file albaOpMMLContourWidget.h.
References VTK_PLANE_OFF.
GetRepresentationMaxValue()
virtual int albaOpMMLContourWidget::GetRepresentationMaxValue () inline virtual
Definition at line 202 of file albaOpMMLContourWidget.h.
References VTK_PLANE_SURFACE.
GetRepresentation()
virtual int albaOpMMLContourWidget::GetRepresentation () inline virtual
Definition at line 203 of file albaOpMMLContourWidget.h.
References m_Representation.
SetRepresentationToOff()
void albaOpMMLContourWidget::SetRepresentationToOff () inline
Definition at line 205 of file albaOpMMLContourWidget.h.
References SetRepresentation(), and VTK_PLANE_OFF.
SetRepresentationToOutline()
void albaOpMMLContourWidget::SetRepresentationToOutline () inline
Definition at line 207 of file albaOpMMLContourWidget.h.
References SetRepresentation(), and VTK_PLANE_OUTLINE.
SetRepresentationToWireframe()
void albaOpMMLContourWidget::SetRepresentationToWireframe () inline
Definition at line 209 of file albaOpMMLContourWidget.h.
References SetRepresentation(), and VTK_PLANE_WIREFRAME.
SetRepresentationToSurface()
void albaOpMMLContourWidget::SetRepresentationToSurface () inline
Definition at line 211 of file albaOpMMLContourWidget.h.
References SetRepresentation(), and VTK_PLANE_SURFACE.
GetPolyData()
void albaOpMMLContourWidget::GetPolyData (vtkPolyData * pd)
GetPlane()
void albaOpMMLContourWidget::GetPlane (vtkPlane * plane)
GetPolyDataSource()
vtkPolyDataSource * albaOpMMLContourWidget::GetPolyDataSource ()
UpdatePlacement()
void albaOpMMLContourWidget::UpdatePlacement (void)
Setm_PlaneProperty()
virtual void albaOpMMLContourWidget::Setm_PlaneProperty (vtkProperty *) virtual
GetPlaneProperty()
virtual vtkProperty * albaOpMMLContourWidget::GetPlaneProperty () inline virtual
Definition at line 270 of file albaOpMMLContourWidget.h.
References m_PlaneProperty.
GetSelectedPlaneProperty()
virtual vtkProperty * albaOpMMLContourWidget::GetSelectedPlaneProperty () inline virtual
Definition at line 271 of file albaOpMMLContourWidget.h.
References m_SelectedPlaneProperty.
ProcessEvents()
static void albaOpMMLContourWidget::ProcessEvents (vtkObject * object, unsigned long event, void * clientdata, void * calldata) static protected
OnLeftButtonDown()
void albaOpMMLContourWidget::OnLeftButtonDown () protected
OnLeftButtonUp()
void albaOpMMLContourWidget::OnLeftButtonUp () protected
OnMiddleButtonDown()
void albaOpMMLContourWidget::OnMiddleButtonDown () protected
OnMiddleButtonUp()
void albaOpMMLContourWidget::OnMiddleButtonUp () protected
OnRightButtonDown()
void albaOpMMLContourWidget::OnRightButtonDown () protected
OnRightButtonUp()
void albaOpMMLContourWidget::OnRightButtonUp () protected
OnMouseMove()
void albaOpMMLContourWidget::OnMouseMove () protected
SelectRepresentation()
void albaOpMMLContourWidget::SelectRepresentation () protected
HighlightPlane()
void albaOpMMLContourWidget::HighlightPlane (int highlight) protected
HandlesOn()
void albaOpMMLContourWidget::HandlesOn (double length) protected
HandlesOff()
void albaOpMMLContourWidget::HandlesOff () protected
HighlightHandle()
int albaOpMMLContourWidget::HighlightHandle (vtkProp * prop) protected
SizeHandles()
virtual void albaOpMMLContourWidget::SizeHandles () protected virtual
HighlightNormal()
void albaOpMMLContourWidget::HighlightNormal (int highlight) protected
Rotate()
void albaOpMMLContourWidget::Rotate (double * p1, double * p2) protected
Scale()
void albaOpMMLContourWidget::Scale (double * p1, double * p2, int X, int Y) protected
Translate()
void albaOpMMLContourWidget::Translate (double * p1, double * p2) protected
Push()
void albaOpMMLContourWidget::Push (double * p1, double * p2) protected
CreateDefaultProperties()
void albaOpMMLContourWidget::CreateDefaultProperties () protected
GeneratePlane()
void albaOpMMLContourWidget::GeneratePlane () protected
Member Data Documentation
m_OperationID
int albaOpMMLContourWidget::m_OperationID
Definition at line 70 of file albaOpMMLContourWidget.h.
m_HandleRadius
float albaOpMMLContourWidget::m_HandleRadius
Definition at line 86 of file albaOpMMLContourWidget.h.
m_PlaneSource
vtkPlaneSource* albaOpMMLContourWidget::m_PlaneSource
Definition at line 98 of file albaOpMMLContourWidget.h.
m_BRotatingMode
BOOL albaOpMMLContourWidget::m_BRotatingMode
Definition at line 115 of file albaOpMMLContourWidget.h.
m_BScalingMode
BOOL albaOpMMLContourWidget::m_BScalingMode
Definition at line 116 of file albaOpMMLContourWidget.h.
m_BTranslatingMode
BOOL albaOpMMLContourWidget::m_BTranslatingMode
Definition at line 117 of file albaOpMMLContourWidget.h.
m_BCenterMode
BOOL albaOpMMLContourWidget::m_BCenterMode
Definition at line 118 of file albaOpMMLContourWidget.h.
m_Bounds
float albaOpMMLContourWidget::m_Bounds[6]
Definition at line 119 of file albaOpMMLContourWidget.h.
m_M
albaOpMMLModelView* albaOpMMLContourWidget::m_M
Definition at line 276 of file albaOpMMLContourWidget.h.
m_CH
albaOpMMLParameterView* albaOpMMLContourWidget::m_CH
Definition at line 278 of file albaOpMMLContourWidget.h.
m_CV
albaOpMMLParameterView* albaOpMMLContourWidget::m_CV
Definition at line 279 of file albaOpMMLContourWidget.h.
m_T
albaOpMMLParameterView* albaOpMMLContourWidget::m_T
Definition at line 280 of file albaOpMMLContourWidget.h.
m_H
albaOpMMLParameterView* albaOpMMLContourWidget::m_H
Definition at line 281 of file albaOpMMLContourWidget.h.
m_V
albaOpMMLParameterView* albaOpMMLContourWidget::m_V
Definition at line 282 of file albaOpMMLContourWidget.h.
m_N
albaOpMMLParameterView* albaOpMMLContourWidget::m_N
Definition at line 283 of file albaOpMMLContourWidget.h.
m_S
albaOpMMLParameterView* albaOpMMLContourWidget::m_S
Definition at line 284 of file albaOpMMLContourWidget.h.
m_E
albaOpMMLParameterView* albaOpMMLContourWidget::m_E
Definition at line 285 of file albaOpMMLContourWidget.h.
m_W
albaOpMMLParameterView* albaOpMMLContourWidget::m_W
Definition at line 286 of file albaOpMMLContourWidget.h.
m_Operation
int albaOpMMLContourWidget::m_Operation protected
Definition at line 294 of file albaOpMMLContourWidget.h.
m_State
int albaOpMMLContourWidget::m_State protected
Definition at line 308 of file albaOpMMLContourWidget.h.
m_Motion
float albaOpMMLContourWidget::m_Motion[3] protected
Definition at line 338 of file albaOpMMLContourWidget.h.
m_NormalToXAxis
int albaOpMMLContourWidget::m_NormalToXAxis protected
Definition at line 342 of file albaOpMMLContourWidget.h.
m_NormalToYAxis
int albaOpMMLContourWidget::m_NormalToYAxis protected
Definition at line 343 of file albaOpMMLContourWidget.h.
m_NormalToZAxis
int albaOpMMLContourWidget::m_NormalToZAxis protected
Definition at line 344 of file albaOpMMLContourWidget.h.
m_Representation
int albaOpMMLContourWidget::m_Representation protected
Definition at line 345 of file albaOpMMLContourWidget.h.
Referenced by GetRepresentation().
m_PlaneActor
vtkActor* albaOpMMLContourWidget::m_PlaneActor protected
Definition at line 349 of file albaOpMMLContourWidget.h.
m_PlaneMapper
vtkPolyDataMapper* albaOpMMLContourWidget::m_PlaneMapper protected
Definition at line 350 of file albaOpMMLContourWidget.h.
m_PlaneOutlineTubes
vtkTubeFilter* albaOpMMLContourWidget::m_PlaneOutlineTubes protected
Definition at line 352 of file albaOpMMLContourWidget.h.
m_PlaneOutline
vtkPolyData* albaOpMMLContourWidget::m_PlaneOutline protected
Definition at line 353 of file albaOpMMLContourWidget.h.
m_Handle
vtkActor** albaOpMMLContourWidget::m_Handle protected
Definition at line 357 of file albaOpMMLContourWidget.h.
m_HandleMapper
vtkPolyDataMapper** albaOpMMLContourWidget::m_HandleMapper protected
Definition at line 358 of file albaOpMMLContourWidget.h.
m_HandleGeometry
vtkSphereSource** albaOpMMLContourWidget::m_HandleGeometry protected
Definition at line 359 of file albaOpMMLContourWidget.h.
m_RotationalHandle
vtkActor* albaOpMMLContourWidget::m_RotationalHandle protected
Definition at line 361 of file albaOpMMLContourWidget.h.
m_RotationalHandleMapper
vtkPolyDataMapper* albaOpMMLContourWidget::m_RotationalHandleMapper protected
Definition at line 362 of file albaOpMMLContourWidget.h.
m_RotationalHandleGeometry
vtkSphereSource* albaOpMMLContourWidget::m_RotationalHandleGeometry protected
Definition at line 363 of file albaOpMMLContourWidget.h.
m_CenterHandle
vtkActor* albaOpMMLContourWidget::m_CenterHandle protected
Definition at line 365 of file albaOpMMLContourWidget.h.
m_CenterHandleMapper
vtkPolyDataMapper* albaOpMMLContourWidget::m_CenterHandleMapper protected
Definition at line 366 of file albaOpMMLContourWidget.h.
m_CenterHandleGeometry
vtkSphereSource* albaOpMMLContourWidget::m_CenterHandleGeometry protected
Definition at line 367 of file albaOpMMLContourWidget.h.
m_ConeActor
vtkActor* albaOpMMLContourWidget::m_ConeActor protected
Definition at line 375 of file albaOpMMLContourWidget.h.
m_ConeMapper
vtkPolyDataMapper* albaOpMMLContourWidget::m_ConeMapper protected
Definition at line 376 of file albaOpMMLContourWidget.h.
m_ConeSource
vtkConeSource* albaOpMMLContourWidget::m_ConeSource protected
Definition at line 377 of file albaOpMMLContourWidget.h.
m_LineActor
vtkActor* albaOpMMLContourWidget::m_LineActor protected
Definition at line 381 of file albaOpMMLContourWidget.h.
m_LineMapper
vtkPolyDataMapper* albaOpMMLContourWidget::m_LineMapper protected
Definition at line 382 of file albaOpMMLContourWidget.h.
m_LineSource
vtkLineSource* albaOpMMLContourWidget::m_LineSource protected
Definition at line 383 of file albaOpMMLContourWidget.h.
m_ConeActor2
vtkActor* albaOpMMLContourWidget::m_ConeActor2 protected
Definition at line 386 of file albaOpMMLContourWidget.h.
m_ConeMapper2
vtkPolyDataMapper* albaOpMMLContourWidget::m_ConeMapper2 protected
Definition at line 387 of file albaOpMMLContourWidget.h.
m_ConeSource2
vtkConeSource* albaOpMMLContourWidget::m_ConeSource2 protected
Definition at line 388 of file albaOpMMLContourWidget.h.
m_LineActor2
vtkActor* albaOpMMLContourWidget::m_LineActor2 protected
Definition at line 391 of file albaOpMMLContourWidget.h.
m_LineMapper2
vtkPolyDataMapper* albaOpMMLContourWidget::m_LineMapper2 protected
Definition at line 392 of file albaOpMMLContourWidget.h.
m_LineSource2
vtkLineSource* albaOpMMLContourWidget::m_LineSource2 protected
Definition at line 393 of file albaOpMMLContourWidget.h.
m_HandlePicker
vtkCellPicker* albaOpMMLContourWidget::m_HandlePicker protected
Definition at line 396 of file albaOpMMLContourWidget.h.
m_PlanePicker
vtkCellPicker* albaOpMMLContourWidget::m_PlanePicker protected
Definition at line 397 of file albaOpMMLContourWidget.h.
m_CurrentHandle
vtkActor* albaOpMMLContourWidget::m_CurrentHandle protected
Definition at line 398 of file albaOpMMLContourWidget.h.
m_Normal
float albaOpMMLContourWidget::m_Normal[3] protected
Definition at line 407 of file albaOpMMLContourWidget.h.
m_Transform
vtkTransform* albaOpMMLContourWidget::m_Transform protected
Definition at line 410 of file albaOpMMLContourWidget.h.
m_HandleProperty
vtkProperty* albaOpMMLContourWidget::m_HandleProperty protected
Definition at line 414 of file albaOpMMLContourWidget.h.
m_SelectedHandleProperty
vtkProperty* albaOpMMLContourWidget::m_SelectedHandleProperty protected
Definition at line 415 of file albaOpMMLContourWidget.h.
m_PlaneProperty
vtkProperty* albaOpMMLContourWidget::m_PlaneProperty protected
Definition at line 416 of file albaOpMMLContourWidget.h.
Referenced by GetPlaneProperty().
m_SelectedPlaneProperty
vtkProperty* albaOpMMLContourWidget::m_SelectedPlaneProperty protected
Definition at line 417 of file albaOpMMLContourWidget.h.
Referenced by GetSelectedPlaneProperty().
The documentation for this class was generated from the following file:
albaOpMMLContourWidget.h