ALBA 2: vtkALBAPolyDataDeformation::CSkeletonVertex Class Reference
vtkALBAPolyDataDeformation::CSkeletonVertex Class Reference
#include <vtkALBAPolyDataDeformation.h>
Classes
struct LOCAL_FRAME
Public Types
typedef struct vtkALBAPolyDataDeformation::CSkeletonVertex::LOCAL_FRAME LOCAL_FRAME
Public Member Functions
CSkeletonVertex ()
CSkeletonVertex (double coords[3])
int GetDegree ()
int GetNumberOfJoinedVertices ()
bool IsInPositiveHalfspace (double coords[3])
Public Attributes
int Id
double Coords [3]
LOCAL_FRAME LF
CSkeletonVertex * PMatch
std::vector< CSkeletonEdge * > OneRingEdges
std::vector< CSkeletonVertex * > JoinedVertices
double WT
int NMark
Detailed Description
Definition at line 112 of file vtkALBAPolyDataDeformation.h.
Member Typedef Documentation
LOCAL_FRAME
typedef struct vtkALBAPolyDataDeformation::CSkeletonVertex::LOCAL_FRAME vtkALBAPolyDataDeformation::CSkeletonVertex::LOCAL_FRAME
Constructor & Destructor Documentation
CSkeletonVertex() [1/2]
vtkALBAPolyDataDeformation::CSkeletonVertex::CSkeletonVertex () inline
Definition at line 135 of file vtkALBAPolyDataDeformation.h.
CSkeletonVertex() [2/2]
vtkALBAPolyDataDeformation::CSkeletonVertex::CSkeletonVertex (double coords[3]) inline
Definition at line 145 of file vtkALBAPolyDataDeformation.h.
Member Function Documentation
GetDegree()
int vtkALBAPolyDataDeformation::CSkeletonVertex::GetDegree () inline
Gets the degree of this vertex.
Definition at line 159 of file vtkALBAPolyDataDeformation.h.
Referenced by vtkALBAPolyDataDeformation::GetNextCurveEdge(), vtkALBAPolyDataDeformation::CSkeletonEdge::GetNumberOfConnectedEdges(), vtkALBAPolyDataDeformation::GetPreviousCurveEdge(), vtkALBAPolyDataDeformation::GetPreviousCurveVertex(), and vtkALBAPolyDataDeformation::CSkeletonEdge::IsInternal().
GetNumberOfJoinedVertices()
int vtkALBAPolyDataDeformation::CSkeletonVertex::GetNumberOfJoinedVertices () inline
Gets the number of vertices having the same coordinate.
Definition at line 164 of file vtkALBAPolyDataDeformation.h.
IsInPositiveHalfspace()
bool vtkALBAPolyDataDeformation::CSkeletonVertex::IsInPositiveHalfspace (double coords[3]) inline
Returns true, if the given point lies in the direction LF.u of the half-space defined by the LF.v, LF.w and m_Coords
Definition at line 171 of file vtkALBAPolyDataDeformation.h.
References vtkALBAPolyDataDeformation::CSkeletonVertex::LOCAL_FRAME::u.
Member Data Documentation
Id
int vtkALBAPolyDataDeformation::CSkeletonVertex::Id
Definition at line 115 of file vtkALBAPolyDataDeformation.h.
Coords
double vtkALBAPolyDataDeformation::CSkeletonVertex::Coords[3]
Definition at line 116 of file vtkALBAPolyDataDeformation.h.
LF
LOCAL_FRAME vtkALBAPolyDataDeformation::CSkeletonVertex::LF
Definition at line 125 of file vtkALBAPolyDataDeformation.h.
PMatch
CSkeletonVertex* vtkALBAPolyDataDeformation::CSkeletonVertex::PMatch
Definition at line 126 of file vtkALBAPolyDataDeformation.h.
OneRingEdges
std::vector< CSkeletonEdge* > vtkALBAPolyDataDeformation::CSkeletonVertex::OneRingEdges
Definition at line 128 of file vtkALBAPolyDataDeformation.h.
Referenced by vtkALBAPolyDataDeformation::GetNextCurveEdge(), vtkALBAPolyDataDeformation::GetNextCurveVertex(), vtkALBAPolyDataDeformation::GetPreviousCurveEdge(), and vtkALBAPolyDataDeformation::GetPreviousCurveVertex().
JoinedVertices
std::vector< CSkeletonVertex* > vtkALBAPolyDataDeformation::CSkeletonVertex::JoinedVertices
Definition at line 129 of file vtkALBAPolyDataDeformation.h.
WT
double vtkALBAPolyDataDeformation::CSkeletonVertex::WT
Definition at line 131 of file vtkALBAPolyDataDeformation.h.
NMark
int vtkALBAPolyDataDeformation::CSkeletonVertex::NMark
Definition at line 132 of file vtkALBAPolyDataDeformation.h.
The documentation for this class was generated from the following file:
vtkALBAPolyDataDeformation.h