ALBA 2: vtkALBACellsFilter Class Reference
vtkALBACellsFilter Class Reference
#include <vtkALBACellsFilter.h>
Public Member Functions
vtkTypeRevisionMacro (vtkALBACellsFilter, vtkPolyDataToPolyDataFilter)
void PrintSelf (ostream &os, vtkIndent indent)
void MarkCell (vtkIdType cellid)
void UnmarkCell (vtkIdType cellid)
void ToggleCell (vtkIdType cellid)
void UndoMarks ()
void SetMarkedColor (double r, double g, double b)
void SetMarkedColor (double rgb[3])
vtkGetVector3Macro (MarkedColor, double)
void SetUnmarkedColor (double r, double g, double b)
void SetUnmarkedColor (double rgb[3])
vtkGetVector3Macro (UnmarkedColor, double)
void SetMarkedOpacity (double opacity)
vtkGetMacro (MarkedOpacity, double)
int GetNumberOfMarkedCells ()
vtkIdType GetIdMarkedCell (int i)
Static Public Member Functions
static vtkALBACellsFilter * New ()
Protected Member Functions
vtkALBACellsFilter ()
~vtkALBACellsFilter ()
void Initialize ()
void InitializeScalars ()
void Execute ()
Protected Attributes
vtkIdList * CellIdList
vtkIdList * MarkedCellIdList
int IsInitialized
int IsScalarsInitialized
vtkCharArray * Scalars
vtkLookupTable * LUT
double MarkedColor [3]
double UnmarkedColor [3]
double MarkedOpacity
Detailed Description
class name : vtkALBACellsFilter.
vtkALBACellsFilter- superclass for selecting cells.
vtkALBACellsFilter is a superclass for classes to perform operations on selected cells.
See also
vtkALBARemoveCellsFilter
Definition at line 40 of file vtkALBACellsFilter.h.
Constructor & Destructor Documentation
vtkALBACellsFilter()
vtkALBACellsFilter::vtkALBACellsFilter () protected
constructor
~vtkALBACellsFilter()
vtkALBACellsFilter::~vtkALBACellsFilter () protected
destructor
Member Function Documentation
New()
static vtkALBACellsFilter * vtkALBACellsFilter::New () static
create an instance of the object
vtkTypeRevisionMacro()
vtkALBACellsFilter::vtkTypeRevisionMacro (vtkALBACellsFilter , vtkPolyDataToPolyDataFilter)
RTTI Macro.
PrintSelf()
void vtkALBACellsFilter::PrintSelf (ostream & os, vtkIndent indent)
Print Object Information.
MarkCell()
void vtkALBACellsFilter::MarkCell (vtkIdType cellid)
Mark a cell.
UnmarkCell()
void vtkALBACellsFilter::UnmarkCell (vtkIdType cellid)
Unmark any cell that has been marked already.
ToggleCell()
void vtkALBACellsFilter::ToggleCell (vtkIdType cellid)
If a cells is unmarked- mark it... if its marked- unmark it.
UndoMarks()
void vtkALBACellsFilter::UndoMarks () inline
Undo all the marks made on cells.
Definition at line 61 of file vtkALBACellsFilter.h.
SetMarkedColor() [1/2]
void vtkALBACellsFilter::SetMarkedColor (double r, double g, double b)
Set the marked color... default is red.
SetMarkedColor() [2/2]
void vtkALBACellsFilter::SetMarkedColor (double rgb[3]) inline
Set the marked color... default is red.
Definition at line 66 of file vtkALBACellsFilter.h.
References SetMarkedColor().
Referenced by SetMarkedColor().
vtkGetVector3Macro() [1/2]
vtkALBACellsFilter::vtkGetVector3Macro (MarkedColor , double)
Get the marked color... default is red.
SetUnmarkedColor() [1/2]
void vtkALBACellsFilter::SetUnmarkedColor (double r, double g, double b)
Set the umarked color... default is white.
You could set this to the same color as the vtkProperty and users won't know they are seeing scalars
SetUnmarkedColor() [2/2]
void vtkALBACellsFilter::SetUnmarkedColor (double rgb[3]) inline
Set the umarked color... default is white.
You could set this to the same color as the vtkProperty and users won't know they are seeing scalars
Definition at line 75 of file vtkALBACellsFilter.h.
References SetUnmarkedColor().
Referenced by SetUnmarkedColor().
vtkGetVector3Macro() [2/2]
vtkALBACellsFilter::vtkGetVector3Macro (UnmarkedColor , double)
Get the umarked color... default is white.
You could set this to the same color as the vtkProperty and users won't know they are seeing scalars
SetMarkedOpacity()
void vtkALBACellsFilter::SetMarkedOpacity (double opacity)
Set the marked opacity... default is 1.0 By setting this to 0.0 you can temporally remove the cells and then permanently remove them with RemoveMarkedCells.
vtkGetMacro()
vtkALBACellsFilter::vtkGetMacro (MarkedOpacity , double)
Get the marked opacity... default is 1.0 By setting this to 0.0 you can temporally remove the cells and then permanently remove them with RemoveMarkedCells.
GetNumberOfMarkedCells()
int vtkALBACellsFilter::GetNumberOfMarkedCells () inline
Get the number of marked cells.
Definition at line 88 of file vtkALBACellsFilter.h.
GetIdMarkedCell()
vtkIdType vtkALBACellsFilter::GetIdMarkedCell (int i) inline
Get the marked cell id from the MarkedCellIdList.
Definition at line 91 of file vtkALBACellsFilter.h.
Initialize()
void vtkALBACellsFilter::Initialize () protected
Referenced by vtkALBARemoveCellsFilter::UndoRemoveCells().
InitializeScalars()
void vtkALBACellsFilter::InitializeScalars () protected
Execute()
void vtkALBACellsFilter::Execute () protected
Member Data Documentation
CellIdList
vtkIdList* vtkALBACellsFilter::CellIdList protected
Definition at line 100 of file vtkALBACellsFilter.h.
MarkedCellIdList
vtkIdList* vtkALBACellsFilter::MarkedCellIdList protected
Definition at line 101 of file vtkALBACellsFilter.h.
IsInitialized
int vtkALBACellsFilter::IsInitialized protected
Definition at line 103 of file vtkALBACellsFilter.h.
IsScalarsInitialized
int vtkALBACellsFilter::IsScalarsInitialized protected
Definition at line 104 of file vtkALBACellsFilter.h.
Scalars
vtkCharArray* vtkALBACellsFilter::Scalars protected
Definition at line 106 of file vtkALBACellsFilter.h.
LUT
vtkLookupTable* vtkALBACellsFilter::LUT protected
Definition at line 107 of file vtkALBACellsFilter.h.
MarkedColor
double vtkALBACellsFilter::MarkedColor[3] protected
Definition at line 112 of file vtkALBACellsFilter.h.
UnmarkedColor
double vtkALBACellsFilter::UnmarkedColor[3] protected
Definition at line 113 of file vtkALBACellsFilter.h.
MarkedOpacity
double vtkALBACellsFilter::MarkedOpacity protected
Definition at line 114 of file vtkALBACellsFilter.h.
The documentation for this class was generated from the following file:
vtkALBACellsFilter.h