ALBA 2: BinaryNode< Real > Class Template Reference
BinaryNode< Real > Class Template Reference
#include <vtkALBAPoissonSurfaceReconstruction.h>
Static Public Member Functions
static int CenterCount (int depth)
static int CumulativeCenterCount (int maxDepth)
static int Index (int depth, int offSet)
static int CornerIndex (int maxDepth, int depth, int offSet, int forwardCorner)
static Real CornerIndexPosition (int index, int maxDepth)
static Real Width (int depth)
static void CenterAndWidth (int depth, int offset, Real &center, Real &width)
static void CenterAndWidth (int idx, Real &center, Real &width)
static void DepthAndOffset (int idx, int &depth, int &offset)
Detailed Description
template<class Real>
class BinaryNode< Real >
class name: BinaryNode template class which represent a binary node of a binary tree, infact the topology of the octree (used inside poisson surface reconstruction) defines a set of binary trees.
Definition at line 269 of file vtkALBAPoissonSurfaceReconstruction.h.
Member Function Documentation
CenterCount()
template<class Real > static int BinaryNode< Real >::CenterCount (int depth) inline static
return double depth, not used in the filter
Definition at line 272 of file vtkALBAPoissonSurfaceReconstruction.h.
CumulativeCenterCount()
template<class Real > static int BinaryNode< Real >::CumulativeCenterCount (int maxDepth) inline static
return maxdepth after increment, double and decrement, used for calculate number of base functions of polyomial
Definition at line 274 of file vtkALBAPoissonSurfaceReconstruction.h.
Index()
template<class Real > static int BinaryNode< Real >::Index (int depth, int offSet) inline static
retrieve index giving tree depth and an offset
Definition at line 276 of file vtkALBAPoissonSurfaceReconstruction.h.
CornerIndex()
template<class Real > static int BinaryNode< Real >::CornerIndex (int maxDepth, int depth, int offSet, int forwardCorner) inline static
retrieve index of the node in the corner
Definition at line 278 of file vtkALBAPoissonSurfaceReconstruction.h.
CornerIndexPosition()
template<class Real > static Real BinaryNode< Real >::CornerIndexPosition (int index, int maxDepth) inline static
retrieve position of the node in the corner
Definition at line 281 of file vtkALBAPoissonSurfaceReconstruction.h.
Width()
template<class Real > static Real BinaryNode< Real >::Width (int depth) inline static
retrieve the width of the node
Definition at line 284 of file vtkALBAPoissonSurfaceReconstruction.h.
CenterAndWidth() [1/2]
template<class Real > static void BinaryNode< Real >::CenterAndWidth (int depth, int offset, Real & center, Real & width) inline static
retrieve the width and the center of the node
Definition at line 287 of file vtkALBAPoissonSurfaceReconstruction.h.
Referenced by BinaryNode< Real >::CenterAndWidth().
CenterAndWidth() [2/2]
template<class Real > static void BinaryNode< Real >::CenterAndWidth (int idx, Real & center, Real & width) inline static
retrieve the width and the center of the node
Definition at line 293 of file vtkALBAPoissonSurfaceReconstruction.h.
References BinaryNode< Real >::CenterAndWidth(), and BinaryNode< Real >::DepthAndOffset().
DepthAndOffset()
template<class Real > static void BinaryNode< Real >::DepthAndOffset (int idx, int & depth, int & offset) inline static
retrieve the depth and the offset of the node
Definition at line 300 of file vtkALBAPoissonSurfaceReconstruction.h.
Referenced by BinaryNode< Real >::CenterAndWidth().
The documentation for this class was generated from the following file:
vtkALBAPoissonSurfaceReconstruction.h