ALBA 2: vtkALBAPolyDataDeformation_M2::CSkeletonVertex Class Reference
vtkALBAPolyDataDeformation_M2::CSkeletonVertex Class Reference
#include <vtkALBAPolyDataDeformation_M2.h>
Classes
struct LOCAL_FRAME
Public Types
typedef struct vtkALBAPolyDataDeformation_M2::CSkeletonVertex::LOCAL_FRAME LOCAL_FRAME
typedef double VCoord[3]
Public Member Functions
CSkeletonVertex ()
CSkeletonVertex (double coords[3])
~CSkeletonVertex ()
int GetDegree ()
int GetNumberOfJoinedVertices ()
bool IsInPositiveHalfspace (double coords[3])
Public Attributes
int m_Id
double m_Coords [3]
LOCAL_FRAME m_LF
CSkeletonVertex * m_pMatch
vtkstd::vector< CSkeletonEdge * > m_OneRingEdges
vtkstd::vector< CSkeletonVertex * > m_JoinedVertices
int m_nPlanes
VCoord * m_pPlaneNormals
double m_WT
int m_nMark
Detailed Description
Definition at line 109 of file vtkALBAPolyDataDeformation_M2.h.
Member Typedef Documentation
LOCAL_FRAME
typedef struct vtkALBAPolyDataDeformation_M2::CSkeletonVertex::LOCAL_FRAME vtkALBAPolyDataDeformation_M2::CSkeletonVertex::LOCAL_FRAME
VCoord
typedef double vtkALBAPolyDataDeformation_M2::CSkeletonVertex::VCoord[3]
Definition at line 131 of file vtkALBAPolyDataDeformation_M2.h.
Constructor & Destructor Documentation
CSkeletonVertex() [1/2]
vtkALBAPolyDataDeformation_M2::CSkeletonVertex::CSkeletonVertex () inline
Definition at line 138 of file vtkALBAPolyDataDeformation_M2.h.
CSkeletonVertex() [2/2]
vtkALBAPolyDataDeformation_M2::CSkeletonVertex::CSkeletonVertex (double coords[3]) inline
Definition at line 150 of file vtkALBAPolyDataDeformation_M2.h.
~CSkeletonVertex()
vtkALBAPolyDataDeformation_M2::CSkeletonVertex::~CSkeletonVertex () inline
Definition at line 166 of file vtkALBAPolyDataDeformation_M2.h.
Member Function Documentation
GetDegree()
int vtkALBAPolyDataDeformation_M2::CSkeletonVertex::GetDegree () inline
Gets the degree of this vertex.
Definition at line 171 of file vtkALBAPolyDataDeformation_M2.h.
Referenced by vtkALBAPolyDataDeformation_M2::GetNextCurveEdge(), vtkALBAPolyDataDeformation_M2::CSkeletonEdge::GetNumberOfConnectedEdges(), vtkALBAPolyDataDeformation_M2::GetPreviousCurveEdge(), vtkALBAPolyDataDeformation_M2::GetPreviousCurveVertex(), and vtkALBAPolyDataDeformation_M2::CSkeletonEdge::IsInternal().
GetNumberOfJoinedVertices()
int vtkALBAPolyDataDeformation_M2::CSkeletonVertex::GetNumberOfJoinedVertices () inline
Gets the number of vertices having the same coordinate.
Definition at line 176 of file vtkALBAPolyDataDeformation_M2.h.
IsInPositiveHalfspace()
bool vtkALBAPolyDataDeformation_M2::CSkeletonVertex::IsInPositiveHalfspace (double coords[3]) inline
Returns true, if the given point lies in the direction LF.u of the half-space defined by the LF.v, LF.w and m_Coords
Definition at line 183 of file vtkALBAPolyDataDeformation_M2.h.
References vtkALBAPolyDataDeformation_M2::CSkeletonVertex::LOCAL_FRAME::u.
Member Data Documentation
m_Id
int vtkALBAPolyDataDeformation_M2::CSkeletonVertex::m_Id
Definition at line 112 of file vtkALBAPolyDataDeformation_M2.h.
m_Coords
double vtkALBAPolyDataDeformation_M2::CSkeletonVertex::m_Coords[3]
Definition at line 113 of file vtkALBAPolyDataDeformation_M2.h.
m_LF
LOCAL_FRAME vtkALBAPolyDataDeformation_M2::CSkeletonVertex::m_LF
Definition at line 122 of file vtkALBAPolyDataDeformation_M2.h.
m_pMatch
CSkeletonVertex* vtkALBAPolyDataDeformation_M2::CSkeletonVertex::m_pMatch
Definition at line 123 of file vtkALBAPolyDataDeformation_M2.h.
m_OneRingEdges
vtkstd::vector< CSkeletonEdge* > vtkALBAPolyDataDeformation_M2::CSkeletonVertex::m_OneRingEdges
Definition at line 125 of file vtkALBAPolyDataDeformation_M2.h.
Referenced by vtkALBAPolyDataDeformation_M2::GetNextCurveEdge(), vtkALBAPolyDataDeformation_M2::GetNextCurveVertex(), vtkALBAPolyDataDeformation_M2::GetPreviousCurveEdge(), and vtkALBAPolyDataDeformation_M2::GetPreviousCurveVertex().
m_JoinedVertices
vtkstd::vector< CSkeletonVertex* > vtkALBAPolyDataDeformation_M2::CSkeletonVertex::m_JoinedVertices
Definition at line 126 of file vtkALBAPolyDataDeformation_M2.h.
m_nPlanes
int vtkALBAPolyDataDeformation_M2::CSkeletonVertex::m_nPlanes
Definition at line 130 of file vtkALBAPolyDataDeformation_M2.h.
m_pPlaneNormals
VCoord* vtkALBAPolyDataDeformation_M2::CSkeletonVertex::m_pPlaneNormals
Definition at line 132 of file vtkALBAPolyDataDeformation_M2.h.
m_WT
double vtkALBAPolyDataDeformation_M2::CSkeletonVertex::m_WT
Definition at line 134 of file vtkALBAPolyDataDeformation_M2.h.
m_nMark
int vtkALBAPolyDataDeformation_M2::CSkeletonVertex::m_nMark
Definition at line 135 of file vtkALBAPolyDataDeformation_M2.h.
The documentation for this class was generated from the following file:
vtkALBAPolyDataDeformation_M2.h