ALBA 2: PPolynomial< Degree > Class Template Reference
PPolynomial< Degree > Class Template Reference
#include <vtkALBAPoissonSurfaceReconstruction.h>
Public Member Functions
PPolynomial (void)
PPolynomial (const PPolynomial< Degree > &p)
~PPolynomial (void)
PPolynomial & operator= (const PPolynomial &p)
int size (void) const
void set (const size_t &size)
void set (StartingPolynomial< Degree > *sps, const int &count)
void reset (const size_t &newSize)
double operator() (const double &t) const
double integral (const double &tMin, const double &tMax) const
double Integral (void) const
template<int Degree2>
PPolynomial< Degree > & operator= (const PPolynomial< Degree2 > &p)
PPolynomial operator+ (const PPolynomial &p) const
PPolynomial operator- (const PPolynomial &p) const
template<int Degree2>
PPolynomial< Degree+Degree2 > operator* (const Polynomial< Degree2 > &p) const
template<int Degree2>
PPolynomial< Degree+Degree2 > operator* (const PPolynomial< Degree2 > &p) const
PPolynomial & operator+= (const double &s)
PPolynomial & operator-= (const double &s)
PPolynomial & operator*= (const double &s)
PPolynomial & operator/= (const double &s)
PPolynomial operator+ (const double &s) const
PPolynomial operator- (const double &s) const
PPolynomial operator* (const double &s) const
PPolynomial operator/ (const double &s) const
PPolynomial & addScaled (const PPolynomial &poly, const double &scale)
PPolynomial scale (const double &s) const
PPolynomial shift (const double &s) const
PPolynomial< Degree-1 > derivative (void) const
PPolynomial< Degree+1 > integral (void) const
void getSolutions (const double &c, std::vector< double > &roots, const double &EPS, const double &min=-DBL_MAX, const double &max=DBL_MAX) const
void printnl (void) const
PPolynomial< Degree+1 > MovingAverage (const double &radius)
PPolynomial< 0 > GaussianApproximation (const double &width)
Static Public Member Functions
static PPolynomial ConstantFunction (const double &radius=0.5)
static PPolynomial GaussianApproximation (const double &width=0.5)
Public Attributes
size_t polyCount
StartingPolynomial< Degree > * polys
Detailed Description
template<int Degree>
class PPolynomial< Degree >
class name: PPolynomial
Definition at line 598 of file vtkALBAPoissonSurfaceReconstruction.h.
Constructor & Destructor Documentation
PPolynomial() [1/2]
template<int Degree> PPolynomial< Degree >::PPolynomial (void) inline
Constructor.
Definition at line 604 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polyCount, and PPolynomial< Degree >::polys.
PPolynomial() [2/2]
template<int Degree> PPolynomial< Degree >::PPolynomial (const PPolynomial< Degree > & p) inline
Constructor.
Definition at line 609 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polyCount, PPolynomial< Degree >::polys, and PPolynomial< Degree >::set().
~PPolynomial()
template<int Degree> PPolynomial< Degree >::~PPolynomial (void) inline
Destructor.
Definition at line 616 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polyCount, and PPolynomial< Degree >::polys.
Member Function Documentation
operator=() [1/2]
template<int Degree> PPolynomial & PPolynomial< Degree >::operator= (const PPolynomial< Degree > & p) inline
Overload operator, according to the operation over coefficients.
Definition at line 623 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polyCount, PPolynomial< Degree >::polys, and PPolynomial< Degree >::set().
size()
template<int Degree> int PPolynomial< Degree >::size (void) const inline
Return the size of polynomial object.
Definition at line 630 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polyCount.
Referenced by PPolynomial< Degree >::set().
set() [1/2]
template<int Degree> void PPolynomial< Degree >::set (const size_t & size) inline
Free polynomials, allocate memory and set size starting polynomial.
Definition at line 633 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polyCount, PPolynomial< Degree >::polys, and PPolynomial< Degree >::size().
Referenced by PPolynomial< Degree >::addScaled(), PPolynomial< Degree >::ConstantFunction(), PPolynomial< Degree >::derivative(), PPolynomial< Degree >::integral(), PPolynomial< Degree >::MovingAverage(), PPolynomial< Degree >::operator*(), PPolynomial< Degree >::operator+(), PPolynomial< Degree >::operator-(), PPolynomial< Degree >::operator=(), PPolynomial< Degree >::PPolynomial(), PPolynomial< Degree >::scale(), PPolynomial< Degree >::set(), and PPolynomial< Degree >::shift().
set() [2/2]
template<int Degree> void PPolynomial< Degree >::set (StartingPolynomial< Degree > * sps, const int & count) inline
Set sps as polynomials: this method will sort the elements in sps.
Definition at line 644 of file vtkALBAPoissonSurfaceReconstruction.h.
References StartingPolynomial< Degree >::p, PPolynomial< Degree >::polys, PPolynomial< Degree >::reset(), and PPolynomial< Degree >::set().
reset()
template<int Degree> void PPolynomial< Degree >::reset (const size_t & newSize) inline
Reallocate memory for newsize polys.
Definition at line 655 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polyCount, and PPolynomial< Degree >::polys.
Referenced by PPolynomial< Degree >::addScaled(), and PPolynomial< Degree >::set().
operator()()
template<int Degree> double PPolynomial< Degree >::operator() (const double & t) const inline
Overload operator, return the sum of polys coefficients with index t.
Definition at line 662 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polyCount, and PPolynomial< Degree >::polys.
integral() [1/2]
template<int Degree> double PPolynomial< Degree >::integral (const double & tMin, const double & tMax) const inline
Compute integral within integration range tMin and tMax, return the sum of integrals of polynomials.
Definition at line 668 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polyCount, and PPolynomial< Degree >::polys.
Integral()
template<int Degree> double PPolynomial< Degree >::Integral (void) const inline
Compute integral.
Definition at line 686 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::integral(), PPolynomial< Degree >::polyCount, and PPolynomial< Degree >::polys.
operator=() [2/2]
template<int Degree> template<int Degree2> PPolynomial< Degree > & PPolynomial< Degree >::operator= (const PPolynomial< Degree2 > & p) inline
Overload operator, according to the operation over polys.
Definition at line 690 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polyCount, PPolynomial< Degree >::polys, and PPolynomial< Degree >::set().
operator+() [1/2]
template<int Degree> PPolynomial PPolynomial< Degree >::operator+ (const PPolynomial< Degree > & p) const inline
Combinate polynomials (sorting according to start value).
Definition at line 700 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polyCount, PPolynomial< Degree >::polys, and PPolynomial< Degree >::set().
operator-() [1/2]
template<int Degree> PPolynomial PPolynomial< Degree >::operator- (const PPolynomial< Degree > & p) const inline
Combinate polynomials (sorting according to start value).
p polys with negative sign.
Definition at line 719 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polyCount, PPolynomial< Degree >::polys, and PPolynomial< Degree >::set().
operator*() [1/3]
template<int Degree> template<int Degree2> PPolynomial< Degree+Degree2 > PPolynomial< Degree >::operator* (const Polynomial< Degree2 > & p) const inline
Combinate polys according to multiplicative operation.
Definition at line 740 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polyCount, PPolynomial< Degree >::polys, and PPolynomial< Degree >::set().
operator*() [2/3]
template<int Degree> template<int Degree2> PPolynomial< Degree+Degree2 > PPolynomial< Degree >::operator* (const PPolynomial< Degree2 > & p) const inline
Combinate polys according to multiplicative operation.
A new polynomial is computed with the multiplication beetwen original polys member and each member of the poly parameter./
Definition at line 754 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polyCount, PPolynomial< Degree >::polys, and PPolynomial< Degree >::set().
operator+=()
template<int Degree> PPolynomial & PPolynomial< Degree >::operator+= (const double & s) inline
Overload operator, according to the operation over polys.
Definition at line 772 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polys.
operator-=()
template<int Degree> PPolynomial & PPolynomial< Degree >::operator-= (const double & s) inline
Overload operator, according to the operation over polys.
Definition at line 774 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polys.
operator*=()
template<int Degree> PPolynomial & PPolynomial< Degree >::operator*= (const double & s) inline
Overload operator, according to the operation over polys.
Definition at line 776 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polyCount, and PPolynomial< Degree >::polys.
operator/=()
template<int Degree> PPolynomial & PPolynomial< Degree >::operator/= (const double & s) inline
Overload operator, according to the operation over polys.
Definition at line 781 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polyCount, and PPolynomial< Degree >::polys.
operator+() [2/2]
template<int Degree> PPolynomial PPolynomial< Degree >::operator+ (const double & s) const inline
Overload operator, according to the operation over polys.
Definition at line 786 of file vtkALBAPoissonSurfaceReconstruction.h.
operator-() [2/2]
template<int Degree> PPolynomial PPolynomial< Degree >::operator- (const double & s) const inline
Overload operator, according to the operation over polys.
Definition at line 792 of file vtkALBAPoissonSurfaceReconstruction.h.
operator*() [3/3]
template<int Degree> PPolynomial PPolynomial< Degree >::operator* (const double & s) const inline
Overload operator, according to the operation over polys.
Definition at line 798 of file vtkALBAPoissonSurfaceReconstruction.h.
operator/()
template<int Degree> PPolynomial PPolynomial< Degree >::operator/ (const double & s) const inline
Overload operator, according to the operation over polys.
Definition at line 804 of file vtkALBAPoissonSurfaceReconstruction.h.
addScaled()
template<int Degree> PPolynomial & PPolynomial< Degree >::addScaled (const PPolynomial< Degree > & poly, const double & scale) inline
Add operation with scaled polynomials.
Definition at line 811 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polyCount, PPolynomial< Degree >::polys, PPolynomial< Degree >::reset(), PPolynomial< Degree >::scale(), PPolynomial< Degree >::set(), and StartingPolynomial< Degree >::start.
scale()
template<int Degree> PPolynomial PPolynomial< Degree >::scale (const double & s) const inline
Scale operation on every polynomial.
Definition at line 834 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polyCount, PPolynomial< Degree >::polys, and PPolynomial< Degree >::set().
Referenced by PPolynomial< Degree >::addScaled().
shift()
template<int Degree> PPolynomial PPolynomial< Degree >::shift (const double & s) const inline
Shift operation on every polynomial.
Definition at line 841 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polyCount, PPolynomial< Degree >::polys, and PPolynomial< Degree >::set().
derivative()
template<int Degree> PPolynomial< Degree-1 > PPolynomial< Degree >::derivative (void) const inline
calculate derivative on polys.
Definition at line 849 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polyCount, PPolynomial< Degree >::polys, and PPolynomial< Degree >::set().
integral() [2/2]
template<int Degree> PPolynomial< Degree+1 > PPolynomial< Degree >::integral (void) const inline
calculate integral on polys.
Definition at line 859 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polyCount, PPolynomial< Degree >::polys, and PPolynomial< Degree >::set().
Referenced by PPolynomial< Degree >::Integral().
getSolutions()
template<int Degree> void PPolynomial< Degree >::getSolutions (const double & c, std::vector< double > & roots, const double & EPS, const double & min = -DBL_MAX, const double & max = DBL_MAX) const inline
solve polynomials.
Definition at line 872 of file vtkALBAPoissonSurfaceReconstruction.h.
References Polynomial< Degree >::GetSolutions(), PPolynomial< Degree >::polyCount, PPolynomial< Degree >::polys, and Polynomial< Degree >::SetZero().
printnl()
template<int Degree> void PPolynomial< Degree >::printnl (void) const inline
print method.
Definition at line 891 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polyCount, PPolynomial< Degree >::polys, and Polynomial< Degree >::Printnl().
MovingAverage()
template<int Degree> PPolynomial< Degree+1 > PPolynomial< Degree >::MovingAverage (const double & radius) inline
Compute moving average.
Definition at line 916 of file vtkALBAPoissonSurfaceReconstruction.h.
References StartingPolynomial< Degree >::p, PPolynomial< Degree >::polyCount, PPolynomial< Degree >::polys, PPolynomial< Degree >::set(), Polynomial< Degree >::Shift(), and StartingPolynomial< Degree >::start.
Referenced by PPolynomial< Degree >::GaussianApproximation().
ConstantFunction()
template<int Degree> static PPolynomial PPolynomial< Degree >::ConstantFunction (const double & radius = 0.5) inline static
Return two polynomials forming a constant function with width as constanct value.
Definition at line 937 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::polys, and PPolynomial< Degree >::set().
GaussianApproximation() [1/2]
template<int Degree> static PPolynomial PPolynomial< Degree >::GaussianApproximation (const double & width = 0.5) inline static
Compute gaussian approximation.
Definition at line 953 of file vtkALBAPoissonSurfaceReconstruction.h.
References PPolynomial< Degree >::GaussianApproximation(), and PPolynomial< Degree >::MovingAverage().
Referenced by PPolynomial< Degree >::GaussianApproximation().
GaussianApproximation() [2/2]
PPolynomial< 0 > PPolynomial< 0 >::GaussianApproximation (const double & width)
Definition at line 958 of file vtkALBAPoissonSurfaceReconstruction.h.
Member Data Documentation
polyCount
template<int Degree> size_t PPolynomial< Degree >::polyCount
Definition at line 600 of file vtkALBAPoissonSurfaceReconstruction.h.
Referenced by PPolynomial< Degree >::addScaled(), PPolynomial< Degree >::derivative(), PPolynomial< Degree >::getSolutions(), PPolynomial< Degree >::integral(), PPolynomial< Degree >::Integral(), PPolynomial< Degree >::MovingAverage(), PPolynomial< Degree >::operator()(), PPolynomial< Degree >::operator*(), PPolynomial< Degree >::operator*=(), PPolynomial< Degree >::operator+(), PPolynomial< Degree >::operator-(), PPolynomial< Degree >::operator/=(), PPolynomial< Degree >::operator=(), PPolynomial< Degree >::PPolynomial(), PPolynomial< Degree >::printnl(), PPolynomial< Degree >::reset(), PPolynomial< Degree >::scale(), PPolynomial< Degree >::set(), PPolynomial< Degree >::shift(), PPolynomial< Degree >::size(), and PPolynomial< Degree >::~PPolynomial().
polys
template<int Degree> StartingPolynomial<Degree>* PPolynomial< Degree >::polys
Definition at line 601 of file vtkALBAPoissonSurfaceReconstruction.h.
Referenced by PPolynomial< Degree >::addScaled(), PPolynomial< Degree >::ConstantFunction(), PPolynomial< Degree >::derivative(), PPolynomial< Degree >::getSolutions(), PPolynomial< Degree >::integral(), PPolynomial< Degree >::Integral(), PPolynomial< Degree >::MovingAverage(), PPolynomial< Degree >::operator()(), PPolynomial< Degree >::operator*(), PPolynomial< Degree >::operator*=(), PPolynomial< Degree >::operator+(), PPolynomial< Degree >::operator+=(), PPolynomial< Degree >::operator-(), PPolynomial< Degree >::operator-=(), PPolynomial< Degree >::operator/=(), PPolynomial< Degree >::operator=(), PPolynomial< Degree >::PPolynomial(), PPolynomial< Degree >::printnl(), PPolynomial< Degree >::reset(), PPolynomial< Degree >::scale(), PPolynomial< Degree >::set(), PPolynomial< Degree >::shift(), and PPolynomial< Degree >::~PPolynomial().
The documentation for this class was generated from the following file:
vtkALBAPoissonSurfaceReconstruction.h