ALBA 2: vtkALBAPolyDataDeformation_M2 Class Reference
vtkALBAPolyDataDeformation_M2 Class Reference
#include <vtkALBAPolyDataDeformation_M2.h>
Classes
class CMatrix
class CMeshVertex
class CMunkres
struct CONTROL_SKELETON
class CSkeleton
class CSkeletonEdge
class CSkeletonVertex
class CSuperSkeleton
Public Member Functions
vtkTypeRevisionMacro (vtkALBAPolyDataDeformation_M2, vtkPolyDataToPolyDataFilter)
void PrintSelf (ostream &os, vtkIndent indent)
vtkGetMacro (MatchGeometryWeight, double)
vtkSetMacro (MatchGeometryWeight, double)
vtkGetMacro (MatchTopologyWeight, double)
vtkSetMacro (MatchTopologyWeight, double)
vtkGetMacro (MatchTolerance, double)
vtkSetMacro (MatchTolerance, double)
vtkGetMacro (DivideSkeletonEdges, int)
vtkSetMacro (DivideSkeletonEdges, int)
vtkBooleanMacro (DivideSkeletonEdges, int)
vtkGetMacro (PreserveVolume, int)
vtkSetMacro (PreserveVolume, int)
vtkBooleanMacro (PreserveVolume, int)
virtual int GetNumberOfSkeletons ()
virtual void SetNumberOfSkeletons (int nCount)
virtual void SetNthSkeleton (int idx, vtkPolyData *original, vtkPolyData *modified, vtkIdList *correspondence)
unsigned long int GetMTime ()
Static Public Member Functions
static vtkALBAPolyDataDeformation_M2 * New ()
Protected Types
typedef struct vtkALBAPolyDataDeformation_M2::CONTROL_SKELETON CONTROL_SKELETON
Protected Member Functions
vtkALBAPolyDataDeformation_M2 ()
virtual ~vtkALBAPolyDataDeformation_M2 ()
void ExecuteInformation ()
void ExecuteData (vtkDataObject *output)
bool CreateSuperSkeleton ()
void DestroySuperSkeleton ()
void CreateSuperSkeleton (vtkPolyData *pOC, vtkPolyData *pDC, vtkIdList *pCC, double dblEdgeFactor)
CSkeleton * CreateSkeleton (vtkPolyData *pPoly)
void DestroySkeleton (CSkeleton *pSkel)
vtkIdList * MatchSkeletons (CSkeleton *pOC, CSkeleton *pDC, vtkIdList *pCC)
int TraceSkeletonCurve (CSkeletonVertex *pStartVertex, int iDir, CSkeletonVertex **pOutBuf)
void MarkCurveEdges (CSkeletonVertex **pCurve, int nCount)
int MatchCurves (CSkeletonVertex **pOC, int nOCVerts, CSkeletonVertex **pDC, int nDCVerts)
void CreateCurveEdges (CSkeletonVertex **pVerts, int nVerts)
void RefineCurve (CSkeletonVertex *pCurve, double dblEdgeFactor)
void AddCurveToSuperSkeleton (CSkeletonVertex *pOCCurve)
double ComputeInputMeshAvgEdgeLength ()
CSkeletonVertex * GetPreviousCurveVertex (CSkeletonVertex *pCurve)
CSkeletonVertex * GetNextCurveVertex (CSkeletonVertex *pCurve)
CSkeletonEdge * GetPreviousCurveEdge (CSkeletonEdge *pCurve)
CSkeletonEdge * GetNextCurveEdge (CSkeletonEdge *pCurve)
void ComputeLFS (CSkeletonVertex *pOC)
void ComputeSeparatingPlanes (CSkeletonVertex *pOC_Curve)
void ComputeSeparatingPlane (CSkeletonVertex *pVert1, CSkeletonVertex *pCenterVert, CSkeletonVertex *pVert2, double *out_normal)
void ComputeROI (CSkeletonEdge *pEdge)
void RefineCurveROIs ()
double GetDistance (vtkIdType nPtStartId, double ptEnd[3], vtkCellLocator *cellLocator, double dblMaxDist)
double GetPathLength (vtkIdType nPtFrom, vtkIdType nPtTo, double dblMaxDist)
int GetNumberOfCurveVertices (CSkeletonVertex *pCurve)
void BuildGeneralRotationMatrix (double r[3], double cos_theta, double M[3][3])
void ComputeMeshParametrization ()
void ComputeParametrization (vtkstd::vector< vtkIdType > &points, CSkeletonEdge *pEdge, int iWSkelEdge, double sigma2)
void DeformMesh (vtkPolyData *output)
void CreatePolyDataFromSkeleton (CSkeleton *pSkel, vtkPolyData *output)
Protected Attributes
CONTROL_SKELETON * Skeletons
int NumberOfSkeletons
CSuperSkeleton * SuperSkeleton
double MatchGeometryWeight
double MatchTopologyWeight
double MatchTolerance
int DivideSkeletonEdges
int PreserveVolume
CMeshVertex * MeshVertices
Friends
class CMatrixTestM2
class CSkeletonVertexM2Test
Detailed Description
Definition at line 72 of file vtkALBAPolyDataDeformation_M2.h.
Member Typedef Documentation
CONTROL_SKELETON
typedef struct vtkALBAPolyDataDeformation_M2::CONTROL_SKELETON vtkALBAPolyDataDeformation_M2::CONTROL_SKELETON protected
Constructor & Destructor Documentation
vtkALBAPolyDataDeformation_M2()
vtkALBAPolyDataDeformation_M2::vtkALBAPolyDataDeformation_M2 () protected
~vtkALBAPolyDataDeformation_M2()
virtual vtkALBAPolyDataDeformation_M2::~vtkALBAPolyDataDeformation_M2 () protected virtual
Member Function Documentation
vtkTypeRevisionMacro()
vtkALBAPolyDataDeformation_M2::vtkTypeRevisionMacro (vtkALBAPolyDataDeformation_M2 , vtkPolyDataToPolyDataFilter)
New()
static vtkALBAPolyDataDeformation_M2 * vtkALBAPolyDataDeformation_M2::New () static
PrintSelf()
void vtkALBAPolyDataDeformation_M2::PrintSelf (ostream & os, vtkIndent indent)
vtkGetMacro() [1/5]
vtkALBAPolyDataDeformation_M2::vtkGetMacro (MatchGeometryWeight , double)
Gets the weight using to match geometry of skeletons.
vtkSetMacro() [1/5]
vtkALBAPolyDataDeformation_M2::vtkSetMacro (MatchGeometryWeight , double)
Sets the weight using to match geometry of skeletons The value must be in the interval (0,1)
vtkGetMacro() [2/5]
vtkALBAPolyDataDeformation_M2::vtkGetMacro (MatchTopologyWeight , double)
Gets the weight using to match topology of skeletons.
vtkSetMacro() [2/5]
vtkALBAPolyDataDeformation_M2::vtkSetMacro (MatchTopologyWeight , double)
Sets the weight using to match topology of skeletons The value must be in the interval (0,1)
vtkGetMacro() [3/5]
vtkALBAPolyDataDeformation_M2::vtkGetMacro (MatchTolerance , double)
Gets the tolerance used to match vertices of two curves.
The tolerance is relative to the length of shortest edge of these curves.
vtkSetMacro() [3/5]
vtkALBAPolyDataDeformation_M2::vtkSetMacro (MatchTolerance , double)
Sets the tolerance used to match vertices of two curves The tolerance is relative to the length of shortest edge of these curves.
The value must be in the interval (0,1).
vtkGetMacro() [4/5]
vtkALBAPolyDataDeformation_M2::vtkGetMacro (DivideSkeletonEdges , int)
Returns 1, if large skeleton edges should be divided.
vtkSetMacro() [4/5]
vtkALBAPolyDataDeformation_M2::vtkSetMacro (DivideSkeletonEdges , int)
Specifies whether large skeleton edges should be divided.
vtkBooleanMacro() [1/2]
vtkALBAPolyDataDeformation_M2::vtkBooleanMacro (DivideSkeletonEdges , int)
Specifies whether large skeleton edges should be divided.
vtkGetMacro() [5/5]
vtkALBAPolyDataDeformation_M2::vtkGetMacro (PreserveVolume , int)
Returns 1, if simple volume preservation technique is to be used.
vtkSetMacro() [5/5]
vtkALBAPolyDataDeformation_M2::vtkSetMacro (PreserveVolume , int)
Specifies whether simple volume preservation technique is to be used.
vtkBooleanMacro() [2/2]
vtkALBAPolyDataDeformation_M2::vtkBooleanMacro (PreserveVolume , int)
Specifies whether simple volume preservation technique is to be used.
GetNumberOfSkeletons()
virtual int vtkALBAPolyDataDeformation_M2::GetNumberOfSkeletons () inline virtual
Get the number of control curves.
Definition at line 402 of file vtkALBAPolyDataDeformation_M2.h.
SetNumberOfSkeletons()
virtual void vtkALBAPolyDataDeformation_M2::SetNumberOfSkeletons (int nCount) virtual
Sets the number of control skeletons.
Old skeletons are copied (and preserved)
SetNthSkeleton()
virtual void vtkALBAPolyDataDeformation_M2::SetNthSkeleton (int idx, vtkPolyData * original, vtkPolyData * modified, vtkIdList * correspondence) virtual
Specifies the n-th control skeleton.
GetMTime()
unsigned long int vtkALBAPolyDataDeformation_M2::GetMTime ()
Return this object's modified time.
ExecuteInformation()
void vtkALBAPolyDataDeformation_M2::ExecuteInformation () protected
By default, UpdateInformation calls this method to copy information unmodified from the input to the output.
ExecuteData()
void vtkALBAPolyDataDeformation_M2::ExecuteData (vtkDataObject * output) protected
This method is the one that should be used by subclasses, right now the default implementation is to call the backwards compatibility method.
CreateSuperSkeleton() [1/2]
bool vtkALBAPolyDataDeformation_M2::CreateSuperSkeleton () protected
Creates a single skeleton that describes the deformation.
Returns false, if the construction failed.
DestroySuperSkeleton()
void vtkALBAPolyDataDeformation_M2::DestroySuperSkeleton () inline protected
Destroys the super skeleton.
Definition at line 432 of file vtkALBAPolyDataDeformation_M2.h.
CreateSuperSkeleton() [2/2]
void vtkALBAPolyDataDeformation_M2::CreateSuperSkeleton (vtkPolyData * pOC, vtkPolyData * pDC, vtkIdList * pCC, double dblEdgeFactor) protected
Creates a single super skeleton for the given control skeleton.
It combines both skeletons together, matching their vertices and creating new vertices as needed. It also computes local frames. The combined information is then appended into super skeleton. If the super skeleton does not exist, it is created.
CreateSkeleton()
CSkeleton * vtkALBAPolyDataDeformation_M2::CreateSkeleton (vtkPolyData * pPoly) protected
Creates the internal skeleton data structure for the given polydata.
DestroySkeleton()
void vtkALBAPolyDataDeformation_M2::DestroySkeleton (CSkeleton * pSkel) inline protected
Releases memory allocated for the given skeleton (in CreateSkeleton)
Definition at line 449 of file vtkALBAPolyDataDeformation_M2.h.
MatchSkeletons()
vtkIdList * vtkALBAPolyDataDeformation_M2::MatchSkeletons (CSkeleton * pOC, CSkeleton * pDC, vtkIdList * pCC) protected
Compute the best match for skeleton vertices.
Only junctions and terminal nodes are matched. The caller can optionally specify some (or all) correspondences. The routine returns the list containing pairs of corresponding vertices.
TraceSkeletonCurve()
int vtkALBAPolyDataDeformation_M2::TraceSkeletonCurve (CSkeletonVertex * pStartVertex, int iDir, CSkeletonVertex ** pOutBuf) protected
Traces the curve in the given direction starting from the given vertex.
Starting from the given vertex, the routine moves in the given direction (which actually defines the edge which to go) storing the visited vertices of the graph into the output buffer. The buffer must be capable to hold all vertices of the graph. The traversal process ends when a "junction" or end-point is reached (those vertices have mark >= 0). The routine returns the number of vertices stored in the buffer. N.B. this routine is supposed to be called from CreateSuperSkeleton
MarkCurveEdges()
void vtkALBAPolyDataDeformation_M2::MarkCurveEdges (CSkeletonVertex ** pCurve, int nCount) protected
Marks every edge of the given skeleton curve.
MatchCurves()
int vtkALBAPolyDataDeformation_M2::MatchCurves (CSkeletonVertex ** pOC, int nOCVerts, CSkeletonVertex ** pDC, int nDCVerts) protected
Matches two curves defined by two arrays of vertices.
It creates at least max(nOCVerts, nDCVerts) new vertices and those vertices are stored in pOC and pDC buffers. Note: both array buffers must be capable enough to hold nOCVerts + nDCVerts vertices. Returns the number of vertices in matched curves. It also creates edges between vertices and establishes links between both vertices and edges. The caller is responsible for deletion of all objects when they are no longer needed. N.B. the original vertices are not destroyed, the routine damages buffers only
CreateCurveEdges()
void vtkALBAPolyDataDeformation_M2::CreateCurveEdges (CSkeletonVertex ** pVerts, int nVerts) protected
Create edges for the given array of vertices.
RefineCurve()
void vtkALBAPolyDataDeformation_M2::RefineCurve (CSkeletonVertex * pCurve, double dblEdgeFactor) protected
Refines the given curve (and its corresponding one) by adding more vertices.
Every skeleton edge larger than sqrt(dblEdgeFactor) is split recursively into two shorter edges. The matching curve is split appropriately. N.B. the routine is intended to be called after CreateCurveEdges
AddCurveToSuperSkeleton()
void vtkALBAPolyDataDeformation_M2::AddCurveToSuperSkeleton (CSkeletonVertex * pOCCurve) protected
Stores vertices and edges from the given curve and the matched one into the superskeleton The routine also constructs automatically joints for end-points of curves.
N.B. both curves must be compatible with curves constructed by CreateCurveEdges.
ComputeInputMeshAvgEdgeLength()
double vtkALBAPolyDataDeformation_M2::ComputeInputMeshAvgEdgeLength () protected
Computes the average length of edges of the input mesh.
GetPreviousCurveVertex()
CSkeletonVertex * vtkALBAPolyDataDeformation_M2::GetPreviousCurveVertex (CSkeletonVertex * pCurve) inline protected
Gets the previous vertex on the curve.
Returns NULL, if the given vertex is the first one.
Definition at line 505 of file vtkALBAPolyDataDeformation_M2.h.
References vtkALBAPolyDataDeformation_M2::CSkeletonVertex::GetDegree(), and vtkALBAPolyDataDeformation_M2::CSkeletonVertex::m_OneRingEdges.
GetNextCurveVertex()
CSkeletonVertex * vtkALBAPolyDataDeformation_M2::GetNextCurveVertex (CSkeletonVertex * pCurve) inline protected
Gets the next vertex on the curve.
Returns NULL, if the given vertex is the last one.
Definition at line 512 of file vtkALBAPolyDataDeformation_M2.h.
References vtkALBAPolyDataDeformation_M2::CSkeletonVertex::m_OneRingEdges.
GetPreviousCurveEdge()
CSkeletonEdge * vtkALBAPolyDataDeformation_M2::GetPreviousCurveEdge (CSkeletonEdge * pCurve) inline protected
Gets the previous edge on the curve.
Returns NULL, if the given vertex is the first one.
Definition at line 520 of file vtkALBAPolyDataDeformation_M2.h.
References vtkALBAPolyDataDeformation_M2::CSkeletonVertex::GetDegree(), vtkALBAPolyDataDeformation_M2::CSkeletonVertex::m_OneRingEdges, and vtkALBAPolyDataDeformation_M2::CSkeletonEdge::m_Verts.
GetNextCurveEdge()
CSkeletonEdge * vtkALBAPolyDataDeformation_M2::GetNextCurveEdge (CSkeletonEdge * pCurve) inline protected
Gets the next edge on the curve.
Returns NULL, if the given vertex is the last one.
Definition at line 530 of file vtkALBAPolyDataDeformation_M2.h.
References vtkALBAPolyDataDeformation_M2::CSkeletonVertex::GetDegree(), vtkALBAPolyDataDeformation_M2::CSkeletonVertex::m_OneRingEdges, and vtkALBAPolyDataDeformation_M2::CSkeletonEdge::m_Verts.
ComputeLFS()
void vtkALBAPolyDataDeformation_M2::ComputeLFS (CSkeletonVertex * pOC) protected
Computes the local frame systems for both curves.
N.B. both curves must be compatible with curves constructed by CreateCurveEdges and the links must be established between them
The algorithm is based on the paper: Blanco FR, Oliveira MM: Instant mesh deformation. In: Proceedings of the 2008 symposium on Interactive 3D graphics and games, Redwood City, California, 2008, pp. 71-78
ComputeSeparatingPlanes()
void vtkALBAPolyDataDeformation_M2::ComputeSeparatingPlanes (CSkeletonVertex * pOC_Curve) protected
Computes separating planes for every vertex on both curves, the original and the deformed ones.
The original curve starts at the given vertex. This routine is supposed to be called together with ComputeLFS. A planes is computed for each pair of edges adjacent to every vertex on the curve. Joined edges are also taken into account. The plane is always perpendicular to both edges and the axis of both edges lies on the plane
ComputeSeparatingPlane()
void vtkALBAPolyDataDeformation_M2::ComputeSeparatingPlane (CSkeletonVertex * pVert1, CSkeletonVertex * pCenterVert, CSkeletonVertex * pVert2, double * out_normal) protected
Computes normal of the separating plane at pCenterVert.
Vertices pVert1, pCenterVert2 and pVert2 form a polyline composed of two edges. The plane is perpendicular to both edges and the axis of both edges lies on the plane. The angle between the computed normal and the vector pVert1 - pCenterVert2 is not obtuse (i.e., the normal directs the same way as the other vector). The returned normal is normalized.
ComputeROI()
void vtkALBAPolyDataDeformation_M2::ComputeROI (CSkeletonEdge * pEdge) protected
Computes the region of interest (ROI) for the given edge of curve.
It detects every mesh vertex in the zone of influence of the given edge. Note: one of end-points of the edge may be NULL to specify half-space
RefineCurveROIs()
void vtkALBAPolyDataDeformation_M2::RefineCurveROIs () protected
Refines ROIs of curves.
Refines the mapping of vertices of the input mesh to edges in such a manner that every vertex is present only in one edge ROI.
GetDistance()
double vtkALBAPolyDataDeformation_M2::GetDistance (vtkIdType nPtStartId, double ptEnd[3], vtkCellLocator * cellLocator, double dblMaxDist) protected
Computes an approximate geodesic distance between two points.
If the straight line between both points does not intersect the input mesh, the returned distance is the Euclidian distance between those two points; otherwise it is the sum of the length of the shortest (surface) path from nPtStartId to the surface point closest to the intersection and the distance that returned by GetDistance with the first parameter to be the surface point closest to the intersection. If the total distance during the computation exceeds the given dblMaxDist, the algorithm stops (and returns the distance measured so far) - this is to speed up the process. N.B. cellLocator must be initialized with the input mesh.
GetPathLength()
double vtkALBAPolyDataDeformation_M2::GetPathLength (vtkIdType nPtFrom, vtkIdType nPtTo, double dblMaxDist) protected
Computes the length of the path between nPtFrom to nPtTo vertices.
The computation is not precise (because of speed). If there is no path, or the path would be too long, the routine returns dblMaxDist. N.B. the found path may not be the shortest one!
GetNumberOfCurveVertices()
int vtkALBAPolyDataDeformation_M2::GetNumberOfCurveVertices (CSkeletonVertex * pCurve) protected
Gets the number of vertices belonging to the given curve.
N.B. curve must be compatible with curves constructed by CreateCurveEdges.
BuildGeneralRotationMatrix()
void vtkALBAPolyDataDeformation_M2::BuildGeneralRotationMatrix (double r[3], double cos_theta, double M[3][3]) protected
Constructs the matrix for rotation of vectors around the vector r by the angle theta.
The angle is given indirectly as cos(theta). N.B. vector r must be normalized.
ComputeMeshParametrization()
void vtkALBAPolyDataDeformation_M2::ComputeMeshParametrization () protected
Parametrize the input mesh using the super-skeleton.
N.B. edges ROI must be build and refined before this routine may be called.
ComputeParametrization()
void vtkALBAPolyDataDeformation_M2::ComputeParametrization (vtkstd::vector< vtkIdType > & points, CSkeletonEdge * pEdge, int iWSkelEdge, double sigma2) protected
Parametrize the given points of the input mesh.
Points are given as indices. Parametrization is done for the given edge. If edge is infinite (only one end-point) or iWSkelEdge is -1, the parametrization of every vertex has the same weight (it is 1.0), otherwise it is computed as a function of the distance between the mesh vertex and skeleton vertex pEdge->m_Verts[iWSkelEdge] and sigma2. This function is (see Blanco's paper): e^-(dist2(x,skelvertex)/sigma2). sigma2 should be 2*dist2(skelvertex,centroid(skelvertex))
DeformMesh()
void vtkALBAPolyDataDeformation_M2::DeformMesh (vtkPolyData * output) protected
Computes new position of vertices in the output mesh.
In this last step, positions of vertices are modified according to their parametrization in respect to the superskeleton.
N.B. the given output polydata must be compatible with the input polydata
CreatePolyDataFromSkeleton()
void vtkALBAPolyDataDeformation_M2::CreatePolyDataFromSkeleton (CSkeleton * pSkel, vtkPolyData * output) protected
Creates polydata from the given skeleton.
Friends And Related Function Documentation
CMatrixTestM2
friend class CMatrixTestM2 friend
Definition at line 81 of file vtkALBAPolyDataDeformation_M2.h.
CSkeletonVertexM2Test
friend class CSkeletonVertexM2Test friend
Definition at line 82 of file vtkALBAPolyDataDeformation_M2.h.
Member Data Documentation
Skeletons
CONTROL_SKELETON* vtkALBAPolyDataDeformation_M2::Skeletons protected
Definition at line 345 of file vtkALBAPolyDataDeformation_M2.h.
NumberOfSkeletons
int vtkALBAPolyDataDeformation_M2::NumberOfSkeletons protected
Definition at line 346 of file vtkALBAPolyDataDeformation_M2.h.
SuperSkeleton
CSuperSkeleton* vtkALBAPolyDataDeformation_M2::SuperSkeleton protected
Definition at line 348 of file vtkALBAPolyDataDeformation_M2.h.
MatchGeometryWeight
double vtkALBAPolyDataDeformation_M2::MatchGeometryWeight protected
Definition at line 350 of file vtkALBAPolyDataDeformation_M2.h.
MatchTopologyWeight
double vtkALBAPolyDataDeformation_M2::MatchTopologyWeight protected
Definition at line 351 of file vtkALBAPolyDataDeformation_M2.h.
MatchTolerance
double vtkALBAPolyDataDeformation_M2::MatchTolerance protected
Definition at line 352 of file vtkALBAPolyDataDeformation_M2.h.
DivideSkeletonEdges
int vtkALBAPolyDataDeformation_M2::DivideSkeletonEdges protected
Definition at line 354 of file vtkALBAPolyDataDeformation_M2.h.
PreserveVolume
int vtkALBAPolyDataDeformation_M2::PreserveVolume protected
Definition at line 355 of file vtkALBAPolyDataDeformation_M2.h.
MeshVertices
CMeshVertex* vtkALBAPolyDataDeformation_M2::MeshVertices protected
Definition at line 357 of file vtkALBAPolyDataDeformation_M2.h.
The documentation for this class was generated from the following file:
vtkALBAPolyDataDeformation_M2.h