ALBA: albaGUILutSlider Class Reference
albaGUILutSlider Class Reference
#include <albaGUILutSlider.h>
Public Types
enum ID_ARG_MOUSE_MOVE { ID_MOUSE_RELEASE = 0 , ID_MOUSE_MOVE , ID_MOUSE_D_CLICK_LEFT }
enum ID_BUTTON { MIN_BUTTON = 1 , MAX_BUTTON , MIDDLE_BUTTON }
Public Member Functions
albaGUILutSlider (wxWindow *parent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxBORDER_SIMPLE|wxCLIP_CHILDREN, const char *middleButtonTitle="windowing")
~albaGUILutSlider ()
void SetListener (albaObserver *listener)
void SetRange (double rmin, double rmax)
void SetRange (double *range)
void GetRange (double *rmin, double *rmax)
void GetRange (double *range)
void SetSubRange (double low, double hi)
void SetSubRange (const double *range)
void GetSubRange (double *low, double *hi)
void GetSubRange (double *range)
void MoveButton (int id, int pos)
void ReleaseButton ()
void ShowRangeEntry (int id)
void ShowSubRangeEntry (int id)
void SetText (long i, wxString text)
void SetColour (long i, wxColour colour)
void SetFloatingPointTextOn ()
void SetFloatingPointTextOff ()
void SetFixedTextOn ()
void SetFixedTextOff ()
void SetFixedTextMinButton (const char *label)
void SetFixedTextMaxButton (const char *label)
void EnableMiddleButton (bool enable)
void EnableMaxButton (bool enable)
void EnableMinButton (bool enable)
Protected Member Functions
void OnSize (wxSizeEvent &event)
void UpdateButtons ()
Protected Attributes
albaGUILutButt * m_MinButton
albaGUILutButt * m_MiddleButton
albaGUILutButt * m_MaxButton
wxTextCtrl * m_MinEntry
wxTextCtrl * m_MaxEntry
wxStaticText * m_MinLabel
wxStaticText * m_MaxLabel
double m_MinValue
double m_MaxValue
double m_LowValue
double m_HighValue
bool m_FloatingPointText
bool m_FixedText
albaObserver * m_Listener
Detailed Description
albaGUILutSlider is a Label that notify user-click using the normal wxEvents.
It is used on the title bar of albaGUINamedPanel to popup a menu.
Definition at line 39 of file albaGUILutSlider.h.
Member Enumeration Documentation
ID_ARG_MOUSE_MOVE
enum albaGUILutSlider::ID_ARG_MOUSE_MOVE
Enumerator
ID_MOUSE_RELEASE
ID_MOUSE_MOVE
ID_MOUSE_D_CLICK_LEFT
Definition at line 52 of file albaGUILutSlider.h.
ID_BUTTON
enum albaGUILutSlider::ID_BUTTON
Enumerator
MIN_BUTTON
MAX_BUTTON
MIDDLE_BUTTON
Definition at line 59 of file albaGUILutSlider.h.
Constructor & Destructor Documentation
albaGUILutSlider()
albaGUILutSlider::albaGUILutSlider (wxWindow * parent, wxWindowID id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxBORDER_SIMPLE|wxCLIP_CHILDREN, const char * middleButtonTitle = "windowing")
~albaGUILutSlider()
albaGUILutSlider::~albaGUILutSlider ()
Member Function Documentation
SetListener()
void albaGUILutSlider::SetListener (albaObserver * listener) inline
Definition at line 66 of file albaGUILutSlider.h.
SetRange() [1/2]
void albaGUILutSlider::SetRange (double rmin, double rmax)
Set the range of the double slider.
SetRange() [2/2]
void albaGUILutSlider::SetRange (double * range) inline
Set the range of the double slider.
Definition at line 72 of file albaGUILutSlider.h.
References SetRange().
Referenced by SetRange().
GetRange() [1/2]
void albaGUILutSlider::GetRange (double * rmin, double * rmax) inline
Get the range of the double slider.
Definition at line 75 of file albaGUILutSlider.h.
GetRange() [2/2]
void albaGUILutSlider::GetRange (double * range) inline
Get the range of the double slider.
Definition at line 78 of file albaGUILutSlider.h.
SetSubRange() [1/2]
void albaGUILutSlider::SetSubRange (double low, double hi)
Set the values of the slider's cursors.
SetSubRange() [2/2]
void albaGUILutSlider::SetSubRange (const double * range) inline
Set the values of the slider's cursors.
Definition at line 84 of file albaGUILutSlider.h.
References SetSubRange().
Referenced by SetSubRange().
GetSubRange() [1/2]
void albaGUILutSlider::GetSubRange (double * low, double * hi) inline
Get the values of the slider's cursors.
Definition at line 87 of file albaGUILutSlider.h.
GetSubRange() [2/2]
void albaGUILutSlider::GetSubRange (double * range) inline
Get the values of the slider's cursors.
Definition at line 90 of file albaGUILutSlider.h.
MoveButton()
void albaGUILutSlider::MoveButton (int id, int pos)
Set the position of the slider's cursors and send the event foe range modified.
ReleaseButton()
void albaGUILutSlider::ReleaseButton ()
Set the position of the slider's cursors and send the event foe range modified.
ShowRangeEntry()
void albaGUILutSlider::ShowRangeEntry (int id)
Show an entry to insert a Range numerical values from keyboard.
ShowSubRangeEntry()
void albaGUILutSlider::ShowSubRangeEntry (int id)
Show an entry to insert a Sub Range numerical values from keyboard.
SetText()
void albaGUILutSlider::SetText (long i, wxString text)
Set the label text.
SetColour()
void albaGUILutSlider::SetColour (long i, wxColour colour)
Set the label background colour.
SetFloatingPointTextOn()
void albaGUILutSlider::SetFloatingPointTextOn () inline
Set the label background colour.
Definition at line 111 of file albaGUILutSlider.h.
SetFloatingPointTextOff()
void albaGUILutSlider::SetFloatingPointTextOff () inline
Definition at line 112 of file albaGUILutSlider.h.
SetFixedTextOn()
void albaGUILutSlider::SetFixedTextOn () inline
Turn On the fixed text for labels.
Definition at line 115 of file albaGUILutSlider.h.
SetFixedTextOff()
void albaGUILutSlider::SetFixedTextOff () inline
Turn Off the fixed text for labels.
Definition at line 118 of file albaGUILutSlider.h.
SetFixedTextMinButton()
void albaGUILutSlider::SetFixedTextMinButton (const char * label)
Set the fixed text for min button.
SetFixedTextMaxButton()
void albaGUILutSlider::SetFixedTextMaxButton (const char * label)
Set the fixed text for max button.
EnableMiddleButton()
void albaGUILutSlider::EnableMiddleButton (bool enable)
Enable/Disable middle button.
EnableMaxButton()
void albaGUILutSlider::EnableMaxButton (bool enable)
Enable/Disable max button.
EnableMinButton()
void albaGUILutSlider::EnableMinButton (bool enable)
Enable/Disable min button.
OnSize()
void albaGUILutSlider::OnSize (wxSizeEvent & event) protected
Update slider's cursors.
UpdateButtons()
void albaGUILutSlider::UpdateButtons () protected
Update slider's cursors position.
Member Data Documentation
m_MinButton
albaGUILutButt* albaGUILutSlider::m_MinButton protected
Definition at line 142 of file albaGUILutSlider.h.
m_MiddleButton
albaGUILutButt* albaGUILutSlider::m_MiddleButton protected
Definition at line 143 of file albaGUILutSlider.h.
m_MaxButton
albaGUILutButt* albaGUILutSlider::m_MaxButton protected
Definition at line 144 of file albaGUILutSlider.h.
m_MinEntry
wxTextCtrl* albaGUILutSlider::m_MinEntry protected
Definition at line 145 of file albaGUILutSlider.h.
m_MaxEntry
wxTextCtrl* albaGUILutSlider::m_MaxEntry protected
Definition at line 146 of file albaGUILutSlider.h.
m_MinLabel
wxStaticText* albaGUILutSlider::m_MinLabel protected
Definition at line 148 of file albaGUILutSlider.h.
m_MaxLabel
wxStaticText* albaGUILutSlider::m_MaxLabel protected
Definition at line 149 of file albaGUILutSlider.h.
m_MinValue
double albaGUILutSlider::m_MinValue protected
Definition at line 151 of file albaGUILutSlider.h.
m_MaxValue
double albaGUILutSlider::m_MaxValue protected
Definition at line 152 of file albaGUILutSlider.h.
m_LowValue
double albaGUILutSlider::m_LowValue protected
Definition at line 153 of file albaGUILutSlider.h.
m_HighValue
double albaGUILutSlider::m_HighValue protected
Definition at line 154 of file albaGUILutSlider.h.
m_FloatingPointText
bool albaGUILutSlider::m_FloatingPointText protected
flag used for visualization of decimal in the title of button, default : false
Definition at line 156 of file albaGUILutSlider.h.
m_FixedText
bool albaGUILutSlider::m_FixedText protected
flag used for visualization of fixed text, default: false
Definition at line 157 of file albaGUILutSlider.h.
m_Listener
albaObserver* albaGUILutSlider::m_Listener protected
Definition at line 159 of file albaGUILutSlider.h.
The documentation for this class was generated from the following file:
albaGUILutSlider.h