ALBA 2: vtkBoundingBox Class Reference
vtkBoundingBox Class Reference
#include <vtkBoundingBox.h>
Public Member Functions
vtkBoundingBox ()
vtkBoundingBox (const vtkBoundingBox &bbox)
vtkBoundingBox & operator= (const vtkBoundingBox &bbox)
int operator== (const vtkBoundingBox &bbox) const
int operator!= (const vtkBoundingBox &bbox) const
void SetBounds (double bounds[6])
void SetBounds (double xMin, double xMax, double yMin, double yMax, double zMin, double zMax)
void SetMinPoint (double x, double y, double z)
void SetMinPoint (double p[3])
void SetMaxPoint (double x, double y, double z)
void SetMaxPoint (double p[3])
void AddPoint (double p[3])
void AddPoint (double px, double py, double pz)
void AddBox (const vtkBoundingBox &bbox)
void AddBounds (double bounds[6])
int IntersectBox (const vtkBoundingBox &bbox)
int Intersects (const vtkBoundingBox &bbox) const
void GetBounds (double bounds[6]) const
void GetBounds (double &xMin, double &xMax, double &yMin, double &yMax, double &zMin, double &zMax) const
double GetBound (int i) const
const double * GetMinPoint () const
void GetMinPoint (double &x, double &y, double &z) const
const double * GetMaxPoint () const
void GetMaxPoint (double &x, double &y, double &z) const
int ContainsPoint (double p[3]) const
int ContainsPoint (double px, double py, double pz) const
void GetCenter (double center[3]) const
void GetLengths (double lengths[3]) const
double GetLength (int i) const
double GetMaxLength () const
int IsValid () const
void Reset ()
Protected Attributes
double MinPnt [3]
double MaxPnt [3]
Detailed Description
class name: vtkBoundingBox.
Fast Simple Class for dealing with 3D bounds. vtkBoundingBox maintains a 3D axis aligned bounding box. It is very lite weight and many of the member functions are in-lined so its very fast It is not derived from vtkObject so it can be allocated on the stack
Definition at line 38 of file vtkBoundingBox.h.
Constructor & Destructor Documentation
vtkBoundingBox() [1/2]
vtkBoundingBox::vtkBoundingBox () inline
Construct a bounding box with the min point set to VTK_DOUBLE_MAX and the max point set to VTK_DOUBLE_MIN.
Definition at line 178 of file vtkBoundingBox.h.
References Reset().
vtkBoundingBox() [2/2]
vtkBoundingBox::vtkBoundingBox (const vtkBoundingBox & bbox) inline
Copy Constructor.
Definition at line 251 of file vtkBoundingBox.h.
References MaxPnt, and MinPnt.
Member Function Documentation
operator=()
vtkBoundingBox & vtkBoundingBox::operator= (const vtkBoundingBox & bbox) inline
Assignment Operator.
Definition at line 262 of file vtkBoundingBox.h.
References MaxPnt, and MinPnt.
operator==()
int vtkBoundingBox::operator== (const vtkBoundingBox & bbox) const inline
Equality Operator.
Definition at line 274 of file vtkBoundingBox.h.
References MaxPnt, and MinPnt.
operator!=()
int vtkBoundingBox::operator!= (const vtkBoundingBox & bbox) const inline
Unequality Operator.
Definition at line 284 of file vtkBoundingBox.h.
SetBounds() [1/2]
void vtkBoundingBox::SetBounds (double bounds[6]) inline
Set the bounds explicitly of the box (vtk Style) Returns 1 if the box was changed else 0.
Definition at line 239 of file vtkBoundingBox.h.
References SetBounds().
Referenced by SetBounds().
SetBounds() [2/2]
void vtkBoundingBox::SetBounds (double xMin, double xMax, double yMin, double yMax, double zMin, double zMax)
Set the bounds explicitly of the box (vtk Style) Returns 1 if the box was changed else 0.
SetMinPoint() [1/2]
void vtkBoundingBox::SetMinPoint (double x, double y, double z)
Set the minimum point of the bounding box - if the min point is greater than the max point then the max point will also be changed.
Referenced by SetMinPoint().
SetMinPoint() [2/2]
void vtkBoundingBox::SetMinPoint (double p[3]) inline
Set the minimum point of the bounding box - if the min point is greater than the max point then the max point will also be changed.
Definition at line 289 of file vtkBoundingBox.h.
References SetMinPoint().
SetMaxPoint() [1/2]
void vtkBoundingBox::SetMaxPoint (double x, double y, double z)
Set the maximum point of the bounding box - if the max point is less than the min point then the min point will also be changed.
Referenced by SetMaxPoint().
SetMaxPoint() [2/2]
void vtkBoundingBox::SetMaxPoint (double p[3]) inline
Set the maximum point of the bounding box - if the max point is less than the min point then the min point will also be changed.
Definition at line 294 of file vtkBoundingBox.h.
References SetMaxPoint().
AddPoint() [1/2]
void vtkBoundingBox::AddPoint (double p[3])
Change bounding box so it includes the point p Note that the bounding box may have 0 volume if its bounds were just initialized.
AddPoint() [2/2]
void vtkBoundingBox::AddPoint (double px, double py, double pz)
Change bounding box so it includes the point p Note that the bounding box may have 0 volume if its bounds were just initialized.
AddBox()
void vtkBoundingBox::AddBox (const vtkBoundingBox & bbox)
Change the bouding box to be the union of itself and bbox.
AddBounds()
void vtkBoundingBox::AddBounds (double bounds[6])
Change the bounding box so it includes bounds (defined by vtk standard)
IntersectBox()
int vtkBoundingBox::IntersectBox (const vtkBoundingBox & bbox)
Intersect this box with bbox.
The method returns 1 if both boxes are valid and they do have overlap else it will return 0. If 0 is returned the box has not been modified
Intersects()
int vtkBoundingBox::Intersects (const vtkBoundingBox & bbox) const
Returns 1 if the boxes intersect else returns 0.
GetBounds() [1/2]
void vtkBoundingBox::GetBounds (double bounds[6]) const inline
Get the bounds of the box (defined by vtk style)
Definition at line 245 of file vtkBoundingBox.h.
References GetBounds().
Referenced by GetBounds().
GetBounds() [2/2]
void vtkBoundingBox::GetBounds (double & xMin, double & xMax, double & yMin, double & yMax, double & zMin, double & zMax) const inline
Get the bounds of the box (defined by vtk style)
Definition at line 183 of file vtkBoundingBox.h.
References MaxPnt, and MinPnt.
GetBound()
double vtkBoundingBox::GetBound (int i) const inline
Return the ith bounds of the box (defined by vtk style)
Definition at line 195 of file vtkBoundingBox.h.
References MaxPnt, and MinPnt.
GetMinPoint() [1/2]
const double * vtkBoundingBox::GetMinPoint () const inline
Get the minimum point of the bounding box.
Definition at line 203 of file vtkBoundingBox.h.
References MinPnt.
GetMinPoint() [2/2]
void vtkBoundingBox::GetMinPoint (double & x, double & y, double & z) const inline
Get the minimum point of the bounding box.
Definition at line 299 of file vtkBoundingBox.h.
References MinPnt.
GetMaxPoint() [1/2]
const double * vtkBoundingBox::GetMaxPoint () const inline
Get the maximum point of the bounding box.
Definition at line 208 of file vtkBoundingBox.h.
References MaxPnt.
GetMaxPoint() [2/2]
void vtkBoundingBox::GetMaxPoint (double & x, double & y, double & z) const inline
Get the maximum point of the bounding box.
Definition at line 306 of file vtkBoundingBox.h.
References MaxPnt.
ContainsPoint() [1/2]
int vtkBoundingBox::ContainsPoint (double p[3]) const inline
Returns 1 if the point is contained in the box else 0;.
Definition at line 331 of file vtkBoundingBox.h.
References ContainsPoint().
Referenced by ContainsPoint().
ContainsPoint() [2/2]
int vtkBoundingBox::ContainsPoint (double px, double py, double pz) const inline
Returns 1 if the point is contained in the box else 0;.
Definition at line 313 of file vtkBoundingBox.h.
References MaxPnt, and MinPnt.
GetCenter()
void vtkBoundingBox::GetCenter (double center[3]) const inline
Get the center of the bounding box.
Definition at line 232 of file vtkBoundingBox.h.
References MaxPnt, and MinPnt.
GetLengths()
void vtkBoundingBox::GetLengths (double lengths[3]) const inline
Get the lengths of the box.
Definition at line 225 of file vtkBoundingBox.h.
References GetLength().
GetLength()
double vtkBoundingBox::GetLength (int i) const inline
Return the length in the ith direction.
Definition at line 220 of file vtkBoundingBox.h.
References MaxPnt, and MinPnt.
Referenced by GetLengths().
GetMaxLength()
double vtkBoundingBox::GetMaxLength () const
Return the Max Length of the box.
IsValid()
int vtkBoundingBox::IsValid () const inline
Returns 1 if the bounds have been set and 0 if the box is in its initialized state which is an inverted state.
Definition at line 213 of file vtkBoundingBox.h.
References MaxPnt, and MinPnt.
Reset()
void vtkBoundingBox::Reset () inline
Returns the box to its initialized state.
Definition at line 172 of file vtkBoundingBox.h.
References MaxPnt, and MinPnt.
Referenced by vtkBoundingBox().
Member Data Documentation
MinPnt
double vtkBoundingBox::MinPnt[3] protected
Definition at line 169 of file vtkBoundingBox.h.
Referenced by ContainsPoint(), GetBound(), GetBounds(), GetCenter(), GetLength(), GetMinPoint(), IsValid(), operator=(), operator==(), Reset(), and vtkBoundingBox().
MaxPnt
double vtkBoundingBox::MaxPnt[3] protected
Definition at line 169 of file vtkBoundingBox.h.
Referenced by ContainsPoint(), GetBound(), GetBounds(), GetCenter(), GetLength(), GetMaxPoint(), IsValid(), operator=(), operator==(), Reset(), and vtkBoundingBox().
The documentation for this class was generated from the following file:
vtkBoundingBox.h