ALBA 2: kdtree.h File Reference
kdtree.h File Reference
Functions
struct kdtree * kd_create (int k)
void kd_free (struct kdtree *tree)
void kd_clear (struct kdtree *tree)
void kd_data_destructor (struct kdtree *tree, void(*destr)(void *))
int kd_insert (struct kdtree *tree, const double *pos, void *data)
int kd_insertf (struct kdtree *tree, const float *pos, void *data)
int kd_insert3 (struct kdtree *tree, double x, double y, double z, void *data)
int kd_insert3f (struct kdtree *tree, float x, float y, float z, void *data)
struct kdres * kd_nearest (struct kdtree *tree, const double *pos)
struct kdres * kd_nearestf (struct kdtree *tree, const float *pos)
struct kdres * kd_nearest3 (struct kdtree *tree, double x, double y, double z)
struct kdres * kd_nearest3f (struct kdtree *tree, float x, float y, float z)
struct kdres * kd_nearest_range (struct kdtree *tree, const double *pos, double range)
struct kdres * kd_nearest_rangef (struct kdtree *tree, const float *pos, float range)
struct kdres * kd_nearest_range3 (struct kdtree *tree, double x, double y, double z, double range)
struct kdres * kd_nearest_range3f (struct kdtree *tree, float x, float y, float z, float range)
void kd_res_free (struct kdres *set)
int kd_res_size (struct kdres *set)
void kd_res_rewind (struct kdres *set)
int kd_res_end (struct kdres *set)
int kd_res_next (struct kdres *set)
void * kd_res_item (struct kdres *set, double *pos)
void * kd_res_itemf (struct kdres *set, float *pos)
void * kd_res_item3 (struct kdres *set, double *x, double *y, double *z)
void * kd_res_item3f (struct kdres *set, float *x, float *y, float *z)
void * kd_res_item_data (struct kdres *set)
Function Documentation
kd_create()
struct kdtree * kd_create (int k)
Referenced by itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::SetVesselPointsKDTreeFromPolyData().
kd_free()
void kd_free (struct kdtree * tree)
kd_clear()
void kd_clear (struct kdtree * tree)
kd_data_destructor()
void kd_data_destructor (struct kdtree * tree, void(*)(void *) destr)
kd_insert()
int kd_insert (struct kdtree * tree, const double * pos, void * data)
kd_insertf()
int kd_insertf (struct kdtree * tree, const float * pos, void * data)
kd_insert3()
int kd_insert3 (struct kdtree * tree, double x, double y, double z, void * data)
Referenced by itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::SetVesselPointsKDTreeFromPolyData().
kd_insert3f()
int kd_insert3f (struct kdtree * tree, float x, float y, float z, void * data)
kd_nearest()
struct kdres * kd_nearest (struct kdtree * tree, const double * pos)
kd_nearestf()
struct kdres * kd_nearestf (struct kdtree * tree, const float * pos)
kd_nearest3()
struct kdres * kd_nearest3 (struct kdtree * tree, double x, double y, double z)
Referenced by itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::ComputeDisplacement().
kd_nearest3f()
struct kdres * kd_nearest3f (struct kdtree * tree, float x, float y, float z)
kd_nearest_range()
struct kdres * kd_nearest_range (struct kdtree * tree, const double * pos, double range)
kd_nearest_rangef()
struct kdres * kd_nearest_rangef (struct kdtree * tree, const float * pos, float range)
kd_nearest_range3()
struct kdres * kd_nearest_range3 (struct kdtree * tree, double x, double y, double z, double range)
kd_nearest_range3f()
struct kdres * kd_nearest_range3f (struct kdtree * tree, float x, float y, float z, float range)
kd_res_free()
void kd_res_free (struct kdres * set)
kd_res_size()
int kd_res_size (struct kdres * set)
kd_res_rewind()
void kd_res_rewind (struct kdres * set)
kd_res_end()
int kd_res_end (struct kdres * set)
kd_res_next()
int kd_res_next (struct kdres * set)
kd_res_item()
void * kd_res_item (struct kdres * set, double * pos)
Referenced by itk::vtkALBADeformableSimplexMeshFilter< TInputMesh, TOutputMesh >::ComputeDisplacement().
kd_res_itemf()
void * kd_res_itemf (struct kdres * set, float * pos)
kd_res_item3()
void * kd_res_item3 (struct kdres * set, double * x, double * y, double * z)
kd_res_item3f()
void * kd_res_item3f (struct kdres * set, float * x, float * y, float * z)
kd_res_item_data()
void * kd_res_item_data (struct kdres * set)