ALBA 2: vtkALBAPoissonSurfaceReconstruction.h File Reference
vtkALBAPoissonSurfaceReconstruction.h File Reference
#include "albaConfigure.h"
#include "vtkPolyData.h"
#include "vtkCellArray.h"
#include "vtkPointData.h"
#include "vtkDataSetToPolyDataFilter.h"
#include <vector>
#include <unordered_map>
#include <algorithm>
Classes
class vtkALBAPoissonSurfaceReconstruction
class AllocatorState
class Allocator< T >
class BinaryNode< Real >
class Polynomial< Degree >
class StartingPolynomial< Degree >
class PPolynomial< Degree >
class FunctionData< Degree, Real >
struct Point3D< Real >
class Edge
class Triangle
class CoredPointIndex
class EdgeIndex
class CoredEdgeIndex
class TriangleIndex
class TriangulationEdge
class TriangulationTriangle
class Triangulation< Real >
class CoredMeshData
class CoredVectorMeshData
class CoredFileMeshData
class Square
class Cube
class MarchingSquares
class MarchingCubes
class MemoryInfo
class Vector< T >
class NVector< T, Dim >
struct MatrixEntry< T >
struct NMatrixEntry< T, Dim >
class SparseMatrix< T >
class SparseNMatrix< T, Dim >
class SparseSymmetricMatrix< T >
class OctNode< NodeData, Real >
class OctNode< NodeData, Real >::Neighbors
class OctNode< NodeData, Real >::NeighborKey
class OctNode< NodeData, Real >::Neighbors2
class OctNode< NodeData, Real >::NeighborKey2
class RootInfo
class VertexData
class SortedTreeNodes
class TreeNodeData
class Octree< Degree >
Macros
#define PI 3.1415926535897932384
#define SQRT_3 1.7320508075688772935
#define DIMENSION 3
#define ITERATION_POWER ((double)(1.0/3))
#define MEMORY_ALLOCATOR_BLOCK_SIZE 1<<12
#define READ_SIZE 1024
#define PAD_SIZE (Real(1.0))
#define SCALE 1.25
Typedefs
typedef float Real
typedef float FunctionDataReal
typedef OctNode< class TreeNodeData, Real > TreeOctNode
Functions
double ArcTan2 (const double &y, const double &x)
double Angle (const double in[2])
void Sqrt (const double in[2], double out[2])
void Add (const double in1[2], const double in2[2], double out[2])
void Subtract (const double in1[2], const double in2[2], double out[2])
void Multiply (const double in1[2], const double in2[2], double out[2])
void Divide (const double in1[2], const double in2[2], double out[2])
int Factor (double a1, double a0, double roots[1][2], const double &EPS)
int Factor (double a2, double a1, double a0, double roots[2][2], const double &EPS)
int Factor (double a3, double a2, double a1, double a0, double roots[3][2], const double &EPS)
int Factor (double a4, double a3, double a2, double a1, double a0, double roots[4][2], const double &EPS)
int Solve (const double *eqns, const double *values, double *solutions, const int &dim)
void PSR_main ()
template<class Real >
Real Random (void)
template<class Real >
Point3D< Real > RandomBallPoint (void)
template<class Real >
Point3D< Real > RandomSpherePoint (void)
template<class Real >
double Length (const Point3D< Real > &p)
template<class Real >
double SquareLength (const Point3D< Real > &p)
template<class Real >
double Distance (const Point3D< Real > &p1, const Point3D< Real > &p2)
template<class Real >
double SquareDistance (const Point3D< Real > &p1, const Point3D< Real > &p2)
template<class Real >
void CrossProduct (const Point3D< Real > &p1, const Point3D< Real > &p2, Point3D< Real > &p)
template<class Real >
void EdgeCollapse (const Real &edgeRatio, std::vector< TriangleIndex > &triangles, std::vector< Point3D< Real > > &positions, std::vector< Point3D< Real > > *normals)
template<class Real >
void TriangleCollapse (const Real &edgeRatio, std::vector< TriangleIndex > &triangles, std::vector< Point3D< Real > > &positions, std::vector< Point3D< Real > > *normals)
Macro Definition Documentation
PI
#define PI 3.1415926535897932384
Definition at line 88 of file vtkALBAPoissonSurfaceReconstruction.h.
SQRT_3
#define SQRT_3 1.7320508075688772935
Definition at line 89 of file vtkALBAPoissonSurfaceReconstruction.h.
DIMENSION
#define DIMENSION 3
Definition at line 90 of file vtkALBAPoissonSurfaceReconstruction.h.
ITERATION_POWER
#define ITERATION_POWER ((double)(1.0/3))
Definition at line 92 of file vtkALBAPoissonSurfaceReconstruction.h.
MEMORY_ALLOCATOR_BLOCK_SIZE
#define MEMORY_ALLOCATOR_BLOCK_SIZE 1<<12
Definition at line 93 of file vtkALBAPoissonSurfaceReconstruction.h.
READ_SIZE
#define READ_SIZE 1024
Definition at line 95 of file vtkALBAPoissonSurfaceReconstruction.h.
PAD_SIZE
#define PAD_SIZE (Real(1.0))
Definition at line 97 of file vtkALBAPoissonSurfaceReconstruction.h.
SCALE
#define SCALE 1.25
Definition at line 100 of file vtkALBAPoissonSurfaceReconstruction.h.
Typedef Documentation
Real
typedef float Real
Definition at line 2721 of file vtkALBAPoissonSurfaceReconstruction.h.
FunctionDataReal
typedef float FunctionDataReal
Definition at line 2722 of file vtkALBAPoissonSurfaceReconstruction.h.
TreeOctNode
typedef OctNode<class TreeNodeData,Real> TreeOctNode
Definition at line 2723 of file vtkALBAPoissonSurfaceReconstruction.h.
Function Documentation
ArcTan2()
double ArcTan2 (const double & y, const double & x)
Angle()
double Angle (const double in[2])
Sqrt()
void Sqrt (const double in[2], double out[2])
Add()
void Add (const double in1[2], const double in2[2], double out[2])
Subtract()
void Subtract (const double in1[2], const double in2[2], double out[2])
Multiply()
void Multiply (const double in1[2], const double in2[2], double out[2])
Referenced by albaMatrix3x3::Multiply().
Divide()
void Divide (const double in1[2], const double in2[2], double out[2])
Factor() [1/4]
int Factor (double a1, double a0, double roots[1][2], const double & EPS)
Referenced by Polynomial< Degree >::GetSolutions().
Factor() [2/4]
int Factor (double a2, double a1, double a0, double roots[2][2], const double & EPS)
Factor() [3/4]
int Factor (double a3, double a2, double a1, double a0, double roots[3][2], const double & EPS)
Factor() [4/4]
int Factor (double a4, double a3, double a2, double a1, double a0, double roots[4][2], const double & EPS)
Solve()
int Solve (const double * eqns, const double * values, double * solutions, const int & dim)
PSR_main()
void PSR_main ()
Random()
template<class Real > Real Random (void)
Return a Real random value.
RandomBallPoint()
template<class Real > Point3D< Real > RandomBallPoint (void)
Return a 3d point with random real coordinates.
RandomSpherePoint()
template<class Real > Point3D< Real > RandomSpherePoint (void)
Return a 3d point with random real coordinates as a center of a sphere.
Length()
template<class Real > double Length (const Point3D< Real > & p)
Return distance beetwen origin and a 3d point.
Definition at line 1041 of file vtkALBAPoissonSurfaceReconstruction.h.
References SquareLength().
Referenced by Triangulation< Real >::Area().
SquareLength()
template<class Real > double SquareLength (const Point3D< Real > & p)
Return square distance beetwen origin and a 3d point.
Definition at line 1045 of file vtkALBAPoissonSurfaceReconstruction.h.
References Point3D< Real >::coords.
Referenced by Length().
Distance()
template<class Real > double Distance (const Point3D< Real > & p1, const Point3D< Real > & p2)
Return distance beetwen two 3d points.
SquareDistance()
template<class Real > double SquareDistance (const Point3D< Real > & p1, const Point3D< Real > & p2)
Return square distance beetwen two 3d points.
CrossProduct()
template<class Real > void CrossProduct (const Point3D< Real > & p1, const Point3D< Real > & p2, Point3D< Real > & p)
Cross product beetwen two 3d points: thrid input parameter will save resulting point.
Definition at line 1057 of file vtkALBAPoissonSurfaceReconstruction.h.
References Point3D< Real >::coords.
Referenced by Triangulation< Real >::Area().
EdgeCollapse()
template<class Real > void EdgeCollapse (const Real & edgeRatio, std::vector< TriangleIndex > & triangles, std::vector< Point3D< Real > > & positions, std::vector< Point3D< Real > > * normals)
simplify mesh with edge collapse.
TriangleCollapse()
template<class Real > void TriangleCollapse (const Real & edgeRatio, std::vector< TriangleIndex > & triangles, std::vector< Point3D< Real > > & positions, std::vector< Point3D< Real > > * normals)
simplify mesh with triangle collapse.